"""Comparator-driven INSERT emitter (operator-locked 2026-05-30).

Operator's insight: the existing comparator perfectly parses the DRD
xlsx and matches every DRD target column against the ODI scenario's
final projection.  In reverse-engineering mode (build an INSERT for a
new target from DRD + ODI), the comparator's per-column verdict is
exactly what we need to emit the INSERT.

Instead of re-deriving column expressions in `drd_first_emitter` (which
produces 297 PROVENANCE_FALLBACK cases because it can't access ODI's
JOIN graph cleanly), this emitter REUSES the comparator's match per
target column.  For every DRD-declared target column:

  * MATCHED / ALIAS_DRIFT_ONLY / REAL_MISMATCH / UNRESOLVABLE:
    ODI projects a value for this column.  Project `S.<col>` from
    ODI's inner SELECT (S is the outer alias over the entire ODI
    USING(...) subquery).
  * SOURCE_MISSING:
    ODI does not project this column.  Emit `NULL` with a comment
    quoting the DRD source so operator sees the gap.
  * ODI_EXTRA columns (ODI projects, DRD does not declare) are NOT
    emitted -- DRD drives the target column list.

The FROM clause is the ODI USING(...) inner SELECT, wrapped as `S`,
so every ODI-generated column (with proper JOINs, role-prefix logic,
filtering, etc.) is available as `S.<name>`.  This guarantees the
JOIN graph is honoured -- no fallback paths.

Output style:
  -- Generated by comparator_driven_emitter v1
  -- Source: comparator + ODI USING(...) subquery
  -- DRD declares N target columns; M projected from ODI; K emitted as NULL.
  INSERT INTO <target_schema>.<target_table> (
      <DRD col list, exact order>
  )
  SELECT
      S.<col_1>,    -- MATCHED (verdict)
      S.<col_2>,    -- REAL_MISMATCH (DRD: <attr>; ODI: <expr>)
      NULL,         -- SOURCE_MISSING: DRD says <attr>, ODI gap
      ...
  FROM (
      <ODI USING(...) inner SELECT verbatim>
  ) S;
"""
from __future__ import annotations

import re
from dataclasses import dataclass, field
from typing import Any, Dict, List, Optional

from app.sql_model.types import ComparisonVerdict, ODIModel
from app.sql_model.comparator import ComparisonResult


@dataclass
class ComparatorDrivenInsert:
    sql: str
    column_count: int = 0
    null_substitutions: List[str] = field(default_factory=list)
    matched_count: int = 0
    real_mismatch_cols: List[str] = field(default_factory=list)
    unresolvable_cols: List[str] = field(default_factory=list)
    source_missing_cols: List[str] = field(default_factory=list)
    notes: List[str] = field(default_factory=list)
    # Phase 7.5 review additions (operator-locked 2026-05-30):
    # Surface columns where the NULL we emit may violate a NOT NULL /
    # PK constraint on the target table -- runtime ORA-01400.
    null_in_not_null_risk_cols: List[str] = field(default_factory=list)
    # Hard failure indicator -- callers MUST check this before showing
    # SQL to the operator.
    extraction_failed: bool = False
    extraction_failure_reason: str = ""


def _extract_odi_using_subselect(final_select_sql: str) -> str:
    """Extract the `select ... from (...)` chunk inside the ODI
    MERGE INTO ... USING (...) wrapper.

    Operator-locked hardening (Phase 7.5, review BLOCKER): the paren
    walker must skip parens inside single-quoted string literals,
    inside `--`-to-EOL line comments, and inside `/* ... */` block
    comments.  Naive char-counting on real Oracle SQL with DECODE
    string-literal parens (e.g. `'Y(es)'`) silently miscounts depth
    and returns truncated/empty SQL.

    Returns the matched substring or empty string if no USING was
    found (caller MUST treat empty as a hard failure).
    """
    if not final_select_sql:
        return ""
    upper = final_select_sql.upper()
    using_idx = upper.find("USING")
    if using_idx < 0:
        return ""
    paren_idx = final_select_sql.find("(", using_idx)
    if paren_idx < 0:
        return ""

    depth = 0
    end_idx = -1
    in_string = False
    in_line_comment = False
    in_block_comment = False
    s = final_select_sql
    i = paren_idx
    while i < len(s):
        c = s[i]
        # String-literal handling (Oracle escapes by doubling: '')
        if in_string:
            if c == "'":
                # Lookahead for '' (escaped quote)
                if i + 1 < len(s) and s[i + 1] == "'":
                    i += 2
                    continue
                in_string = False
            i += 1
            continue
        # Line comment
        if in_line_comment:
            if c == "\n":
                in_line_comment = False
            i += 1
            continue
        # Block comment
        if in_block_comment:
            if c == "*" and i + 1 < len(s) and s[i + 1] == "/":
                in_block_comment = False
                i += 2
                continue
            i += 1
            continue
        # Not in any string/comment: check for openers
        if c == "'":
            in_string = True
            i += 1
            continue
        if c == "-" and i + 1 < len(s) and s[i + 1] == "-":
            in_line_comment = True
            i += 2
            continue
        if c == "/" and i + 1 < len(s) and s[i + 1] == "*":
            in_block_comment = True
            i += 2
            continue
        # Real structural paren
        if c == "(":
            depth += 1
        elif c == ")":
            depth -= 1
            if depth == 0:
                end_idx = i
                break
        i += 1
    if end_idx < 0:
        return ""
    return final_select_sql[paren_idx + 1:end_idx].strip()


def emit_insert_comparator_driven(
    target_schema: str,
    target_table: str,
    drd_rows: List[Dict[str, Any]],
    comparison_results: List[ComparisonResult],
    odi_model: ODIModel,
    target_definition: Optional[Dict[str, Any]] = None,
) -> ComparatorDrivenInsert:
    """Build a target INSERT by projecting from ODI's USING subquery
    according to the comparator's per-column verdict.

    `drd_rows` defines the target column ORDER + the full DRD column
    list (operator-locked: DRD drives the target shape).

    `target_definition` (optional): the target PDM definition.  When
    provided, the emitter cross-checks SOURCE_MISSING NULL emissions
    against NOT NULL / PK constraints so the operator sees the runtime
    ORA-01400 risk BEFORE running the SQL (review MAJOR).
    """
    import logging
    _log = logging.getLogger(__name__)

    # Build the NOT NULL / PK column set from target_definition (if given).
    not_null_cols: set = set()
    if target_definition:
        for c in target_definition.get("columns", []) or []:
            name = (c.get("name") or "").strip().upper()
            if not name:
                continue
            if c.get("is_pk") or not c.get("nullable", True):
                not_null_cols.add(name)

    by_target: Dict[str, ComparisonResult] = {
        (r.target_col or "").strip().upper(): r for r in comparison_results
    }
    odi_cols = {(c or "").strip().upper() for c in (odi_model.final_insert_columns or [])}

    inner_select = _extract_odi_using_subselect(odi_model.final_select_sql or "")
    if not inner_select:
        reason = (
            "Could not extract the ODI USING(...) inner SELECT.  "
            "Either the ODI model has no final_select_sql or the paren "
            "walker failed (check for unbalanced strings/comments)."
        )
        _log.warning("comparator_driven_emitter: %s", reason)
        return ComparatorDrivenInsert(
            sql="",
            notes=[reason],
            extraction_failed=True,
            extraction_failure_reason=reason,
        )

    # ── Build INSERT column list (DRD order) ─────────────────────────────
    target_cols: List[str] = []
    seen: set = set()
    for r in drd_rows:
        c = (r.get("physical_name") or r.get("column") or "").strip().upper()
        if not c or c in seen:
            continue
        seen.add(c)
        target_cols.append(c)
    if not target_cols:
        return ComparatorDrivenInsert(
            sql="",
            notes=["DRD has zero target columns; cannot emit INSERT."],
        )

    # ── Build SELECT projection (comparator-driven) ──────────────────────
    select_lines: List[str] = []
    null_substitutions: List[str] = []
    real_mismatch_cols: List[str] = []
    unresolvable_cols: List[str] = []
    source_missing_cols: List[str] = []
    matched_count = 0

    # Build projections as (expression, comment) pairs so we can join
    # with commas BEFORE the trailing comment (else the `--` swallows
    # the comma and breaks Oracle parsing).
    proj_pairs: List[tuple] = []
    null_in_not_null_risk_cols: List[str] = []
    for col in target_cols:
        res = by_target.get(col)
        in_odi = col in odi_cols
        if res is None:
            if in_odi:
                proj_pairs.append((
                    f"S.{col}",
                    "WARNING: no comparator verdict; projecting from ODI by name."
                ))
                matched_count += 1
            else:
                proj_pairs.append((
                    "NULL",
                    "WARNING: no comparator verdict + ODI gap. Operator review required."
                ))
                null_substitutions.append(col)
            continue
        v = res.verdict
        if v == ComparisonVerdict.MATCHED:
            proj_pairs.append((
                f"S.{col}",
                f"[MATCHED] ODI: {res.odi_table}.{res.odi_col}"
            ))
            matched_count += 1
        elif v == ComparisonVerdict.ALIAS_DRIFT_ONLY:
            proj_pairs.append((
                f"S.{col}",
                f"[ALIAS_DRIFT_ONLY] same column, surface alias diff "
                f"(DRD: {res.drd_table}.{res.drd_attr})"
            ))
            matched_count += 1
        elif v == ComparisonVerdict.REAL_MISMATCH:
            real_mismatch_cols.append(col)
            proj_pairs.append((
                f"S.{col}",
                f"[REAL_MISMATCH] DRD says {res.drd_attr!r}; "
                f"ODI projects {res.odi_table}.{res.odi_col}. "
                f"Operator MUST decide which is correct before trusting."
            ))
        elif v == ComparisonVerdict.UNRESOLVABLE:
            unresolvable_cols.append(col)
            proj_pairs.append((
                f"S.{col}",
                f"[UNRESOLVABLE] ODI expression: "
                f"{(res.odi_expr_sql or '')[:60]!r}.  Operator review."
            ))
        elif v == ComparisonVerdict.SOURCE_MISSING:
            source_missing_cols.append(col)
            null_substitutions.append(col)
            drd_src = ".".join(filter(None, [res.drd_schema, res.drd_table, res.drd_attr]))
            # Cross-check NOT NULL constraint (review MAJOR).
            constraint_warning = ""
            if col in not_null_cols:
                null_in_not_null_risk_cols.append(col)
                constraint_warning = (
                    " *** OPERATOR MUST REVIEW: target column is "
                    "NOT NULL / PK; this NULL will violate the "
                    "constraint at runtime (ORA-01400). ***"
                )
            proj_pairs.append((
                "NULL",
                f"[SOURCE_MISSING] DRD says {drd_src!r}, "
                f"ODI does NOT project this column anywhere. "
                f"Operator must extend ODI or accept as deprecated."
                + constraint_warning
            ))
        elif v == ComparisonVerdict.ODI_EXTRA:
            # Defensive (review MINOR): ODI_EXTRA columns should NOT
            # appear in target_cols (no DRD declaration).  If a stray
            # one sneaks in, emit explicit NULL so the column count
            # matches the INSERT list and surface the bug in notes.
            null_substitutions.append(col)
            proj_pairs.append((
                "NULL",
                f"[BUG] ODI_EXTRA verdict on DRD-declared column "
                f"{col!r}; comparator may have mis-routed this row. "
                f"Operator MUST investigate."
            ))
        else:
            _log.warning(
                "comparator_driven_emitter: unknown verdict %r for "
                "column %r; falling back to NULL.", v, col,
            )
            proj_pairs.append((
                "NULL",
                f"WARNING: unknown verdict {v!r}; falling back to NULL."
            ))
            null_substitutions.append(col)

    # Compose SELECT lines with COMMA BEFORE COMMENT so Oracle parses
    # correctly even when the trailing `--` comment is long.
    select_lines = []
    last_idx = len(proj_pairs) - 1
    for i, (expr, comment) in enumerate(proj_pairs):
        sep = "" if i == last_idx else ","
        # Sanitize comment: collapse newlines/tabs to space; trim.
        clean_comment = re.sub(r"[\r\n\t]+", " ", comment or "").strip()
        if clean_comment:
            select_lines.append(f"    {expr}{sep}  -- {clean_comment}")
        else:
            select_lines.append(f"    {expr}{sep}")

    # ── Compose final SQL ────────────────────────────────────────────────
    col_list_sql = ",\n    ".join(target_cols)
    select_sql = "\n".join(select_lines)
    header = (
        f"-- Generated by comparator_driven_emitter v1 (operator-locked 2026-05-30)\n"
        f"-- Source: comparator per-column verdict + ODI USING(...) inner SELECT\n"
        f"-- DRD declares {len(target_cols)} target columns; "
        f"{matched_count} MATCHED/ALIAS_DRIFT; "
        f"{len(real_mismatch_cols)} REAL_MISMATCH (projecting ODI value); "
        f"{len(unresolvable_cols)} UNRESOLVABLE (projecting ODI value); "
        f"{len(source_missing_cols)} SOURCE_MISSING (emitted as NULL).\n"
    )
    sql = (
        f"{header}\n"
        f"INSERT INTO {target_schema}.{target_table} (\n"
        f"    {col_list_sql}\n"
        f")\n"
        f"SELECT\n"
        f"{select_sql}\n"
        f"FROM (\n"
        f"{inner_select}\n"
        f") S;\n"
    )

    notes: List[str] = []
    if real_mismatch_cols:
        notes.append(
            f"{len(real_mismatch_cols)} REAL_MISMATCH columns projected from "
            f"ODI; operator decides whether to keep ODI value or rewrite "
            f"using DRD spec."
        )
    if source_missing_cols:
        notes.append(
            f"{len(source_missing_cols)} SOURCE_MISSING columns emitted as "
            f"NULL: {', '.join(source_missing_cols[:5])}"
            + ("..." if len(source_missing_cols) > 5 else "")
        )
    if null_in_not_null_risk_cols:
        notes.append(
            f"*** RUNTIME RISK: {len(null_in_not_null_risk_cols)} NULL "
            f"emission(s) target NOT NULL / PK column(s) "
            f"({', '.join(null_in_not_null_risk_cols[:5])}). "
            f"These will fail at INSERT time with ORA-01400."
        )

    return ComparatorDrivenInsert(
        sql=sql,
        column_count=len(target_cols),
        null_substitutions=null_substitutions,
        matched_count=matched_count,
        real_mismatch_cols=real_mismatch_cols,
        unresolvable_cols=unresolvable_cols,
        source_missing_cols=source_missing_cols,
        notes=notes,
        null_in_not_null_risk_cols=null_in_not_null_risk_cols,
        extraction_failed=False,
    )
