"""DRD-driven INSERT emitter that REUSES comparator's per-column DRD claim.

Operator-locked architecture (2026-05-30 Phase 7.6, corrects 7.5):

  Comparator already knows where each target column lives in the DRD
  (schema, table, attribute).  Reverse-engineering an INSERT means
  projecting FROM the DRD-stated source -- not from ODI's staging.

  ODI's role is VERIFICATION (per-row verdict tells us whether DRD's
  claim matches what ODI projects).  ODI is NEVER the source of the
  output; if ODI has bugs (REAL_MISMATCH), inheriting ODI's projection
  would propagate the bug.  The DRD specification is the truth.

Per-column emission:

  * MATCHED / ALIAS_DRIFT_ONLY -- project `<alias>.<drd_attr>` from
    DRD's stated source_table.  Comment: ODI verified.
  * REAL_MISMATCH               -- project `<alias>.<drd_attr>` from
    DRD's stated source_table.  Comment: WARNING -- ODI projects
    something different (operator sees the divergence).
  * UNRESOLVABLE                -- project DRD's stated source.
    Comment: ODI uses complex expression.
  * SOURCE_MISSING              -- DRD says X but no PDM entry;
    project `<alias>.<drd_attr>` from DRD's stated source with
    WARNING.  Operator decides whether to extend PDM, fix DRD, or
    deprecate.
  * ODI_EXTRA                   -- skip (DRD has no rule).

Alias map (DRD-driven):
  1. Base table  = most frequent source_table in comparison_results.
                   Alias = "t".
  2. Other tables -> derived alias (lowercased base name; numbered
                     suffix if collisions).
  3. Lookup tables (CL_VAL, _DIM, _MAP, _LKU, _LKUP) used by multiple
     rows with different discriminators (e.g. CL_SCM_ID=N) -> per-row
     numbered alias (CL_VAL_1, CL_VAL_2, ...).

JOIN clauses are built from DRD's source_table set.  Join keys are
derived from DRD's transformation text where the parser succeeds;
otherwise the emitter emits an explicit `CROSS JOIN` annotated with
`-- JOIN_UNDETERMINED: operator must specify` so nothing is hidden.

Output style:
  -- Generated by comparator_driven_emitter v2 (DRD-driven, ODI-verified)
  -- Source: DRD source_table.source_attribute per row (comparator-verified)
  -- DRD declares N target columns; M verified by ODI; K need operator review.
  INSERT INTO <target_schema>.<target_table> (
      <DRD col list, exact order>
  )
  SELECT
      t.<drd_attr_1>    AS <tgt_col_1>,    -- [MATCHED]
      apa.<drd_attr_2>  AS <tgt_col_2>,    -- [REAL_MISMATCH] DRD says X; ODI says Y
      NULL              AS <tgt_col_3>,    -- [SOURCE_MISSING]
      ...
  FROM <base_schema>.<base_table> t
  JOIN <other_schema>.<other_table> apa ON <derived ON clause>
  -- JOIN clauses where operator must add ON predicate are explicitly marked.
"""
from __future__ import annotations

import logging
import re
from collections import Counter
from dataclasses import dataclass, field
from typing import Any, Dict, List, Optional, Tuple

from app.sql_model.types import ComparisonVerdict, ODIModel
from app.sql_model.comparator import ComparisonResult, _columns_equivalent_via_confirmed_pair


_log = logging.getLogger(__name__)

# Substrings that mark a table as a lookup / dimension whose use
# typically requires per-row discriminator-based aliasing.
_LOOKUP_TABLE_MARKERS = ("CL_VAL", "_DIM", "_MAP", "_LKU", "_LKUP")


@dataclass
class DrdDrivenInsert:
    sql: str
    column_count: int = 0
    null_substitutions: List[str] = field(default_factory=list)
    matched_count: int = 0
    real_mismatch_cols: List[str] = field(default_factory=list)
    unresolvable_cols: List[str] = field(default_factory=list)
    source_missing_cols: List[str] = field(default_factory=list)
    null_in_not_null_risk_cols: List[str] = field(default_factory=list)
    join_undetermined_tables: List[str] = field(default_factory=list)
    join_derived_tables: List[str] = field(default_factory=list)
    # Phase 7.8 (operator-locked 2026-05-30): columns where DRD wrote
    # an English-text rule instead of a structured `schema.table.col`
    # source, but the comparator MATCHED ODI's computed expression.
    # Emitter cannot project DRD's prose, so emits NULL + shows the
    # comparator-matched ODI expression in the comment as a hint for
    # the operator to restructure the DRD spec.
    complex_drd_expression_cols: List[str] = field(default_factory=list)
    # Phase 7.9: prose-DRD rows where comparator MATCHED ODI's computed
    # expression -- emitter projects the ODI expression as the SQL
    # realization of DRD's intent (operator-locked recovery path).
    recovered_from_prose_cols: List[str] = field(default_factory=list)
    base_table: str = ""
    aliases_used: Dict[str, str] = field(default_factory=dict)
    notes: List[str] = field(default_factory=list)
    extraction_failed: bool = False
    extraction_failure_reason: str = ""


_ORACLE_RESERVED = frozenset({
    # Common Oracle reserved words that conflict with bare identifier use.
    "CHECK", "ORDER", "GROUP", "WHERE", "TABLE", "INDEX", "VIEW",
    "USER", "DATE", "LEVEL", "ROWID", "ROWNUM", "MINUS", "UNION",
    "INTERSECT", "DESC", "ASC", "NULL", "BETWEEN", "DISTINCT",
    "EXISTS", "INTO", "FROM", "SELECT", "WITH", "AS", "OR", "AND",
    "NOT", "IN", "IS", "LIKE", "VALUES", "CASE", "WHEN", "THEN",
    "ELSE", "END",
})


def _quote_if_reserved(col: str) -> str:
    """Wrap an Oracle reserved word in double quotes so it's parsed as
    an identifier (e.g. CHECK -> \"CHECK\").  Other tokens unchanged."""
    if (col or "").upper() in _ORACLE_RESERVED:
        return f'"{col.upper()}"'
    return col


def _canonical_table(schema: str, table: str) -> str:
    """Lowercase normalised 'schema.table' or just 'table'.

    Operator-locked filters:
      * Phase 7.7: reject pseudo-tables where schema == table (DRD
        parse artefact for English-as-table).
      * Phase 7.11: take FIRST line only when table is multi-line --
        DRD source_table sometimes has the full FQN spread across
        cell lines (e.g. "TRANSACTIONS_OWNER\\n.LGCY_TRD_CPCTY_TP_DIM").
        Raw multi-line emits `JOIN TRANSACTIONS_OWNER\\n.LGCY...` which
        Oracle parses as a JOIN without table name (ORA-02000).
    """
    schema = (schema or "").split("\n")[0].strip()
    table = (table or "").split("\n")[0].strip()
    if not table:
        return ""
    # Reject: schema literally equals table (TRD_CNCLD_F.TRD_CNCLD_F).
    if schema and schema.upper() == table.upper():
        return ""
    # Reject: table contains a space or is excessively long (English
    # prose, not an Oracle identifier).
    if " " in table or len(table) > 64:
        return ""
    if schema:
        return f"{schema}.{table}".upper()
    return table.upper()


def _is_lookup_table(table: str) -> bool:
    t = (table or "").upper()
    return any(m in t for m in _LOOKUP_TABLE_MARKERS)


def _derive_alias(fq_table: str, used: set) -> str:
    """Derive a short alias from a fully-qualified table name.  Avoids
    collisions by appending a numeric suffix."""
    bare = fq_table.split(".")[-1].strip().lower()
    if not bare:
        bare = "src"
    base = bare
    i = 1
    while base in used:
        i += 1
        base = f"{bare}_{i}"
    used.add(base)
    return base


_DISC_RE = re.compile(
    r"\b(?:CL_SCM_ID|SCHEMA_ID|TYPE_ID|CATEGORY_ID|GROUP_ID)\s*=\s*(\d+)",
    re.IGNORECASE,
)


def _lookup_discriminator(transformation_text: str) -> str:
    """Extract a per-row discriminator (e.g. 'CL_SCM_ID = 114') from the
    DRD transformation text so the emitter can give each distinct lookup
    use its own alias instance (CL_VAL_1, CL_VAL_2, ...).  Returns ""
    when no discriminator is found."""
    if not transformation_text:
        return ""
    m = _DISC_RE.search(transformation_text)
    if m:
        return m.group(1)
    return ""


def _build_alias_map(
    rows: List[Tuple[str, str, str, str, str]],
) -> Tuple[str, Dict[Tuple[str, str], str], Dict[str, List[str]], Dict[Tuple[str, str], Tuple[str, str, str]]]:
    """Return (base_fq_table, per_row_alias_map, per_table_alias_map,
    representative_row_per_alias).

    `rows` is list of (target_col, fq_table, source_attr, drd_logic, verdict).

    - per_row_alias_map maps (fq_table, discriminator) -> alias.  Lookup
      tables get one alias per unique discriminator; non-lookup tables
      get a single shared alias keyed by (fq_table, "").
    - per_table_alias_map maps fq_table -> list of aliases assigned.
    - representative_row_per_alias maps (fq_table, discriminator) ->
      (target_col, source_attr, drd_logic) of the FIRST row that pulled
      from this alias.  Used by JOIN-derivation logic to extract ON
      clause from the DRD transformation text.
    """
    counter: Counter = Counter()
    for _, fq, _, _, _ in rows:
        if not fq or _is_lookup_table(fq):
            continue
        counter[fq] += 1
    if not counter:
        for _, fq, _, _, _ in rows:
            if fq:
                counter[fq] += 1
    base_fq = counter.most_common(1)[0][0] if counter else ""

    used_aliases: set = set()
    per_row: Dict[Tuple[str, str], str] = {}
    per_table: Dict[str, List[str]] = {}
    representative: Dict[Tuple[str, str], Tuple[str, str, str]] = {}
    if base_fq:
        base_alias = "t"
        used_aliases.add(base_alias)
        per_row[(base_fq, "")] = base_alias
        per_table[base_fq] = [base_alias]

    for tgt, fq, src_attr, drd_logic, _ in rows:
        if not fq or fq == base_fq:
            continue
        if _is_lookup_table(fq):
            disc = _lookup_discriminator(drd_logic)
            key = (fq, disc)
        else:
            key = (fq, "")
        if key in per_row:
            continue
        alias = _derive_alias(fq, used_aliases)
        per_row[key] = alias
        per_table.setdefault(fq, []).append(alias)
        representative[key] = (tgt, src_attr, drd_logic)

    return base_fq, per_row, per_table, representative


def _derive_on_clause(
    fq_table: str,
    alias: str,
    discriminator: str,
    representative: Tuple[str, str, str],
    base_alias: str,
    base_fq: str,
) -> Tuple[str, bool]:
    """Return (on_clause, success).

    Tries to derive a valid ON clause for `alias` joined to base.  Uses:
      1. DRD-recognised lookup spec patterns (USE X AS CL_VAL_ID, etc.)
      2. DIM table standard pattern (<table_base>_ID == base.<...>_ID)
      3. Discriminator-only WHERE for CL_VAL (1=1 + AND CL_SCM_ID = N)
      4. Failure -> ('1=1', False) so caller emits CROSS JOIN with TODO.
    """
    tgt_col, src_attr, drd_logic = representative
    src_attr_u = (src_attr or "").upper()
    target_col_u = (tgt_col or "").upper()
    bare_table = fq_table.split(".")[-1].upper()

    # PDM-aware validation helper (Phase 7.13).  Imports lazily so the
    # comparator stays usable when PDM is absent.  Available to ALL
    # paths below (Phase 7.14: also Path 1).
    from app.sql_model.schema_provider import default_provider
    provider = default_provider()
    base_sch, base_tab = (base_fq.split(".", 1) + [""])[:2] if "." in base_fq else ("", base_fq)
    tgt_sch, tgt_tab = (fq_table.split(".", 1) + [""])[:2] if "." in fq_table else ("", fq_table)

    def _both_exist(b_col: str, t_col: str) -> bool:
        return (
            provider.has_column(base_sch, base_tab, b_col)
            and provider.has_column(tgt_sch, tgt_tab, t_col)
        )

    def _make_join(t_col: str, b_col: str, extra_clause: str = "") -> str:
        out = (
            f"{alias}.{_quote_if_reserved(t_col)} = "
            f"{base_alias}.{_quote_if_reserved(b_col)}"
        )
        if extra_clause:
            out += f" AND {extra_clause}"
        return out

    # Path 1: reuse drd_import_service's lookup-spec extractor.
    try:
        from app.services.drd_import_service import _extract_lookup_spec
        spec = _extract_lookup_spec(
            drd_logic or "", src_attr_u, target_col_u,
            src_schema=(fq_table.split(".")[0] if "." in fq_table else ""),
            src_table=bare_table,
        )
    except Exception:
        spec = None
    if spec:
        src_join = (spec.get("source_lookup_col") or "").strip().upper()
        lookup_join = (spec.get("lookup_join_col") or "").strip().upper()
        extra = (spec.get("extra_filter") or "").strip()
        # Rewrite extra_filter `LK.X` -> `<alias>.X` (the helper used a
        # hardcoded 'LK.' prefix; we own the alias here).
        if extra:
            extra = re.sub(r"\bLK\.", f"{alias}.", extra, flags=re.IGNORECASE)
            extra = re.sub(r"^\s*AND\s+", "", extra, flags=re.IGNORECASE).strip()
            extra = re.sub(r"\s+AND\s*$", "", extra, flags=re.IGNORECASE).strip()
            # Safety check (review MAJOR): if extra still has any
            # `<WORD>.` prefix that is NEITHER alias NOR base_alias,
            # it references a DRD-text alias we cannot resolve here.
            # Drop the extra_filter entirely rather than emit invalid
            # SQL pointing at undefined aliases.
            valid_prefixes = {alias.upper(), base_alias.upper()}
            stray_aliases = set()
            for pm in re.finditer(r"\b([A-Z][A-Z0-9_]*)\.", extra, flags=re.IGNORECASE):
                p = pm.group(1).upper()
                if p not in valid_prefixes:
                    stray_aliases.add(p)
            if stray_aliases:
                _log.debug(
                    "comparator_driven_emitter: dropping extra_filter for "
                    "%s; references undefined alias(es) %s",
                    fq_table, ", ".join(sorted(stray_aliases)),
                )
                extra = ""
        # Standalone literal? (e.g. "Use TYPE_ID as 84" with literal id)
        src_literal = (spec.get("source_lookup_literal") or "").strip()
        # Phase 7.14: PDM-validate Path 1 before emit (was unvalidated).
        if src_join and lookup_join:
            if _both_exist(src_join, lookup_join):
                return (_make_join(lookup_join, src_join, extra), True)
            # PDM rejects -> fall through to Path 2 cascade.
        elif src_literal and lookup_join:
            if provider.has_column(tgt_sch, tgt_tab, lookup_join):
                base = f"{alias}.{_quote_if_reserved(lookup_join)} = {src_literal}"
                if extra:
                    base += f" AND {extra}"
                return (base, True)

    # Path 2: DIM/LKU table standard pattern, PDM-VALIDATED.  Try
    # multiple FK candidates (TABLE_ID, ID, TABLE_KEY, ...) and use the
    # FIRST one that exists in BOTH the join table and base table.
    if _is_lookup_table(fq_table):
        m = re.match(r"^(.*?)(?:_DIM|_MAP|_LKU|_LKUP)$", bare_table, re.IGNORECASE)
        if m:
            stem = m.group(1).upper()
            for cand in (f"{stem}_ID", stem, f"{stem}_KEY", f"{stem}_CD"):
                if _both_exist(cand, cand):
                    return (_make_join(cand, cand), True)
            # Try alias side `<stem>_ID` joined to base side via
            # `<bare_table>_ID` (often DIM-side has its own PK).
            for cand_t, cand_b in [
                (f"{stem}_ID", f"{bare_table}_ID"),
                ("ID", f"{bare_table}_ID"),
            ]:
                if _both_exist(cand_b, cand_t):
                    return (_make_join(cand_t, cand_b), True)
            # No verified FK -> caller emits CROSS JOIN + TODO.
            return ("1=1", False)
        # CL_VAL with discriminator -> PDM should have CL_VAL_ID and
        # CL_SCM_ID; verify before emitting.
        if bare_table == "CL_VAL" and discriminator:
            if (provider.has_column(tgt_sch, tgt_tab, "CL_VAL_ID")
                    and provider.has_column(tgt_sch, tgt_tab, "CL_SCM_ID")):
                # Need a base-side column.  Try src_attr_u first.
                if src_attr_u and provider.has_column(base_sch, base_tab, src_attr_u):
                    return (
                        _make_join("CL_VAL_ID", src_attr_u,
                                   f"{alias}.CL_SCM_ID = {discriminator}"),
                        True,
                    )
                # Fall through to CROSS JOIN
                return ("1=1", False)
            return ("1=1", False)

    # Path 3: same-name _ID join -- PDM-VALIDATED.
    if src_attr_u and src_attr_u.endswith("_ID") and _both_exist(src_attr_u, src_attr_u):
        return (_make_join(src_attr_u, src_attr_u), True)

    # Path 3.5: fact-extension convention -- PDM-VALIDATED + candidate
    # cascade.  Operator-locked Phase 7.13: NEVER emit an inferred FK
    # the PDM does not back up.  Cascade through candidate FK columns
    # and pick the first that exists in BOTH tables.  If none verified,
    # downgrade to CROSS JOIN + TODO (operator-visible).
    if base_fq:
        base_bare = base_fq.split(".")[-1].upper()
        if base_bare:
            candidates = [
                f"{base_bare}_ID",
                base_bare,
                f"{base_bare}_KEY",
                f"{base_bare}_CD",
                f"{base_bare}_CODE",
                "ID",
            ]
            for cand in candidates:
                if _both_exist(cand, cand):
                    return (_make_join(cand, cand), True)
            # PDM has both tables but no shared FK column -> honest
            # CROSS JOIN.  If either table is unknown in PDM, the
            # `_both_exist` check returned True (conservative) and one
            # of the candidates may pass -- that's intentional, we
            # want to keep working when PDM is incomplete.

    # No verified derivation -> caller emits CROSS JOIN + TODO.
    return ("1=1", False)


def _alias_for_row(
    fq_table: str, drd_logic: str, base_fq: str,
    per_row: Dict[Tuple[str, str], str],
) -> str:
    """Pick the correct alias for a single row."""
    if not fq_table:
        return ""
    if fq_table == base_fq:
        return per_row.get((base_fq, ""), "t")
    if _is_lookup_table(fq_table):
        disc = _lookup_discriminator(drd_logic)
        return per_row.get((fq_table, disc), "")
    return per_row.get((fq_table, ""), "")


def emit_insert_comparator_driven(
    target_schema: str,
    target_table: str,
    drd_rows: List[Dict[str, Any]],
    comparison_results: List[ComparisonResult],
    odi_model: ODIModel,
    target_definition: Optional[Dict[str, Any]] = None,
) -> DrdDrivenInsert:
    """Build a target INSERT that projects from DRD-stated sources for
    every target column, using the comparator's per-row DRD claim and
    verdict as the sole drivers.

    `odi_model` is accepted for API symmetry but used only to compute
    ODI annotations (no SQL inherited from ODI).
    """
    # Build a lookup by target_col so we can iterate in DRD row order.
    by_target: Dict[str, ComparisonResult] = {
        (r.target_col or "").strip().upper(): r for r in comparison_results
    }

    # NOT NULL / PK column set for constraint cross-check.
    not_null_cols: set = set()
    if target_definition:
        for c in target_definition.get("columns", []) or []:
            name = (c.get("name") or "").strip().upper()
            if not name:
                continue
            if c.get("is_pk") or not c.get("nullable", True):
                not_null_cols.add(name)

    # Collect ordered (target_col, fq_table, drd_attr, drd_logic, verdict)
    tuples: List[Tuple[str, str, str, str, str]] = []
    seen_targets: set = set()
    for drd_row in drd_rows:
        col = (drd_row.get("physical_name") or drd_row.get("column") or "").strip().upper()
        if not col or col in seen_targets:
            continue
        seen_targets.add(col)
        res = by_target.get(col)
        if res is None:
            tuples.append((col, "", "", "", ""))
            continue
        fq = _canonical_table(res.drd_schema, res.drd_table)
        tuples.append((
            col,
            fq,
            # Multi-line source_attribute is the DRD convention for
            # "any of these candidates is OK" (e.g. "BKR_AR_ID\nAR_ID").
            # The emitter MUST pick a SINGLE column name -- raw multi-
            # line would emit `alias.BKR_AR_ID\nAR_ID` as the projection,
            # which Oracle parses as TWO tokens (ORA-00923).  Operator-
            # locked Phase 7.11 live-run bug fix: take the FIRST line.
            (res.drd_attr or "").split("\n")[0].strip(),
            (res.drd_logic or "").strip(),
            res.verdict.value if res.verdict else "",
        ))

    if not tuples:
        return DrdDrivenInsert(
            sql="",
            notes=["DRD has zero target columns; cannot emit INSERT."],
            extraction_failed=True,
            extraction_failure_reason="empty drd_rows",
        )

    base_fq, per_row_alias, per_table_alias, representative_row = _build_alias_map(tuples)
    if not base_fq:
        return DrdDrivenInsert(
            sql="",
            notes=[
                "Could not pick a base table (no rows had a usable "
                "source_table).  Operator must populate DRD source_table "
                "before this emitter can produce SQL."
            ],
            extraction_failed=True,
            extraction_failure_reason="no base table",
        )

    null_substitutions: List[str] = []
    real_mismatch_cols: List[str] = []
    unresolvable_cols: List[str] = []
    source_missing_cols: List[str] = []
    null_in_not_null_risk_cols: List[str] = []
    complex_drd_expression_cols: List[str] = []
    recovered_from_prose_cols: List[str] = []
    matched_count = 0
    proj_pairs: List[Tuple[str, str]] = []

    def _notes_suffix(r) -> str:
        """Append DRD col-AE notes to the inline comment when present.
        Operator-locked 2026-05-30: AE = decision history / PBI refs /
        cross-reference rationale.  Surfacing inline gives operator
        full context next to the SQL."""
        if r is None:
            return ""
        notes = (getattr(r, "drd_notes", "") or "").strip()
        if not notes:
            return ""
        clean = re.sub(r"[\r\n\t]+", " ", notes).strip()
        return f"  [DRD-notes: {clean[:160]}]"

    for col, fq, drd_attr, drd_logic, verdict in tuples:
        res = by_target.get(col)
        if not drd_attr or not fq:
            # DRD source is unparseable (English text, missing, or
            # pseudo-table parse artefact).  Three sub-cases:
            #
            #  (a) Comparator MATCHED with ODI expression available
            #      (Phase 7.9 -- operator-locked 2026-05-30):
            #      ODI's expression IS the SQL realization of DRD's
            #      intent (comparator MATCHED them).  Project the
            #      ODI expression with [RECOVERED_FROM_PROSE] marker.
            #      This is NOT "ODI inheritance" -- it's "DRD intent
            #      translated to SQL", which is exactly what
            #      reverse-engineering wants.  Operator sees BOTH
            #      DRD prose AND realized SQL in the comment.
            #
            #  (b) Comparator MATCHED but no usable ODI expression:
            #      surface as COMPLEX_DRD_EXPRESSION (Phase 7.8) --
            #      NULL with hint.
            #
            #  (c) No match at all: honest NULL.
            if (
                res
                and verdict == ComparisonVerdict.MATCHED.value
                and res.odi_expr_sql
                and res.odi_expr_sql.strip()
            ):
                odi_expr = res.odi_expr_sql.strip()
                # Phase 7.9: ODI expression often references aliases
                # specific to ODI's staging (TXN_RLTNP, APA_CASH, ...).
                # We keep the raw expression but warn operator that
                # alias resolution to OUR FROM-graph may need manual
                # adjustment.
                recovered_from_prose_cols.append(col)
                matched_count += 1  # counts -- we emit real SQL
                drd_prose = (drd_logic or drd_attr or "")
                clean_prose = re.sub(r"[\r\n\t]+", " ", drd_prose).strip()
                clean_expr = re.sub(r"[\r\n\t]+", " ", odi_expr).strip()
                # Wrap in parens for safety inside SELECT.
                expr_for_select = odi_expr if odi_expr.strip().startswith("(") else f"({odi_expr})"
                proj_pairs.append((
                    expr_for_select,
                    f"[RECOVERED_FROM_PROSE] DRD wrote intent as English: "
                    f"{clean_prose[:80]!r}; comparator MATCHED ODI's SQL "
                    f"realization: {clean_expr[:80]!r}.  Operator: verify "
                    f"alias names in the expression resolve in our FROM "
                    f"graph; restructure DRD source_table when convenient."
                    + _notes_suffix(res)
                ))
                continue
            # (b)/(c): NULL paths
            if res and verdict == ComparisonVerdict.MATCHED.value:
                complex_drd_expression_cols.append(col)
            if col in not_null_cols:
                null_in_not_null_risk_cols.append(col)
            null_substitutions.append(col)
            proj_pairs.append((
                "NULL",
                (
                    f"[COMPLEX_DRD_EXPRESSION] DRD wrote a prose rule for "
                    f"{col}; comparator MATCHED but no ODI expression to "
                    f"recover.  Operator must restructure DRD."
                    if res and verdict == ComparisonVerdict.MATCHED.value
                    else f"DRD did not state a source for {col}; "
                         f"projecting NULL.  Operator must populate DRD."
                )
                + _notes_suffix(res)
            ))
            continue
        if verdict == ComparisonVerdict.ODI_EXTRA.value:
            # Defensive (should not happen if drd_rows drives the loop).
            null_substitutions.append(col)
            proj_pairs.append((
                "NULL",
                f"[BUG] ODI_EXTRA verdict on DRD-declared column "
                f"{col!r}; comparator may have mis-routed this row."
            ))
            continue

        alias = _alias_for_row(fq, drd_logic, base_fq, per_row_alias)
        if not alias:
            null_substitutions.append(col)
            proj_pairs.append((
                "NULL",
                f"ALIAS_RESOLVE_FAIL: could not derive an alias for "
                f"DRD source {fq}.{drd_attr} (col {col}). Operator "
                f"must check DRD source_table."
            ))
            continue

        # Phase 7.19.15 (2026-06-02): emit the PHYSICAL column name, not the
        # DRD logical name, when the two are an operator-confirmed pair
        # (e.g. DRD wrote YIELD_TO_WORST_CD but the physical column is
        # YTW_CD).  The confirmed pair resolved the COMPARISON to MATCHED,
        # but emitting the DRD logical name produced ORA-00904 at runtime
        # (no such column).  res.odi_col is the comparator-verified physical
        # name; use it when it differs from drd_attr and forms a confirmed
        # pair.  Generic -- pairs live in comparator_config.json, not code.
        _emit_attr = drd_attr
        _odi_col = (res.odi_col or "").strip() if res else ""
        if _odi_col and _odi_col.upper() != drd_attr.upper() \
                and _columns_equivalent_via_confirmed_pair(drd_attr, _odi_col):
            _emit_attr = _odi_col
        proj_expr = f"{alias}.{_quote_if_reserved(_emit_attr)}"

        # Verdict annotation (ODI verifies DRD; ODI is NEVER the source).
        if verdict == ComparisonVerdict.MATCHED.value:
            matched_count += 1
            comment = (
                f"[MATCHED] DRD source verified against ODI "
                f"(ODI projects {res.odi_table}.{res.odi_col})"
            )
        elif verdict == ComparisonVerdict.ALIAS_DRIFT_ONLY.value:
            matched_count += 1
            comment = (
                f"[ALIAS_DRIFT_ONLY] DRD source verified -- same physical "
                f"column under a different alias in ODI."
            )
        elif verdict == ComparisonVerdict.REAL_MISMATCH.value:
            real_mismatch_cols.append(col)
            comment = (
                f"[REAL_MISMATCH] DRD source {fq}.{drd_attr} used; "
                f"ODI projects DIFFERENT value: "
                f"{res.odi_table}.{res.odi_col}. "
                f"Operator must reconcile DRD vs ODI."
            )
        elif verdict == ComparisonVerdict.UNRESOLVABLE.value:
            unresolvable_cols.append(col)
            comment = (
                f"[UNRESOLVABLE] DRD source used; ODI emits complex "
                f"expression: {(res.odi_expr_sql or '')[:60]!r}. "
                f"Operator should confirm equivalence."
            )
        elif verdict == ComparisonVerdict.SOURCE_MISSING.value:
            source_missing_cols.append(col)
            comment = (
                f"[SOURCE_MISSING] DRD source {fq}.{drd_attr} used; "
                f"ODI does NOT project this target column anywhere. "
                f"Operator must extend ODI or accept gap."
            )
        else:
            comment = (
                f"[NO_VERDICT or unknown verdict {verdict!r}] -- "
                f"DRD source used.  Operator review."
            )

        proj_pairs.append((proj_expr, comment + _notes_suffix(res)))

    # ── Compose SELECT projection (comma BEFORE comment for Oracle) ──────
    select_lines: List[str] = []
    last_idx = len(proj_pairs) - 1
    for i, (expr, comment) in enumerate(proj_pairs):
        sep = "" if i == last_idx else ","
        # Compute padded expression for readability + risk marker.
        col = tuples[i][0]
        if expr == "NULL" and col in not_null_cols:
            null_in_not_null_risk_cols.append(col)
            comment = (
                comment + " *** OPERATOR MUST REVIEW: target column is "
                "NOT NULL / PK; runtime ORA-01400. ***"
            )
        clean_comment = re.sub(r"[\r\n\t]+", " ", comment or "").strip()
        # Pad expr to 30 chars for readability when short; ALWAYS keep
        # at least one space before AS to avoid token-collision bugs
        # like 'FA_NUMBER_ENTITY_CODEAS' when expr exceeds 30 chars
        # (operator-locked Phase 7.11 live-run bug fix).
        expr_padded = expr.ljust(30) if len(expr) < 30 else expr + " "
        select_lines.append(f"    {expr_padded}AS {col}{sep}  -- {clean_comment}")

    # ── Build FROM + JOIN clauses (DRD-driven) ───────────────────────────
    base_alias = per_row_alias[(base_fq, "")]
    base_parts = base_fq.split(".", 1)
    if len(base_parts) == 2:
        base_sql_table = f"{base_parts[0]}.{base_parts[1]}"
    else:
        base_sql_table = base_fq
    from_clauses: List[str] = [f"FROM {base_sql_table} {base_alias}"]
    join_undetermined: List[str] = []
    join_derived: List[str] = []
    seen_aliases: set = {base_alias}
    # Walk per_row_alias and emit one JOIN per (fq_table, discriminator).
    # Each non-base entry tries to derive an ON clause from the DRD
    # transformation text of its representative row; falls back to
    # CROSS JOIN + TODO when the derivation can't pin a clean predicate.
    for (fq, disc), alias in per_row_alias.items():
        if alias in seen_aliases:
            continue
        seen_aliases.add(alias)
        parts = fq.split(".", 1)
        sql_table = f"{parts[0]}.{parts[1]}" if len(parts) == 2 else fq
        rep = representative_row.get((fq, disc), ("", "", ""))
        on_clause, success = _derive_on_clause(
            fq_table=fq, alias=alias, discriminator=disc,
            representative=rep, base_alias=base_alias, base_fq=base_fq,
        )
        if success:
            from_clauses.append(
                f"  JOIN {sql_table} {alias} ON {on_clause}"
            )
            join_derived.append(f"{alias}={fq}")
        else:
            # Operator-visible CROSS JOIN with explicit TODO so nothing
            # silent and operator can spot-fix.
            disc_hint = f" (discriminator: {disc})" if disc else ""
            from_clauses.append(
                f"  -- TODO: replace CROSS JOIN with operator-supplied "
                f"ON clause for {fq}{disc_hint}"
            )
            from_clauses.append(f"  CROSS JOIN {sql_table} {alias}")
            join_undetermined.append(f"{alias}={fq}")

    # ── Compose final SQL ────────────────────────────────────────────────
    target_cols = [t[0] for t in tuples]
    col_list_sql = ",\n    ".join(target_cols)
    header = (
        f"-- Generated by comparator_driven_emitter v2 (DRD-driven; ODI verifies)\n"
        f"-- Source per row: DRD source_table.source_attribute (NOT ODI staging).\n"
        f"-- Operator-locked architecture (2026-05-30 Phase 7.6).\n"
        f"-- DRD declares {len(target_cols)} target columns;\n"
        f"-- {matched_count} MATCHED/ALIAS_DRIFT (DRD verified by ODI);\n"
        f"-- {len(real_mismatch_cols)} REAL_MISMATCH (DRD used; ODI divergent);\n"
        f"-- {len(unresolvable_cols)} UNRESOLVABLE (DRD used; ODI complex);\n"
        f"-- {len(source_missing_cols)} SOURCE_MISSING (DRD used; ODI gap);\n"
        f"-- {len(recovered_from_prose_cols)} RECOVERED_FROM_PROSE (DRD prose; ODI's SQL realization projected with marker);\n"
        f"-- {len(complex_drd_expression_cols)} COMPLEX_DRD_EXPRESSION (DRD prose; no ODI expr available; NULL'd);\n"
        f"-- {len(null_substitutions)} NULL total (no DRD source or prose-only DRD);\n"
        f"-- {len(null_in_not_null_risk_cols)} NOT NULL constraint risk;\n"
        f"-- {len(join_derived)} JOIN clauses auto-derived from DRD;\n"
        f"-- {len(join_undetermined)} JOIN clauses need operator-supplied ON predicate.\n"
    )
    sql = (
        f"{header}\n"
        f"INSERT INTO {target_schema}.{target_table} (\n"
        f"    {col_list_sql}\n"
        f")\n"
        f"SELECT\n"
        + "\n".join(select_lines) + "\n"
        + "\n".join(from_clauses) + ";\n"
    )

    notes: List[str] = []
    if real_mismatch_cols:
        notes.append(
            f"{len(real_mismatch_cols)} REAL_MISMATCH columns: DRD source "
            f"projected (DRD is the spec); ODI divergence shown in comments."
        )
    if source_missing_cols:
        notes.append(
            f"{len(source_missing_cols)} SOURCE_MISSING columns: DRD source "
            f"projected; ODI does not provide the column (potential ODI gap)."
        )
    if complex_drd_expression_cols:
        notes.append(
            f"{len(complex_drd_expression_cols)} COMPLEX_DRD_EXPRESSION "
            f"columns ({', '.join(complex_drd_expression_cols[:5])}): "
            f"DRD wrote a prose rule; comparator MATCHED ODI's computed "
            f"expression.  Emitted as NULL with hint -- operator must "
            f"restructure DRD spec into table.column form for the "
            f"emitter to project it."
        )
    if null_in_not_null_risk_cols:
        notes.append(
            f"*** RUNTIME RISK: {len(null_in_not_null_risk_cols)} NULL "
            f"emission(s) target NOT NULL / PK column(s) "
            f"({', '.join(null_in_not_null_risk_cols[:5])}); will fail "
            f"with ORA-01400 unless DRD is populated."
        )
    if join_undetermined:
        notes.append(
            f"{len(join_undetermined)} JOIN clauses lack ON predicates "
            f"(emitted as CROSS JOIN + TODO marker).  Operator MUST "
            f"replace each CROSS JOIN with an ON clause before running."
        )

    return DrdDrivenInsert(
        sql=sql,
        column_count=len(target_cols),
        null_substitutions=null_substitutions,
        matched_count=matched_count,
        real_mismatch_cols=real_mismatch_cols,
        unresolvable_cols=unresolvable_cols,
        source_missing_cols=source_missing_cols,
        null_in_not_null_risk_cols=null_in_not_null_risk_cols,
        join_undetermined_tables=join_undetermined,
        join_derived_tables=join_derived,
        complex_drd_expression_cols=complex_drd_expression_cols,
        recovered_from_prose_cols=recovered_from_prose_cols,
        base_table=base_fq,
        aliases_used={f"{fq}@{disc}": alias for (fq, disc), alias in per_row_alias.items()},
        notes=notes,
        extraction_failed=False,
    )


# ── Back-compat aliases (Phase 7.5 callers expect ComparatorDrivenInsert
# and the old API surface) ────────────────────────────────────────────────────
ComparatorDrivenInsert = DrdDrivenInsert


def _extract_odi_using_subselect(final_select_sql: str) -> str:
    """Phase 7.5 helper retained for back-compat with existing tests.
    Phase 7.6 emitter no longer needs this -- DRD-driven projection
    does not project from ODI's USING(...) inner SELECT.  The helper
    is kept so existing unit tests that exercise the paren-walker
    invariants continue to pass."""
    if not final_select_sql:
        return ""
    upper = final_select_sql.upper()
    using_idx = upper.find("USING")
    if using_idx < 0:
        return ""
    paren_idx = final_select_sql.find("(", using_idx)
    if paren_idx < 0:
        return ""
    depth = 0
    end_idx = -1
    in_string = False
    in_line_comment = False
    in_block_comment = False
    s = final_select_sql
    i = paren_idx
    while i < len(s):
        c = s[i]
        if in_string:
            if c == "'":
                if i + 1 < len(s) and s[i + 1] == "'":
                    i += 2
                    continue
                in_string = False
            i += 1
            continue
        if in_line_comment:
            if c == "\n":
                in_line_comment = False
            i += 1
            continue
        if in_block_comment:
            if c == "*" and i + 1 < len(s) and s[i + 1] == "/":
                in_block_comment = False
                i += 2
                continue
            i += 1
            continue
        if c == "'":
            in_string = True
            i += 1
            continue
        if c == "-" and i + 1 < len(s) and s[i + 1] == "-":
            in_line_comment = True
            i += 2
            continue
        if c == "/" and i + 1 < len(s) and s[i + 1] == "*":
            in_block_comment = True
            i += 2
            continue
        if c == "(":
            depth += 1
        elif c == ")":
            depth -= 1
            if depth == 0:
                end_idx = i
                break
        i += 1
    if end_idx < 0:
        return ""
    return final_select_sql[paren_idx + 1:end_idx].strip()
