"""DRD-driven INSERT emitter that REUSES comparator's per-column DRD claim.

Operator-locked architecture (2026-05-30 Phase 7.6, corrects 7.5):

  Comparator already knows where each target column lives in the DRD
  (schema, table, attribute).  Reverse-engineering an INSERT means
  projecting FROM the DRD-stated source -- not from ODI's staging.

  ODI's role is VERIFICATION (per-row verdict tells us whether DRD's
  claim matches what ODI projects).  ODI is NEVER the source of the
  output; if ODI has bugs (REAL_MISMATCH), inheriting ODI's projection
  would propagate the bug.  The DRD specification is the truth.

Per-column emission:

  * MATCHED / ALIAS_DRIFT_ONLY -- project `<alias>.<drd_attr>` from
    DRD's stated source_table.  Comment: ODI verified.
  * REAL_MISMATCH               -- project `<alias>.<drd_attr>` from
    DRD's stated source_table.  Comment: WARNING -- ODI projects
    something different (operator sees the divergence).
  * UNRESOLVABLE                -- project DRD's stated source.
    Comment: ODI uses complex expression.
  * SOURCE_MISSING              -- DRD says X but no PDM entry;
    project `<alias>.<drd_attr>` from DRD's stated source with
    WARNING.  Operator decides whether to extend PDM, fix DRD, or
    deprecate.
  * ODI_EXTRA                   -- skip (DRD has no rule).

Alias map (DRD-driven):
  1. Base table  = most frequent source_table in comparison_results.
                   Alias = "t".
  2. Other tables -> derived alias (lowercased base name; numbered
                     suffix if collisions).
  3. Lookup tables (CL_VAL, _DIM, _MAP, _LKU, _LKUP) used by multiple
     rows with different discriminators (e.g. CL_SCM_ID=N) -> per-row
     numbered alias (CL_VAL_1, CL_VAL_2, ...).

JOIN clauses are built from DRD's source_table set.  Join keys are
derived from DRD's transformation text where the parser succeeds;
otherwise the emitter emits an explicit `CROSS JOIN` annotated with
`-- JOIN_UNDETERMINED: operator must specify` so nothing is hidden.

Output style:
  -- Generated by comparator_driven_emitter v2 (DRD-driven, ODI-verified)
  -- Source: DRD source_table.source_attribute per row (comparator-verified)
  -- DRD declares N target columns; M verified by ODI; K need operator review.
  INSERT INTO <target_schema>.<target_table> (
      <DRD col list, exact order>
  )
  SELECT
      t.<drd_attr_1>    AS <tgt_col_1>,    -- [MATCHED]
      apa.<drd_attr_2>  AS <tgt_col_2>,    -- [REAL_MISMATCH] DRD says X; ODI says Y
      NULL              AS <tgt_col_3>,    -- [SOURCE_MISSING]
      ...
  FROM <base_schema>.<base_table> t
  JOIN <other_schema>.<other_table> apa ON <derived ON clause>
  -- JOIN clauses where operator must add ON predicate are explicitly marked.
"""
from __future__ import annotations

import logging
import re
from collections import Counter
from dataclasses import dataclass, field
from typing import Any, Dict, List, Optional, Tuple

from app.sql_model.types import ComparisonVerdict, ODIModel
from app.sql_model.comparator import ComparisonResult


_log = logging.getLogger(__name__)

# Substrings that mark a table as a lookup / dimension whose use
# typically requires per-row discriminator-based aliasing.
_LOOKUP_TABLE_MARKERS = ("CL_VAL", "_DIM", "_MAP", "_LKU", "_LKUP")


@dataclass
class DrdDrivenInsert:
    sql: str
    column_count: int = 0
    null_substitutions: List[str] = field(default_factory=list)
    matched_count: int = 0
    real_mismatch_cols: List[str] = field(default_factory=list)
    unresolvable_cols: List[str] = field(default_factory=list)
    source_missing_cols: List[str] = field(default_factory=list)
    null_in_not_null_risk_cols: List[str] = field(default_factory=list)
    join_undetermined_tables: List[str] = field(default_factory=list)
    base_table: str = ""
    aliases_used: Dict[str, str] = field(default_factory=dict)
    notes: List[str] = field(default_factory=list)
    extraction_failed: bool = False
    extraction_failure_reason: str = ""


def _canonical_table(schema: str, table: str) -> str:
    """Lowercase normalised 'schema.table' or just 'table'."""
    schema = (schema or "").strip()
    table = (table or "").strip()
    if not table:
        return ""
    if schema:
        return f"{schema}.{table}".upper()
    return table.upper()


def _is_lookup_table(table: str) -> bool:
    t = (table or "").upper()
    return any(m in t for m in _LOOKUP_TABLE_MARKERS)


def _derive_alias(fq_table: str, used: set) -> str:
    """Derive a short alias from a fully-qualified table name.  Avoids
    collisions by appending a numeric suffix."""
    bare = fq_table.split(".")[-1].strip().lower()
    if not bare:
        bare = "src"
    base = bare
    i = 1
    while base in used:
        i += 1
        base = f"{bare}_{i}"
    used.add(base)
    return base


_DISC_RE = re.compile(
    r"\b(?:CL_SCM_ID|SCHEMA_ID|TYPE_ID|CATEGORY_ID|GROUP_ID)\s*=\s*(\d+)",
    re.IGNORECASE,
)


def _lookup_discriminator(transformation_text: str) -> str:
    """Extract a per-row discriminator (e.g. 'CL_SCM_ID = 114') from the
    DRD transformation text so the emitter can give each distinct lookup
    use its own alias instance (CL_VAL_1, CL_VAL_2, ...).  Returns ""
    when no discriminator is found."""
    if not transformation_text:
        return ""
    m = _DISC_RE.search(transformation_text)
    if m:
        return m.group(1)
    return ""


def _build_alias_map(
    rows: List[Tuple[str, str, str, str, str]],
) -> Tuple[str, Dict[Tuple[str, str], str], Dict[str, str]]:
    """Return (base_fq_table, per_row_alias_map, per_table_alias_map).

    `rows` is list of (target_col, fq_table, source_attr, drd_logic, verdict).

    - per_row_alias_map maps (fq_table, discriminator) -> alias.  Lookup
      tables get one alias per unique discriminator; non-lookup tables
      get a single shared alias keyed by (fq_table, "").
    - per_table_alias_map maps fq_table -> list of all aliases ever
      assigned for that table (used by JOIN-emit step).
    """
    # Pick base table = most-common non-lookup table
    counter: Counter = Counter()
    for _, fq, _, _, _ in rows:
        if not fq or _is_lookup_table(fq):
            continue
        counter[fq] += 1
    if not counter:
        # No non-lookup table; fall back to most common overall
        for _, fq, _, _, _ in rows:
            if fq:
                counter[fq] += 1
    base_fq = counter.most_common(1)[0][0] if counter else ""

    used_aliases: set = set()
    per_row: Dict[Tuple[str, str], str] = {}
    per_table: Dict[str, List[str]] = {}
    if base_fq:
        base_alias = "t"
        used_aliases.add(base_alias)
        per_row[(base_fq, "")] = base_alias
        per_table[base_fq] = [base_alias]

    for _, fq, _, drd_logic, _ in rows:
        if not fq or fq == base_fq:
            continue
        if _is_lookup_table(fq):
            disc = _lookup_discriminator(drd_logic)
            key = (fq, disc)
        else:
            key = (fq, "")
        if key in per_row:
            continue
        alias = _derive_alias(fq, used_aliases)
        per_row[key] = alias
        per_table.setdefault(fq, []).append(alias)

    return base_fq, per_row, per_table


def _alias_for_row(
    fq_table: str, drd_logic: str, base_fq: str,
    per_row: Dict[Tuple[str, str], str],
) -> str:
    """Pick the correct alias for a single row."""
    if not fq_table:
        return ""
    if fq_table == base_fq:
        return per_row.get((base_fq, ""), "t")
    if _is_lookup_table(fq_table):
        disc = _lookup_discriminator(drd_logic)
        return per_row.get((fq_table, disc), "")
    return per_row.get((fq_table, ""), "")


def emit_insert_comparator_driven(
    target_schema: str,
    target_table: str,
    drd_rows: List[Dict[str, Any]],
    comparison_results: List[ComparisonResult],
    odi_model: ODIModel,
    target_definition: Optional[Dict[str, Any]] = None,
) -> DrdDrivenInsert:
    """Build a target INSERT that projects from DRD-stated sources for
    every target column, using the comparator's per-row DRD claim and
    verdict as the sole drivers.

    `odi_model` is accepted for API symmetry but used only to compute
    ODI annotations (no SQL inherited from ODI).
    """
    # Build a lookup by target_col so we can iterate in DRD row order.
    by_target: Dict[str, ComparisonResult] = {
        (r.target_col or "").strip().upper(): r for r in comparison_results
    }

    # NOT NULL / PK column set for constraint cross-check.
    not_null_cols: set = set()
    if target_definition:
        for c in target_definition.get("columns", []) or []:
            name = (c.get("name") or "").strip().upper()
            if not name:
                continue
            if c.get("is_pk") or not c.get("nullable", True):
                not_null_cols.add(name)

    # Collect ordered (target_col, fq_table, drd_attr, drd_logic, verdict)
    tuples: List[Tuple[str, str, str, str, str]] = []
    seen_targets: set = set()
    for drd_row in drd_rows:
        col = (drd_row.get("physical_name") or drd_row.get("column") or "").strip().upper()
        if not col or col in seen_targets:
            continue
        seen_targets.add(col)
        res = by_target.get(col)
        if res is None:
            tuples.append((col, "", "", "", ""))
            continue
        fq = _canonical_table(res.drd_schema, res.drd_table)
        tuples.append((
            col,
            fq,
            (res.drd_attr or "").strip(),
            (res.drd_logic or "").strip(),
            res.verdict.value if res.verdict else "",
        ))

    if not tuples:
        return DrdDrivenInsert(
            sql="",
            notes=["DRD has zero target columns; cannot emit INSERT."],
            extraction_failed=True,
            extraction_failure_reason="empty drd_rows",
        )

    base_fq, per_row_alias, per_table_alias = _build_alias_map(tuples)
    if not base_fq:
        return DrdDrivenInsert(
            sql="",
            notes=[
                "Could not pick a base table (no rows had a usable "
                "source_table).  Operator must populate DRD source_table "
                "before this emitter can produce SQL."
            ],
            extraction_failed=True,
            extraction_failure_reason="no base table",
        )

    null_substitutions: List[str] = []
    real_mismatch_cols: List[str] = []
    unresolvable_cols: List[str] = []
    source_missing_cols: List[str] = []
    null_in_not_null_risk_cols: List[str] = []
    matched_count = 0
    proj_pairs: List[Tuple[str, str]] = []

    for col, fq, drd_attr, drd_logic, verdict in tuples:
        res = by_target.get(col)
        if not drd_attr or not fq:
            # DRD did not state a clear source; honest NULL.
            if col in not_null_cols:
                null_in_not_null_risk_cols.append(col)
            null_substitutions.append(col)
            proj_pairs.append((
                "NULL",
                f"DRD did not state a source for {col}; "
                f"projecting NULL.  Operator must populate DRD or "
                f"accept the NULL."
            ))
            continue
        if verdict == ComparisonVerdict.ODI_EXTRA.value:
            # Defensive (should not happen if drd_rows drives the loop).
            null_substitutions.append(col)
            proj_pairs.append((
                "NULL",
                f"[BUG] ODI_EXTRA verdict on DRD-declared column "
                f"{col!r}; comparator may have mis-routed this row."
            ))
            continue

        alias = _alias_for_row(fq, drd_logic, base_fq, per_row_alias)
        if not alias:
            null_substitutions.append(col)
            proj_pairs.append((
                "NULL",
                f"ALIAS_RESOLVE_FAIL: could not derive an alias for "
                f"DRD source {fq}.{drd_attr} (col {col}). Operator "
                f"must check DRD source_table."
            ))
            continue

        proj_expr = f"{alias}.{drd_attr}"

        # Verdict annotation (ODI verifies DRD; ODI is NEVER the source).
        if verdict == ComparisonVerdict.MATCHED.value:
            matched_count += 1
            comment = (
                f"[MATCHED] DRD source verified against ODI "
                f"(ODI projects {res.odi_table}.{res.odi_col})"
            )
        elif verdict == ComparisonVerdict.ALIAS_DRIFT_ONLY.value:
            matched_count += 1
            comment = (
                f"[ALIAS_DRIFT_ONLY] DRD source verified -- same physical "
                f"column under a different alias in ODI."
            )
        elif verdict == ComparisonVerdict.REAL_MISMATCH.value:
            real_mismatch_cols.append(col)
            comment = (
                f"[REAL_MISMATCH] DRD source {fq}.{drd_attr} used; "
                f"ODI projects DIFFERENT value: "
                f"{res.odi_table}.{res.odi_col}. "
                f"Operator must reconcile DRD vs ODI."
            )
        elif verdict == ComparisonVerdict.UNRESOLVABLE.value:
            unresolvable_cols.append(col)
            comment = (
                f"[UNRESOLVABLE] DRD source used; ODI emits complex "
                f"expression: {(res.odi_expr_sql or '')[:60]!r}. "
                f"Operator should confirm equivalence."
            )
        elif verdict == ComparisonVerdict.SOURCE_MISSING.value:
            source_missing_cols.append(col)
            comment = (
                f"[SOURCE_MISSING] DRD source {fq}.{drd_attr} used; "
                f"ODI does NOT project this target column anywhere. "
                f"Operator must extend ODI or accept gap."
            )
        else:
            comment = (
                f"[NO_VERDICT or unknown verdict {verdict!r}] -- "
                f"DRD source used.  Operator review."
            )

        proj_pairs.append((proj_expr, comment))

    # ── Compose SELECT projection (comma BEFORE comment for Oracle) ──────
    select_lines: List[str] = []
    last_idx = len(proj_pairs) - 1
    for i, (expr, comment) in enumerate(proj_pairs):
        sep = "" if i == last_idx else ","
        # Compute padded expression for readability + risk marker.
        col = tuples[i][0]
        if expr == "NULL" and col in not_null_cols:
            null_in_not_null_risk_cols.append(col)
            comment = (
                comment + " *** OPERATOR MUST REVIEW: target column is "
                "NOT NULL / PK; runtime ORA-01400. ***"
            )
        clean_comment = re.sub(r"[\r\n\t]+", " ", comment or "").strip()
        select_lines.append(f"    {expr:30s}AS {col}{sep}  -- {clean_comment}")

    # ── Build FROM + JOIN clauses (DRD-driven) ───────────────────────────
    base_alias = per_row_alias[(base_fq, "")]
    base_parts = base_fq.split(".", 1)
    if len(base_parts) == 2:
        base_sql_table = f"{base_parts[0]}.{base_parts[1]}"
    else:
        base_sql_table = base_fq
    from_clauses: List[str] = [f"FROM {base_sql_table} {base_alias}"]
    join_undetermined: List[str] = []
    # Walk per_row_alias map and emit one JOIN per (fq_table, discriminator).
    seen_aliases: set = {base_alias}
    for (fq, disc), alias in per_row_alias.items():
        if alias in seen_aliases:
            continue
        seen_aliases.add(alias)
        parts = fq.split(".", 1)
        if len(parts) == 2:
            sql_table = f"{parts[0]}.{parts[1]}"
        else:
            sql_table = fq
        # Without DRD-derived JOIN keys this emitter cannot produce a
        # valid ON clause; emit explicit CROSS JOIN + warning so
        # operator sees the gap (nothing silent).
        if _is_lookup_table(fq) and disc:
            from_clauses.append(
                f"  -- TODO: replace CROSS JOIN with ON clause using "
                f"discriminator {disc} for lookup {fq}"
            )
        else:
            from_clauses.append(
                f"  -- TODO: replace CROSS JOIN with operator-supplied "
                f"ON clause for {fq}"
            )
        from_clauses.append(f"  CROSS JOIN {sql_table} {alias}")
        join_undetermined.append(f"{alias}={fq}")

    # ── Compose final SQL ────────────────────────────────────────────────
    target_cols = [t[0] for t in tuples]
    col_list_sql = ",\n    ".join(target_cols)
    header = (
        f"-- Generated by comparator_driven_emitter v2 (DRD-driven; ODI verifies)\n"
        f"-- Source per row: DRD source_table.source_attribute (NOT ODI staging).\n"
        f"-- Operator-locked architecture (2026-05-30 Phase 7.6).\n"
        f"-- DRD declares {len(target_cols)} target columns;\n"
        f"-- {matched_count} MATCHED/ALIAS_DRIFT (DRD verified by ODI);\n"
        f"-- {len(real_mismatch_cols)} REAL_MISMATCH (DRD used; ODI divergent);\n"
        f"-- {len(unresolvable_cols)} UNRESOLVABLE (DRD used; ODI complex);\n"
        f"-- {len(source_missing_cols)} SOURCE_MISSING (DRD used; ODI gap);\n"
        f"-- {len(null_substitutions)} NULL (no DRD source given);\n"
        f"-- {len(null_in_not_null_risk_cols)} NOT NULL constraint risk;\n"
        f"-- {len(join_undetermined)} JOIN clauses need operator-supplied ON predicate.\n"
    )
    sql = (
        f"{header}\n"
        f"INSERT INTO {target_schema}.{target_table} (\n"
        f"    {col_list_sql}\n"
        f")\n"
        f"SELECT\n"
        + "\n".join(select_lines) + "\n"
        + "\n".join(from_clauses) + ";\n"
    )

    notes: List[str] = []
    if real_mismatch_cols:
        notes.append(
            f"{len(real_mismatch_cols)} REAL_MISMATCH columns: DRD source "
            f"projected (DRD is the spec); ODI divergence shown in comments."
        )
    if source_missing_cols:
        notes.append(
            f"{len(source_missing_cols)} SOURCE_MISSING columns: DRD source "
            f"projected; ODI does not provide the column (potential ODI gap)."
        )
    if null_in_not_null_risk_cols:
        notes.append(
            f"*** RUNTIME RISK: {len(null_in_not_null_risk_cols)} NULL "
            f"emission(s) target NOT NULL / PK column(s) "
            f"({', '.join(null_in_not_null_risk_cols[:5])}); will fail "
            f"with ORA-01400 unless DRD is populated."
        )
    if join_undetermined:
        notes.append(
            f"{len(join_undetermined)} JOIN clauses lack ON predicates "
            f"(emitted as CROSS JOIN + TODO marker).  Operator MUST "
            f"replace each CROSS JOIN with an ON clause before running."
        )

    return DrdDrivenInsert(
        sql=sql,
        column_count=len(target_cols),
        null_substitutions=null_substitutions,
        matched_count=matched_count,
        real_mismatch_cols=real_mismatch_cols,
        unresolvable_cols=unresolvable_cols,
        source_missing_cols=source_missing_cols,
        null_in_not_null_risk_cols=null_in_not_null_risk_cols,
        join_undetermined_tables=join_undetermined,
        base_table=base_fq,
        aliases_used={f"{fq}@{disc}": alias for (fq, disc), alias in per_row_alias.items()},
        notes=notes,
        extraction_failed=False,
    )


# ── Back-compat aliases (Phase 7.5 callers expect ComparatorDrivenInsert
# and the old API surface) ────────────────────────────────────────────────────
ComparatorDrivenInsert = DrdDrivenInsert


def _extract_odi_using_subselect(final_select_sql: str) -> str:
    """Phase 7.5 helper retained for back-compat with existing tests.
    Phase 7.6 emitter no longer needs this -- DRD-driven projection
    does not project from ODI's USING(...) inner SELECT.  The helper
    is kept so existing unit tests that exercise the paren-walker
    invariants continue to pass."""
    if not final_select_sql:
        return ""
    upper = final_select_sql.upper()
    using_idx = upper.find("USING")
    if using_idx < 0:
        return ""
    paren_idx = final_select_sql.find("(", using_idx)
    if paren_idx < 0:
        return ""
    depth = 0
    end_idx = -1
    in_string = False
    in_line_comment = False
    in_block_comment = False
    s = final_select_sql
    i = paren_idx
    while i < len(s):
        c = s[i]
        if in_string:
            if c == "'":
                if i + 1 < len(s) and s[i + 1] == "'":
                    i += 2
                    continue
                in_string = False
            i += 1
            continue
        if in_line_comment:
            if c == "\n":
                in_line_comment = False
            i += 1
            continue
        if in_block_comment:
            if c == "*" and i + 1 < len(s) and s[i + 1] == "/":
                in_block_comment = False
                i += 2
                continue
            i += 1
            continue
        if c == "'":
            in_string = True
            i += 1
            continue
        if c == "-" and i + 1 < len(s) and s[i + 1] == "-":
            in_line_comment = True
            i += 2
            continue
        if c == "/" and i + 1 < len(s) and s[i + 1] == "*":
            in_block_comment = True
            i += 2
            continue
        if c == "(":
            depth += 1
        elif c == ")":
            depth -= 1
            if depth == 0:
                end_idx = i
                break
        i += 1
    if end_idx < 0:
        return ""
    return final_select_sql[paren_idx + 1:end_idx].strip()
