SELECT
    B.SRC_TXN_TP AS SHDW_TXN_TP_CD,
    J27.SRC_TXN_TP_NM AS SHDW_TXN_TP_NM,
    B.SRC_ACTN_CODE AS IMP_SRC_ACTN_CD,
    J28.desc_text AS IMP_SRC_ACTN_NM,
    B.SRC_BUY_SELL_MULTI_ID AS SIS_DLTD_EV_ID,
    J3.CL_VAL_NM AS SIS_DLTD_EV_NM,
    B.USR_ID AS SIS_USR_ID,
    B.SRC_PRIM_CL AS SIS_AC_CL_CD,
    B.SRC_CNCL_RSN_ID AS SRC_CNCL_RSN_ID,
    J3.CL_VAL_CODE AS SRC_CNCL_RSN_CD,
    J3.CL_VAL_NM AS SRC_CNCL_RSN_NM,
    B.SRC_TXN_SEQ_NUM AS SRC_TXN_SEQ_NUM,
    B.DVDN_RCRD_DT AS DVDN_RCRD_DT,
    B.SALE_PSN_NUM AS OWN_IMP_FA_NUM,
    J29.FA_NUM AS OWN_FA_NUM,
    J18.FA_NUMBER_ENTITY_CODE AS OWN_FA_NUM_ENT_CD,
    J18.RESPONSIBLE_PARTY_EMPLOYEE_ID AS FA_OWN_EMPE_ID,
    J30.ENTITY_ENTERPRISE_ID AS OWN_FA_NUM_ENT_ENTP_ID,
    B.ORIG_SRC_STM_CODE AS ACAT_CNTRA_FIRM_CLRG_NUM,
    J8.BROKER_NAME AS ACAT_CNTRA_FIRM_NM,
    J8.BROKER_SHORT_NAME AS ACAT_CNTRA_FIRM_SHRT_NM,
    J8.BROKER_ID_TYPE AS ACAT_CNTRA_FIRM_CLRG_ID_TP_CD,
    B.ORIG_SRC_STM_CODE AS MM_ALT_ID,
    J4.ORIG_SRC_STM_CD AS AR_ORIG_SRC_STM_CD,
    B.SRC_STM_ID AS SRC_STM_ID,
    J7.SRC_STM_NM AS SRC_STM_NM,
    B.SRC_CXL_REV AS SRC_CNCL_X_RVSN_CD,
    B.SRC_OPT_CLS AS SRC_OPT_CLSS_CD,
    B.TXN_REPL_CNT AS TXN_RCNCL_REPL_CNT,
    B.TXN_ST_ID AS TXN_RCNCL_ST_ID,
    J3.CL_VAL_CODE AS TXN_RCNCL_ST_CD,
    J3.CL_VAL_NM AS TXN_RCNCL_ST_NM,
    J4.MF_DRC_EXT_AC_NUM AS MF_AC_NUM,
    J4.ORIG_SRC_STM_AR_ID AS OFST_ORIG_SRC_STM_AR_ID,
    J4.ORIG_SRC_STM_CD AS OFST_AR_ORIG_SRC_STM_CD,
    J4.SETL_TP_CD AS OFST_AR_SETL_TP_CD,
    J4.SETL_TP AS OFST_AR_SETL_TP_DSC,
    J4.SETL_TP_CD AS AR_SETL_TP_CD,
    J4.SETL_TP AS AR_SETL_TP_DSC,
    CAST(NULL AS VARCHAR2(50)) AS ORIG_SRC_STM_AR_ID,
    J19.DT_DIM_ID AS TD_DIM_ID,
    J20.EXG_DIM_ID AS EXG_DIM_ID,
    J9.ACG_TP_CD AS ACG_TP_CD,
    J9.ACG_TP_DIM_ID AS ACG_TP_DIM_ID,
    J9.ACG_TP_NM AS ACG_TP_NM,
    J2.ACG_TP_ID AS ACG_TP_ID,
    B.ACTV_F AS ACTV_F,
    B.AR_ID AS AR_ID,
    J31.BATCH_DT AS BATCH_DT,
    B.BKG_DT AS BKG_DT,
    B.BR_CODE AS BR_CD,
    CAST(NULL AS NUMBER) AS BKR_AR_ID,
    B.BUY_SELL_IND AS BUY_SELL_IND,
    J5.AVY_CGY AS CASH_AVY_CGY,
    J5.DSPL_AVY_CGY AS CASH_SIMP_DSPL_AVY_CGY,
    J10.AVY_CL_ID AS CSH_AVY_CL_ID,
    J5.AVY_TP AS CASH_AVY_TP,
    J5.DSPL_AVY_TP AS CASH_SIMP_DSPL_AVY_TP,
    J2.ALT_DSC AS CASH_ALT_DSC_TRAILER_2,
    J2.APA_EXT_QUALFR AS CASH_APA_EXT_QUALFR,
    J2.APA_ID AS CSH_APA_ID,
    J3.CL_VAL_CODE AS CASH_APA_TP_CD,
    J3.DSC AS CASH_APA_TP_DSC,
    J2.APA_TP_ID AS CSH_APA_TP_ID,
    J3.CL_VAL_NM AS CASH_APA_TP_NM,
    J32.CIRD_PD_ID AS CASH_CIRD_PD_ID,
    J3.CL_VAL_CODE AS CASH_DB_CR_CD,
    J3.CL_VAL_NM AS CASH_DB_CR_NM,
    J2.APA_DSC AS CASH_DSC_TRAILER_1,
    B.CF_GEN_F AS CF_GEN_F,
    J11.CASH_POS_TP_CD AS CASH_POS_TP_CD,
    J11.CASH_POS_TP_DIM_ID AS CASH_POS_TP_DIM_ID,
    J11.CASH_POS_TP_NM AS CASH_POS_TP_NM,
    J2.CASH_POS_TP_ID AS CASH_POS_TP_ID,
    J2.PD_ID AS CASH_PD_ID,
    J21.IMT_PD_DIM_ID AS CASH_PD_DIM_ID,
    J2.SRC_SEQ_NUM AS CASH_SRC_SEQ_NUM,
    J2.STM_BASE_CCY_AMT AS CASH_SBC_AMT,
    J2.TXN_AMT AS CASH_TXN_AMT,
    J2.CLNT_FRIENDLY_DESC AS CLNT_FRIENDLY_DSC,
    B.CRT_DTM AS CRT_DTM,
    B.CRT_USR_NM AS CRT_USR_NM,
    J2.txn_iso_ccy_code AS CCY_CD,
    J22.CCY_DIM_ID AS CCY_DIM_ID,
    J3.CL_VAL_CODE AS DOL_IND_CD,
    B.DOL_IND_ID AS DOL_IND_ID,
    J3.CL_VAL_NM AS DOL_IND_NM,
    B.EXG_CODE AS EXG_CD,
    J20.EXG_NM AS EXG_NM,
    B.EXEC_DTM AS EXEC_DTM,
    J3.CL_VAL_CODE AS EXEC_SBTP_CD,
    J3.DSC AS EXEC_SBTP_DSC,
    B.EXEC_SBTP_ID AS EXEC_SBTP_ID,
    J3.CL_VAL_NM AS EXEC_SBTP_NM,
    J3.CL_VAL_CODE AS EXEC_TP_CD,
    J3.DSC AS EXEC_TP_DSC,
    B.EXEC_TP_ID AS EXEC_TP_ID,
    J3.CL_VAL_NM AS EXEC_TP_NM,
    B.FA_NUM AS FA_NUM,
    J12.LGCY_CNCL_CMPLN_RSN_TP_CD AS LGCY_CNCL_CMPLN_RSN_TP_CD,
    J12.LGCY_CNCL_CMPLN_RSN_TP_DIM_ID AS LGCY_CNCL_CMPLN_RSN_DIM_ID,
    J12.LGCY_CNCL_CMPLN_RSN_TP_NM AS LGCY_CNCL_CMPLN_RSN_TP_NM,
    B.LGCY_CNCL_CMPLN_RSN_TP_ID AS LGCY_CNCL_CMPLN_RSN_TP_ID,
    J13.LGCY_CNCL_CMPLN_SRC_TP_CD AS LGCY_CNCL_CMPLN_SRC_TP_CD,
    J13.LGCY_CNCL_CMPLN_SRC_TP_DIM_ID AS LGCY_CNCL_CMPLN_SRC_DIM_ID,
    J13.LGCY_CNCL_CMPLN_SRC_TP_NM AS LGCY_CNCL_CMPLN_SRC_TP_NM,
    B.LGCY_CNCL_CMPLN_SRC_TP_ID AS LGCY_CNCL_CMPLN_SRC_TP_ID,
    J14.LGCY_MKT_TP_CD AS LGCY_MKT_TP_CD,
    J14.LGCY_MKT_TP_DIM_ID AS LGCY_MKT_TP_DIM_ID,
    J14.LGCY_MKT_TP_NM AS LGCY_MKT_TP_NM,
    B.LGCY_MKT_TP_ID AS LGCY_MKT_TP_ID,
    CAST(NULL AS VARCHAR2(20)) AS LGCY_TRD_CPCTY_TP_CD,
    J33.LGCY_TRD_CPCTY_TP_DIM_ID AS LGCY_TRD_CPCTY_TP_DIM_ID,
    CAST(NULL AS VARCHAR2(200)) AS LGCY_TRD_CPCTY_TP_NM,
    B.LGCY_TRD_CPCTY_TP_ID AS LGCY_TRD_CPCTY_TP_ID,
    J2.OFST_AR_ID AS OFST_AR_ID,
    B.OPTS_CLSS_CODE AS OPT_CLSS_CD,
    J3.CL_VAL_CODE AS OMS_EXEC_TP_CD,
    J3.DSC AS OMS_EXEC_TP_DSC,
    B.OMS_EXEC_TP_ID AS OMS_EXEC_TP_ID,
    J3.CL_VAL_NM AS OMS_EXEC_TP_NM,
    B.OMS_ORDR_KEY AS OMS_ORDR_KEY,
    B.ORIG_BKG_DT AS ORIG_BKG_DT,
    B.ORIG_TRD_NUM AS ORIG_TRD_NUM,
    B.ORIG_TD AS ORIG_TD,
    J7.SRC_STM_DIM_ID AS REL_TXN_SRC_STM_DIM_ID,
    CAST(NULL AS NUMBER) AS REL_TXN_SRC_STM_ID,
    J7.SRC_STM_CD AS REL_TXN_SRC_STM_CD,
    J24.TXN_RLTNP_TP_ID AS REL_TXN_RLTNP_TP_ID,
    J3.CL_VAL_CODE AS REL_TXN_RLTNP_TP_CD,
    J3.CL_VAL_NM AS REL_TXN_RLTNP_TP_NM,
    J2.SALE_CHRG_RATE AS SALE_CHRG_RATE_MULTI_NUM,
    J2.SALE_CHRG_RATE AS SALE_CHRG_RATE_PCT,
    J3.CL_VAL_CODE AS SALE_CHRG_RATE_TP_CD,
    J2.SALE_CHRG_RATE_TP_ID AS SALE_CHRG_RATE_TP_ID,
    J3.CL_VAL_NM AS SALE_CHRG_RATE_TP_NM,
    J5.AVY_CGY AS SCR_AVY_CGY,
    J5.DSPL_AVY_CGY AS SCR_SIMP_DSPL_AVY_CGY,
    J5.AVY_CL_ID AS SEC_AVY_CL_ID,
    J5.AVY_TP AS SCR_AVY_TP,
    J5.DSPL_AVY_TP AS SCR_SIMP_DSPL_AVY_TP,
    J2.ALT_DSC AS SEC_ALT_DSC_TRAILER_2,
    J2.APA_EXT_QUALFR AS SEC_APA_EXT_QUALFR,
    J2.APA_ID AS SEC_APA_ID,
    J3.CL_VAL_CODE AS SCR_APA_TP_CD,
    J3.DSC AS SCR_APA_TP_DSC,
    J2.APA_TP_ID AS SEC_APA_TP_ID,
    J3.CL_VAL_NM AS SCR_APA_TP_NM,
    J34.CIRD_PD_ID AS SEC_CIRD_PD_ID,
    J3.CL_VAL_CODE AS SEC_DB_CR_CD,
    J3.CL_VAL_NM AS SEC_DB_CR_NM,
    J2.APA_DSC AS SEC_DSC_TRAILER_1,
    J2.ORIG_QTY AS SEC_ORIG_QTY,
    J2.PD_ID AS SEC_PD_ID,
    J21.IMT_PD_DIM_ID AS SEC_PD_DIM_ID,
    J2.SCR_PRC_IN_TXN_CCY AS SEC_PRC_IN_TXN_CCY,
    J2.SCR_PRC_IN_SBC AS SEC_SRC_PRC_IN_SBC,
    J2.SRC_SEQ_NUM AS SEC_SRC_SEQ_NUM,
    J2.STM_BASE_CCY_AMT AS SEC_SBC_AMT,
    J2.TXN_AMT AS SEC_TXN_AMT,
    B.SD AS SD,
    J19.DT_DIM_ID AS SD_DIM_ID,
    B.SRC_CRT_USRNM AS SRC_CRT_USRNM,
    J2.SRC_EFF_DT AS SRC_EFF_DT,
    J15.SRC_ENTR_CNL_TP_CD AS SRC_ENTR_CNL_TP_CD,
    J15.SRC_ENTR_CNL_TP_DIM_ID AS SRC_ENTR_CNL_TP_DIM_ID,
    J15.SRC_ENTR_CNL_TP_NM AS SRC_ENTR_CNL_TP_NM,
    B.SRC_ENTR_CNL_TP_ID AS SRC_ENTR_CNL_TP_ID,
    B.SRC_ENTR_DTM AS SRC_ENTR_DTM,
    J16.SRC_PCS_TP_DIM_ID AS SRC_PCS_TP_DIM_ID,
    B.SRC_PCS_TP_ID AS SRC_PCS_TP_ID,
    J16.SRC_PCS_TP_CD AS SRC_PCS_TP_CD,
    J16.SRC_PCS_TP_NM AS SRC_PCS_TP_NM,
    J7.SRC_STM_CD AS SRC_STM_CD,
    J7.SRC_STM_DIM_ID AS TXN_SRC_STM_DIM_ID,
    B.SRC_TXN_CODE AS SRC_TXN_CODE,
    J2.STM_BASE_CCY_CLC_DTM AS SBC_CCY_CALC_DT,
    J2.STM_BASE_ISO_CCY_CODE AS SBC_CCY_CD,
    J22.CCY_DIM_ID AS SBC_CCY_DIM_ID,
    J2.STM_BASE_CCY_EXG_RATE AS SBC_EXG_RATE,
    J24.TRGT_TXN_ID AS REL_TXN_ID,
    B.TD AS TD,
    B.TRD_NUM AS TRD_NUM,
    J17.TRD_SLCT_TP_DIM_ID AS TRD_SLCT_TP_DIM_ID,
    B.TRD_SLCT_TP_ID AS TRD_SLCT_TP_ID,
    J17.TRD_SLCT_TP_CD AS TRD_SLCT_TP_CD,
    J17.TRD_SLCT_TP_NM AS TRD_SLCT_TP_NM,
    B.TXN_CL_F AS TXN_CL_F,
    B.TXN_ID AS TXN_ID,
    B.TXN_SRC_KEY AS TXN_SRC_KEY,
    J3.CL_VAL_CODE AS TXN_SUB_TP_CD,
    J3.DSC AS TXN_SUB_TP_DSC,
    B.TXN_SBTP_ID AS TXN_SBTP_ID,
    J3.CL_VAL_NM AS TXN_SUB_TP_NM,
    J3.CL_VAL_CODE AS TXN_TP_CD,
    J3.DSC AS TXN_TP_DSC,
    B.TXN_TP_ID AS TXN_TP_ID,
    J3.CL_VAL_NM AS TXN_TP_NM,
    B.ORIG_SRC_STM_ID AS ORIG_SRC_STM_ID,
    B.ORIG_SRC_STM_CODE AS ORIG_SRC_STM_CD,
    J4.AR_DIM_ID AS BKR_AR_DIM_ID,
    J4.AR_DIM_ID AS OFST_AR_DIM_ID,
    J4.AR_DIM_ID AS AR_DIM_ID,
    B.LAST_UDT_USR_NM AS LAST_UDT_USR_NM,
    B.LAST_UDT_DTM AS LAST_UDT_DTM,
    B.SESS_NO AS SESS_NO,
    J2.OPT_SYMB AS SCR_OPT_SYMB,
    J3.CL_VAL_CODE AS DRVD_TRD_CPCTY_CD,
    J3.CL_VAL_NM AS DRVD_TRD_CPCTY_NM,
    B.DRVD_TRD_CPCTY_TP_ID AS DRVD_TRD_CPCTY_ID,
    B.ADL_TRD_INSR AS ADL_TRD_INSR,
    J2.TRD_FCTR_RATE AS TRD_FCTR_RATE,
    J2.MRKUP_RATE AS MRKUP_RATE,
    J2.STD_CMSN_AMT AS STD_CMSN_AMT,
    J6.STM_BASE_CCY_AMT AS ACT_CMSN_AMT,
    J6.STM_BASE_CCY_AMT AS TRD_PCS_FEE_AMT,
    J6.STM_BASE_CCY_AMT AS SEC_FEE_AMT,
    J6.STM_BASE_CCY_AMT AS ACR_INT_AMT,
    J6.STM_BASE_CCY_AMT AS CNCSN_AMT,
    CAST(NULL AS NUMBER) AS CDSC_AMT,
    CAST(NULL AS NUMBER) AS OTHR_FEE_AMT,
    B.TRD_CNCLD_F AS TRD_CNCLD_F,
    J2.SYMB AS SYMB,
    J2.ISIN AS ISIN,
    J25.SRC_TAX_CODE AS TXN_SRC_TAX_CD,
    J25.SRC_TAX_CODE_DSC AS TXN_SRC_TAX_CD_DSC,
    J10.NNA_CGY_ID AS CASH_NNA_CGY_ID,
    J26.NNA_CGY_NM AS CASH_NNA_CGY_NM,
    J10.NNA_CGY_ID AS SCR_NNA_CGY_ID,
    J26.NNA_CGY_NM AS SCR_NNA_CGY_NM
FROM CCAL_REPL_OWNER.TXN B
LEFT JOIN CCAL_REPL_OWNER.SHDW_TXN_TP J27
    ON TXN.SRC_TXN_TP = SHDW_TXN_TP.SRC_TXN_TP
LEFT JOIN REFERENCE_REPL_OWNER.IMPCT_ACTION_LKU J28
    ON t.src_actn_code = impct_action_lku.action_code
LEFT JOIN CCAL_REPL_OWNER.CL_VAL J3
    ON cv.cl_val_id = t.SRC_BUY_SELL_MULTI_ID and cv.CL_SCM_ID = '99'
LEFT JOIN CCAL_REPL_OWNER.CL_VAL J3
    ON cl_val.cl_val_id = t.SRC_CNCL_RSN_ID cs.cl_scm_id = '102'
LEFT JOIN CCSI_OWNER.AR_GRP_SUBDIM J29
    ON t.AR_ID = fa.AR_ID and t.td >= fa.EFF_DT and t.td < fa.END_DT
LEFT JOIN SSDS_DAL_OWNER.FA_NUMBER_V J18
    ON OWN_FA_NUM field. left join SSDS_DAL_OWNER.FA_NUMBER_V fn on fn.FA_NUMBER = OWN_FA_NUM and t.td >= fn.EFF_DT AND t.td < fn.END_DT
LEFT JOIN SSDS_DAL_OWNER.ENTERPRISE_ENTITY_DIM_V J30
    ON OWN_FA_NUM_ENT_CD field. LEFT JOIN SSDS_DAL_OWNER.ENTERPRISE_ENTITY_DIM_V e ON e.Entity_code_long = OWN_FA_NUM_ENT_CD AND t.td >= e.EFF_DT AND t.td < e.END_DT AND e.ENTITY_RECYCLED_BOOLEAN='0' AND e.ENTITY_FINANCIAL_RIA_BOOLEAN = '0'
LEFT JOIN CCAL_REPL_OWNER.ACATS_BROKER J8
    ON b.broker_id = t.orig_src_stm_code and t.src_stm_id IN ( 53, 54 )
LEFT JOIN CCSI_OWNER.AR_DIM J4
    ON ard.AR_ID = t.AR_ID and ard.eff_dt <= t.td and ard.end_dt > t.td
LEFT JOIN COMMON_OWNER.SRC_STM_DIM J7
    ON t.src_stm_id = ss.src_stm_id
LEFT JOIN CCAL_REPL_OWNER.CL_VAL J3
    ON cv.cl_val_id = t.txn_st_id and cv.CL_SCM_ID = 12
LEFT JOIN CCSI_OWNER.AR_DIM J4
    ON ap.exec_id = t.txn_id left join ccsi_owner.ar_dim ad ON AP.OFST_AR_ID = ad.AR_ID and t.td >= ad.EFF_DT and t.td < ad.END_DT
LEFT JOIN COMMON_OWNER.DATE_DIM J19
    ON t.td = dd.cal_dt
LEFT JOIN CIRD_OWNER.EXG_DIM J20
    ON ed.EXG_CD = t.exg_code
LEFT JOIN COMMON_OWNER.ACG_TP_DIM J9
    ON ap.exec_id = t.txn_id left join common_owner.acg_tp_dim atd ON AP.ACG_TP_ID = atd.ACG_TP_ID
LEFT JOIN CCAL_REPL_OWNER.APA J2
    ON ap.exec_id = t.txn_id
LEFT JOIN CCAL_REPL_OWNER.J$TXN J31
    ON jt.txn_id = t.txn_id
LEFT JOIN CCAL_REPL_OWNER.AVY_CL J5
    ON ap.exec_id = t.txn_id left join ccal_repl_owner.txn_avy_cl tac ON tac.txn_id = t.txn_id and tac.actv_f = 'Y' and ap.apa_id = tac.apa_id left join ccal_repl_owner.avy_cl acl ON acl.avy_cl_id = tac.avy_cl_id
LEFT JOIN CCAL_REPL_OWNER.TXN_AVY_CL J10
    ON ap.exec_id = t.txn_id left join ccal_repl_owner.txn_avy_cl tac ON tac.txn_id = t.txn_id and tac.actv_f = 'Y' and ap.apa_id = tac.apa_id
LEFT JOIN CCAL_REPL_OWNER.CCAL_CIRD_PD_MAP J32
    ON ap.pd_id = ccpd.ccal_pd_id and ccpm.actv_f = 'Y'
LEFT JOIN CCAL_REPL_OWNER.CL_VAL J3
    ON ap.db_cr_id = cv.cl_val_id and cv.cl_scm_id = '15'
LEFT JOIN COMMON_OWNER.CASH_POS_TP_DIM J11
    ON ap.CASH_POS_TP_ID = cptd.CASH_POS_TP_ID
LEFT JOIN CIRD_OWNER.IMT_PD_DIM J21
    ON ap.exec_id = t.txn_id LEFT join cird_owner.imt_pd_dim ipd ON ipd.CCAL_PD_ID = ap.PD_ID and ipd.eff_dt <= t.td and ipd.end_dt > t.td
LEFT JOIN CIRD_OWNER.CCY_DIM J22
    ON ap.exec_id = t.txn_id left join cird_owner.ccy_dim cd ON cd.ccy_cd = ap.txn_iso_ccy_code
LEFT JOIN CCAL_REPL_OWNER.CL_VAL J3
    ON t.dol_ind_id = cv.cl_val_id and cv.cl_scm_id = '35'
LEFT JOIN CCAL_REPL_OWNER.CL_VAL J3
    ON t.EXEC_SBTP_ID = cv.CL_VAL_ID and cv.cl_scm_id = '6'
LEFT JOIN CCAL_REPL_OWNER.CL_VAL J3
    ON t.EXEC_TP_ID = cv.CL_VAL_ID and cv.cl_scm_id = '5'
LEFT JOIN TRANSACTIONS_OWNER.LGCY_CNCL_CMPLN_RSN_TP_DIM J12
    ON ld.lgcy_cncl_cmpln_rsn_tp_id = t.lgcy_cncl_cmpln_rsn_tp_id
LEFT JOIN TRANSACTIONS_OWNER.LGCY_CNCL_CMPLN_SRC_TP_DIM J13
    ON ld.lgcy_cncl_cmpln_src_tp_id = t.lgcy_cncl_cmpln_src_tp_id
LEFT JOIN TRANSACTIONS_OWNER.LGCY_MKT_TP_DIM J14
    ON lmtd.lgcy_mkt_tp_id = t.lgcy_mkt_tp_id
LEFT JOIN TRANSACTIONS_OWNER.LGCY_TRD_CPCTY_TP_DIM J33
    ON t.lgcy_trd_cpcty_tp_id = ltctd.lgcy_trd_cpcty_tp_id
LEFT JOIN CCAL_REPL_OWNER.CL_VAL J3
    ON cv.cl_val_id = t.oms_exec_tp_id and cv.cl_scm_id = '96'
LEFT JOIN CCAL_REPL_OWNER.CL_VAL J3
    ON ap.exec_id = t.txn_id left join ccal_repl_owner.cl_val cv ON cv.cl_val_id = t.oms_exec_tp_id and cv.cl_scm_id = '96'
LEFT JOIN COMMON_OWNER.SRC_STM_DIM J7
    ON t.txn_id = tr.src_txn_id and tr.actv_f = 'Y' left join ccal_repl_owner.txn t2 ON tr.trgt_txn_id = t2.txn_id left join ccal_repl_owner.src_stm_dim stm ON t2.src_stm_id = stm.src_stm_id
LEFT JOIN CCAL_REPL_OWNER.TXN_RLTNP J24
    ON t.txn_id = tr.src_txn_id and tr.actv_f = 'Y'
LEFT JOIN CCAL_REPL_OWNER.CL_VAL J3
    ON t.txn_id = tr.src_txn_id and tr.actv_f = 'Y' left join ccal_repl_owner.cl_val cv ON cl_val_id = tr.TXN_RLTNP_TP_ID and cv.cl_scm_id = '4'
LEFT JOIN CCAL_REPL_OWNER.APA J2
    ON ap.exec_id = t.txn_id left join ccal_repl_owner.cl_val cv ON AP.APA_TP_ID = cv.CL_VAL_ID AND CASE WHEN AP.SALE_CHRG_RATE_TP_ID = 2507 THEN AP.SALE_CHRG_RATE
LEFT JOIN CCAL_REPL_OWNER.APA J2
    ON ap.exec_id = t.txn_id left join ccal_repl_owner.cl_val cv ON AP.APA_TP_ID = cv.CL_VAL_ID AND CASE WHEN AP.SALE_CHRG_RATE_TP_ID = 2506 THEN AP.SALE_CHRG_RATE
LEFT JOIN CCAL_REPL_OWNER.CL_VAL J3
    ON cv.cl_val_id = ap.sale_chrg_rate_tp_id and cv.cl_scm_id = '73'
LEFT JOIN CCAL_REPL_OWNER.APA J2
    ON this field is always null, so there is no need to expose this field in view.
LEFT JOIN CCAL_REPL_OWNER.ccal_cird_pd_map J34
    ON ap.exec_id = t.txn_id left join ccal_repl_owner.ccal_cird_pd_map ccpm on ccpm.ccal_pd_id = ap.pd_id and ccpm.actv_f = 'Y'
LEFT JOIN CCAL_REPL_OWNER.CL_VAL J3
    ON cv.cl_val_id = ap.db_cr_id dci and cv.cl_scm_id = '15'
LEFT JOIN COMMON_OWNER.DATE_DIM J19
    ON t.sd = dd.cal_dt
LEFT JOIN TRANSACTIONS_OWNER.SRC_ENTR_CNL_TP_DIM J15
    ON t.src_entr_cnl_tp_id = sectd.src_entr_cnl_tp_id
LEFT JOIN TRANSACTIONS_OWNER.SRC_PCS_TP_DIM J16
    ON t.src_pcs_tp_id = sptd.src_pcs_tp_id
LEFT JOIN COMMON_OWNER.SRC_STM_DIM J7
    ON ssd.src_stm_id = t.src_stm_id
LEFT JOIN CIRD_OWNER.CCY_DIM J22
    ON ap.stm_base_iso_ccy_code = cd.ccy_cd
LEFT JOIN TRANSACTIONS_OWNER.TRD_SLCT_TP_DIM J17
    ON t.trd_slct_tp_id = tstd.trd_slct_tp_id
LEFT JOIN CCAL_REPL_OWNER.CL_VAL J3
    ON cv.cl_val_id = t.txn_sbtp_id and cv.cl_scm_id = '3'
LEFT JOIN CCAL_REPL_OWNER.CL_VAL J3
    ON cv.cl_val_id = t.txn_tp_id and cv.cl_scm_id = '2'
LEFT JOIN CCSI_OWNER.AR_DIM J4
    ON the lookup for BKR_AR_ID
LEFT JOIN CCSI_OWNER.AR_DIM J4
    ON ap.exec_id = t.txn_id LEFT join ccsi_repl_owner.ar_dim ard ON ard.AR_ID = ap.OFST_AR_ID and ard.eff_dt <= t.td and ard.end_dt > t.td
LEFT JOIN CCAL_REPL_OWNER.TXN_SRC_TAX_CODE_LKUP J25
    ON TXN.SRC_TAX_CODE_ID = LKP.SRC_TAX_CODE_ID and LKP.ACTV_F = 'Y'
LEFT JOIN CCAL_REPL_OWNER.TXN_AVY_CL J10
    ON ap.exec_id = t.txn_id left join ccal_repl_owner.txn_avy_cl tac ON tac.txn_id = t.txn_id and tac.actv_f = 'Y' and ap.apa_id = tac.apa_id left join ccal_repl_owner.avy_cl acl ON acl.avy_cl_id = tac.avy_cl_id
LEFT JOIN CCAL_REPL_OWNER.NNA_CGY J26
    ON ap.exec_id = t.txn_id left join ccal_repl_owner.txn_avy_cl tac ON tac.txn_id = t.txn_id and tac.actv_f = 'Y' and ap.apa_id = tac.apa_id left join ccal_repl_owner.net_new _ast_cgy nna ON nna.net_new_ast_cgy_id = tac.net_new_ast_cgy_id