-- Validation 1: Table exists and column count
SELECT COUNT(*) AS COL_COUNT FROM ALL_TAB_COLUMNS WHERE OWNER='SSDS_TRANSACTIONS_OWNER' AND TABLE_NAME='AVY_FACT_SIDE';

-- Validation 2: Row count
SELECT COUNT(*) AS ROW_COUNT FROM SSDS_TRANSACTIONS_OWNER.AVY_FACT_SIDE;

-- Validation 3: Column listing
SELECT COLUMN_NAME, DATA_TYPE, DATA_LENGTH, NULLABLE FROM ALL_TAB_COLUMNS WHERE OWNER='SSDS_TRANSACTIONS_OWNER' AND TABLE_NAME='AVY_FACT_SIDE' ORDER BY COLUMN_ID;
