-- TEST 1: Table exists with expected column count
SELECT COUNT(*) AS COL_COUNT FROM ALL_TAB_COLUMNS 
WHERE OWNER='TRANSACTIONS_OWNER' AND TABLE_NAME='AVY_FACT_SIDE';

-- TEST 2: Row count
SELECT COUNT(*) AS ROW_COUNT FROM TRANSACTIONS_OWNER.AVY_FACT_SIDE;

-- TEST 3: Verify key columns are populated (sample top 10 rows)
SELECT TXN_ID, TD, AR_ID, SRC_STM_ID, TXN_TP_CD, BUY_SELL_IND
FROM TRANSACTIONS_OWNER.AVY_FACT_SIDE
WHERE ROWNUM <= 10;

-- TEST 4: Validate data type distribution
SELECT DATA_TYPE, COUNT(*) AS CNT
FROM ALL_TAB_COLUMNS 
WHERE OWNER='TRANSACTIONS_OWNER' AND TABLE_NAME='AVY_FACT_SIDE'
GROUP BY DATA_TYPE
ORDER BY CNT DESC;

-- TEST 5: NULL percentage on key columns (sample 1000 rows)
SELECT 
    COUNT(*) AS TOTAL_ROWS,
    SUM(CASE WHEN TXN_ID IS NULL THEN 1 ELSE 0 END) AS NULL_TXN_ID,
    SUM(CASE WHEN TD IS NULL THEN 1 ELSE 0 END) AS NULL_TD,
    SUM(CASE WHEN AR_ID IS NULL THEN 1 ELSE 0 END) AS NULL_AR_ID,
    SUM(CASE WHEN SRC_STM_ID IS NULL THEN 1 ELSE 0 END) AS NULL_SRC_STM_ID,
    SUM(CASE WHEN SHDW_TXN_TP_CD IS NULL THEN 1 ELSE 0 END) AS NULL_SHDW_TXN_TP_CD
FROM (SELECT * FROM TRANSACTIONS_OWNER.AVY_FACT_SIDE WHERE ROWNUM <= 1000);

-- TEST 6: Check dimension ID validity
SELECT 
    COUNT(*) AS TOTAL,
    SUM(CASE WHEN EXG_DIM_ID = 0 THEN 1 ELSE 0 END) AS DEFAULT_EXG_DIM,
    SUM(CASE WHEN AR_DIM_ID = 0 THEN 1 ELSE 0 END) AS DEFAULT_AR_DIM,
    SUM(CASE WHEN TD_DIM_ID = 0 THEN 1 ELSE 0 END) AS DEFAULT_TD_DIM
FROM (SELECT * FROM TRANSACTIONS_OWNER.AVY_FACT_SIDE WHERE ROWNUM <= 1000);

-- TEST 7: Date range validation
SELECT 
    MIN(TD) AS MIN_TD,
    MAX(TD) AS MAX_TD,
    MIN(SD) AS MIN_SD,
    MAX(SD) AS MAX_SD,
    COUNT(DISTINCT TRUNC(TD)) AS DISTINCT_TRADE_DATES
FROM TRANSACTIONS_OWNER.AVY_FACT_SIDE
WHERE ROWNUM <= 10000;

-- TEST 8: Source system distribution
SELECT SRC_STM_CD, SRC_STM_NM, COUNT(*) AS CNT
FROM TRANSACTIONS_OWNER.AVY_FACT_SIDE
WHERE ROWNUM <= 50000
GROUP BY SRC_STM_CD, SRC_STM_NM
ORDER BY CNT DESC;

-- TEST 9: Transaction type coverage
SELECT TXN_TP_CD, TXN_TP_NM, COUNT(*) AS CNT
FROM TRANSACTIONS_OWNER.AVY_FACT_SIDE
WHERE ROWNUM <= 50000
GROUP BY TXN_TP_CD, TXN_TP_NM
ORDER BY CNT DESC;

-- TEST 10: Shadow transaction type values
SELECT SHDW_TXN_TP_CD, COUNT(*) AS CNT
FROM TRANSACTIONS_OWNER.AVY_FACT_SIDE
WHERE ROWNUM <= 50000
GROUP BY SHDW_TXN_TP_CD
ORDER BY CNT DESC;
