INSERT INTO TAXLOTS_OWNER.OPN_TAX_LOTS_NON_BKR_FACT (
    SRC_STM_CD,
    AR_ID,
    CIRD_PD_ID,
    CCAL_PD_ID,
    ACG_TP_CD,
    TAX_LOT_EXT_REFR_KEY_PRIM,
    TAX_LOT_EXT_REFR_KEY_SCDY,
    TAX_LOT_EXT_REFR_KEY_TRTY,
    TAX_LOT_EXT_REFR_KEY_QTRNY,
    END_DT,
    EFF_DT,
    ACG_TP_NM,
    ACQ_DT,
    ADJ_COST,
    CCY_CD,
    CTF_NUM,
    CTF_NUM_PFX,
    COST_BSS_LEGS_CVR_CD,
    DISALWD_WASH_SALE_AMT,
    EXG_RATE,
    FAIR_MKT_VAL_OF_GIFT_OR_INHTN,
    GIFT_DT,
    POS_INCPTN_DT,
    LONG_SHRT_POS_CD,
    LOSS_NOT_ALWD_F,
    LIFE_TO_DTD_MKT_DCN,
    MISS_COST_BSS_F,
    ADJ_COST_NOT_ACRT_F,
    OPN_PRC_FCTR,
    OPN_TXN_EV_TP,
    COST_AMT,
    ORIG_EV_TP,
    ORIG_PRC,
    ORIG_PROCD,
    ORIG_TXN_TP_CD,
    PREM_AMT,
    QTY,
    SRC_RCRD_TP_CD,
    RVST_LOT_F,
    SD,
    TRD_NUM,
    TXN_INTT_DT,
    TXN_TP_CD,
    UC,
    SBC_UC,
    WASH_SALE_F,
    ZERO_COST_BSS_F,
    WASH_SALE_TP,
    SBC_DISALWD_WASH_SALE_AMT,
    SBC_ADJ_COST,
    SBC_FAIR_MKT_VAL,
    SBC_OPN_PRC_FCTR,
    SBC_COST_AMT,
    SBC_ORIG_PRC,
    SBC_ORIG_PROCD,
    SRC_STM_ID,
    SRC_STM_NM,
    ACG_TP_ID,
    TAX_LOT_TP,
    COST_BSS_LEGS_CVR_F,
    MISS_IVS_COST_F,
    SESN_NUM,
    CRT_DTM,
    CRT_USR_NM,
    LAST_UDT_DTM,
    LAST_UDT_USR_NM
)
SELECT

    SRC_STM_DIM.SRC_STM_CD AS SRC_STM_CD,

    OPN_TAX_LOTS_NONBKR_TGT.AR_ID AS AR_ID,

    CCAL_CIRD_PD_MAP.CIRD_PD_ID AS CIRD_PD_ID,

    OPN_TAX_LOTS_NONBKR_TGT.CCAL_PD_ID AS CCAL_PD_ID,

    OPN_TAX_LOTS_NONBKR_TGT.AC_TP_CODE AS ACG_TP_CD,

    OPN_TAX_LOTS_NONBKR_TGT.TAX_LOT_EXT_REFR_KEY_PRIM AS TAX_LOT_EXT_REFR_KEY_PRIM,

    OPN_TAX_LOTS_NONBKR_TGT.TAX_LOT_EXT_REFR_KEY_SCDY AS TAX_LOT_EXT_REFR_KEY_SCDY,

    OPN_TAX_LOTS_NONBKR_TGT.TAX_LOT_EXT_REFR_KEY_TRTY AS TAX_LOT_EXT_REFR_KEY_TRTY,

    OPN_TAX_LOTS_NONBKR_TGT.TAX_LOT_EXT_REFR_KEY_QTRNY AS TAX_LOT_EXT_REFR_KEY_QTRNY,

    OPN_TAX_LOTS_NONBKR_TGT.EFF_TO_DT AS END_DT,

    OPN_TAX_LOTS_NONBKR_TGT.EFF_FM_DT AS EFF_DT,

    ACG_TP_DIM.ACG_TP_NM AS ACG_TP_NM,

    OPN_TAX_LOTS_NONBKR_TGT.ACQ_DT AS ACQ_DT,

    case when (CCY_CODE ='USD' or (SBC_EXG_RATE is NULL OR SBC_EXG_RATE = 0)) THEN ADJ_COST ELSE ADJ_COST * SBC_EXG_RATE END AS ADJ_COST,

    OPN_TAX_LOTS_NONBKR_TGT.STM_BASE_ISO_CCY_CODE AS CCY_CD,

    OPN_TAX_LOTS_NONBKR_TGT.TAX_LOT_CTF_NUM AS CTF_NUM,

    OPN_TAX_LOTS_NONBKR_TGT.TAX_LOT_CTF_NUM_PFX AS CTF_NUM_PFX,

    OPN_TAX_LOTS_NONBKR_TGT.CVRD_UNCVRD AS COST_BSS_LEGS_CVR_CD,

    OPN_TAX_LOTS_NONBKR_TGT.SBC_WASH_SALE_AMT AS DISALWD_WASH_SALE_AMT,

    OPN_TAX_LOTS_NONBKR_TGT.SBC_EXG_RATE AS EXG_RATE,

    case when (CCY_CODE ='USD' or (SBC_EXG_RATE is NULL OR SBC_EXG_RATE = 0)) THEN FMV ELSE FMV * SBC_EXG_RATE END AS FAIR_MKT_VAL_OF_GIFT_OR_INHTN,

    OPN_TAX_LOTS_NONBKR_TGT.GIFT_DT AS GIFT_DT,

    OPN_TAX_LOTS_NONBKR_TGT.POS_INCPTN_DT AS POS_INCPTN_DT,

    OPN_TAX_LOTS_NONBKR_TGT.POS_LONG_SHRT_CODE AS LONG_SHRT_POS_CD,

    NULL AS LOSS_NOT_ALWD_F,

    NULL AS LIFE_TO_DTD_MKT_DCN,

    CASE WHEN (OPN_TAX_LOTS_NONBKR_TGT.MISS_COST_F = 'Y' OR OPN_TAX_LOTS_NONBKR_TGT.null_bss_f = 'Y') THEN 'Y' ELSE 'N' END AS MISS_COST_BSS_F,

    OPN_TAX_LOTS_NONBKR_TGT.NULL_BSS_F AS ADJ_COST_NOT_ACRT_F,

    case when (CCY_CODE ='USD' or (SBC_EXG_RATE is NULL OR SBC_EXG_RATE = 0)) THEN OPN_FCTR ELSE OPN_FCTR * SBC_EXG_RATE END AS OPN_PRC_FCTR,

    OPN_TXN_EV_TP_CL_VAL.CL_VAL_NM AS OPN_TXN_EV_TP,

    case when (CCY_CODE ='USD' or (SBC_EXG_RATE is NULL OR SBC_EXG_RATE = 0)) THEN ORIG_COST ELSE ORIG_COST * SBC_EXG_RATE END AS COST_AMT,

    NULL AS ORIG_EV_TP,

    case when (CCY_CODE ='USD' or (SBC_EXG_RATE is NULL OR SBC_EXG_RATE = 0)) THEN ORIG_PRC ELSE ORIG_PRC * SBC_EXG_RATE END AS ORIG_PRC,

    case when (CCY_CODE ='USD' or (SBC_EXG_RATE is NULL OR SBC_EXG_RATE = 0)) THEN ORIG_PROCD ELSE ORIG_PROCD * SBC_EXG_RATE END AS ORIG_PROCD,

    NULL AS ORIG_TXN_TP_CD,

    NULL AS PREM_AMT,

    OPN_TAX_LOTS_NONBKR_TGT.TAX_LOT_ASOF_QTY AS QTY,

    SRC_RCRD_TP_CD_CL_VAL.CL_VAL_CD AS SRC_RCRD_TP_CD,

    OPN_TAX_LOTS_NONBKR_TGT.RVST_F AS RVST_LOT_F,

    OPN_TAX_LOTS_NONBKR_TGT.SD AS SD,

    OPN_TAX_LOTS_NONBKR_TGT.TRD_NUM AS TRD_NUM,

    OPN_TAX_LOTS_NONBKR_TGT.TXN_INIT_DT AS TXN_INTT_DT,

    NULL AS TXN_TP_CD,

    case when (CCY_CODE ='USD' or (SBC_EXG_RATE is NULL OR SBC_EXG_RATE = 0)) THEN UC ELSE UC * SBC_EXG_RATE END AS UC,

    case when (CCY_CODE ='USD' or (SBC_EXG_RATE is NULL OR SBC_EXG_RATE = 0)) THEN UC ELSE UC * SBC_EXG_RATE END AS SBC_UC,

    OPN_TAX_LOTS_NONBKR_TGT.WASH_SALE_F AS WASH_SALE_F,

    OPN_TAX_LOTS_NONBKR_TGT.ZERO_BSS_IND_F AS ZERO_COST_BSS_F,

    CASE WHEN OPN_TAX_LOTS_NONBKR_TGT.WASH_SALE_IND ='Y' AND OPN_TAX_LOTS_NONBKR_TGT.DISALWD_WASHSALE_AMT = 0 THEN 'CBW' WHEN OPN_TAX_LOTS_NONBKR_TGT.WASH_SALE_IND ='Y' AND OPN_TAX_LOTS_NONBKR_TGT.DISALWD_WASHSALE_AMT > 0 THEN 'BOTHW' WHEN OPN_TAX_LOTS_NONBKR_TGT.WASH_SALE_IND <> 'Y' AND OPN_TAX_LOTS_NONBKR_TGT.DISALWD_WASHSALE_AMT > 0 THEN 'GLW' END AS WASH_SALE_TP,

    OPN_TAX_LOTS_NONBKR_TGT.SBC_WASH_SALE_AMT AS SBC_DISALWD_WASH_SALE_AMT,

    case when (CCY_CODE ='USD' or (SBC_EXG_RATE is NULL OR SBC_EXG_RATE = 0)) THEN ADJ_COST ELSE ADJ_COST * SBC_EXG_RATE END AS SBC_ADJ_COST,

    case when (CCY_CODE ='USD' or (SBC_EXG_RATE is NULL OR SBC_EXG_RATE = 0)) THEN FMV ELSE FMV * SBC_EXG_RATE END AS SBC_FAIR_MKT_VAL,

    case when (CCY_CODE ='USD' or (SBC_EXG_RATE is NULL OR SBC_EXG_RATE = 0)) THEN OPN_FCTR ELSE OPN_FCTR * SBC_EXG_RATE END AS SBC_OPN_PRC_FCTR,

    case when (CCY_CODE ='USD' or (SBC_EXG_RATE is NULL OR SBC_EXG_RATE = 0)) THEN ORIG_COST ELSE ORIG_COST * SBC_EXG_RATE END AS SBC_COST_AMT,

    case when (CCY_CODE ='USD' or (SBC_EXG_RATE is NULL OR SBC_EXG_RATE = 0)) THEN ORIG_PRC ELSE ORIG_PRC * SBC_EXG_RATE END AS SBC_ORIG_PRC,

    case when (CCY_CODE ='USD' or (SBC_EXG_RATE is NULL OR SBC_EXG_RATE = 0)) THEN ORIG_PROCD ELSE ORIG_PROCD * SBC_EXG_RATE END AS SBC_ORIG_PROCD,

    OPN_TAX_LOTS_NONBKR_TGT.SRC_STM_ID AS SRC_STM_ID,

    SRC_STM_DIM.SRC_STM_NM AS SRC_STM_NM,

    ACG_TP_DIM.ACG_TP_ID AS ACG_TP_ID,

    TAX_LOT_TP_CL_VAL.CL_VAL_NM AS TAX_LOT_TP,

    case when OPN_TAX_LOTS_NONBKR_TGT.CVRD_UNCVRD = 'C' then 'Y' else 'N' end AS COST_BSS_LEGS_CVR_F,

    CASE WHEN (OPN_TAX_LOTS_NONBKR_TGT.RVST_F<>'Y' AND (OPN_TAX_LOTS_NONBKR_TGT.MISS_COST_F = 'Y' OR OPN_TAX_LOTS_NONBKR_TGT.null_bss_f = 'Y')) THEN 'Y' ELSE 'N' END AS MISS_IVS_COST_F,

    NULL AS SESN_NUM,

    NULL AS CRT_DTM,

    NULL AS CRT_USR_NM,

    NULL AS LAST_UDT_DTM,

    NULL AS LAST_UDT_USR_NM
FROM TAXLOT_STG_OWNER.OPN_TAX_LOTS_NONBKR_TGT OPN_TAX_LOTS_NONBKR_TGT
    LEFT JOIN COMMON_OWNER.SRC_STM_DIM SRC_STM_DIM ON OPN_TAX_LOTS_NONBKR_TGT.SRC_STM_ID = SRC_STM_DIM.SRC_STM_ID
    LEFT JOIN CCAL_REPL_OWNER.CCAL_CIRD_PD_MAP CCAL_CIRD_PD_MAP ON CCAL_CIRD_PD_MAP.CCAL_PD_ID = OPN_TAX_LOTS_NONBKR_TGT.CCAL_PD_ID AND CCAL_CIRD_PD_MAP.ACTV_F = 'Y'
    LEFT JOIN COMMON_OWNER.ACG_TP_DIM ACG_TP_DIM ON ACG_TP_DIM.ACG_TP_CD = OPN_TAX_LOTS_NONBKR_TGT.AC_TP_CODE
    LEFT JOIN CCAL_REPL_OWNER.CL_VAL OPN_TXN_EV_TP_CL_VAL ON OPN_TXN_EV_TP_CL_VAL.CL_VAL_ID = OPN_TAX_LOTS_NONBKR_TGT.TAX_LOT_TXN_EV_TP_ID AND OPN_TXN_EV_TP_CL_VAL.CL_SCM_ID = 86
    LEFT JOIN CCAL_REPL_OWNER.CL_VAL SRC_RCRD_TP_CD_CL_VAL ON SRC_RCRD_TP_CD_CL_VAL.CL_VAL_ID = OPN_TAX_LOTS_NONBKR_TGT.SRC_RCRD_TP_ID
    LEFT JOIN CCAL_REPL_OWNER.CL_VAL TAX_LOT_TP_CL_VAL ON TAX_LOT_TP_CL_VAL.CL_VAL_ID = OPN_TAX_LOTS_NONBKR_TGT.TAX_LOT_TXN_TP_ID AND TAX_LOT_TP_CL_VAL.CL_SCM_ID = 84  ;
