-- Generated by drd_first_emitter v1
-- Target: IKOROSTELEV.AVY_FACT_SIDE
-- Columns: 369  Joins: 73  CTEs: 2
-- Provenance: DRD_INLINE_FALLBACK=2, DRD_PHYSICAL=134, DRD_PHYSICAL_FALLBACK=1, ETL_DEFAULT=7, NULL_FALLBACK=1, ODI=224

-- ETL Notes block(s) referenced by some DRD col-AD cells; the
-- emitter projects from each column's physical DRD source_attribute
-- and annotates the projection with the referenced block name so
-- the operator can apply the prose filter rule (e.g. APASEC/APACSH
-- subset selection) by hand.
-- ETL_BLOCK[PRODUCT_INFORMATION]:
--   (Security source CUSIP, Security Product Id, Security CIRD Product Id, Security Option Symbol, Symbol, ISIN, Product Composite Description, Product Short Name, Product Description)
--   If there is atleast 1 APASEC, consider above fields from that APASEC
--   If there is an iAPASEC but no APASEC, consider above fields from iAPASEC
--
--   Source Effective Date:
--   If there is only iAPASEC or only iAPACSH, grab source effective date from the iAPASEC/iAPACSH
--   If there is atleast 1 APASEC or APACSH, grab source effective date from that APASEC/APACSH
--   Updates from below user names should be skipped by main process (Product Backlog Item 1937973: Skip Activity updates from additional usernames)
--   CCAL_PKG_TXN_RECON_REPL (EOD CCAL Recon Replay)
--   PERF_MAP_CF_MASTER_STG_PROC (Cash Flow Generation)
--   CCAL_PKG_TXN_POS_RECON_STS_UPD (EOD CCAL Recon)
--   CCAL_PERF_PKG_CF_MSTR_LOAD_RJTRST  (Cash Flow Generation)
--   CCAL_PKG_TXN_POS_RECON (EOD CCAL Recon)
--   CCAL_PKG_TXN_RECON_RJTRUST_1 (EOD CCAL Recon)
--   PERF_PKG_CF_MSTR_LOAD (Cash Flow Generation)
--   CCAL_PKG_TXN_RECON_SHADOW_1 (EOD CCAL Recon)
--   CCAL_PKG_LOAD_TXN_AY_CL_1 (Activity Reclassification)
--   CCAL_PKG_LOAD_TXN_AY_CL_2 (Activity Reclassification)
--   CCAL_PKG_LOAD_TXN_AY_CL_3 (Activity Reclassification)
--   CCAL_PKG_LOAD_TXN_AY_CL_4 (Activity Reclassification)
--   CCAL_PKG_LOAD_TXN_AY_CL_5 (Activity Reclassification)
--   CCAL_PKG_LOAD_TXN_AY_CL_6 (Activity Reclassification)
--   CCAL_PKG_LOAD_TXN_AY_CL_7 (Activity Reclassification)
--   CCAL_PKG_LOAD_TXN_AY_CL_8 (Activity Reclassification)
--   CCAL_PKG_LOAD_TXN_AY_CL_9 (Activity Reclassification)
--   CCAL_PKG_LOAD_TXN_AY_CL_10 (Activity Reclassification)
--   Update Trade Cancelled Flag on original trade when cancellation arrives (Product Backlog Item 2030710: Add columns available in DWH and missing in Lighthouse for Trade Activity)
-- ETL_BLOCK[APACASH]:
--   Check for regexp_like(cv.cl_val_code,'^APACSH[0-7][0-9]')
--   For a Transaction, 
--   If only one record exists then consider that record.
--   If 2 records exists ( 
--        If (one record is 'APACSH04' & other is 'APACSH11') 
--             then consider skip 'APACSH04' record and load 'APACSH11' but use the values to
--             (1) calculate aggregated value from APA.TXN_AMT fields from 'APACSH04' and 'APACSH11' and store it in Cash Transaction Amount and Cash System base currency amount
--             (2) populate sales charge attributes from 'APACSH04' for 5 attributes (Sales Charge Rate Multiplier Number, Sales Charge Rate, Sales Charge Rate Type Code, Sales Charge Rate Type Id, Sales Charge Rate Type Name)
--        else Drop those 2 records exception entire transaction
--   )
--
--   APASEC :
--   Check for cl_val_Code like '^APASEC[0-7][0-9]' THEN consider as 'Security' record.
--
--   iAPASEC/iAPACSH:
--   Refer to below section for further filter criteria on iAPASEC/iAPACSH. Applicable to both iAPACSH and iAPASEC.
TRUNCATE TABLE IKOROSTELEV.AVY_FACT_SIDE;
INSERT /*+ APPEND PARALLEL(8) */ INTO IKOROSTELEV.AVY_FACT_SIDE (
    EXG_DIM_ID,
    AR_DIM_ID,
    OFST_AR_DIM_ID,
    ACG_TP_DIM_ID,
    CASH_POS_TP_DIM_ID,
    SBC_CCY_DIM_ID,
    SEC_PD_DIM_ID,
    CASH_PD_DIM_ID,
    LGCY_CNCL_CMPLN_RSN_DIM_ID,
    LGCY_CNCL_CMPLN_SRC_DIM_ID,
    LGCY_MKT_TP_DIM_ID,
    LGCY_TRD_CPCTY_TP_DIM_ID,
    SRC_PCS_TP_DIM_ID,
    SRC_ENTR_CNL_TP_DIM_ID,
    TRD_SLCT_TP_DIM_ID,
    TXN_SRC_STM_DIM_ID,
    REL_TXN_SRC_STM_DIM_ID,
    BKR_AR_DIM_ID,
    TD_DIM_ID,
    TD,
    SD_DIM_ID,
    SD,
    BKG_DT,
    ORIG_BKG_DT,
    EXEC_DTM,
    TXN_ID,
    REL_TXN_ID,
    TRD_NUM,
    ORIG_TRD_NUM,
    TXN_SRC_KEY,
    SEC_APA_ID,
    CSH_APA_ID,
    SEC_PRC_IN_TXN_CCY,
    SEC_TXN_AMT,
    CASH_TXN_AMT,
    SEC_ORIG_QTY,
    SEC_SRC_PRC_IN_SBC,
    SALE_CHRG_RATE_PCT,
    SALE_CHRG_RATE_TP_ID,
    SALE_CHRG_RATE_TP_CD,
    SEC_SBC_AMT,
    CASH_SBC_AMT,
    SBC_CCY_CALC_DT,
    SBC_EXG_RATE,
    CASH_DB_CR_CD,
    SEC_DB_CR_CD,
    SEC_SRC_SEQ_NUM,
    SEC_APA_EXT_QUALFR,
    SEC_DSC_TRAILER_1,
    SEC_ALT_DSC_TRAILER_2,
    BUY_SELL_IND,
    CF_GEN_F,
    TXN_CL_F,
    OPT_CLSS_CD,
    SEC_SRC_CUSIP,
    CASH_DSC_TRAILER_1,
    CASH_ALT_DSC_TRAILER_2,
    CASH_SRC_SEQ_NUM,
    TXN_TP_ID,
    TXN_TP_CD,
    TXN_TP_NM,
    TXN_TP_DSC,
    TXN_SBTP_ID,
    TXN_SUB_TP_NM,
    TXN_SUB_TP_CD,
    TXN_SUB_TP_DSC,
    EXEC_TP_ID,
    EXEC_TP_CD,
    EXEC_TP_NM,
    EXEC_TP_DSC,
    EXEC_SBTP_CD,
    EXEC_SBTP_NM,
    EXEC_SBTP_DSC,
    EXEC_SBTP_ID,
    SEC_APA_TP_ID,
    SCR_APA_TP_CD,
    SCR_APA_TP_NM,
    SCR_APA_TP_DSC,
    CSH_APA_TP_ID,
    CASH_APA_TP_CD,
    CASH_APA_TP_NM,
    CASH_APA_TP_DSC,
    SCR_AVY_CGY,
    SCR_AVY_TP,
    SEC_AVY_CL_ID,
    CASH_AVY_CGY,
    CASH_AVY_TP,
    CSH_AVY_CL_ID,
    CRT_DTM,
    CRT_USR_NM,
    SESS_NO,
    SRC_ENTR_DTM,
    AR_ID,
    SEC_PD_ID,
    CASH_PD_ID,
    BKR_AR_ID,
    OFST_AR_ID,
    BR_CD,
    FA_NUM,
    SRC_CRT_USRNM,
    ORIG_TD,
    SRC_PCS_TP_CD,
    SRC_PCS_TP_NM,
    CCY_DIM_ID,
    CCY_CD,
    SBC_CCY_CD,
    SRC_EFF_DT,
    DOL_IND_ID,
    DOL_IND_CD,
    DOL_IND_NM,
    OMS_ORDR_KEY,
    EXG_CD,
    EXG_NM,
    ACG_TP_CD,
    ACG_TP_NM,
    CASH_POS_TP_CD,
    CASH_POS_TP_NM,
    LGCY_CNCL_CMPLN_RSN_TP_CD,
    LGCY_CNCL_CMPLN_RSN_TP_NM,
    LGCY_CNCL_CMPLN_SRC_TP_CD,
    LGCY_CNCL_CMPLN_SRC_TP_NM,
    LGCY_MKT_TP_CD,
    LGCY_MKT_TP_NM,
    LGCY_TRD_CPCTY_TP_CD,
    LGCY_TRD_CPCTY_TP_NM,
    SRC_ENTR_CNL_TP_CD,
    SRC_ENTR_CNL_TP_NM,
    TRD_SLCT_TP_CD,
    TRD_SLCT_TP_NM,
    SALE_CHRG_RATE_TP_NM,
    CASH_DB_CR_NM,
    SEC_DB_CR_NM,
    SRC_STM_CD,
    BATCH_DT,
    CASH_CIRD_PD_ID,
    SEC_CIRD_PD_ID,
    ACTV_F,
    SRC_TXN_CODE,
    OMS_EXEC_TP_ID,
    OMS_EXEC_TP_CD,
    OMS_EXEC_TP_NM,
    OMS_EXEC_TP_DSC,
    CLNT_FRIENDLY_DSC,
    ORIG_SRC_STM_ID,
    ORIG_SRC_STM_CD,
    ACG_TP_ID,
    CASH_APA_EXT_QUALFR,
    CASH_POS_TP_ID,
    SALE_CHRG_RATE_MULTI_NUM,
    AR_ORIG_SRC_STM_CD,
    MF_AC_NUM,
    OFST_ORIG_SRC_STM_AR_ID,
    OFST_AR_ORIG_SRC_STM_CD,
    OFST_AR_SETL_TP_CD,
    OFST_AR_SETL_TP_DSC,
    AR_SETL_TP_CD,
    AR_SETL_TP_DSC,
    ORIG_SRC_STM_AR_ID,
    CASH_SIMP_DSPL_AVY_CGY,
    CASH_SIMP_DSPL_AVY_TP,
    SCR_SIMP_DSPL_AVY_CGY,
    SCR_SIMP_DSPL_AVY_TP,
    SHDW_TXN_TP_CD,
    IMP_SRC_ACTN_CD,
    SIS_DLTD_EV_ID,
    SIS_USR_ID,
    SIS_AC_CL_CD,
    SRC_CNCL_RSN_ID,
    SRC_TXN_SEQ_NUM,
    DVDN_RCRD_DT,
    OWN_IMP_FA_NUM,
    OWN_FA_NUM,
    ACAT_CNTRA_FIRM_CLRG_NUM,
    MM_ALT_ID,
    SRC_STM_ID,
    SRC_CNCL_X_RVSN_CD,
    SRC_OPT_CLSS_CD,
    TXN_RCNCL_REPL_CNT,
    TXN_RCNCL_ST_ID,
    LGCY_CNCL_CMPLN_RSN_TP_ID,
    LGCY_CNCL_CMPLN_SRC_TP_ID,
    LGCY_MKT_TP_ID,
    LGCY_TRD_CPCTY_TP_ID,
    REL_TXN_SRC_STM_ID,
    SRC_ENTR_CNL_TP_ID,
    SRC_PCS_TP_ID,
    TRD_SLCT_TP_ID,
    LAST_UDT_USR_NM,
    LAST_UDT_DTM,
    REL_TXN_RLTNP_TP_ID,
    ACAT_CNTRA_FIRM_NM,
    ACAT_CNTRA_FIRM_SHRT_NM,
    ACAT_CNTRA_FIRM_CLRG_ID_TP_CD,
    SIS_DLTD_EV_NM,
    SRC_CNCL_RSN_CD,
    SRC_CNCL_RSN_NM,
    TXN_RCNCL_ST_CD,
    TXN_RCNCL_ST_NM,
    REL_TXN_RLTNP_TP_CD,
    REL_TXN_RLTNP_TP_NM,
    SRC_STM_NM,
    REL_TXN_SRC_STM_CD,
    SHDW_TXN_TP_NM,
    IMP_SRC_ACTN_NM,
    OWN_FA_NUM_ENT_CD,
    FA_OWN_EMPE_ID,
    OWN_FA_NUM_ENT_ENTP_ID,
    AGRT_ORIG_FEES,
    AGRT_STMT_FEES,
    DRVD_TRD_CPCTY_CD,
    DRVD_TRD_CPCTY_NM,
    DRVD_TRD_CPCTY_ID,
    SCR_OPT_SYMB,
    ADL_TRD_INSR,
    TRD_FCTR_RATE,
    MRKUP_RATE,
    STD_CMSN_AMT,
    ACT_CMSN_AMT,
    TRD_PCS_FEE_AMT,
    SEC_FEE_AMT,
    ACR_INT_AMT,
    CNCSN_AMT,
    CDSC_AMT,
    OTHR_FEE_AMT,
    TRD_CNCLD_F,
    SYMB,
    ISIN,
    TXN_SRC_TAX_CD,
    TXN_SRC_TAX_CD_DSC,
    TM_PRC_DISCRETION_F,
    CASH_NNA_CGY_ID,
    CASH_NNA_CGY_NM,
    SCR_NNA_CGY_ID,
    SCR_NNA_CGY_NM,
    YLD,
    YTW,
    YTW_CD,
    BKR_AC_NUM,
    SIS_DLTD_EV_CD,
    DB_CARD_TXN_DT,
    DB_CARD_ORIG_CCY_CD,
    DB_CARD_ORIG_CCY,
    SDIRA_TXN_TP_CD,
    SDIRA_TXN_TP,
    SDIRA_TXN_YR,
    TXN_CCY,
    BKR_IRA_F,
    BKR_ERISA_F,
    BKR_ORIG_SRC_STM_CD,
    BKR_ABC_CLSS_CD,
    BKR_ABC_CLSS,
    AC_CGY_CD,
    BKR_AC_CGY_CD,
    AC_CGY,
    BKR_AC_CGY,
    BKR_BSN_LINE_AFFLT,
    BKR_BSN_LINE_AFFLT_CD,
    TST_AC_F,
    BKR_TST_AC_F,
    TAX_RPT_CLNT_ID,
    BKR_TAX_RPT_CLNT_ID,
    TAX_AC_F,
    BKR_TAX_AC_F,
    BKR_RJ_TAX_RPT_RSPL_F,
    RJ_BSN_UNIT_CD,
    BKR_RJ_BSN_UNIT_CD,
    RJ_BSN_UNIT,
    BKR_RJ_BSN_UNIT,
    AC_OWNSHP_TP_CD,
    BKR_AC_OWNSHP_TP_CD,
    AC_OWNSHP_TP,
    BKR_AC_OWNSHP_TP,
    BKR_FIRM_AC_F,
    BKR_FEE_BASE_AC_F,
    BKR_RJ_TRUST_F,
    OWN_PRIM_FA_NUM,
    OWN_FA_CSS_PSN_ID,
    OWN_FA_CRN_ADV_F,
    OWN_FA_DEPT_BR_CD,
    OWN_FA_DSCR_F,
    OWN_FA_DSCR_ST,
    OWN_FA_DSCR_ST_CD,
    OWN_FA_FINRA_CRD_CLSS_CD,
    OWN_FA_HR_ST_CD,
    OWN_FA_PRODUCER_F,
    OWN_FA_QUALF_ADV_F,
    OWN_FA_ENT_BR_CD,
    OWN_FA_ENT_BSN_ST,
    OWN_FA_ENT_DIV_CD,
    OWN_FA_ENT_DIV_DSC,
    OWN_FA_ENT_DIV_NODE,
    OWN_FA_ENT_MAIN_BR_STE,
    OWN_FA_ENT_OSJ,
    OWN_FA_ENT_RTL_HIER_BSN_MODL_CD,
    OWN_FA_ENT_RTL_HIER_BSN_MODL_DSC,
    OWN_FA_ENT_RTL_SALE_HIER_LOB_CD,
    OWN_FA_ENT_RTL_SALE_HIER_LOB_DSC,
    OWN_FA_ENT_RTL_HIER_RPT_UNIT_CD,
    OWN_FA_ENT_RTL_HIER_RPT_UNIT_DSC,
    OWN_FA_ENT_RTL_SALE_DIV_CD,
    OWN_FA_ENT_RTL_SALE_HIER_RGON_CD,
    OWN_FA_ENT_RTL_SALE_HIER_RGON_DSC,
    OWN_FA_ENT_RTL_HIER_TERR_CD,
    OWN_FA_ENT_RTL_HIER_TERR_DSC,
    OWN_FA_ENT_RSK_HIER_BSN_UNIT_CD,
    OWN_FA_ENT_RSK_HIER_BSN_UNIT_DSC,
    OWN_FA_ENT_RJAS_ID_F,
    OWN_FA_ENT_SUBDIV_CD,
    OWN_FA_ENT_SUBDIV_DSC,
    OWN_FA_ENT_SUBS,
    OWN_FA_ENT_SBTP,
    OWN_FA_ENT_SBTP_CD,
    OWN_FA_ENT_TP,
    OWN_FA_ENT_TP_CD,
    OWN_FA_ENT_LOB_AB_F,
    OWN_FA_ENT_LOB_AMS_F,
    OWN_FA_ENT_LOB_BSN_MODL,
    OWN_FA_ENT_BSN_OPN_DT,
    OWN_FA_ENT_LONG_CD,
    OWN_FA_ENT_SHRT_CD,
    OWN_FA_ENT_CSS_ID,
    OWN_FA_ENT_RTL_SALE_CPX_CD,
    EQTY_IDY,
    EQTY_IDY_CD,
    EQTY_IDY_GRP,
    EQTY_IDY_GRP_CD,
    EQTY_SECT,
    EQTY_SECT_CD,
    EQTY_SUP_SECT,
    EQTY_SUP_SECT_CD,
    MODL_STRTG_DTL_AST_CLSS,
    MODL_STRTG_DTL_AST_CLSS_CD,
    MODL_STRTG_SMY_AST_CLSS,
    MODL_STRTG_SMY_AST_CLSS_CD,
    PD_CMPOS_DSC,
    PD_SHRT_NM,
    PD_DSC,
    RPT_CL_LVL_1,
    RPT_CL_LVL_2,
    RPT_STRTG_DTL_AST_CLSS,
    RPT_STRTG_DTL_AST_CLSS_CD,
    RPT_STRTG_SMY_AST_CLSS,
    RPT_STRTG_SMY_AST_CLSS_CD,
    FND_FAM,
    SHR_CLSS_TP_CD,
    SHR_CLSS_TP,
    IMT_CL_LVL_1,
    IMT_CL_LVL_1_CD,
    IMT_CL_LVL_2,
    IMT_CL_LVL_2_CD,
    IMT_CL_LVL_3,
    IMT_CL_LVL_3_CD,
    IMT_CL_LVL_4,
    IMT_CL_LVL_4_CD,
    IMT_CL_LVL_5,
    IMT_CL_LVL_5_CD,
    OWN_FA_NUM_TP_CD,
    OWN_FA_NUM_TP,
    BOND_ACRTN_DCN_AMT,
    BOND_AMRZ_PREM_AMT,
    RJ_TRUST_BOOK_VAL_AMT,
    RJ_TRUST_RLZD_TAX_GAIN_OR_LOSS_AMT,
    BFR_REPYMT_FACE_VAL_AMT,
    BFR_INCM_PYMT_FACE_VAL_AMT,
    BASE_POS_QTY,
    NO_SIS_SCR_MVMT_TXN_QTY,
    NO_SIS_SCR_MVMT_TXN_PRC,
    REIVS_SHR_QTY,
    REIVS_PRC
)
SELECT /*+ PARALLEL(8) */
    EXG_DIM.EXG_DIM_ID                       AS EXG_DIM_ID,  -- [DRD_PHYSICAL] DRD source CIRD_OWNER.EXG_DIM.EXG_DIM_ID
    BKR_AR_DIM.AR_DIM_ID                     AS AR_DIM_ID,  -- [DRD_PHYSICAL] DRD source CCSI_OWNER.AR_DIM.AR_DIM_ID /* see ETL block PRODUCT_INFORMATION in header */
    BKR_AR_DIM.AR_DIM_ID                     AS OFST_AR_DIM_ID,  -- [DRD_PHYSICAL] DRD source CCSI_OWNER.AR_DIM.AR_DIM_ID /* see ETL block PRODUCT_INFORMATION in header */
    ACG_TP_DIM.ACG_TP_DIM_ID                 AS ACG_TP_DIM_ID,  -- [DRD_PHYSICAL] DRD source COMMON_OWNER.ACG_TP_DIM.ACG_TP_DIM_ID
    CASH_POS_TP_DIM.CASH_POS_TP_DIM_ID       AS CASH_POS_TP_DIM_ID,  -- [DRD_PHYSICAL] DRD source COMMON_OWNER.CASH_POS_TP_DIM.CASH_POS_TP_DIM_ID
    CCY_DIM.CCY_DIM_ID                       AS SBC_CCY_DIM_ID,  -- [DRD_PHYSICAL] DRD source CIRD_OWNER.CCY_DIM.CCY_DIM_ID
    IMT_PD_DIM.IMT_PD_DIM_ID                 AS SEC_PD_DIM_ID,  -- [DRD_PHYSICAL] DRD source CIRD_OWNER.IMT_PD_DIM.IMT_PD_DIM_ID /* see ETL block PRODUCT_INFORMATION in header */
    IMT_PD_DIM.IMT_PD_DIM_ID                 AS CASH_PD_DIM_ID,  -- [DRD_PHYSICAL] DRD source CIRD_OWNER.IMT_PD_DIM.IMT_PD_DIM_ID /* see ETL block APACASH in header */
    lccrtd.LGCY_CNCL_CMPLN_RSN_TP_DIM_ID     AS LGCY_CNCL_CMPLN_RSN_DIM_ID,  -- [DRD_PHYSICAL] DRD source TRANSACTIONS_OWNER.LGCY_CNCL_CMPLN_RSN_TP_DIM.LGCY_CNCL_CMPLN_RSN_TP_DIM_ID
    lccstd.LGCY_CNCL_CMPLN_SRC_TP_DIM_ID     AS LGCY_CNCL_CMPLN_SRC_DIM_ID,  -- [DRD_PHYSICAL] DRD source TRANSACTIONS_OWNER.LGCY_CNCL_CMPLN_SRC_TP_DIM.LGCY_CNCL_CMPLN_SRC_TP_DIM_ID
    lmtd.LGCY_MKT_TP_DIM_ID                  AS LGCY_MKT_TP_DIM_ID,  -- [DRD_PHYSICAL] DRD source TRANSACTIONS_OWNER.LGCY_MKT_TP_DIM.LGCY_MKT_TP_DIM_ID
    ltctd.LGCY_TRD_CPCTY_TP_DIM_ID           AS LGCY_TRD_CPCTY_TP_DIM_ID,  -- [DRD_PHYSICAL] DRD source TRANSACTIONS_OWNER.LGCY_TRD_CPCTY_TP_DIM.LGCY_TRD_CPCTY_TP_DIM_ID
    sptd.SRC_PCS_TP_DIM_ID                   AS SRC_PCS_TP_DIM_ID,  -- [DRD_PHYSICAL] DRD source TRANSACTIONS_OWNER.SRC_PCS_TP_DIM.SRC_PCS_TP_DIM_ID
    sectd.SRC_ENTR_CNL_TP_DIM_ID             AS SRC_ENTR_CNL_TP_DIM_ID,  -- [DRD_PHYSICAL] DRD source TRANSACTIONS_OWNER.SRC_ENTR_CNL_TP_DIM.SRC_ENTR_CNL_TP_DIM_ID
    tstd.TRD_SLCT_TP_DIM_ID                  AS TRD_SLCT_TP_DIM_ID,  -- [DRD_PHYSICAL] DRD source TRANSACTIONS_OWNER.TRD_SLCT_TP_DIM.TRD_SLCT_TP_DIM_ID
    TXN_RLTNP_SRC_STM_DIM.SRC_STM_DIM_ID     AS TXN_SRC_STM_DIM_ID,  -- [DRD_PHYSICAL] DRD source COMMON_OWNER.SRC_STM_DIM.SRC_STM_DIM_ID
    TXN_RLTNP_SRC_STM_DIM.SRC_STM_DIM_ID     AS REL_TXN_SRC_STM_DIM_ID,  -- [DRD_PHYSICAL] DRD source COMMON_OWNER.SRC_STM_DIM.SRC_STM_DIM_ID
    BKR_AR_DIM.AR_DIM_ID                     AS BKR_AR_DIM_ID,  -- [DRD_PHYSICAL] DRD source CCSI_OWNER.AR_DIM.AR_DIM_ID /* see ETL block PRODUCT_INFORMATION in header */
    SD_DATE_DIM.DT_DIM_ID                    AS TD_DIM_ID,  -- [DRD_PHYSICAL] DRD source COMMON_OWNER.DATE_DIM.DT_DIM_ID
    t.TD                                     AS TD,  -- [ODI] ODI staging chain -> CCAL_REPL_OWNER.TXN.TD
    SD_DATE_DIM.DT_DIM_ID                    AS SD_DIM_ID,  -- [DRD_PHYSICAL] DRD source COMMON_OWNER.DATE_DIM.DT_DIM_ID
    t.SD                                     AS SD,  -- [ODI] ODI staging chain -> CCAL_REPL_OWNER.TXN.SD
    t.BKG_DT                                 AS BKG_DT,  -- [ODI] ODI staging chain -> CCAL_REPL_OWNER.TXN.BKG_DT
    t.ORIG_BKG_DT                            AS ORIG_BKG_DT,  -- [ODI] ODI staging chain -> CCAL_REPL_OWNER.TXN.ORIG_BKG_DT
    t.EXEC_DTM                               AS EXEC_DTM,  -- [ODI] ODI staging chain -> CCAL_REPL_OWNER.TXN.EXEC_DTM
    t.TXN_ID                                 AS TXN_ID,  -- [ODI] ODI staging chain -> CCAL_REPL_OWNER.TXN.TXN_ID
    TXN_RLTNP1.TRGT_TXN_ID                   AS REL_TXN_ID,  -- [ODI] ODI staging chain -> CCAL_REPL_OWNER.TXN_RLTNP.TRGT_TXN_ID
    t.TRD_NUM                                AS TRD_NUM,  -- [ODI] ODI staging chain -> CCAL_REPL_OWNER.TXN.TRD_NUM
    t.ORIG_TRD_NUM                           AS ORIG_TRD_NUM,  -- [ODI] ODI staging chain -> CCAL_REPL_OWNER.TXN.ORIG_TRD_NUM
    t.TXN_SRC_KEY                            AS TXN_SRC_KEY,  -- [ODI] ODI staging chain -> CCAL_REPL_OWNER.TXN.TXN_SRC_KEY
    APA.APA_ID                               AS SEC_APA_ID,  -- [ODI] ODI staging chain -> CCAL_REPL_OWNER.APA.APA_ID /* see ETL block PRODUCT_INFORMATION in header */
    APA.APA_ID                               AS CSH_APA_ID,  -- [ODI] ODI staging chain -> CCAL_REPL_OWNER.APA.APA_ID /* see ETL block APACASH in header */
    APA.SCR_PRC_IN_TXN_CCY                   AS SEC_PRC_IN_TXN_CCY,  -- [ODI] ODI staging chain -> CCAL_REPL_OWNER.APA.SCR_PRC_IN_TXN_CCY /* see ETL block PRODUCT_INFORMATION in header */
    APA.TXN_AMT                              AS SEC_TXN_AMT,  -- [ODI] ODI staging chain -> CCAL_REPL_OWNER.APA.TXN_AMT /* see ETL block PRODUCT_INFORMATION in header */
    APA.TXN_AMT                              AS CASH_TXN_AMT,  -- [ODI] ODI staging chain -> CCAL_REPL_OWNER.APA.TXN_AMT /* see ETL block APACASH in header */
    APA.ORIG_QTY                             AS SEC_ORIG_QTY,  -- [ODI] ODI staging chain -> CCAL_REPL_OWNER.APA.ORIG_QTY /* see ETL block PRODUCT_INFORMATION in header */
    APA.SCR_PRC_IN_SBC                       AS SEC_SRC_PRC_IN_SBC,  -- [ODI] ODI staging chain -> CCAL_REPL_OWNER.APA.SCR_PRC_IN_SBC /* see ETL block PRODUCT_INFORMATION in header */
    APA.SALE_CHRG_RATE                       AS SALE_CHRG_RATE_PCT,  -- [DRD_PHYSICAL] DRD source CCAL_REPL_OWNER.APA.SALE_CHRG_RATE /* see ETL block APACASH in header */
    APA.SALE_CHRG_RATE_TP_ID                 AS SALE_CHRG_RATE_TP_ID,  -- [ODI] ODI staging chain -> CCAL_REPL_OWNER.APA.SALE_CHRG_RATE_TP_ID /* see ETL block APACASH in header */
    DRVD_TRD_CPCTY.CL_VAL_CODE               AS SALE_CHRG_RATE_TP_CD,  -- [ODI] ODI staging chain -> CCAL_REPL_OWNER.CL_VAL.CL_VAL_CODE /* see ETL block APACASH in header */
    APA.STM_BASE_CCY_AMT                     AS SEC_SBC_AMT,  -- [ODI] ODI staging chain -> CCAL_REPL_OWNER.APA.STM_BASE_CCY_AMT /* see ETL block PRODUCT_INFORMATION in header */
    APA.STM_BASE_CCY_AMT                     AS CASH_SBC_AMT,  -- [ODI] ODI staging chain -> CCAL_REPL_OWNER.APA.STM_BASE_CCY_AMT /* see ETL block APACASH in header */
    APA.STM_BASE_CCY_CLC_DTM                 AS SBC_CCY_CALC_DT,  -- [ODI] ODI staging chain -> CCAL_REPL_OWNER.APA.STM_BASE_CCY_CLC_DTM
    APA.STM_BASE_CCY_EXG_RATE                AS SBC_EXG_RATE,  -- [ODI] ODI staging chain -> CCAL_REPL_OWNER.APA.STM_BASE_CCY_EXG_RATE
    DRVD_TRD_CPCTY.CL_VAL_CODE               AS CASH_DB_CR_CD,  -- [ODI] ODI staging chain -> CCAL_REPL_OWNER.CL_VAL.CL_VAL_CODE /* see ETL block APACASH in header */
    DRVD_TRD_CPCTY.CL_VAL_CODE               AS SEC_DB_CR_CD,  -- [ODI] ODI staging chain -> CCAL_REPL_OWNER.CL_VAL.CL_VAL_CODE /* see ETL block PRODUCT_INFORMATION in header */
    APA.SRC_SEQ_NUM                          AS SEC_SRC_SEQ_NUM,  -- [ODI] ODI staging chain -> CCAL_REPL_OWNER.APA.SRC_SEQ_NUM /* see ETL block PRODUCT_INFORMATION in header */
    APA.APA_EXT_QUALFR                       AS SEC_APA_EXT_QUALFR,  -- [ODI] ODI staging chain -> CCAL_REPL_OWNER.APA.APA_EXT_QUALFR /* see ETL block PRODUCT_INFORMATION in header */
    APA.APA_DSC                              AS SEC_DSC_TRAILER_1,  -- [ODI] ODI staging chain -> CCAL_REPL_OWNER.APA.APA_DSC /* see ETL block PRODUCT_INFORMATION in header */
    APA.ALT_DSC                              AS SEC_ALT_DSC_TRAILER_2,  -- [ODI] ODI staging chain -> CCAL_REPL_OWNER.APA.ALT_DSC /* see ETL block PRODUCT_INFORMATION in header */
    t.BUY_SELL_IND                           AS BUY_SELL_IND,  -- [ODI] ODI staging chain -> CCAL_REPL_OWNER.TXN.BUY_SELL_IND
    t.CF_GEN_F                               AS CF_GEN_F,  -- [ODI] ODI staging chain -> CCAL_REPL_OWNER.TXN.CF_GEN_F
    t.TXN_CL_F                               AS TXN_CL_F,  -- [ODI] ODI staging chain -> CCAL_REPL_OWNER.TXN.TXN_CL_F
    t.OPTS_CLSS_CODE                         AS OPT_CLSS_CD,  -- [ODI] ODI staging chain -> CCAL_REPL_OWNER.TXN.OPTS_CLSS_CODE
    APA.SRC_PD_ID                            AS SEC_SRC_CUSIP,  -- [ODI] ODI staging chain -> CCAL_REPL_OWNER.APA.SRC_PD_ID /* see ETL block PRODUCT_INFORMATION in header */
    APA.APA_DSC                              AS CASH_DSC_TRAILER_1,  -- [ODI] ODI staging chain -> CCAL_REPL_OWNER.APA.APA_DSC /* see ETL block APACASH in header */
    APA.ALT_DSC                              AS CASH_ALT_DSC_TRAILER_2,  -- [ODI] ODI staging chain -> CCAL_REPL_OWNER.APA.ALT_DSC /* see ETL block APACASH in header */
    APA.SRC_SEQ_NUM                          AS CASH_SRC_SEQ_NUM,  -- [ODI] ODI staging chain -> CCAL_REPL_OWNER.APA.SRC_SEQ_NUM /* see ETL block APACASH in header */
    t.TXN_TP_ID                              AS TXN_TP_ID,  -- [ODI] ODI staging chain -> CCAL_REPL_OWNER.TXN.TXN_TP_ID
    DRVD_TRD_CPCTY.CL_VAL_CODE               AS TXN_TP_CD,  -- [ODI] ODI staging chain -> CCAL_REPL_OWNER.CL_VAL.CL_VAL_CODE
    DRVD_TRD_CPCTY.CL_VAL_NM                 AS TXN_TP_NM,  -- [ODI] ODI staging chain -> CCAL_REPL_OWNER.CL_VAL.CL_VAL_NM
    DRVD_TRD_CPCTY.DSC                       AS TXN_TP_DSC,  -- [ODI] ODI staging chain -> CCAL_REPL_OWNER.CL_VAL.DSC
    t.TXN_SBTP_ID                            AS TXN_SBTP_ID,  -- [ODI] ODI staging chain -> CCAL_REPL_OWNER.TXN.TXN_SBTP_ID
    DRVD_TRD_CPCTY.CL_VAL_NM                 AS TXN_SUB_TP_NM,  -- [ODI] ODI staging chain -> CCAL_REPL_OWNER.CL_VAL.CL_VAL_NM
    DRVD_TRD_CPCTY.CL_VAL_CODE               AS TXN_SUB_TP_CD,  -- [ODI] ODI staging chain -> CCAL_REPL_OWNER.CL_VAL.CL_VAL_CODE
    DRVD_TRD_CPCTY.DSC                       AS TXN_SUB_TP_DSC,  -- [ODI] ODI staging chain -> CCAL_REPL_OWNER.CL_VAL.DSC
    t.EXEC_TP_ID                             AS EXEC_TP_ID,  -- [ODI] ODI staging chain -> CCAL_REPL_OWNER.TXN.EXEC_TP_ID
    DRVD_TRD_CPCTY.CL_VAL_CODE               AS EXEC_TP_CD,  -- [ODI] ODI staging chain -> CCAL_REPL_OWNER.CL_VAL.CL_VAL_CODE
    DRVD_TRD_CPCTY.CL_VAL_NM                 AS EXEC_TP_NM,  -- [ODI] ODI staging chain -> CCAL_REPL_OWNER.CL_VAL.CL_VAL_NM
    DRVD_TRD_CPCTY.DSC                       AS EXEC_TP_DSC,  -- [ODI] ODI staging chain -> CCAL_REPL_OWNER.CL_VAL.DSC
    DRVD_TRD_CPCTY.CL_VAL_CODE               AS EXEC_SBTP_CD,  -- [ODI] ODI staging chain -> CCAL_REPL_OWNER.CL_VAL.CL_VAL_CODE
    DRVD_TRD_CPCTY.CL_VAL_NM                 AS EXEC_SBTP_NM,  -- [ODI] ODI staging chain -> CCAL_REPL_OWNER.CL_VAL.CL_VAL_NM
    DRVD_TRD_CPCTY.DSC                       AS EXEC_SBTP_DSC,  -- [ODI] ODI staging chain -> CCAL_REPL_OWNER.CL_VAL.DSC
    t.EXEC_SBTP_ID                           AS EXEC_SBTP_ID,  -- [ODI] ODI staging chain -> CCAL_REPL_OWNER.TXN.EXEC_SBTP_ID
    APA.APA_TP_ID                            AS SEC_APA_TP_ID,  -- [ODI] ODI staging chain -> CCAL_REPL_OWNER.APA.APA_TP_ID /* see ETL block PRODUCT_INFORMATION in header */
    DRVD_TRD_CPCTY.CL_VAL_CODE               AS SCR_APA_TP_CD,  -- [ODI] ODI staging chain -> CCAL_REPL_OWNER.CL_VAL.CL_VAL_CODE /* see ETL block PRODUCT_INFORMATION in header */
    DRVD_TRD_CPCTY.CL_VAL_NM                 AS SCR_APA_TP_NM,  -- [ODI] ODI staging chain -> CCAL_REPL_OWNER.CL_VAL.CL_VAL_NM /* see ETL block PRODUCT_INFORMATION in header */
    DRVD_TRD_CPCTY.DSC                       AS SCR_APA_TP_DSC,  -- [ODI] ODI staging chain -> CCAL_REPL_OWNER.CL_VAL.DSC /* see ETL block PRODUCT_INFORMATION in header */
    APA.APA_TP_ID                            AS CSH_APA_TP_ID,  -- [ODI] ODI staging chain -> CCAL_REPL_OWNER.APA.APA_TP_ID /* see ETL block APACASH in header */
    DRVD_TRD_CPCTY.CL_VAL_CODE               AS CASH_APA_TP_CD,  -- [ODI] ODI staging chain -> CCAL_REPL_OWNER.CL_VAL.CL_VAL_CODE /* see ETL block APACASH in header */
    DRVD_TRD_CPCTY.CL_VAL_NM                 AS CASH_APA_TP_NM,  -- [ODI] ODI staging chain -> CCAL_REPL_OWNER.CL_VAL.CL_VAL_NM /* see ETL block APACASH in header */
    DRVD_TRD_CPCTY.DSC                       AS CASH_APA_TP_DSC,  -- [ODI] ODI staging chain -> CCAL_REPL_OWNER.CL_VAL.DSC /* see ETL block APACASH in header */
    AVY_CL.AVY_CGY                           AS SCR_AVY_CGY,  -- [ODI] ODI staging chain -> CCAL_REPL_OWNER.AVY_CL.AVY_CGY /* see ETL block PRODUCT_INFORMATION in header */
    AVY_CL.AVY_TP                            AS SCR_AVY_TP,  -- [ODI] ODI staging chain -> CCAL_REPL_OWNER.AVY_CL.AVY_TP /* see ETL block PRODUCT_INFORMATION in header */
    TXN_AVY_CL.AVY_CL_ID                     AS SEC_AVY_CL_ID,  -- [ODI] ODI staging chain -> CCAL_REPL_OWNER.TXN_AVY_CL.AVY_CL_ID /* see ETL block PRODUCT_INFORMATION in header */
    AVY_CL.AVY_CGY                           AS CASH_AVY_CGY,  -- [ODI] ODI staging chain -> CCAL_REPL_OWNER.AVY_CL.AVY_CGY /* see ETL block APACASH in header */
    AVY_CL.AVY_TP                            AS CASH_AVY_TP,  -- [ODI] ODI staging chain -> CCAL_REPL_OWNER.AVY_CL.AVY_TP /* see ETL block APACASH in header */
    TXN_AVY_CL.AVY_CL_ID                     AS CSH_AVY_CL_ID,  -- [ODI] ODI staging chain -> CCAL_REPL_OWNER.TXN_AVY_CL.AVY_CL_ID /* see ETL block APACASH in header */
    SYSDATE                                  AS CRT_DTM,  -- [ETL_DEFAULT] system-managed
    'ODI_ETL'                                AS CRT_USR_NM,  -- [ETL_DEFAULT] system-managed
    0                                        AS SESS_NO,  -- [ETL_DEFAULT] system-managed
    t.SRC_ENTR_DTM                           AS SRC_ENTR_DTM,  -- [ODI] ODI staging chain -> CCAL_REPL_OWNER.TXN.SRC_ENTR_DTM
    t.AR_ID                                  AS AR_ID,  -- [ODI] ODI staging chain -> CCAL_REPL_OWNER.TXN.AR_ID
    APA.PD_ID                                AS SEC_PD_ID,  -- [ODI] ODI staging chain -> CCAL_REPL_OWNER.APA.PD_ID /* see ETL block PRODUCT_INFORMATION in header */
    APA.PD_ID                                AS CASH_PD_ID,  -- [ODI] ODI staging chain -> CCAL_REPL_OWNER.APA.PD_ID /* see ETL block APACASH in header */
    APA.BKR_AR_ID                            AS BKR_AR_ID,  -- [DRD_PHYSICAL] DRD source CCAL_REPL_OWNER.APA.BKR_AR_ID /* see ETL block APACASH in header */
    APA.OFST_AR_ID                           AS OFST_AR_ID,  -- [DRD_PHYSICAL] DRD source CCAL_REPL_OWNER.APA.OFST_AR_ID
    t.BR_CODE                                AS BR_CD,  -- [ODI] ODI staging chain -> CCAL_REPL_OWNER.TXN.BR_CODE
    t.FA_NUM                                 AS FA_NUM,  -- [ODI] ODI staging chain -> CCAL_REPL_OWNER.TXN.FA_NUM
    t.SRC_CRT_USRNM                          AS SRC_CRT_USRNM,  -- [ODI] ODI staging chain -> CCAL_REPL_OWNER.TXN.SRC_CRT_USRNM
    t.ORIG_TD                                AS ORIG_TD,  -- [ODI] ODI staging chain -> CCAL_REPL_OWNER.TXN.ORIG_TD
    SRC_PCS_TP_DIM.SRC_PCS_TP_CD             AS SRC_PCS_TP_CD,  -- [ODI] ODI staging chain -> SSDS_TRANSACTIONS_OWNER.SRC_PCS_TP_DIM.SRC_PCS_TP_CD
    SRC_PCS_TP_DIM.SRC_PCS_TP_NM             AS SRC_PCS_TP_NM,  -- [ODI] ODI staging chain -> SSDS_TRANSACTIONS_OWNER.SRC_PCS_TP_DIM.SRC_PCS_TP_NM
    CCY_DIM.CCY_DIM_ID                       AS CCY_DIM_ID,  -- [DRD_PHYSICAL] DRD source CIRD_OWNER.CCY_DIM.CCY_DIM_ID
    APA.TXN_ISO_CCY_CODE                     AS CCY_CD,  -- [DRD_PHYSICAL] DRD source CCAL_REPL_OWNER.APA.TXN_ISO_CCY_CODE
    APA.STM_BASE_ISO_CCY_CODE                AS SBC_CCY_CD,  -- [DRD_PHYSICAL] DRD source CCAL_REPL_OWNER.APA.STM_BASE_ISO_CCY_CODE
    APA.SRC_EFF_DT                           AS SRC_EFF_DT,  -- [DRD_PHYSICAL] DRD source CCAL_REPL_OWNER.APA.SRC_EFF_DT
    t.DOL_IND_ID                             AS DOL_IND_ID,  -- [ODI] ODI staging chain -> CCAL_REPL_OWNER.TXN.DOL_IND_ID
    DRVD_TRD_CPCTY.CL_VAL_CODE               AS DOL_IND_CD,  -- [ODI] ODI staging chain -> CCAL_REPL_OWNER.CL_VAL.CL_VAL_CODE
    DRVD_TRD_CPCTY.CL_VAL_NM                 AS DOL_IND_NM,  -- [ODI] ODI staging chain -> CCAL_REPL_OWNER.CL_VAL.CL_VAL_NM
    t.OMS_ORDR_KEY                           AS OMS_ORDR_KEY,  -- [ODI] ODI staging chain -> CCAL_REPL_OWNER.TXN.OMS_ORDR_KEY
    t.EXG_CODE                               AS EXG_CD,  -- [ODI] ODI staging chain -> CCAL_REPL_OWNER.TXN.EXG_CODE
    EXG_DIM.EXG_NM                           AS EXG_NM,  -- [ODI] ODI staging chain -> CIRD_OWNER.EXG_DIM.EXG_NM
    ACG_TP_DIM.ACG_TP_CD                     AS ACG_TP_CD,  -- [DRD_PHYSICAL] DRD source COMMON_OWNER.ACG_TP_DIM.ACG_TP_CD
    ACG_TP_DIM.ACG_TP_NM                     AS ACG_TP_NM,  -- [DRD_PHYSICAL] DRD source COMMON_OWNER.ACG_TP_DIM.ACG_TP_NM
    CASH_POS_TP_DIM.CASH_POS_TP_CD           AS CASH_POS_TP_CD,  -- [ODI] ODI staging chain -> COMMON_OWNER.CASH_POS_TP_DIM.CASH_POS_TP_CD
    CASH_POS_TP_DIM.CASH_POS_TP_NM           AS CASH_POS_TP_NM,  -- [ODI] ODI staging chain -> COMMON_OWNER.CASH_POS_TP_DIM.CASH_POS_TP_NM
    LGCY_CNCL_CMPLN_RSN_TP_DIM.LGCY_CNCL_CMPLN_RSN_TP_CD AS LGCY_CNCL_CMPLN_RSN_TP_CD,  -- [ODI] ODI staging chain -> SSDS_TRANSACTIONS_OWNER.LGCY_CNCL_CMPLN_RSN_TP_DIM.LGCY_CNCL_CMPLN_RSN_TP_CD
    LGCY_CNCL_CMPLN_RSN_TP_DIM.LGCY_CNCL_CMPLN_RSN_TP_NM AS LGCY_CNCL_CMPLN_RSN_TP_NM,  -- [ODI] ODI staging chain -> SSDS_TRANSACTIONS_OWNER.LGCY_CNCL_CMPLN_RSN_TP_DIM.LGCY_CNCL_CMPLN_RSN_TP_NM
    LGCY_CNCL_CMPLN_SRC_TP_DIM.LGCY_CNCL_CMPLN_SRC_TP_CD AS LGCY_CNCL_CMPLN_SRC_TP_CD,  -- [ODI] ODI staging chain -> SSDS_TRANSACTIONS_OWNER.LGCY_CNCL_CMPLN_SRC_TP_DIM.LGCY_CNCL_CMPLN_SRC_TP_CD
    LGCY_CNCL_CMPLN_SRC_TP_DIM.LGCY_CNCL_CMPLN_SRC_TP_NM AS LGCY_CNCL_CMPLN_SRC_TP_NM,  -- [ODI] ODI staging chain -> SSDS_TRANSACTIONS_OWNER.LGCY_CNCL_CMPLN_SRC_TP_DIM.LGCY_CNCL_CMPLN_SRC_TP_NM
    LGCY_MKT_TP_DIM.LGCY_MKT_TP_CD           AS LGCY_MKT_TP_CD,  -- [ODI] ODI staging chain -> SSDS_TRANSACTIONS_OWNER.LGCY_MKT_TP_DIM.LGCY_MKT_TP_CD
    LGCY_MKT_TP_DIM.LGCY_MKT_TP_NM           AS LGCY_MKT_TP_NM,  -- [ODI] ODI staging chain -> SSDS_TRANSACTIONS_OWNER.LGCY_MKT_TP_DIM.LGCY_MKT_TP_NM
    ltctd.LGCY_TRD_CPCTY_TP_CD               AS LGCY_TRD_CPCTY_TP_CD,  -- [DRD_INLINE_FALLBACK] DRD inline join TRANSACTIONS_OWNER.LGCY_TRD_CPCTY_TP_DIM.LGCY_TRD_CPCTY_TP_CD (ODI ref to SCRATCH_TS_OWNER.LGCY_TRD_CPCTY_TP_DIM skipped: no JOIN)
    ltctd.LGCY_TRD_CPCTY_TP_NM               AS LGCY_TRD_CPCTY_TP_NM,  -- [DRD_INLINE_FALLBACK] DRD inline join TRANSACTIONS_OWNER.LGCY_TRD_CPCTY_TP_DIM.LGCY_TRD_CPCTY_TP_NM (ODI ref to SCRATCH_TS_OWNER.LGCY_TRD_CPCTY_TP_DIM skipped: no JOIN)
    SRC_ENTR_CNL_TP_DIM.SRC_ENTR_CNL_TP_CD   AS SRC_ENTR_CNL_TP_CD,  -- [ODI] ODI staging chain -> SSDS_TRANSACTIONS_OWNER.SRC_ENTR_CNL_TP_DIM.SRC_ENTR_CNL_TP_CD
    SRC_ENTR_CNL_TP_DIM.SRC_ENTR_CNL_TP_NM   AS SRC_ENTR_CNL_TP_NM,  -- [ODI] ODI staging chain -> SSDS_TRANSACTIONS_OWNER.SRC_ENTR_CNL_TP_DIM.SRC_ENTR_CNL_TP_NM
    TRD_SLCT_TP_DIM.TRD_SLCT_TP_CD           AS TRD_SLCT_TP_CD,  -- [ODI] ODI staging chain -> SSDS_TRANSACTIONS_OWNER.TRD_SLCT_TP_DIM.TRD_SLCT_TP_CD
    TRD_SLCT_TP_DIM.TRD_SLCT_TP_NM           AS TRD_SLCT_TP_NM,  -- [ODI] ODI staging chain -> SSDS_TRANSACTIONS_OWNER.TRD_SLCT_TP_DIM.TRD_SLCT_TP_NM
    DRVD_TRD_CPCTY.CL_VAL_NM                 AS SALE_CHRG_RATE_TP_NM,  -- [ODI] ODI staging chain -> CCAL_REPL_OWNER.CL_VAL.CL_VAL_NM /* see ETL block APACASH in header */
    DRVD_TRD_CPCTY.CL_VAL_NM                 AS CASH_DB_CR_NM,  -- [ODI] ODI staging chain -> CCAL_REPL_OWNER.CL_VAL.CL_VAL_NM /* see ETL block APACASH in header */
    DRVD_TRD_CPCTY.CL_VAL_NM                 AS SEC_DB_CR_NM,  -- [ODI] ODI staging chain -> CCAL_REPL_OWNER.CL_VAL.CL_VAL_NM /* see ETL block PRODUCT_INFORMATION in header */
    TXN_RLTNP_SRC_STM_DIM.SRC_STM_CD         AS SRC_STM_CD,  -- [ODI] ODI staging chain -> COMMON_OWNER.SRC_STM_DIM.SRC_STM_CD
    TRUNC(SYSDATE)                           AS BATCH_DT,  -- [ETL_DEFAULT] system-managed
    CCAL_CIRD_PD_MAP.CIRD_PD_ID              AS CASH_CIRD_PD_ID,  -- [ODI] ODI staging chain -> CCAL_REPL_OWNER.CCAL_CIRD_PD_MAP.CIRD_PD_ID /* see ETL block APACASH in header */
    CCAL_CIRD_PD_MAP.CIRD_PD_ID              AS SEC_CIRD_PD_ID,  -- [ODI] ODI staging chain -> CCAL_REPL_OWNER.CCAL_CIRD_PD_MAP.CIRD_PD_ID
    'Y'                                      AS ACTV_F,  -- [ETL_DEFAULT] system-managed
    t.SRC_TXN_CODE                           AS SRC_TXN_CODE,  -- [ODI] ODI staging chain -> CCAL_REPL_OWNER.TXN.SRC_TXN_CODE
    t.OMS_EXEC_TP_ID                         AS OMS_EXEC_TP_ID,  -- [ODI] ODI staging chain -> CCAL_REPL_OWNER.TXN.OMS_EXEC_TP_ID
    DRVD_TRD_CPCTY.CL_VAL_CODE               AS OMS_EXEC_TP_CD,  -- [ODI] ODI staging chain -> CCAL_REPL_OWNER.CL_VAL.CL_VAL_CODE
    DRVD_TRD_CPCTY.CL_VAL_NM                 AS OMS_EXEC_TP_NM,  -- [ODI] ODI staging chain -> CCAL_REPL_OWNER.CL_VAL.CL_VAL_NM
    DRVD_TRD_CPCTY.DSC                       AS OMS_EXEC_TP_DSC,  -- [ODI] ODI staging chain -> CCAL_REPL_OWNER.CL_VAL.DSC
    APA.CLNT_FRIENDLY_DESC                   AS CLNT_FRIENDLY_DSC,  -- [DRD_PHYSICAL] DRD source CCAL_REPL_OWNER.APA.CLNT_FRIENDLY_DESC
    t.ORIG_SRC_STM_ID                        AS ORIG_SRC_STM_ID,  -- [ODI] ODI staging chain -> CCAL_REPL_OWNER.TXN.ORIG_SRC_STM_ID
    t.ORIG_SRC_STM_CODE                      AS ORIG_SRC_STM_CD,  -- [ODI] ODI staging chain -> CCAL_REPL_OWNER.TXN.ORIG_SRC_STM_CODE
    APA.ACG_TP_ID                            AS ACG_TP_ID,  -- [DRD_PHYSICAL] DRD source CCAL_REPL_OWNER.APA.ACG_TP_ID
    APA.APA_EXT_QUALFR                       AS CASH_APA_EXT_QUALFR,  -- [ODI] ODI staging chain -> CCAL_REPL_OWNER.APA.APA_EXT_QUALFR /* see ETL block APACASH in header */
    APA.CASH_POS_TP_ID                       AS CASH_POS_TP_ID,  -- [ODI] ODI staging chain -> CCAL_REPL_OWNER.APA.CASH_POS_TP_ID
    APA.SALE_CHRG_RATE                       AS SALE_CHRG_RATE_MULTI_NUM,  -- [DRD_PHYSICAL] DRD source CCAL_REPL_OWNER.APA.SALE_CHRG_RATE /* see ETL block APACASH in header */
    BKR_AR_DIM.ORIG_SRC_STM_CD               AS AR_ORIG_SRC_STM_CD,  -- [ODI] ODI staging chain -> CCSI_OWNER.AR_DIM.ORIG_SRC_STM_CD /* see ETL block PRODUCT_INFORMATION in header */
    BKR_AR_DIM.MF_DRC_EXT_AC_NUM             AS MF_AC_NUM,  -- [ODI] ODI staging chain -> CCSI_OWNER.AR_DIM.MF_DRC_EXT_AC_NUM /* see ETL block PRODUCT_INFORMATION in header */
    BKR_AR_DIM.ORIG_SRC_STM_AR_ID            AS OFST_ORIG_SRC_STM_AR_ID,  -- [DRD_PHYSICAL] DRD source CCSI_OWNER.AR_DIM.ORIG_SRC_STM_AR_ID /* see ETL block PRODUCT_INFORMATION in header */
    BKR_AR_DIM.ORIG_SRC_STM_CD               AS OFST_AR_ORIG_SRC_STM_CD,  -- [DRD_PHYSICAL] DRD source CCSI_OWNER.AR_DIM.ORIG_SRC_STM_CD /* see ETL block PRODUCT_INFORMATION in header */
    BKR_AR_DIM.SETL_TP_CD                    AS OFST_AR_SETL_TP_CD,  -- [DRD_PHYSICAL] DRD source CCSI_OWNER.AR_DIM.SETL_TP_CD /* see ETL block PRODUCT_INFORMATION in header */
    BKR_AR_DIM.SETL_TP                       AS OFST_AR_SETL_TP_DSC,  -- [DRD_PHYSICAL] DRD source CCSI_OWNER.AR_DIM.SETL_TP /* see ETL block PRODUCT_INFORMATION in header */
    BKR_AR_DIM.SETL_TP_CD                    AS AR_SETL_TP_CD,  -- [ODI] ODI staging chain -> CCSI_OWNER.AR_DIM.SETL_TP_CD /* see ETL block PRODUCT_INFORMATION in header */
    BKR_AR_DIM.SETL_TP                       AS AR_SETL_TP_DSC,  -- [ODI] ODI staging chain -> CCSI_OWNER.AR_DIM.SETL_TP /* see ETL block PRODUCT_INFORMATION in header */
    BKR_AR_DIM.ORIG_SRC_STM_AR_ID            AS ORIG_SRC_STM_AR_ID,  -- [DRD_PHYSICAL] DRD source CCSI_OWNER.AR_DIM.ORIG_SRC_STM_AR_ID /* see ETL block PRODUCT_INFORMATION in header */
    AVY_CL.DSPL_AVY_CGY                      AS CASH_SIMP_DSPL_AVY_CGY,  -- [ODI] ODI staging chain -> CCAL_REPL_OWNER.AVY_CL.DSPL_AVY_CGY /* see ETL block APACASH in header */
    AVY_CL.DSPL_AVY_TP                       AS CASH_SIMP_DSPL_AVY_TP,  -- [ODI] ODI staging chain -> CCAL_REPL_OWNER.AVY_CL.DSPL_AVY_TP /* see ETL block APACASH in header */
    AVY_CL.DSPL_AVY_CGY                      AS SCR_SIMP_DSPL_AVY_CGY,  -- [ODI] ODI staging chain -> CCAL_REPL_OWNER.AVY_CL.DSPL_AVY_CGY /* see ETL block PRODUCT_INFORMATION in header */
    AVY_CL.DSPL_AVY_TP                       AS SCR_SIMP_DSPL_AVY_TP,  -- [ODI] ODI staging chain -> CCAL_REPL_OWNER.AVY_CL.DSPL_AVY_TP /* see ETL block PRODUCT_INFORMATION in header */
    t.SRC_TXN_TP                             AS SHDW_TXN_TP_CD,  -- [ODI] ODI staging chain -> CCAL_REPL_OWNER.TXN.SRC_TXN_TP
    t.SRC_ACTN_CODE                          AS IMP_SRC_ACTN_CD,  -- [ODI] ODI staging chain -> CCAL_REPL_OWNER.TXN.SRC_ACTN_CODE
    t.SRC_BUY_SELL_MULTI_ID                  AS SIS_DLTD_EV_ID,  -- [ODI] ODI staging chain -> CCAL_REPL_OWNER.TXN.SRC_BUY_SELL_MULTI_ID
    t.USR_ID                                 AS SIS_USR_ID,  -- [ODI] ODI staging chain -> CCAL_REPL_OWNER.TXN.USR_ID
    t.SRC_PRIM_CL                            AS SIS_AC_CL_CD,  -- [ODI] ODI staging chain -> CCAL_REPL_OWNER.TXN.SRC_PRIM_CL
    t.SRC_CNCL_RSN_ID                        AS SRC_CNCL_RSN_ID,  -- [ODI] ODI staging chain -> CCAL_REPL_OWNER.TXN.SRC_CNCL_RSN_ID
    t.SRC_TXN_SEQ_NUM                        AS SRC_TXN_SEQ_NUM,  -- [ODI] ODI staging chain -> CCAL_REPL_OWNER.TXN.SRC_TXN_SEQ_NUM
    t.DVDN_RCRD_DT                           AS DVDN_RCRD_DT,  -- [ODI] ODI staging chain -> CCAL_REPL_OWNER.TXN.DVDN_RCRD_DT
    t.SALE_PSN_NUM                           AS OWN_IMP_FA_NUM,  -- [ODI] ODI staging chain -> CCAL_REPL_OWNER.TXN.SALE_PSN_NUM
    AR_GRP_SUBDIM.FA_NUM                     AS OWN_FA_NUM,  -- [ODI] ODI staging chain -> CCSI_OWNER.AR_GRP_SUBDIM.FA_NUM /* see ETL block PRODUCT_INFORMATION in header */
    t.ORIG_SRC_STM_CODE                      AS ACAT_CNTRA_FIRM_CLRG_NUM,  -- [DRD_PHYSICAL] DRD source CCAL_REPL_OWNER.TXN.ORIG_SRC_STM_CODE
    t.ORIG_SRC_STM_CODE                      AS MM_ALT_ID,  -- [DRD_PHYSICAL] DRD source CCAL_REPL_OWNER.TXN.ORIG_SRC_STM_CODE
    t.SRC_STM_ID                             AS SRC_STM_ID,  -- [DRD_PHYSICAL_FALLBACK] DRD physical source CCAL_REPL_OWNER.TXN.SRC_STM_ID (ODI ref to CCAL_REPL_OWNER.J$AVY_FACT skipped: no JOIN)
    t.SRC_CXL_REV                            AS SRC_CNCL_X_RVSN_CD,  -- [ODI] ODI staging chain -> CCAL_REPL_OWNER.TXN.SRC_CXL_REV
    t.SRC_OPT_CLS                            AS SRC_OPT_CLSS_CD,  -- [ODI] ODI staging chain -> CCAL_REPL_OWNER.TXN.SRC_OPT_CLS
    t.TXN_REPL_CNT                           AS TXN_RCNCL_REPL_CNT,  -- [ODI] ODI staging chain -> CCAL_REPL_OWNER.TXN.TXN_REPL_CNT
    t.TXN_ST_ID                              AS TXN_RCNCL_ST_ID,  -- [ODI] ODI staging chain -> CCAL_REPL_OWNER.TXN.TXN_ST_ID
    t.LGCY_CNCL_CMPLN_RSN_TP_ID              AS LGCY_CNCL_CMPLN_RSN_TP_ID,  -- [ODI] ODI staging chain -> CCAL_REPL_OWNER.TXN.LGCY_CNCL_CMPLN_RSN_TP_ID
    t.LGCY_CNCL_CMPLN_SRC_TP_ID              AS LGCY_CNCL_CMPLN_SRC_TP_ID,  -- [ODI] ODI staging chain -> CCAL_REPL_OWNER.TXN.LGCY_CNCL_CMPLN_SRC_TP_ID
    t.LGCY_MKT_TP_ID                         AS LGCY_MKT_TP_ID,  -- [ODI] ODI staging chain -> CCAL_REPL_OWNER.TXN.LGCY_MKT_TP_ID
    t.LGCY_TRD_CPCTY_TP_ID                   AS LGCY_TRD_CPCTY_TP_ID,  -- [ODI] ODI staging chain -> CCAL_REPL_OWNER.TXN.LGCY_TRD_CPCTY_TP_ID
    t.SRC_STM_ID                             AS REL_TXN_SRC_STM_ID,  -- [ODI] ODI staging chain -> CCAL_REPL_OWNER.TXN.SRC_STM_ID
    t.SRC_ENTR_CNL_TP_ID                     AS SRC_ENTR_CNL_TP_ID,  -- [ODI] ODI staging chain -> CCAL_REPL_OWNER.TXN.SRC_ENTR_CNL_TP_ID
    t.SRC_PCS_TP_ID                          AS SRC_PCS_TP_ID,  -- [ODI] ODI staging chain -> CCAL_REPL_OWNER.TXN.SRC_PCS_TP_ID
    t.TRD_SLCT_TP_ID                         AS TRD_SLCT_TP_ID,  -- [ODI] ODI staging chain -> CCAL_REPL_OWNER.TXN.TRD_SLCT_TP_ID
    'ODI_ETL'                                AS LAST_UDT_USR_NM,  -- [ETL_DEFAULT] system-managed
    SYSDATE                                  AS LAST_UDT_DTM,  -- [ETL_DEFAULT] system-managed
    TXN_RLTNP1.TXN_RLTNP_TP_ID               AS REL_TXN_RLTNP_TP_ID,  -- [ODI] ODI staging chain -> CCAL_REPL_OWNER.TXN_RLTNP.TXN_RLTNP_TP_ID
    ACATS_BROKER.BROKER_NAME                 AS ACAT_CNTRA_FIRM_NM,  -- [DRD_PHYSICAL] DRD source CCAL_REPL_OWNER.ACATS_BROKER.BROKER_NAME
    ACATS_BROKER.BROKER_SHORT_NAME           AS ACAT_CNTRA_FIRM_SHRT_NM,  -- [DRD_PHYSICAL] DRD source CCAL_REPL_OWNER.ACATS_BROKER.BROKER_SHORT_NAME
    ACATS_BROKER.BROKER_ID_TYPE              AS ACAT_CNTRA_FIRM_CLRG_ID_TP_CD,  -- [DRD_PHYSICAL] DRD source CCAL_REPL_OWNER.ACATS_BROKER.BROKER_ID_TYPE
    DRVD_TRD_CPCTY.CL_VAL_NM                 AS SIS_DLTD_EV_NM,  -- [ODI] ODI staging chain -> CCAL_REPL_OWNER.CL_VAL.CL_VAL_NM
    DRVD_TRD_CPCTY.CL_VAL_CODE               AS SRC_CNCL_RSN_CD,  -- [ODI] ODI staging chain -> CCAL_REPL_OWNER.CL_VAL.CL_VAL_CODE
    DRVD_TRD_CPCTY.CL_VAL_NM                 AS SRC_CNCL_RSN_NM,  -- [ODI] ODI staging chain -> CCAL_REPL_OWNER.CL_VAL.CL_VAL_NM
    DRVD_TRD_CPCTY.CL_VAL_CODE               AS TXN_RCNCL_ST_CD,  -- [ODI] ODI staging chain -> CCAL_REPL_OWNER.CL_VAL.CL_VAL_CODE
    DRVD_TRD_CPCTY.CL_VAL_NM                 AS TXN_RCNCL_ST_NM,  -- [ODI] ODI staging chain -> CCAL_REPL_OWNER.CL_VAL.CL_VAL_NM
    DRVD_TRD_CPCTY.CL_VAL_CODE               AS REL_TXN_RLTNP_TP_CD,  -- [ODI] ODI staging chain -> CCAL_REPL_OWNER.CL_VAL.CL_VAL_CODE
    DRVD_TRD_CPCTY.CL_VAL_NM                 AS REL_TXN_RLTNP_TP_NM,  -- [ODI] ODI staging chain -> CCAL_REPL_OWNER.CL_VAL.CL_VAL_NM
    TXN_RLTNP_SRC_STM_DIM.SRC_STM_NM         AS SRC_STM_NM,  -- [ODI] ODI staging chain -> COMMON_OWNER.SRC_STM_DIM.SRC_STM_NM
    TXN_RLTNP_SRC_STM_DIM.SRC_STM_CD         AS REL_TXN_SRC_STM_CD,  -- [ODI] ODI staging chain -> COMMON_OWNER.SRC_STM_DIM.SRC_STM_CD
    SHDW_TXN_TP.SRC_TXN_TP_NM                AS SHDW_TXN_TP_NM,  -- [ODI] ODI staging chain -> CCAL_REPL_OWNER.SHDW_TXN_TP.SRC_TXN_TP_NM /* see ETL block PRODUCT_INFORMATION in header */
    IMPCT_ACTION_LKU.DESC_TEXT               AS IMP_SRC_ACTN_NM,  -- [ODI] ODI staging chain -> REFERENCE_REPL_OWNER.IMPCT_ACTION_LKU.DESC_TEXT
    FA_NUMBER_V.FA_NUMBER_ENTITY_CODE        AS OWN_FA_NUM_ENT_CD,  -- [ODI] ODI staging chain -> SSDS_DAL_OWNER.FA_NUMBER_V.FA_NUMBER_ENTITY_CODE /* see ETL block PRODUCT_INFORMATION in header */
    FA_NUMBER_V.RESPONSIBLE_PARTY_EMPLOYEE_ID AS FA_OWN_EMPE_ID,  -- [ODI] ODI staging chain -> SSDS_DAL_OWNER.FA_NUMBER_V.RESPONSIBLE_PARTY_EMPLOYEE_ID
    ENTERPRISE_ENTITY_DIM_V.ENTITY_ENTERPRISE_ID AS OWN_FA_NUM_ENT_ENTP_ID,  -- [ODI] ODI staging chain -> SSDS_DAL_OWNER.ENTERPRISE_ENTITY_DIM_V.ENTITY_ENTERPRISE_ID /* see ETL block PRODUCT_INFORMATION in header */
    FIP.FIP_ORIG_AMT                         AS AGRT_ORIG_FEES,  -- [DRD_PHYSICAL] DRD source CCAL_REPL_OWNER.FIP.FIP_ORIG_AMT
    FIP.FIP_STMT_AMT                         AS AGRT_STMT_FEES,  -- [DRD_PHYSICAL] DRD source CCAL_REPL_OWNER.FIP.FIP_STMT_AMT
    DRVD_TRD_CPCTY.CL_VAL_CODE               AS DRVD_TRD_CPCTY_CD,  -- [ODI] ODI staging chain -> CCAL_REPL_OWNER.CL_VAL.CL_VAL_CODE
    DRVD_TRD_CPCTY.CL_VAL_NM                 AS DRVD_TRD_CPCTY_NM,  -- [ODI] ODI staging chain -> CCAL_REPL_OWNER.CL_VAL.CL_VAL_NM
    t.DRVD_TRD_CPCTY_TP_ID                   AS DRVD_TRD_CPCTY_ID,  -- [ODI] ODI staging chain -> CCAL_REPL_OWNER.TXN.DRVD_TRD_CPCTY_TP_ID
    APA.OPT_SYMB                             AS SCR_OPT_SYMB,  -- [ODI] ODI staging chain -> CCAL_REPL_OWNER.APA.OPT_SYMB /* see ETL block PRODUCT_INFORMATION in header */
    t.ADL_TRD_INSR                           AS ADL_TRD_INSR,  -- [ODI] ODI staging chain -> CCAL_REPL_OWNER.TXN.ADL_TRD_INSR
    APA.TRD_FCTR_RATE                        AS TRD_FCTR_RATE,  -- [ODI] ODI staging chain -> CCAL_REPL_OWNER.APA.TRD_FCTR_RATE /* see ETL block PRODUCT_INFORMATION in header */
    APA.MRKUP_RATE                           AS MRKUP_RATE,  -- [ODI] ODI staging chain -> CCAL_REPL_OWNER.APA.MRKUP_RATE /* see ETL block PRODUCT_INFORMATION in header */
    APA.STD_CMSN_AMT                         AS STD_CMSN_AMT,  -- [ODI] ODI staging chain -> CCAL_REPL_OWNER.APA.STD_CMSN_AMT /* see ETL block APACASH in header */
    FIP.STM_BASE_CCY_AMT                     AS ACT_CMSN_AMT,  -- [DRD_PHYSICAL] DRD source CCAL_REPL_OWNER.FIP.STM_BASE_CCY_AMT
    FIP.STM_BASE_CCY_AMT                     AS TRD_PCS_FEE_AMT,  -- [DRD_PHYSICAL] DRD source CCAL_REPL_OWNER.FIP.STM_BASE_CCY_AMT
    FIP.STM_BASE_CCY_AMT                     AS SEC_FEE_AMT,  -- [DRD_PHYSICAL] DRD source CCAL_REPL_OWNER.FIP.STM_BASE_CCY_AMT
    FIP.STM_BASE_CCY_AMT                     AS ACR_INT_AMT,  -- [DRD_PHYSICAL] DRD source CCAL_REPL_OWNER.FIP.STM_BASE_CCY_AMT
    FIP.STM_BASE_CCY_AMT                     AS CNCSN_AMT,  -- [DRD_PHYSICAL] DRD source CCAL_REPL_OWNER.FIP.STM_BASE_CCY_AMT
    FIP.STM_BASE_CCY_AMT                     AS CDSC_AMT,  -- [DRD_PHYSICAL] DRD source CCAL_REPL_OWNER.FIP.STM_BASE_CCY_AMT
    FIP.STM_BASE_CCY_AMT                     AS OTHR_FEE_AMT,  -- [DRD_PHYSICAL] DRD source CCAL_REPL_OWNER.FIP.STM_BASE_CCY_AMT
    NULL                                     AS TRD_CNCLD_F,  -- [NULL_FALLBACK] no DRD source attribute and no ODI projection found
    APA.SYMB                                 AS SYMB,  -- [ODI] ODI staging chain -> CCAL_REPL_OWNER.APA.SYMB /* see ETL block PRODUCT_INFORMATION in header */
    APA.ISIN                                 AS ISIN,  -- [ODI] ODI staging chain -> CCAL_REPL_OWNER.APA.ISIN /* see ETL block PRODUCT_INFORMATION in header */
    TXN_SRC_TAX_CODE_LKUP.SRC_TAX_CODE       AS TXN_SRC_TAX_CD,  -- [ODI] ODI staging chain -> CCAL_REPL_OWNER.TXN_SRC_TAX_CODE_LKUP.SRC_TAX_CODE
    TXN_SRC_TAX_CODE_LKUP.SRC_TAX_CODE_DSC   AS TXN_SRC_TAX_CD_DSC,  -- [ODI] ODI staging chain -> CCAL_REPL_OWNER.TXN_SRC_TAX_CODE_LKUP.SRC_TAX_CODE_DSC
    t.TM_PRC_DSCTN_F                         AS TM_PRC_DISCRETION_F,  -- [ODI] ODI staging chain -> CCAL_REPL_OWNER.TXN.TM_PRC_DSCTN_F
    TXN_AVY_CL.NNA_CGY_ID                    AS CASH_NNA_CGY_ID,  -- [ODI] ODI staging chain -> CCAL_REPL_OWNER.TXN_AVY_CL.NNA_CGY_ID /* see ETL block APACASH in header */
    NNA_CGY.NNA_CGY_NM                       AS CASH_NNA_CGY_NM,  -- [ODI] ODI staging chain -> CCAL_REPL_OWNER.NNA_CGY.NNA_CGY_NM /* see ETL block APACASH in header */
    TXN_AVY_CL.NNA_CGY_ID                    AS SCR_NNA_CGY_ID,  -- [ODI] ODI staging chain -> CCAL_REPL_OWNER.TXN_AVY_CL.NNA_CGY_ID /* see ETL block PRODUCT_INFORMATION in header */
    NNA_CGY.NNA_CGY_NM                       AS SCR_NNA_CGY_NM,  -- [ODI] ODI staging chain -> CCAL_REPL_OWNER.NNA_CGY.NNA_CGY_NM /* see ETL block PRODUCT_INFORMATION in header */
    APA.YLD                                  AS YLD,  -- [ODI] ODI staging chain -> CCAL_REPL_OWNER.APA.YLD
    APA.YTW                                  AS YTW,  -- [ODI] ODI staging chain -> CCAL_REPL_OWNER.APA.YTW
    APA.YTW_CD                               AS YTW_CD,  -- [ODI] ODI staging chain -> CCAL_REPL_OWNER.APA.YTW_CD
    BKR_AR_DIM.ORIG_SRC_STM_AR_ID            AS BKR_AC_NUM,  -- [DRD_PHYSICAL] DRD source CCSI_OWNER.AR_DIM.ORIG_SRC_STM_AR_ID
    DRVD_TRD_CPCTY.CL_VAL_CODE               AS SIS_DLTD_EV_CD,  -- [DRD_PHYSICAL] DRD source CCAL_REPL_OWNER.CL_VAL.CL_VAL_CODE
    t.ORIG_TD                                AS DB_CARD_TXN_DT,  -- [ODI] ODI staging chain -> CCAL_REPL_OWNER.TXN.ORIG_TD
    CCY.CCY_CODE                             AS DB_CARD_ORIG_CCY_CD,  -- [ODI] ODI staging chain -> REFERENCE_REPL_OWNER.CCY.CCY_CODE
    CCY.CCY_NM                               AS DB_CARD_ORIG_CCY,  -- [ODI] ODI staging chain -> REFERENCE_REPL_OWNER.CCY.CCY_NM
    DRVD_TRD_CPCTY.CL_VAL_CODE               AS SDIRA_TXN_TP_CD,  -- [DRD_PHYSICAL] DRD source CCAL_REPL_OWNER.CL_VAL.CL_VAL_CODE
    DRVD_TRD_CPCTY.CL_VAL_NM                 AS SDIRA_TXN_TP,  -- [DRD_PHYSICAL] DRD source CCAL_REPL_OWNER.CL_VAL.CL_VAL_NM
    t.TRD_NUM                                AS SDIRA_TXN_YR,  -- [ODI] ODI staging chain -> CCAL_REPL_OWNER.TXN.TRD_NUM
    CCY.CCY_NM                               AS TXN_CCY,  -- [DRD_PHYSICAL] DRD source REFERENCE_REPL_OWNER.CCY.CCY_NM
    BKR_AR_DIM.IRA_F                         AS BKR_IRA_F,  -- [DRD_PHYSICAL] DRD source CCSI_OWNER.AR_DIM.IRA_F
    BKR_AR_DIM.ERISSA_F                      AS BKR_ERISA_F,  -- [DRD_PHYSICAL] DRD source CCSI_OWNER.AR_DIM.ERISSA_F
    BKR_AR_DIM.ORIG_SRC_STM_CD               AS BKR_ORIG_SRC_STM_CD,  -- [DRD_PHYSICAL] DRD source CCSI_OWNER.AR_DIM.ORIG_SRC_STM_CD
    BKR_AR_DIM.ABC_CLSS_CD                   AS BKR_ABC_CLSS_CD,  -- [DRD_PHYSICAL] DRD source CCSI_OWNER.AR_DIM.ABC_CLSS_CD
    BKR_AR_DIM.ABC_CLSS_NM                   AS BKR_ABC_CLSS,  -- [DRD_PHYSICAL] DRD source CCSI_OWNER.AR_DIM.ABC_CLSS_NM
    BKR_AR_DIM.AR_CGY_CD                     AS AC_CGY_CD,  -- [ODI] ODI staging chain -> CCSI_OWNER.AR_DIM.AR_CGY_CD
    BKR_AR_DIM.AR_CGY_CD                     AS BKR_AC_CGY_CD,  -- [DRD_PHYSICAL] DRD source CCSI_OWNER.AR_DIM.AR_CGY_CD
    BKR_AR_DIM.AR_CGY                        AS AC_CGY,  -- [ODI] ODI staging chain -> CCSI_OWNER.AR_DIM.AR_CGY
    BKR_AR_DIM.AR_CGY                        AS BKR_AC_CGY,  -- [DRD_PHYSICAL] DRD source CCSI_OWNER.AR_DIM.AR_CGY
    BKR_AR_DIM.BSN_LINE_AFFLT                AS BKR_BSN_LINE_AFFLT,  -- [DRD_PHYSICAL] DRD source CCSI_OWNER.AR_DIM.BSN_LINE_AFFLT
    BKR_AR_DIM.BSN_LINE_AFFLT_CD             AS BKR_BSN_LINE_AFFLT_CD,  -- [DRD_PHYSICAL] DRD source CCSI_OWNER.AR_DIM.BSN_LINE_AFFLT_CD
    BKR_AR_DIM.TST_AR_F                      AS TST_AC_F,  -- [ODI] ODI staging chain -> CCSI_OWNER.AR_DIM.TST_AR_F
    BKR_AR_DIM.TST_AR_F                      AS BKR_TST_AC_F,  -- [DRD_PHYSICAL] DRD source CCSI_OWNER.AR_DIM.TST_AR_F
    BKR_AR_DIM.TAX_RPT_PARTY_ID              AS TAX_RPT_CLNT_ID,  -- [ODI] ODI staging chain -> CCSI_OWNER.AR_DIM.TAX_RPT_PARTY_ID
    BKR_AR_DIM.TAX_RPT_PARTY_ID              AS BKR_TAX_RPT_CLNT_ID,  -- [DRD_PHYSICAL] DRD source CCSI_OWNER.AR_DIM.TAX_RPT_PARTY_ID
    BKR_AR_DIM.TAX_AC_F                      AS TAX_AC_F,  -- [ODI] ODI staging chain -> CCSI_OWNER.AR_DIM.TAX_AC_F
    BKR_AR_DIM.TAX_AC_F                      AS BKR_TAX_AC_F,  -- [DRD_PHYSICAL] DRD source CCSI_OWNER.AR_DIM.TAX_AC_F
    BKR_AR_DIM.RJ_TAX_RPT_RSPL_F             AS BKR_RJ_TAX_RPT_RSPL_F,  -- [DRD_PHYSICAL] DRD source CCSI_OWNER.AR_DIM.RJ_TAX_RPT_RSPL_F
    BKR_AR_DIM.RJ_BSN_UNIT_CD                AS RJ_BSN_UNIT_CD,  -- [ODI] ODI staging chain -> CCSI_OWNER.AR_DIM.RJ_BSN_UNIT_CD
    BKR_AR_DIM.RJ_BSN_UNIT_CD                AS BKR_RJ_BSN_UNIT_CD,  -- [DRD_PHYSICAL] DRD source CCSI_OWNER.AR_DIM.RJ_BSN_UNIT_CD
    BKR_AR_DIM.RJ_BSN_UNIT                   AS RJ_BSN_UNIT,  -- [ODI] ODI staging chain -> CCSI_OWNER.AR_DIM.RJ_BSN_UNIT
    BKR_AR_DIM.RJ_BSN_UNIT                   AS BKR_RJ_BSN_UNIT,  -- [DRD_PHYSICAL] DRD source CCSI_OWNER.AR_DIM.RJ_BSN_UNIT
    BKR_AR_DIM.OWNSHP_TP_CD                  AS AC_OWNSHP_TP_CD,  -- [ODI] ODI staging chain -> CCSI_OWNER.AR_DIM.OWNSHP_TP_CD
    BKR_AR_DIM.OWNSHP_TP_CD                  AS BKR_AC_OWNSHP_TP_CD,  -- [DRD_PHYSICAL] DRD source CCSI_OWNER.AR_DIM.OWNSHP_TP_CD
    BKR_AR_DIM.OWNSHP_TP                     AS AC_OWNSHP_TP,  -- [ODI] ODI staging chain -> CCSI_OWNER.AR_DIM.OWNSHP_TP
    BKR_AR_DIM.OWNSHP_TP                     AS BKR_AC_OWNSHP_TP,  -- [DRD_PHYSICAL] DRD source CCSI_OWNER.AR_DIM.OWNSHP_TP
    BKR_AR_DIM.FIRM_AC_F                     AS BKR_FIRM_AC_F,  -- [DRD_PHYSICAL] DRD source CCSI_OWNER.AR_DIM.FIRM_AC_F
    BKR_AR_DIM.FEE_BASE_F                    AS BKR_FEE_BASE_AC_F,  -- [DRD_PHYSICAL] DRD source CCSI_OWNER.AR_DIM.FEE_BASE_F
    BKR_AR_DIM.BSN_LINE_AFFLT_CD             AS BKR_RJ_TRUST_F,  -- [DRD_PHYSICAL] DRD source CCSI_OWNER.AR_DIM.BSN_LINE_AFFLT_CD
    FA_NUMBER_V.FA_NUMBER                    AS OWN_PRIM_FA_NUM,  -- [DRD_PHYSICAL] DRD source SSDS_DAL_OWNER.FA_NUMBER_V.FA_NUMBER
    pr.CSS_PERSON_ID                         AS OWN_FA_CSS_PSN_ID,  -- [DRD_PHYSICAL] DRD source SSDS_DAL_OWNER.PERSON_RV.CSS_PERSON_ID
    pbsv.CURRENT_ADVISOR_FLAG                AS OWN_FA_CRN_ADV_F,  -- [DRD_PHYSICAL] DRD source SSDS_DAL_OWNER.PERSON_BROKERAGE_SUBDIMENSION_V.CURRENT_ADVISOR_FLAG
    pr.DEPARTMENT_BRANCH_CODE                AS OWN_FA_DEPT_BR_CD,  -- [DRD_PHYSICAL] DRD source SSDS_DAL_OWNER.PERSON_RV.DEPARTMENT_BRANCH_CODE
    padsv.DISCRETIONARY_INDICATOR            AS OWN_FA_DSCR_F,  -- [DRD_PHYSICAL] DRD source SSDS_DAL_OWNER.PERSON_AMS_DISCRETIONARY_STATUS_V.DISCRETIONARY_INDICATOR
    padsv.DISCRETIONARY_STATUS               AS OWN_FA_DSCR_ST,  -- [DRD_PHYSICAL] DRD source SSDS_DAL_OWNER.PERSON_AMS_DISCRETIONARY_STATUS_V.DISCRETIONARY_STATUS
    padsv.DISCRETIONARY_STATUS_CODE          AS OWN_FA_DSCR_ST_CD,  -- [DRD_PHYSICAL] DRD source SSDS_DAL_OWNER.PERSON_AMS_DISCRETIONARY_STATUS_V.DISCRETIONARY_STATUS_CODE
    pr.FINRA_CRD_CLASS_CODE                  AS OWN_FA_FINRA_CRD_CLSS_CD,  -- [DRD_PHYSICAL] DRD source SSDS_DAL_OWNER.PERSON_RV.FINRA_CRD_CLASS_CODE
    pr.HR_STATUS_CODE                        AS OWN_FA_HR_ST_CD,  -- [DRD_PHYSICAL] DRD source SSDS_DAL_OWNER.PERSON_RV.HR_STATUS_CODE
    pr.PRODUCER_FLAG                         AS OWN_FA_PRODUCER_F,  -- [DRD_PHYSICAL] DRD source SSDS_DAL_OWNER.PERSON_RV.PRODUCER_FLAG
    pbsv.QUALIFIED_ADVISOR_FLAG              AS OWN_FA_QUALF_ADV_F,  -- [DRD_PHYSICAL] DRD source SSDS_DAL_OWNER.PERSON_BROKERAGE_SUBDIMENSION_V.QUALIFIED_ADVISOR_FLAG
    ENTERPRISE_ENTITY_DIM_V.ENTITY_BRANCH_CODE AS OWN_FA_ENT_BR_CD,  -- [DRD_PHYSICAL] DRD source SSDS_DAL_OWNER.ENTERPRISE_ENTITY_DIM_V.ENTITY_BRANCH_CODE
    ENTERPRISE_ENTITY_DIM_V.ENTITY_BUSINESS_STATUS AS OWN_FA_ENT_BSN_ST,  -- [DRD_PHYSICAL] DRD source SSDS_DAL_OWNER.ENTERPRISE_ENTITY_DIM_V.ENTITY_BUSINESS_STATUS
    ENTERPRISE_ENTITY_DIM_V.ENTITY_DIVISION_CODE AS OWN_FA_ENT_DIV_CD,  -- [DRD_PHYSICAL] DRD source SSDS_DAL_OWNER.ENTERPRISE_ENTITY_DIM_V.ENTITY_DIVISION_CODE
    ENTERPRISE_ENTITY_DIM_V.ENTITY_DIVISION_DESCRIPTION AS OWN_FA_ENT_DIV_DSC,  -- [DRD_PHYSICAL] DRD source SSDS_DAL_OWNER.ENTERPRISE_ENTITY_DIM_V.ENTITY_DIVISION_DESCRIPTION
    ENTERPRISE_ENTITY_DIM_V.ENTITY_DIVISION_NODE AS OWN_FA_ENT_DIV_NODE,  -- [DRD_PHYSICAL] DRD source SSDS_DAL_OWNER.ENTERPRISE_ENTITY_DIM_V.ENTITY_DIVISION_NODE
    ENTERPRISE_ENTITY_DIM_V.ENTITY_MAIN_BRANCH_STATE AS OWN_FA_ENT_MAIN_BR_STE,  -- [DRD_PHYSICAL] DRD source SSDS_DAL_OWNER.ENTERPRISE_ENTITY_DIM_V.ENTITY_MAIN_BRANCH_STATE
    ENTERPRISE_ENTITY_DIM_V.ENTITY_OSJ       AS OWN_FA_ENT_OSJ,  -- [DRD_PHYSICAL] DRD source SSDS_DAL_OWNER.ENTERPRISE_ENTITY_DIM_V.ENTITY_OSJ
    eerdv.ENTITY_RETAIL_BUSINESS_MODEL_CODE  AS OWN_FA_ENT_RTL_HIER_BSN_MODL_CD,  -- [DRD_PHYSICAL] DRD source SSDS_DAL_OWNER.ENTERPRISE_ENTITY_RETAIL_DIMENSION_V.ENTITY_RETAIL_BUSINESS_MODEL_CODE
    eerdv.ENTITY_RETAIL_BUSINESS_MODEL_DESCRIPTION AS OWN_FA_ENT_RTL_HIER_BSN_MODL_DSC,  -- [DRD_PHYSICAL] DRD source SSDS_DAL_OWNER.ENTERPRISE_ENTITY_RETAIL_DIMENSION_V.ENTITY_RETAIL_BUSINESS_MODEL_DESCRIPTION
    eerdv.ENTITY_RETAIL_SALES_LOB_CODE       AS OWN_FA_ENT_RTL_SALE_HIER_LOB_CD,  -- [DRD_PHYSICAL] DRD source SSDS_DAL_OWNER.ENTERPRISE_ENTITY_RETAIL_DIMENSION_V.ENTITY_RETAIL_SALES_LOB_CODE
    eerdv.ENTITY_RETAIL_SALES_LOB_DESCRIPTION AS OWN_FA_ENT_RTL_SALE_HIER_LOB_DSC,  -- [DRD_PHYSICAL] DRD source SSDS_DAL_OWNER.ENTERPRISE_ENTITY_RETAIL_DIMENSION_V.ENTITY_RETAIL_SALES_LOB_DESCRIPTION
    eerdv.ENTITY_RETAIL_REPORTING_UNIT_CODE  AS OWN_FA_ENT_RTL_HIER_RPT_UNIT_CD,  -- [DRD_PHYSICAL] DRD source SSDS_DAL_OWNER.ENTERPRISE_ENTITY_RETAIL_DIMENSION_V.ENTITY_RETAIL_REPORTING_UNIT_CODE
    eerdv.ENTITY_RETAIL_REPORTING_UNIT_DESCRIPTION AS OWN_FA_ENT_RTL_HIER_RPT_UNIT_DSC,  -- [DRD_PHYSICAL] DRD source SSDS_DAL_OWNER.ENTERPRISE_ENTITY_RETAIL_DIMENSION_V.ENTITY_RETAIL_REPORTING_UNIT_DESCRIPTION
    eerdv.ENTITY_RETAIL_SALES_DIVISION_CODE  AS OWN_FA_ENT_RTL_SALE_DIV_CD,  -- [DRD_PHYSICAL] DRD source SSDS_DAL_OWNER.ENTERPRISE_ENTITY_RETAIL_DIMENSION_V.ENTITY_RETAIL_SALES_DIVISION_CODE
    eerdv.ENTITY_RETAIL_SALES_REGION_CODE    AS OWN_FA_ENT_RTL_SALE_HIER_RGON_CD,  -- [DRD_PHYSICAL] DRD source SSDS_DAL_OWNER.ENTERPRISE_ENTITY_RETAIL_DIMENSION_V.ENTITY_RETAIL_SALES_REGION_CODE
    eerdv.ENTITY_RETAIL_SALES_REGION_DESCRIPTION AS OWN_FA_ENT_RTL_SALE_HIER_RGON_DSC,  -- [DRD_PHYSICAL] DRD source SSDS_DAL_OWNER.ENTERPRISE_ENTITY_RETAIL_DIMENSION_V.ENTITY_RETAIL_SALES_REGION_DESCRIPTION
    eerdv.ENTITY_RETAIL_TERRITORY_CODE       AS OWN_FA_ENT_RTL_HIER_TERR_CD,  -- [DRD_PHYSICAL] DRD source SSDS_DAL_OWNER.ENTERPRISE_ENTITY_RETAIL_DIMENSION_V.ENTITY_RETAIL_TERRITORY_CODE
    eerdv.ENTITY_RETAIL_TERRITORY_DESCRIPTION AS OWN_FA_ENT_RTL_HIER_TERR_DSC,  -- [DRD_PHYSICAL] DRD source SSDS_DAL_OWNER.ENTERPRISE_ENTITY_RETAIL_DIMENSION_V.ENTITY_RETAIL_TERRITORY_DESCRIPTION
    eerdv2.ENTITY_RISK_BUSINESS_UNIT_CODE    AS OWN_FA_ENT_RSK_HIER_BSN_UNIT_CD,  -- [DRD_PHYSICAL] DRD source SSDS_DAL_OWNER.ENTERPRISE_ENTITY_RISK_DIMENSION_V.ENTITY_RISK_BUSINESS_UNIT_CODE
    eerdv2.ENTITY_RISK_BUSINESS_UNIT_DESCRIPTION AS OWN_FA_ENT_RSK_HIER_BSN_UNIT_DSC,  -- [DRD_PHYSICAL] DRD source SSDS_DAL_OWNER.ENTERPRISE_ENTITY_RISK_DIMENSION_V.ENTITY_RISK_BUSINESS_UNIT_DESCRIPTION
    ENTERPRISE_ENTITY_DIM_V.ENTITY_RJAS_ID_BOOLEAN AS OWN_FA_ENT_RJAS_ID_F,  -- [DRD_PHYSICAL] DRD source SSDS_DAL_OWNER.ENTERPRISE_ENTITY_DIM_V.ENTITY_RJAS_ID_BOOLEAN
    ENTERPRISE_ENTITY_DIM_V.ENTITY_SUBDIVISION_CODE AS OWN_FA_ENT_SUBDIV_CD,  -- [DRD_PHYSICAL] DRD source SSDS_DAL_OWNER.ENTERPRISE_ENTITY_DIM_V.ENTITY_SUBDIVISION_CODE
    ENTERPRISE_ENTITY_DIM_V.ENTITY_SUBDIVISION_DESCRIPTION AS OWN_FA_ENT_SUBDIV_DSC,  -- [DRD_PHYSICAL] DRD source SSDS_DAL_OWNER.ENTERPRISE_ENTITY_DIM_V.ENTITY_SUBDIVISION_DESCRIPTION
    ENTERPRISE_ENTITY_DIM_V.ENTITY_SUBSIDIARY AS OWN_FA_ENT_SUBS,  -- [DRD_PHYSICAL] DRD source SSDS_DAL_OWNER.ENTERPRISE_ENTITY_DIM_V.ENTITY_SUBSIDIARY
    ENTERPRISE_ENTITY_DIM_V.ENTITY_SUBTYPE   AS OWN_FA_ENT_SBTP,  -- [DRD_PHYSICAL] DRD source SSDS_DAL_OWNER.ENTERPRISE_ENTITY_DIM_V.ENTITY_SUBTYPE
    ENTERPRISE_ENTITY_DIM_V.ENTITY_SUBTYPE_CODE AS OWN_FA_ENT_SBTP_CD,  -- [DRD_PHYSICAL] DRD source SSDS_DAL_OWNER.ENTERPRISE_ENTITY_DIM_V.ENTITY_SUBTYPE_CODE
    ENTERPRISE_ENTITY_DIM_V.ENTITY_TYPE      AS OWN_FA_ENT_TP,  -- [DRD_PHYSICAL] DRD source SSDS_DAL_OWNER.ENTERPRISE_ENTITY_DIM_V.ENTITY_TYPE
    ENTERPRISE_ENTITY_DIM_V.ENTITY_TYPE_CODE AS OWN_FA_ENT_TP_CD,  -- [DRD_PHYSICAL] DRD source SSDS_DAL_OWNER.ENTERPRISE_ENTITY_DIM_V.ENTITY_TYPE_CODE
    ENTERPRISE_ENTITY_DIM_V.LOB_ALEX_BROWN_BOOLEAN AS OWN_FA_ENT_LOB_AB_F,  -- [DRD_PHYSICAL] DRD source SSDS_DAL_OWNER.ENTERPRISE_ENTITY_DIM_V.LOB_ALEX_BROWN_BOOLEAN
    ENTERPRISE_ENTITY_DIM_V.LOB_AMS_BOOLEAN  AS OWN_FA_ENT_LOB_AMS_F,  -- [DRD_PHYSICAL] DRD source SSDS_DAL_OWNER.ENTERPRISE_ENTITY_DIM_V.LOB_AMS_BOOLEAN
    ENTERPRISE_ENTITY_DIM_V.LOB_BUSINESS_MODEL AS OWN_FA_ENT_LOB_BSN_MODL,  -- [DRD_PHYSICAL] DRD source SSDS_DAL_OWNER.ENTERPRISE_ENTITY_DIM_V.LOB_BUSINESS_MODEL
    ENTERPRISE_ENTITY_DIM_V.ENTITY_BUSINESS_OPEN_DATE AS OWN_FA_ENT_BSN_OPN_DT,  -- [DRD_PHYSICAL] DRD source SSDS_DAL_OWNER.ENTERPRISE_ENTITY_DIM_V.ENTITY_BUSINESS_OPEN_DATE
    ENTERPRISE_ENTITY_DIM_V.ENTITY_CODE_LONG AS OWN_FA_ENT_LONG_CD,  -- [DRD_PHYSICAL] DRD source SSDS_DAL_OWNER.ENTERPRISE_ENTITY_DIM_V.ENTITY_CODE_LONG
    ENTERPRISE_ENTITY_DIM_V.ENTITY_CODE_SHORT AS OWN_FA_ENT_SHRT_CD,  -- [DRD_PHYSICAL] DRD source SSDS_DAL_OWNER.ENTERPRISE_ENTITY_DIM_V.ENTITY_CODE_SHORT
    ENTERPRISE_ENTITY_DIM_V.ENTITY_CSS_ID    AS OWN_FA_ENT_CSS_ID,  -- [DRD_PHYSICAL] DRD source SSDS_DAL_OWNER.ENTERPRISE_ENTITY_DIM_V.ENTITY_CSS_ID
    eerdv.ENTITY_RETAIL_SALES_COMPLEX_CODE   AS OWN_FA_ENT_RTL_SALE_CPX_CD,  -- [DRD_PHYSICAL] DRD source SSDS_DAL_OWNER.ENTERPRISE_ENTITY_RETAIL_DIMENSION_V.ENTITY_RETAIL_SALES_COMPLEX_CODE
    IMT_PD_DIM.EQTY_SECT_LVL_4               AS EQTY_IDY,  -- [ODI] ODI staging chain -> CIRD_OWNER.IMT_PD_DIM.EQTY_SECT_LVL_4
    IMT_PD_DIM.EQTY_SECT_LVL_4_CD            AS EQTY_IDY_CD,  -- [ODI] ODI staging chain -> CIRD_OWNER.IMT_PD_DIM.EQTY_SECT_LVL_4_CD
    IMT_PD_DIM.EQTY_SECT_LVL_3               AS EQTY_IDY_GRP,  -- [ODI] ODI staging chain -> CIRD_OWNER.IMT_PD_DIM.EQTY_SECT_LVL_3
    IMT_PD_DIM.EQTY_SECT_LVL_3_CD            AS EQTY_IDY_GRP_CD,  -- [ODI] ODI staging chain -> CIRD_OWNER.IMT_PD_DIM.EQTY_SECT_LVL_3_CD
    IMT_PD_DIM.EQTY_SECT_LVL_2               AS EQTY_SECT,  -- [ODI] ODI staging chain -> CIRD_OWNER.IMT_PD_DIM.EQTY_SECT_LVL_2
    IMT_PD_DIM.EQTY_SECT_LVL_2_CD            AS EQTY_SECT_CD,  -- [ODI] ODI staging chain -> CIRD_OWNER.IMT_PD_DIM.EQTY_SECT_LVL_2_CD
    IMT_PD_DIM.EQTY_SECT_LVL_1               AS EQTY_SUP_SECT,  -- [ODI] ODI staging chain -> CIRD_OWNER.IMT_PD_DIM.EQTY_SECT_LVL_1
    IMT_PD_DIM.EQTY_SECT_LVL_1_CD            AS EQTY_SUP_SECT_CD,  -- [ODI] ODI staging chain -> CIRD_OWNER.IMT_PD_DIM.EQTY_SECT_LVL_1_CD
    IMT_PD_DIM.FIRM_MODL_LVL_2               AS MODL_STRTG_DTL_AST_CLSS,  -- [ODI] ODI staging chain -> CIRD_OWNER.IMT_PD_DIM.FIRM_MODL_LVL_2
    IMT_PD_DIM.FIRM_MODL_LVL_2_CD            AS MODL_STRTG_DTL_AST_CLSS_CD,  -- [ODI] ODI staging chain -> CIRD_OWNER.IMT_PD_DIM.FIRM_MODL_LVL_2_CD
    IMT_PD_DIM.FIRM_MODL_LVL_1               AS MODL_STRTG_SMY_AST_CLSS,  -- [ODI] ODI staging chain -> CIRD_OWNER.IMT_PD_DIM.FIRM_MODL_LVL_1
    IMT_PD_DIM.FIRM_MODL_LVL_1_CD            AS MODL_STRTG_SMY_AST_CLSS_CD,  -- [ODI] ODI staging chain -> CIRD_OWNER.IMT_PD_DIM.FIRM_MODL_LVL_1_CD
    APA.PD_CMPOS_DSC                         AS PD_CMPOS_DSC,  -- [ODI] ODI staging chain -> CCAL_REPL_OWNER.APA.PD_CMPOS_DSC /* see ETL block PRODUCT_INFORMATION in header */
    IMT_PD_DIM.PD_NM                         AS PD_SHRT_NM,  -- [ODI] ODI staging chain -> CIRD_OWNER.IMT_PD_DIM.PD_NM /* see ETL block PRODUCT_INFORMATION in header */
    IMT_PD_DIM.PD_DSC                        AS PD_DSC,  -- [ODI] ODI staging chain -> CIRD_OWNER.IMT_PD_DIM.PD_DSC /* see ETL block PRODUCT_INFORMATION in header */
    IMT_PD_DIM.RPT_CL_LVL_1                  AS RPT_CL_LVL_1,  -- [ODI] ODI staging chain -> CIRD_OWNER.IMT_PD_DIM.RPT_CL_LVL_1
    IMT_PD_DIM.RPT_CL_LVL_2                  AS RPT_CL_LVL_2,  -- [ODI] ODI staging chain -> CIRD_OWNER.IMT_PD_DIM.RPT_CL_LVL_2
    IMT_PD_DIM.FIRM_RPT_LVL_2                AS RPT_STRTG_DTL_AST_CLSS,  -- [ODI] ODI staging chain -> CIRD_OWNER.IMT_PD_DIM.FIRM_RPT_LVL_2
    IMT_PD_DIM.FIRM_RPT_LVL_2_CD             AS RPT_STRTG_DTL_AST_CLSS_CD,  -- [ODI] ODI staging chain -> CIRD_OWNER.IMT_PD_DIM.FIRM_RPT_LVL_2_CD
    IMT_PD_DIM.FIRM_RPT_LVL_1                AS RPT_STRTG_SMY_AST_CLSS,  -- [ODI] ODI staging chain -> CIRD_OWNER.IMT_PD_DIM.FIRM_RPT_LVL_1
    IMT_PD_DIM.FIRM_RPT_LVL_1_CD             AS RPT_STRTG_SMY_AST_CLSS_CD,  -- [ODI] ODI staging chain -> CIRD_OWNER.IMT_PD_DIM.FIRM_RPT_LVL_1_CD
    IMT_PD_DIM.FND_FAM                       AS FND_FAM,  -- [ODI] ODI staging chain -> CIRD_OWNER.IMT_PD_DIM.FND_FAM
    IMT_PD_DIM.SHR_CLSS_TP_CD                AS SHR_CLSS_TP_CD,  -- [ODI] ODI staging chain -> CIRD_OWNER.IMT_PD_DIM.SHR_CLSS_TP_CD
    IMT_PD_DIM.SHR_CLSS_TP_NM                AS SHR_CLSS_TP,  -- [ODI] ODI staging chain -> CIRD_OWNER.IMT_PD_DIM.SHR_CLSS_TP_NM
    IMT_PD_DIM.IMT_CL_LVL_1                  AS IMT_CL_LVL_1,  -- [ODI] ODI staging chain -> CIRD_OWNER.IMT_PD_DIM.IMT_CL_LVL_1
    IMT_PD_DIM.IMT_CL_LVL_1_CD               AS IMT_CL_LVL_1_CD,  -- [ODI] ODI staging chain -> CIRD_OWNER.IMT_PD_DIM.IMT_CL_LVL_1_CD
    IMT_PD_DIM.IMT_CL_LVL_2                  AS IMT_CL_LVL_2,  -- [ODI] ODI staging chain -> CIRD_OWNER.IMT_PD_DIM.IMT_CL_LVL_2
    IMT_PD_DIM.IMT_CL_LVL_2_CD               AS IMT_CL_LVL_2_CD,  -- [ODI] ODI staging chain -> CIRD_OWNER.IMT_PD_DIM.IMT_CL_LVL_2_CD
    IMT_PD_DIM.IMT_CL_LVL_3                  AS IMT_CL_LVL_3,  -- [ODI] ODI staging chain -> CIRD_OWNER.IMT_PD_DIM.IMT_CL_LVL_3
    IMT_PD_DIM.IMT_CL_LVL_3_CD               AS IMT_CL_LVL_3_CD,  -- [ODI] ODI staging chain -> CIRD_OWNER.IMT_PD_DIM.IMT_CL_LVL_3_CD
    IMT_PD_DIM.IMT_CL_LVL_4                  AS IMT_CL_LVL_4,  -- [ODI] ODI staging chain -> CIRD_OWNER.IMT_PD_DIM.IMT_CL_LVL_4
    IMT_PD_DIM.IMT_CL_LVL_4_CD               AS IMT_CL_LVL_4_CD,  -- [ODI] ODI staging chain -> CIRD_OWNER.IMT_PD_DIM.IMT_CL_LVL_4_CD
    IMT_PD_DIM.IMT_CL_LVL_5                  AS IMT_CL_LVL_5,  -- [ODI] ODI staging chain -> CIRD_OWNER.IMT_PD_DIM.IMT_CL_LVL_5
    IMT_PD_DIM.IMT_CL_LVL_5_CD               AS IMT_CL_LVL_5_CD,  -- [ODI] ODI staging chain -> CIRD_OWNER.IMT_PD_DIM.IMT_CL_LVL_5_CD
    FA_NUMBER_V.FA_NUMBER_TYPE_CODE          AS OWN_FA_NUM_TP_CD,  -- [ODI] ODI staging chain -> SSDS_DAL_OWNER.FA_NUMBER_V.FA_NUMBER_TYPE_CODE
    CODE_SET_VALUE_V.CODE_VALUE_DESCRIPTION  AS OWN_FA_NUM_TP,  -- [ODI] ODI staging chain -> SSDS_DAL_OWNER.CODE_SET_VALUE_V.CODE_VALUE_DESCRIPTION
    APA.ORIG_QTY                             AS BOND_ACRTN_DCN_AMT,  -- [DRD_PHYSICAL] DRD source CCAL_REPL_OWNER.APA.ORIG_QTY /* see ETL block APACASH in header */
    APA.ORIG_QTY                             AS BOND_AMRZ_PREM_AMT,  -- [DRD_PHYSICAL] DRD source CCAL_REPL_OWNER.APA.ORIG_QTY /* see ETL block APACASH in header */
    APA.ORIG_QTY                             AS RJ_TRUST_BOOK_VAL_AMT,  -- [DRD_PHYSICAL] DRD source CCAL_REPL_OWNER.APA.ORIG_QTY /* see ETL block APACASH in header */
    APA.ORIG_QTY                             AS RJ_TRUST_RLZD_TAX_GAIN_OR_LOSS_AMT,  -- [DRD_PHYSICAL] DRD source CCAL_REPL_OWNER.APA.ORIG_QTY /* see ETL block APACASH in header */
    APA.ORIG_QTY                             AS BFR_REPYMT_FACE_VAL_AMT,  -- [DRD_PHYSICAL] DRD source CCAL_REPL_OWNER.APA.ORIG_QTY /* see ETL block PRODUCT_INFORMATION in header */
    APA.ORIG_QTY                             AS BFR_INCM_PYMT_FACE_VAL_AMT,  -- [DRD_PHYSICAL] DRD source CCAL_REPL_OWNER.APA.ORIG_QTY /* see ETL block PRODUCT_INFORMATION in header */
    APA.ORIG_QTY                             AS BASE_POS_QTY,  -- [DRD_PHYSICAL] DRD source CCAL_REPL_OWNER.APA.ORIG_QTY /* see ETL block PRODUCT_INFORMATION in header */
    APA.ORIG_QTY                             AS NO_SIS_SCR_MVMT_TXN_QTY,  -- [DRD_PHYSICAL] DRD source CCAL_REPL_OWNER.APA.ORIG_QTY /* see ETL block PRODUCT_INFORMATION in header */
    APA.SCR_PRC_IN_TXN_CCY                   AS NO_SIS_SCR_MVMT_TXN_PRC,  -- [DRD_PHYSICAL] DRD source CCAL_REPL_OWNER.APA.SCR_PRC_IN_TXN_CCY /* see ETL block PRODUCT_INFORMATION in header */
    APA.ORIG_QTY                             AS REIVS_SHR_QTY,  -- [DRD_PHYSICAL] DRD source CCAL_REPL_OWNER.APA.ORIG_QTY /* see ETL block PRODUCT_INFORMATION in header */
    APA.SCR_PRC_IN_TXN_CCY                   AS REIVS_PRC  -- [DRD_PHYSICAL] DRD source CCAL_REPL_OWNER.APA.SCR_PRC_IN_TXN_CCY /* see ETL block PRODUCT_INFORMATION in header */
FROM CCAL_REPL_OWNER.TXN t
LEFT JOIN CCAL_REPL_OWNER.APA APA ON TXN.TXN_ID = APA.EXEC_ID AND APA.exec_id = t.txn_id
LEFT JOIN CCAL_REPL_OWNER.TXN_AVY_CL TXN_AVY_CL ON TXN.TXN_ID = TXN_AVY_CL.TXN_ID (+) AND APA.EXEC_ID = TXN_AVY_CL.EXEC_ID (+) AND APA.APA_ID = TXN_AVY_CL.APA_ID (+) AND TXN_AVY_CL.txn_id = t.txn_id AND APA.apa_id = TXN_AVY_CL.apa_id
LEFT JOIN CCAL_REPL_OWNER.AVY_CL AVY_CL ON TXN_AVY_CL.AVY_CL_ID = AVY_CL.AVY_CL_ID (+) AND AVY_CL.avy_cl_id = TXN_AVY_CL.avy_cl_id
LEFT JOIN CIRD_OWNER.IMT_PD_DIM SEC_IMT_PD_DIM ON APA.PD_ID = SEC_IMT_PD_DIM.CCAL_PD_ID (+)
LEFT JOIN CIRD_OWNER.CCY_DIM SEC_CCY_DIM ON APA.STM_BASE_ISO_CCY_CODE = SEC_CCY_DIM.CCY_CD (+)
LEFT JOIN COMMON_OWNER.ACG_TP_DIM ACG_TP_DIM ON APA.ACG_TP_ID = ACG_TP_DIM.ACG_TP_ID (+) AND APA.ACG_TP_ID = ACG_TP_DIM.ACG_TP_ID
LEFT JOIN CCSI_OWNER.AR_DIM OFST_AR_DIM ON APA.OFST_AR_ID = OFST_AR_DIM.AR_ID (+)
LEFT JOIN CCAL_REPL_OWNER.CL_VAL ASSET_PACKAGE_TYPE ON APA.APA_TP_ID = ASSET_PACKAGE_TYPE.CL_VAL_ID (+)
LEFT JOIN CCAL_REPL_OWNER.CL_VAL DEBIT_CREDIT_TYPES ON APA.DB_CR_ID = DEBIT_CREDIT_TYPES.CL_VAL_ID (+)
LEFT JOIN COMMON_OWNER.CASH_POS_TP_DIM CASH_POS_TP_DIM ON APA.CASH_POS_TP_ID = CASH_POS_TP_DIM.CASH_POS_TP_ID (+) AND APA.CASH_POS_TP_ID = CASH_POS_TP_DIM.CASH_POS_TP_ID
LEFT JOIN CCAL_REPL_OWNER.CL_VAL SALE_CHARGE_RATE_TYPE ON APA.SALE_CHRG_RATE_TP_ID = SALE_CHARGE_RATE_TYPE.CL_VAL_ID (+)
LEFT JOIN CCAL_REPL_OWNER.CCAL_CIRD_PD_MAP CCAL_CIRD_PD_MAP ON APA.PD_ID = CCAL_CIRD_PD_MAP.CCAL_PD_ID (+) AND APA.pd_id = CCAL_CIRD_PD_MAP.ccal_pd_id AND CCAL_CIRD_PD_MAP.ccal_pd_id = APA.pd_id AND ap.pd_id = CCAL_CIRD_PD_MAP.ccal_pd_id
LEFT JOIN CIRD_OWNER.IMT_PD_DIM IMT_PD_DIM ON CCAL_CIRD_PD_MAP.CIRD_PD_ID = IMT_PD_DIM.CIRD_PD_ID (+) AND IMT_PD_DIM.CCAL_PD_ID = APA.PD_ID AND ap.pd_id = IMT_PD_DIM.cird_pd_id AND ap.pd_id = IMT_PD_DIM.ccal_pd_id AND CCAL_CIRD_PD_MAP.cird_pd_id = IMT_PD_DIM.cird_pd_id
LEFT JOIN CIRD_OWNER.CCY_DIM CCY_DIM ON APA.TXN_ISO_CCY_CODE = CCY_DIM.CCY_CD (+) AND APA.stm_base_iso_ccy_code = CCY_DIM.ccy_cd AND CCY_DIM.ccy_cd = APA.txn_iso_ccy_code
LEFT JOIN CCAL_REPL_OWNER.FIP FIP ON APA.APA_ID = FIP.APA_ID (+) AND FIP.apa_id = APA.apa_id
LEFT JOIN CCAL_REPL_OWNER.NNA_CGY NNA_CGY ON TXN_AVY_CL.NNA_CGY_ID = NNA_CGY.NNA_CGY_ID (+)
LEFT JOIN REFERENCE_REPL_OWNER.CCY CCY ON APA.ORIG_CCY_ID = CCY.CCY_ISO_NUM_CODE (+) AND apa.orig_ccy_id = CCY.CCY_ISO_NUM_CODE AND apa.txn_iso_ccy_code = CCY.CCY_CODE
LEFT JOIN CCAL_REPL_OWNER.CL_VAL TRANSACTION_TYPE ON TXN.TXN_TP_ID = TRANSACTION_TYPE.CL_VAL_ID (+)
LEFT JOIN CCAL_REPL_OWNER.CL_VAL TRANSACTION_SUBTYPE ON TXN.TXN_SBTP_ID = TRANSACTION_SUBTYPE.CL_VAL_ID (+)
LEFT JOIN CCAL_REPL_OWNER.CL_VAL EXECUTION_SUBTYPE ON TXN.EXEC_SBTP_ID = EXECUTION_SUBTYPE.CL_VAL_ID (+)
LEFT JOIN CCAL_REPL_OWNER.CL_VAL EXECUTION_TYPE ON TXN.EXEC_TP_ID = EXECUTION_TYPE.CL_VAL_ID (+)
LEFT JOIN COMMON_OWNER.DATE_DIM TD_DATE_DIM ON TXN.TD= TD_DATE_DIM.CAL_DT (+)
LEFT JOIN COMMON_OWNER.DATE_DIM SD_DATE_DIM ON TXN.SD = SD_DATE_DIM.CAL_DT (+) AND t.td = SD_DATE_DIM.cal_dt
LEFT JOIN COMMON_OWNER.SRC_STM_DIM SRC_STM_DIM ON TXN.SRC_STM_ID = SRC_STM_DIM.SRC_STM_ID (+)
LEFT JOIN SSDS_TRANSACTIONS_OWNER.TRD_SLCT_TP_DIM TRD_SLCT_TP_DIM ON TXN.TRD_SLCT_TP_ID = TRD_SLCT_TP_DIM.TRD_SLCT_TP_ID (+)
LEFT JOIN SSDS_TRANSACTIONS_OWNER.SRC_ENTR_CNL_TP_DIM SRC_ENTR_CNL_TP_DIM ON TXN.SRC_ENTR_CNL_TP_ID = SRC_ENTR_CNL_TP_DIM.SRC_ENTR_CNL_TP_ID (+)
LEFT JOIN SSDS_TRANSACTIONS_OWNER.SRC_PCS_TP_DIM SRC_PCS_TP_DIM ON TXN.SRC_PCS_TP_ID = SRC_PCS_TP_DIM.SRC_PCS_TP_ID (+)
LEFT JOIN SSDS_TRANSACTIONS_OWNER.LGCY_TRD_CPCTY_TP_DIM LGCY_TRD_CPCTY_TP_DIM ON TXN.LGCY_TRD_CPCTY_TP_ID = LGCY_TRD_CPCTY_TP_DIM.LGCY_TRD_CPCTY_TP_ID (+)
LEFT JOIN SSDS_TRANSACTIONS_OWNER.LGCY_MKT_TP_DIM LGCY_MKT_TP_DIM ON TXN.LGCY_MKT_TP_ID = LGCY_MKT_TP_DIM.LGCY_MKT_TP_ID (+)
LEFT JOIN SSDS_TRANSACTIONS_OWNER.LGCY_CNCL_CMPLN_SRC_TP_DIM LGCY_CNCL_CMPLN_SRC_TP_DIM ON TXN.LGCY_CNCL_CMPLN_SRC_TP_ID = LGCY_CNCL_CMPLN_SRC_TP_DIM.LGCY_CNCL_CMPLN_SRC_TP_ID (+)
LEFT JOIN SSDS_TRANSACTIONS_OWNER.LGCY_CNCL_CMPLN_RSN_TP_DIM LGCY_CNCL_CMPLN_RSN_TP_DIM ON TXN.LGCY_CNCL_CMPLN_RSN_TP_ID = LGCY_CNCL_CMPLN_RSN_TP_DIM.LGCY_CNCL_CMPLN_RSN_TP_ID (+)
LEFT JOIN CIRD_OWNER.EXG_DIM EXG_DIM ON TXN.EXG_CODE = EXG_DIM.EXG_CD (+) AND EXG_DIM.EXG_CD = t.exg_code
LEFT JOIN CCAL_REPL_OWNER.TXN_RLTNP TXN_RLTNP ON TXN.TXN_ID = TXN_RLTNP.SRC_TXN_ID (+)
LEFT JOIN CCAL_REPL_OWNER.CL_VAL CD_CL_VAL ON TXN.DOL_IND_ID = CD_CL_VAL.CL_VAL_ID (+)
LEFT JOIN CCAL_REPL_OWNER.CL_VAL OMS_EXEC_TP ON TXN.OMS_EXEC_TP_ID = OMS_EXEC_TP.CL_VAL_ID (+)
LEFT JOIN COMMON_OWNER.SRC_STM_DIM ORIG_SRC_STM_DIM ON TXN.ORIG_SRC_STM_ID =ORIG_SRC_STM_DIM.SRC_STM_ID (+)
LEFT JOIN CCAL_REPL_OWNER.ACATS_BROKER ACATS_BROKER ON TXN.ORIG_SRC_STM_CODE = ACATS_BROKER.BROKER_ID (+) AND b.broker_id = t.orig_src_stm_code AND ACATS_BROKER.broker_id = t.orig_src_stm_code
LEFT JOIN CCAL_REPL_OWNER.CL_VAL SIS_DLTD_EV ON TXN.SRC_BUY_SELL_MULTI_ID = SIS_DLTD_EV.CL_VAL_ID (+)
LEFT JOIN CCAL_REPL_OWNER.CL_VAL SRC_CNCL_RSN ON TXN.SRC_CNCL_RSN_ID = SRC_CNCL_RSN.CL_VAL_ID (+)
LEFT JOIN CCAL_REPL_OWNER.CL_VAL TXN_RCNCL_ST ON TXN.TXN_ST_ID = TXN_RCNCL_ST.CL_VAL_ID (+)
LEFT JOIN CCAL_REPL_OWNER.CL_VAL REL_TXN_RLTNP_TP ON TXN_RLTNP.TXN_RLTNP_TP_ID = REL_TXN_RLTNP_TP.CL_VAL_ID (+)
LEFT JOIN COMMON_OWNER.SRC_STM_DIM TXN_RLTNP_SRC_STM_DIM ON TXN_RLTNP_TXN.SRC_STM_ID = TXN_RLTNP_SRC_STM_DIM.SRC_STM_ID (+) AND TXN_RLTNP_SRC_STM_DIM.src_stm_id = t.src_stm_id AND t.src_stm_id = TXN_RLTNP_SRC_STM_DIM.src_stm_id
LEFT JOIN CCAL_REPL_OWNER.SHDW_TXN_TP SHDW_TXN_TP ON TXN.SRC_TXN_TP = SHDW_TXN_TP.SRC_TXN_TP (+)
LEFT JOIN REFERENCE_REPL_OWNER.IMPCT_ACTION_LKU IMPCT_ACTION_LKU ON TXN.SRC_ACTN_CODE = IMPCT_ACTION_LKU.ACTION_CODE (+)
LEFT JOIN CCSI_OWNER.AR_GRP_SUBDIM AR_GRP_SUBDIM ON TXN.AR_ID = AR_GRP_SUBDIM.AR_ID (+) AND AR_GRP_SUBDIM.AR_ID = t.AR_ID AND t.AR_ID = AR_GRP_SUBDIM.AR_ID AND AR_GRP_SUBDIM.ar_id = t.ar_id
LEFT JOIN CCSI_OWNER.AR_DIM AR_DIM ON TXN.AR_ID = AR_DIM.AR_ID (+)
LEFT JOIN CCSI_OWNER.AR_AC_SUBDIM AR_AC_SUBDIM ON TXN.AR_ID = AR_AC_SUBDIM.AR_ID (+) AND APA_CASH.AC_ID = AR_AC_SUBDIM.DEP_AC_SETUP_ID (+) AND AR_AC_SUBDIM.ar_id = t.ar_id AND AR_AC_SUBDIM.dep_ac_setup_id = APA.ac_id
LEFT JOIN CCAL_REPL_OWNER.CL_VAL IMPACT_TRD_LGCY_TRD_CPCTY_TP_DIM ON TXN.LGCY_TRD_CPCTY_TP_ID = IMPACT_TRD_LGCY_TRD_CPCTY_TP_DIM.CL_VAL_ID (+)
LEFT JOIN CCAL_REPL_OWNER.CL_VAL DRVD_TRD_CPCTY ON TXN.DRVD_TRD_CPCTY_TP_ID = DRVD_TRD_CPCTY.CL_VAL_ID (+) AND APA.APA_TP_ID = DRVD_TRD_CPCTY.CL_VAL_ID AND DRVD_TRD_CPCTY.cl_val_id = APA.sale_chrg_rate_tp_id AND APA.db_cr_id = DRVD_TRD_CPCTY.cl_val_id AND DRVD_TRD_CPCTY.cl_val_id = APA.db_cr_id AND DRVD_TRD_CPCTY.cl_val_id = t.txn_tp_id AND DRVD_TRD_CPCTY.cl_val_id = t.txn_sbtp_id AND t.EXEC_TP_ID = DRVD_TRD_CPCTY.CL_VAL_ID AND t.EXEC_SBTP_ID = DRVD_TRD_CPCTY.CL_VAL_ID AND t.dol_ind_id = DRVD_TRD_CPCTY.cl_val_id AND DRVD_TRD_CPCTY.cl_val_id = t.lgcy_trd_cpcty_tp_id AND DRVD_TRD_CPCTY.cl_val_id = t.oms_exec_tp_id AND DRVD_TRD_CPCTY.cl_val_id = t.SRC_BUY_SELL_MULTI_ID AND cl_val.cl_val_id = t.SRC_CNCL_RSN_ID AND DRVD_TRD_CPCTY.cl_val_id = t.txn_st_id AND cl_val_id = TXN_RLTNP1.TXN_RLTNP_TP_ID
LEFT JOIN CCAL_REPL_OWNER.TXN_RLTNP TXN_RLTNP1 ON TXN.TXN_ID = TXN_RLTNP1.TRGT_TXN_ID (+) AND t.txn_id = TXN_RLTNP1.src_txn_id
LEFT JOIN CCAL_REPL_OWNER.TXN_SRC_TAX_CODE_LKUP TXN_SRC_TAX_CODE_LKUP ON TXN.SRC_TAX_CODE_ID = TXN_SRC_TAX_CODE_LKUP.SRC_TAX_CODE_ID (+)
LEFT JOIN SSDS_DAL_OWNER.FA_NUMBER_V FA_NUMBER_V ON AR_GRP_SUBDIM.FA_NUM = FA_NUMBER_V.FA_NUMBER (+) AND AVY_FACT_STEP3_STG_RT.OWN_FA_NUM = FA_NUMBER_V.FA_NUMBER (+) AND FA_NUMBER_V.FA_NUMBER = OWN_FA_NUM AND FA_NUMBER_V.responsible_party_employee_id = FA_NUMBER_V.responsible_party_employee_id AND AR_GRP_SUBDIM.FA_NUM = FA_NUMBER_V.FA_NUMBER
LEFT JOIN SSDS_DAL_OWNER.CODE_SET_VALUE_V CODE_SET_VALUE_V ON FA_NUMBER_V.FA_NUMBER_TYPE_CODE_ID = CODE_SET_VALUE_V.CODE_VALUE_ID (+) AND CODE_SET_VALUE_V.CODE_VALUE_ID = FA_NUMBER_V.FA_NUMBER_TYPE_CODE_ID
LEFT JOIN SSDS_DAL_OWNER.ENTERPRISE_ENTITY_DIM_V ENTERPRISE_ENTITY_DIM_V ON FA_NUMBER_V.FA_NUMBER_ENTITY_CODE = ENTERPRISE_ENTITY_DIM_V.ENTITY_CODE_LONG (+) AND ENTERPRISE_ENTITY_DIM_V.Entity_code_long = OWN_FA_NUM_ENT_CD AND ENTERPRISE_ENTITY_DIM_V.entity_code_long = FA_NUMBER_V.fa_number_entity_code
LEFT JOIN CCSI_OWNER.AR_DIM BKR_AR_DIM ON AVY_FACT_STEP3_STG_RT.BKR_AR_ID = BKR_AR_DIM.AR_ID (+) AND BKR_AR_DIM.AR_ID = t.AR_ID AND APA.OFST_AR_ID = BKR_AR_DIM.AR_ID AND AR_GRP_SUBDIM.linked_bkr_ar_id = BKR_AR_DIM.ar_id AND t.ar_id = BKR_AR_DIM.ar_id
LEFT JOIN CCSI_REPL_OWNER.AR_DIM ad ON ad.AR_ID = APA.OFST_AR_ID
LEFT JOIN TRANSACTIONS_OWNER.LGCY_CNCL_CMPLN_RSN_TP_DIM lccrtd ON lccrtd.lgcy_cncl_cmpln_rsn_tp_id = t.lgcy_cncl_cmpln_rsn_tp_id
LEFT JOIN TRANSACTIONS_OWNER.LGCY_CNCL_CMPLN_SRC_TP_DIM lccstd ON lccstd.lgcy_cncl_cmpln_src_tp_id = t.lgcy_cncl_cmpln_src_tp_id
LEFT JOIN TRANSACTIONS_OWNER.LGCY_MKT_TP_DIM lmtd ON lmtd.lgcy_mkt_tp_id = t.lgcy_mkt_tp_id
LEFT JOIN TRANSACTIONS_OWNER.LGCY_TRD_CPCTY_TP_DIM ltctd ON t.lgcy_trd_cpcty_tp_id = ltctd.lgcy_trd_cpcty_tp_id
LEFT JOIN TRANSACTIONS_OWNER.SRC_PCS_TP_DIM sptd ON t.src_pcs_tp_id = sptd.src_pcs_tp_id
LEFT JOIN TRANSACTIONS_OWNER.SRC_ENTR_CNL_TP_DIM sectd ON t.src_entr_cnl_tp_id = sectd.src_entr_cnl_tp_id
LEFT JOIN TRANSACTIONS_OWNER.TRD_SLCT_TP_DIM tstd ON t.trd_slct_tp_id = tstd.trd_slct_tp_id
LEFT JOIN CCAL_REPL_OWNER.SRC_STM_DIM ssd ON t.src_stm_id = ssd.src_stm_id
LEFT JOIN COMMON_OWNER.DT_DIM dd ON t.sd = dd.cal_dt
LEFT JOIN CCAL_REPL_OWNER.AR_DIM ad2 ON t.AR_ID = ad2.AR_ID
LEFT JOIN CCAL_REPL_OWNER.J$TXN jt ON jt.txn_id = t.txn_id
LEFT JOIN CCAL_REPL_OWNER.IMPCT_ACTION_LKU ial ON t.src_actn_code = impct_action_lku.action_code
LEFT JOIN SSDS_DAL_OWNER.PERSON_RV pr ON pr.EMPLOYEE_ID = FA_NUMBER_V.responsible_party_employee_id
LEFT JOIN SSDS_DAL_OWNER.PERSON_BROKERAGE_SUBDIMENSION_V pbsv ON brk_own_psn_brk.EMPLOYEE_ID = FA_NUMBER_V.responsible_party_employee_id
LEFT JOIN SSDS_DAL_OWNER.PERSON_AMS_DISCRETIONARY_STATUS_V padsv ON padsv.EMPLOYEE_ID = FA_NUMBER_V.responsible_party_employee_id
LEFT JOIN SSDS_DAL_OWNER.ENTERPRISE_ENTITY_RETAIL_DIMENSION_V eerdv ON eerdv.entity_enterprise_id = ENTERPRISE_ENTITY_DIM_V.entity_enterprise_id
LEFT JOIN SSDS_DAL_OWNER.ENTERPRISE_ENTITY_RISK_DIMENSION_V eerdv2 ON ENTERPRISE_ENTITY_DIM_V.entity_enterprise_id = eerdv2.entity_enterprise_id;
