-- Generated by drd_first_emitter v1
-- Target: IKOROSTELEV.AVY_FACT_SIDE
-- Columns: 369  Joins: 35  CTEs: 2
-- Provenance: DRD_AD=92, ETL_BLOCK=93, ETL_DEFAULT=7, FALLBACK=120, ODI=57

WITH product_information AS (
  (Security source CUSIP, Security Product Id, Security CIRD Product Id, Security Option Symbol, Symbol, ISIN, Product Composite Description, Product Short Name, Product Description)
  If there is atleast 1 APASEC, consider above fields from that APASEC
  If there is an iAPASEC but no APASEC, consider above fields from iAPASEC

  Source Effective Date:
  If there is only iAPASEC or only iAPACSH, grab source effective date from the iAPASEC/iAPACSH
  If there is atleast 1 APASEC or APACSH, grab source effective date from that APASEC/APACSH
  Updates from below user names should be skipped by main process (Product Backlog Item 1937973: Skip Activity updates from additional usernames)
  CCAL_PKG_TXN_RECON_REPL (EOD CCAL Recon Replay)
  PERF_MAP_CF_MASTER_STG_PROC (Cash Flow Generation)
  CCAL_PKG_TXN_POS_RECON_STS_UPD (EOD CCAL Recon)
  CCAL_PERF_PKG_CF_MSTR_LOAD_RJTRST  (Cash Flow Generation)
  CCAL_PKG_TXN_POS_RECON (EOD CCAL Recon)
  CCAL_PKG_TXN_RECON_RJTRUST_1 (EOD CCAL Recon)
  PERF_PKG_CF_MSTR_LOAD (Cash Flow Generation)
  CCAL_PKG_TXN_RECON_SHADOW_1 (EOD CCAL Recon)
  CCAL_PKG_LOAD_TXN_AY_CL_1 (Activity Reclassification)
  CCAL_PKG_LOAD_TXN_AY_CL_2 (Activity Reclassification)
  CCAL_PKG_LOAD_TXN_AY_CL_3 (Activity Reclassification)
  CCAL_PKG_LOAD_TXN_AY_CL_4 (Activity Reclassification)
  CCAL_PKG_LOAD_TXN_AY_CL_5 (Activity Reclassification)
  CCAL_PKG_LOAD_TXN_AY_CL_6 (Activity Reclassification)
  CCAL_PKG_LOAD_TXN_AY_CL_7 (Activity Reclassification)
  CCAL_PKG_LOAD_TXN_AY_CL_8 (Activity Reclassification)
  CCAL_PKG_LOAD_TXN_AY_CL_9 (Activity Reclassification)
  CCAL_PKG_LOAD_TXN_AY_CL_10 (Activity Reclassification)
  Update Trade Cancelled Flag on original trade when cancellation arrives (Product Backlog Item 2030710: Add columns available in DWH and missing in Lighthouse for Trade Activity)
),
apacash AS (
  Check for regexp_like(cv.cl_val_code,'^APACSH[0-7][0-9]')
  For a Transaction, 
  If only one record exists then consider that record.
  If 2 records exists ( 
       If (one record is 'APACSH04' & other is 'APACSH11') 
            then consider skip 'APACSH04' record and load 'APACSH11' but use the values to
            (1) calculate aggregated value from APA.TXN_AMT fields from 'APACSH04' and 'APACSH11' and store it in Cash Transaction Amount and Cash System base currency amount
            (2) populate sales charge attributes from 'APACSH04' for 5 attributes (Sales Charge Rate Multiplier Number, Sales Charge Rate, Sales Charge Rate Type Code, Sales Charge Rate Type Id, Sales Charge Rate Type Name)
       else Drop those 2 records exception entire transaction
  )

  APASEC :
  Check for cl_val_Code like '^APASEC[0-7][0-9]' THEN consider as 'Security' record.

  iAPASEC/iAPACSH:
  Refer to below section for further filter criteria on iAPASEC/iAPACSH. Applicable to both iAPACSH and iAPASEC.
)
TRUNCATE TABLE IKOROSTELEV.AVY_FACT_SIDE;
INSERT /*+ APPEND PARALLEL(8) */ INTO IKOROSTELEV.AVY_FACT_SIDE (
    EXG_DIM_ID,
    AR_DIM_ID,
    OFST_AR_DIM_ID,
    ACG_TP_DIM_ID,
    CASH_POS_TP_DIM_ID,
    SBC_CCY_DIM_ID,
    SEC_PD_DIM_ID,
    CASH_PD_DIM_ID,
    LGCY_CNCL_CMPLN_RSN_DIM_ID,
    LGCY_CNCL_CMPLN_SRC_DIM_ID,
    LGCY_MKT_TP_DIM_ID,
    LGCY_TRD_CPCTY_TP_DIM_ID,
    SRC_PCS_TP_DIM_ID,
    SRC_ENTR_CNL_TP_DIM_ID,
    TRD_SLCT_TP_DIM_ID,
    TXN_SRC_STM_DIM_ID,
    REL_TXN_SRC_STM_DIM_ID,
    BKR_AR_DIM_ID,
    TD_DIM_ID,
    TD,
    SD_DIM_ID,
    SD,
    BKG_DT,
    ORIG_BKG_DT,
    EXEC_DTM,
    TXN_ID,
    REL_TXN_ID,
    TRD_NUM,
    ORIG_TRD_NUM,
    TXN_SRC_KEY,
    SEC_APA_ID,
    CSH_APA_ID,
    SEC_PRC_IN_TXN_CCY,
    SEC_TXN_AMT,
    CASH_TXN_AMT,
    SEC_ORIG_QTY,
    SEC_SRC_PRC_IN_SBC,
    SALE_CHRG_RATE_PCT,
    SALE_CHRG_RATE_TP_ID,
    SALE_CHRG_RATE_TP_CD,
    SEC_SBC_AMT,
    CASH_SBC_AMT,
    SBC_CCY_CALC_DT,
    SBC_EXG_RATE,
    CASH_DB_CR_CD,
    SEC_DB_CR_CD,
    SEC_SRC_SEQ_NUM,
    SEC_APA_EXT_QUALFR,
    SEC_DSC_TRAILER_1,
    SEC_ALT_DSC_TRAILER_2,
    BUY_SELL_IND,
    CF_GEN_F,
    TXN_CL_F,
    OPT_CLSS_CD,
    SEC_SRC_CUSIP,
    CASH_DSC_TRAILER_1,
    CASH_ALT_DSC_TRAILER_2,
    CASH_SRC_SEQ_NUM,
    TXN_TP_ID,
    TXN_TP_CD,
    TXN_TP_NM,
    TXN_TP_DSC,
    TXN_SBTP_ID,
    TXN_SUB_TP_NM,
    TXN_SUB_TP_CD,
    TXN_SUB_TP_DSC,
    EXEC_TP_ID,
    EXEC_TP_CD,
    EXEC_TP_NM,
    EXEC_TP_DSC,
    EXEC_SBTP_CD,
    EXEC_SBTP_NM,
    EXEC_SBTP_DSC,
    EXEC_SBTP_ID,
    SEC_APA_TP_ID,
    SCR_APA_TP_CD,
    SCR_APA_TP_NM,
    SCR_APA_TP_DSC,
    CSH_APA_TP_ID,
    CASH_APA_TP_CD,
    CASH_APA_TP_NM,
    CASH_APA_TP_DSC,
    SCR_AVY_CGY,
    SCR_AVY_TP,
    SEC_AVY_CL_ID,
    CASH_AVY_CGY,
    CASH_AVY_TP,
    CSH_AVY_CL_ID,
    CRT_DTM,
    CRT_USR_NM,
    SESS_NO,
    SRC_ENTR_DTM,
    AR_ID,
    SEC_PD_ID,
    CASH_PD_ID,
    BKR_AR_ID,
    OFST_AR_ID,
    BR_CD,
    FA_NUM,
    SRC_CRT_USRNM,
    ORIG_TD,
    SRC_PCS_TP_CD,
    SRC_PCS_TP_NM,
    CCY_DIM_ID,
    CCY_CD,
    SBC_CCY_CD,
    SRC_EFF_DT,
    DOL_IND_ID,
    DOL_IND_CD,
    DOL_IND_NM,
    OMS_ORDR_KEY,
    EXG_CD,
    EXG_NM,
    ACG_TP_CD,
    ACG_TP_NM,
    CASH_POS_TP_CD,
    CASH_POS_TP_NM,
    LGCY_CNCL_CMPLN_RSN_TP_CD,
    LGCY_CNCL_CMPLN_RSN_TP_NM,
    LGCY_CNCL_CMPLN_SRC_TP_CD,
    LGCY_CNCL_CMPLN_SRC_TP_NM,
    LGCY_MKT_TP_CD,
    LGCY_MKT_TP_NM,
    LGCY_TRD_CPCTY_TP_CD,
    LGCY_TRD_CPCTY_TP_NM,
    SRC_ENTR_CNL_TP_CD,
    SRC_ENTR_CNL_TP_NM,
    TRD_SLCT_TP_CD,
    TRD_SLCT_TP_NM,
    SALE_CHRG_RATE_TP_NM,
    CASH_DB_CR_NM,
    SEC_DB_CR_NM,
    SRC_STM_CD,
    BATCH_DT,
    CASH_CIRD_PD_ID,
    SEC_CIRD_PD_ID,
    ACTV_F,
    SRC_TXN_CODE,
    OMS_EXEC_TP_ID,
    OMS_EXEC_TP_CD,
    OMS_EXEC_TP_NM,
    OMS_EXEC_TP_DSC,
    CLNT_FRIENDLY_DSC,
    ORIG_SRC_STM_ID,
    ORIG_SRC_STM_CD,
    ACG_TP_ID,
    CASH_APA_EXT_QUALFR,
    CASH_POS_TP_ID,
    SALE_CHRG_RATE_MULTI_NUM,
    AR_ORIG_SRC_STM_CD,
    MF_AC_NUM,
    OFST_ORIG_SRC_STM_AR_ID,
    OFST_AR_ORIG_SRC_STM_CD,
    OFST_AR_SETL_TP_CD,
    OFST_AR_SETL_TP_DSC,
    AR_SETL_TP_CD,
    AR_SETL_TP_DSC,
    ORIG_SRC_STM_AR_ID,
    CASH_SIMP_DSPL_AVY_CGY,
    CASH_SIMP_DSPL_AVY_TP,
    SCR_SIMP_DSPL_AVY_CGY,
    SCR_SIMP_DSPL_AVY_TP,
    SHDW_TXN_TP_CD,
    IMP_SRC_ACTN_CD,
    SIS_DLTD_EV_ID,
    SIS_USR_ID,
    SIS_AC_CL_CD,
    SRC_CNCL_RSN_ID,
    SRC_TXN_SEQ_NUM,
    DVDN_RCRD_DT,
    OWN_IMP_FA_NUM,
    OWN_FA_NUM,
    ACAT_CNTRA_FIRM_CLRG_NUM,
    MM_ALT_ID,
    SRC_STM_ID,
    SRC_CNCL_X_RVSN_CD,
    SRC_OPT_CLSS_CD,
    TXN_RCNCL_REPL_CNT,
    TXN_RCNCL_ST_ID,
    LGCY_CNCL_CMPLN_RSN_TP_ID,
    LGCY_CNCL_CMPLN_SRC_TP_ID,
    LGCY_MKT_TP_ID,
    LGCY_TRD_CPCTY_TP_ID,
    REL_TXN_SRC_STM_ID,
    SRC_ENTR_CNL_TP_ID,
    SRC_PCS_TP_ID,
    TRD_SLCT_TP_ID,
    LAST_UDT_USR_NM,
    LAST_UDT_DTM,
    REL_TXN_RLTNP_TP_ID,
    ACAT_CNTRA_FIRM_NM,
    ACAT_CNTRA_FIRM_SHRT_NM,
    ACAT_CNTRA_FIRM_CLRG_ID_TP_CD,
    SIS_DLTD_EV_NM,
    SRC_CNCL_RSN_CD,
    SRC_CNCL_RSN_NM,
    TXN_RCNCL_ST_CD,
    TXN_RCNCL_ST_NM,
    REL_TXN_RLTNP_TP_CD,
    REL_TXN_RLTNP_TP_NM,
    SRC_STM_NM,
    REL_TXN_SRC_STM_CD,
    SHDW_TXN_TP_NM,
    IMP_SRC_ACTN_NM,
    OWN_FA_NUM_ENT_CD,
    FA_OWN_EMPE_ID,
    OWN_FA_NUM_ENT_ENTP_ID,
    AGRT_ORIG_FEES,
    AGRT_STMT_FEES,
    DRVD_TRD_CPCTY_CD,
    DRVD_TRD_CPCTY_NM,
    DRVD_TRD_CPCTY_ID,
    SCR_OPT_SYMB,
    ADL_TRD_INSR,
    TRD_FCTR_RATE,
    MRKUP_RATE,
    STD_CMSN_AMT,
    ACT_CMSN_AMT,
    TRD_PCS_FEE_AMT,
    SEC_FEE_AMT,
    ACR_INT_AMT,
    CNCSN_AMT,
    CDSC_AMT,
    OTHR_FEE_AMT,
    TRD_CNCLD_F,
    SYMB,
    ISIN,
    TXN_SRC_TAX_CD,
    TXN_SRC_TAX_CD_DSC,
    TM_PRC_DISCRETION_F,
    CASH_NNA_CGY_ID,
    CASH_NNA_CGY_NM,
    SCR_NNA_CGY_ID,
    SCR_NNA_CGY_NM,
    YLD,
    YTW,
    YTW_CD,
    BKR_AC_NUM,
    SIS_DLTD_EV_CD,
    DB_CARD_TXN_DT,
    DB_CARD_ORIG_CCY_CD,
    DB_CARD_ORIG_CCY,
    SDIRA_TXN_TP_CD,
    SDIRA_TXN_TP,
    SDIRA_TXN_YR,
    TXN_CCY,
    BKR_IRA_F,
    BKR_ERISA_F,
    BKR_ORIG_SRC_STM_CD,
    BKR_ABC_CLSS_CD,
    BKR_ABC_CLSS,
    AC_CGY_CD,
    BKR_AC_CGY_CD,
    AC_CGY,
    BKR_AC_CGY,
    BKR_BSN_LINE_AFFLT,
    BKR_BSN_LINE_AFFLT_CD,
    TST_AC_F,
    BKR_TST_AC_F,
    TAX_RPT_CLNT_ID,
    BKR_TAX_RPT_CLNT_ID,
    TAX_AC_F,
    BKR_TAX_AC_F,
    BKR_RJ_TAX_RPT_RSPL_F,
    RJ_BSN_UNIT_CD,
    BKR_RJ_BSN_UNIT_CD,
    RJ_BSN_UNIT,
    BKR_RJ_BSN_UNIT,
    AC_OWNSHP_TP_CD,
    BKR_AC_OWNSHP_TP_CD,
    AC_OWNSHP_TP,
    BKR_AC_OWNSHP_TP,
    BKR_FIRM_AC_F,
    BKR_FEE_BASE_AC_F,
    BKR_RJ_TRUST_F,
    OWN_PRIM_FA_NUM,
    OWN_FA_CSS_PSN_ID,
    OWN_FA_CRN_ADV_F,
    OWN_FA_DEPT_BR_CD,
    OWN_FA_DSCR_F,
    OWN_FA_DSCR_ST,
    OWN_FA_DSCR_ST_CD,
    OWN_FA_FINRA_CRD_CLSS_CD,
    OWN_FA_HR_ST_CD,
    OWN_FA_PRODUCER_F,
    OWN_FA_QUALF_ADV_F,
    OWN_FA_ENT_BR_CD,
    OWN_FA_ENT_BSN_ST,
    OWN_FA_ENT_DIV_CD,
    OWN_FA_ENT_DIV_DSC,
    OWN_FA_ENT_DIV_NODE,
    OWN_FA_ENT_MAIN_BR_STE,
    OWN_FA_ENT_OSJ,
    OWN_FA_ENT_RTL_HIER_BSN_MODL_CD,
    OWN_FA_ENT_RTL_HIER_BSN_MODL_DSC,
    OWN_FA_ENT_RTL_SALE_HIER_LOB_CD,
    OWN_FA_ENT_RTL_SALE_HIER_LOB_DSC,
    OWN_FA_ENT_RTL_HIER_RPT_UNIT_CD,
    OWN_FA_ENT_RTL_HIER_RPT_UNIT_DSC,
    OWN_FA_ENT_RTL_SALE_DIV_CD,
    OWN_FA_ENT_RTL_SALE_HIER_RGON_CD,
    OWN_FA_ENT_RTL_SALE_HIER_RGON_DSC,
    OWN_FA_ENT_RTL_HIER_TERR_CD,
    OWN_FA_ENT_RTL_HIER_TERR_DSC,
    OWN_FA_ENT_RSK_HIER_BSN_UNIT_CD,
    OWN_FA_ENT_RSK_HIER_BSN_UNIT_DSC,
    OWN_FA_ENT_RJAS_ID_F,
    OWN_FA_ENT_SUBDIV_CD,
    OWN_FA_ENT_SUBDIV_DSC,
    OWN_FA_ENT_SUBS,
    OWN_FA_ENT_SBTP,
    OWN_FA_ENT_SBTP_CD,
    OWN_FA_ENT_TP,
    OWN_FA_ENT_TP_CD,
    OWN_FA_ENT_LOB_AB_F,
    OWN_FA_ENT_LOB_AMS_F,
    OWN_FA_ENT_LOB_BSN_MODL,
    OWN_FA_ENT_BSN_OPN_DT,
    OWN_FA_ENT_LONG_CD,
    OWN_FA_ENT_SHRT_CD,
    OWN_FA_ENT_CSS_ID,
    OWN_FA_ENT_RTL_SALE_CPX_CD,
    EQTY_IDY,
    EQTY_IDY_CD,
    EQTY_IDY_GRP,
    EQTY_IDY_GRP_CD,
    EQTY_SECT,
    EQTY_SECT_CD,
    EQTY_SUP_SECT,
    EQTY_SUP_SECT_CD,
    MODL_STRTG_DTL_AST_CLSS,
    MODL_STRTG_DTL_AST_CLSS_CD,
    MODL_STRTG_SMY_AST_CLSS,
    MODL_STRTG_SMY_AST_CLSS_CD,
    PD_CMPOS_DSC,
    PD_SHRT_NM,
    PD_DSC,
    RPT_CL_LVL_1,
    RPT_CL_LVL_2,
    RPT_STRTG_DTL_AST_CLSS,
    RPT_STRTG_DTL_AST_CLSS_CD,
    RPT_STRTG_SMY_AST_CLSS,
    RPT_STRTG_SMY_AST_CLSS_CD,
    FND_FAM,
    SHR_CLSS_TP_CD,
    SHR_CLSS_TP,
    IMT_CL_LVL_1,
    IMT_CL_LVL_1_CD,
    IMT_CL_LVL_2,
    IMT_CL_LVL_2_CD,
    IMT_CL_LVL_3,
    IMT_CL_LVL_3_CD,
    IMT_CL_LVL_4,
    IMT_CL_LVL_4_CD,
    IMT_CL_LVL_5,
    IMT_CL_LVL_5_CD,
    OWN_FA_NUM_TP_CD,
    OWN_FA_NUM_TP,
    BOND_ACRTN_DCN_AMT,
    BOND_AMRZ_PREM_AMT,
    RJ_TRUST_BOOK_VAL_AMT,
    RJ_TRUST_RLZD_TAX_GAIN_OR_LOSS_AMT,
    BFR_REPYMT_FACE_VAL_AMT,
    BFR_INCM_PYMT_FACE_VAL_AMT,
    BASE_POS_QTY,
    NO_SIS_SCR_MVMT_TXN_QTY,
    NO_SIS_SCR_MVMT_TXN_PRC,
    REIVS_SHR_QTY,
    REIVS_PRC
)
SELECT /*+ PARALLEL(8) */
    ed.EXG_DIM_ID                            AS EXG_DIM_ID,  -- [DRD_AD] JOIN from DRD col-AD
    product_information.AR_DIM_ID            AS AR_DIM_ID,  -- [ETL_BLOCK] from ETL Notes block PRODUCT_INFORMATION
    product_information.AR_DIM_ID            AS OFST_AR_DIM_ID,  -- [ETL_BLOCK] from ETL Notes block PRODUCT_INFORMATION
    atd.ACG_TP_DIM_ID                        AS ACG_TP_DIM_ID,  -- [DRD_AD] JOIN from DRD col-AD
    cptd.CASH_POS_TP_DIM_ID                  AS CASH_POS_TP_DIM_ID,  -- [DRD_AD] JOIN from DRD col-AD
    cd.CCY_DIM_ID                            AS SBC_CCY_DIM_ID,  -- [DRD_AD] JOIN from DRD col-AD
    product_information.IMT_PD_DIM_ID        AS SEC_PD_DIM_ID,  -- [ETL_BLOCK] from ETL Notes block PRODUCT_INFORMATION
    apacash.IMT_PD_DIM_ID                    AS CASH_PD_DIM_ID,  -- [ETL_BLOCK] from ETL Notes block APACASH
    lccrtd.LGCY_CNCL_CMPLN_RSN_TP_DIM_ID     AS LGCY_CNCL_CMPLN_RSN_DIM_ID,  -- [DRD_AD] JOIN from DRD col-AD
    lccstd.LGCY_CNCL_CMPLN_SRC_TP_DIM_ID     AS LGCY_CNCL_CMPLN_SRC_DIM_ID,  -- [DRD_AD] JOIN from DRD col-AD
    lmtd.LGCY_MKT_TP_DIM_ID                  AS LGCY_MKT_TP_DIM_ID,  -- [DRD_AD] JOIN from DRD col-AD
    ltctd.LGCY_TRD_CPCTY_TP_DIM_ID           AS LGCY_TRD_CPCTY_TP_DIM_ID,  -- [DRD_AD] JOIN from DRD col-AD
    sptd.SRC_PCS_TP_DIM_ID                   AS SRC_PCS_TP_DIM_ID,  -- [DRD_AD] JOIN from DRD col-AD
    sectd.SRC_ENTR_CNL_TP_DIM_ID             AS SRC_ENTR_CNL_TP_DIM_ID,  -- [DRD_AD] JOIN from DRD col-AD
    tstd.TRD_SLCT_TP_DIM_ID                  AS TRD_SLCT_TP_DIM_ID,  -- [DRD_AD] JOIN from DRD col-AD
    ssd.SRC_STM_DIM_ID                       AS TXN_SRC_STM_DIM_ID,  -- [DRD_AD] JOIN from DRD col-AD
    ssd2.SRC_STM_DIM_ID                      AS REL_TXN_SRC_STM_DIM_ID,  -- [DRD_AD] JOIN from DRD col-AD
    product_information.AR_DIM_ID            AS BKR_AR_DIM_ID,  -- [ETL_BLOCK] from ETL Notes block PRODUCT_INFORMATION
    dd.DT_DIM_ID                             AS TD_DIM_ID,  -- [DRD_AD] JOIN from DRD col-AD
    t.TD                                     AS TD,  -- [ODI] ODI projection (matched DRD)
    dd.DT_DIM_ID                             AS SD_DIM_ID,  -- [FALLBACK] plain pass-through (no DRD AD or ODI hint)
    t.SD                                     AS SD,  -- [ODI] ODI projection (matched DRD)
    t.BKG_DT                                 AS BKG_DT,  -- [ODI] ODI projection (matched DRD)
    t.ORIG_BKG_DT                            AS ORIG_BKG_DT,  -- [ODI] ODI projection (matched DRD)
    t.EXEC_DTM                               AS EXEC_DTM,  -- [ODI] ODI projection (matched DRD)
    t.TXN_ID                                 AS TXN_ID,  -- [ODI] ODI projection (matched DRD)
    tr.TRGT_TXN_ID                           AS REL_TXN_ID,  -- [DRD_AD] JOIN from DRD col-AD
    t.TRD_NUM                                AS TRD_NUM,  -- [ODI] ODI projection (matched DRD)
    t.ORIG_TRD_NUM                           AS ORIG_TRD_NUM,  -- [ODI] ODI projection (matched DRD)
    t.TXN_SRC_KEY                            AS TXN_SRC_KEY,  -- [ODI] ODI projection (matched DRD)
    product_information.APA_ID               AS SEC_APA_ID,  -- [ETL_BLOCK] from ETL Notes block PRODUCT_INFORMATION
    apacash.APA_ID                           AS CSH_APA_ID,  -- [ETL_BLOCK] from ETL Notes block APACASH
    product_information.SCR_PRC_IN_TXN_CCY   AS SEC_PRC_IN_TXN_CCY,  -- [ETL_BLOCK] from ETL Notes block PRODUCT_INFORMATION
    product_information.TXN_AMT              AS SEC_TXN_AMT,  -- [ETL_BLOCK] from ETL Notes block PRODUCT_INFORMATION
    apacash.TXN_AMT                          AS CASH_TXN_AMT,  -- [ETL_BLOCK] from ETL Notes block APACASH
    product_information.ORIG_QTY             AS SEC_ORIG_QTY,  -- [ETL_BLOCK] from ETL Notes block PRODUCT_INFORMATION
    product_information.SCR_PRC_IN_SBC       AS SEC_SRC_PRC_IN_SBC,  -- [ETL_BLOCK] from ETL Notes block PRODUCT_INFORMATION
    apacash.SALE_CHRG_RATE                   AS SALE_CHRG_RATE_PCT,  -- [ETL_BLOCK] from ETL Notes block APACASH
    apacash.SALE_CHRG_RATE_TP_ID             AS SALE_CHRG_RATE_TP_ID,  -- [ETL_BLOCK] from ETL Notes block APACASH
    apacash.CL_VAL_CODE                      AS SALE_CHRG_RATE_TP_CD,  -- [ETL_BLOCK] from ETL Notes block APACASH
    product_information.STM_BASE_CCY_AMT     AS SEC_SBC_AMT,  -- [ETL_BLOCK] from ETL Notes block PRODUCT_INFORMATION
    apacash.STM_BASE_CCY_AMT                 AS CASH_SBC_AMT,  -- [ETL_BLOCK] from ETL Notes block APACASH
    a.STM_BASE_CCY_CLC_DTM                   AS SBC_CCY_CALC_DT,  -- [DRD_AD] JOIN from DRD col-AD
    a.STM_BASE_CCY_EXG_RATE                  AS SBC_EXG_RATE,  -- [DRD_AD] JOIN from DRD col-AD
    apacash.CL_VAL_CODE                      AS CASH_DB_CR_CD,  -- [ETL_BLOCK] from ETL Notes block APACASH
    product_information.CL_VAL_CODE          AS SEC_DB_CR_CD,  -- [ETL_BLOCK] from ETL Notes block PRODUCT_INFORMATION
    product_information.SRC_SEQ_NUM          AS SEC_SRC_SEQ_NUM,  -- [ETL_BLOCK] from ETL Notes block PRODUCT_INFORMATION
    product_information.APA_EXT_QUALFR       AS SEC_APA_EXT_QUALFR,  -- [ETL_BLOCK] from ETL Notes block PRODUCT_INFORMATION
    product_information.APA_DSC              AS SEC_DSC_TRAILER_1,  -- [ETL_BLOCK] from ETL Notes block PRODUCT_INFORMATION
    product_information.ALT_DSC              AS SEC_ALT_DSC_TRAILER_2,  -- [ETL_BLOCK] from ETL Notes block PRODUCT_INFORMATION
    t.BUY_SELL_IND                           AS BUY_SELL_IND,  -- [ODI] ODI projection (matched DRD)
    t.CF_GEN_F                               AS CF_GEN_F,  -- [ODI] ODI projection (matched DRD)
    t.TXN_CL_F                               AS TXN_CL_F,  -- [ODI] ODI projection (matched DRD)
    t.OPTS_CLSS_CODE                         AS OPT_CLSS_CD,  -- [ODI] ODI projection (matched DRD)
    product_information.SRC_PD_ID            AS SEC_SRC_CUSIP,  -- [ETL_BLOCK] from ETL Notes block PRODUCT_INFORMATION
    apacash.APA_DSC                          AS CASH_DSC_TRAILER_1,  -- [ETL_BLOCK] from ETL Notes block APACASH
    apacash.ALT_DSC                          AS CASH_ALT_DSC_TRAILER_2,  -- [ETL_BLOCK] from ETL Notes block APACASH
    apacash.SRC_SEQ_NUM                      AS CASH_SRC_SEQ_NUM,  -- [ETL_BLOCK] from ETL Notes block APACASH
    t.TXN_TP_ID                              AS TXN_TP_ID,  -- [ODI] ODI projection (matched DRD)
    cv.CL_VAL_CODE                           AS TXN_TP_CD,  -- [DRD_AD] JOIN from DRD col-AD
    cv.CL_VAL_NM                             AS TXN_TP_NM,  -- [DRD_AD] JOIN from DRD col-AD
    cv.DSC                                   AS TXN_TP_DSC,  -- [DRD_AD] JOIN from DRD col-AD
    t.TXN_SBTP_ID                            AS TXN_SBTP_ID,  -- [ODI] ODI projection (matched DRD)
    cv.CL_VAL_NM                             AS TXN_SUB_TP_NM,  -- [DRD_AD] JOIN from DRD col-AD
    cv.CL_VAL_CODE                           AS TXN_SUB_TP_CD,  -- [DRD_AD] JOIN from DRD col-AD
    cv.DSC                                   AS TXN_SUB_TP_DSC,  -- [DRD_AD] JOIN from DRD col-AD
    t.EXEC_TP_ID                             AS EXEC_TP_ID,  -- [ODI] ODI projection (matched DRD)
    cv.CL_VAL_CODE                           AS EXEC_TP_CD,  -- [DRD_AD] JOIN from DRD col-AD
    cv.CL_VAL_NM                             AS EXEC_TP_NM,  -- [DRD_AD] JOIN from DRD col-AD
    cv.DSC                                   AS EXEC_TP_DSC,  -- [DRD_AD] JOIN from DRD col-AD
    cv.CL_VAL_CODE                           AS EXEC_SBTP_CD,  -- [DRD_AD] JOIN from DRD col-AD
    cv.CL_VAL_NM                             AS EXEC_SBTP_NM,  -- [DRD_AD] JOIN from DRD col-AD
    cv.DSC                                   AS EXEC_SBTP_DSC,  -- [DRD_AD] JOIN from DRD col-AD
    t.EXEC_SBTP_ID                           AS EXEC_SBTP_ID,  -- [ODI] ODI projection (matched DRD)
    product_information.APA_TP_ID            AS SEC_APA_TP_ID,  -- [ETL_BLOCK] from ETL Notes block PRODUCT_INFORMATION
    product_information.CL_VAL_CODE          AS SCR_APA_TP_CD,  -- [ETL_BLOCK] from ETL Notes block PRODUCT_INFORMATION
    product_information.CL_VAL_NM            AS SCR_APA_TP_NM,  -- [ETL_BLOCK] from ETL Notes block PRODUCT_INFORMATION
    product_information.DSC                  AS SCR_APA_TP_DSC,  -- [ETL_BLOCK] from ETL Notes block PRODUCT_INFORMATION
    apacash.APA_TP_ID                        AS CSH_APA_TP_ID,  -- [ETL_BLOCK] from ETL Notes block APACASH
    apacash.CL_VAL_CODE                      AS CASH_APA_TP_CD,  -- [ETL_BLOCK] from ETL Notes block APACASH
    apacash.CL_VAL_NM                        AS CASH_APA_TP_NM,  -- [ETL_BLOCK] from ETL Notes block APACASH
    apacash.DSC                              AS CASH_APA_TP_DSC,  -- [ETL_BLOCK] from ETL Notes block APACASH
    product_information.AVY_CGY              AS SCR_AVY_CGY,  -- [ETL_BLOCK] from ETL Notes block PRODUCT_INFORMATION
    product_information.AVY_TP               AS SCR_AVY_TP,  -- [ETL_BLOCK] from ETL Notes block PRODUCT_INFORMATION
    product_information.AVY_CL_ID            AS SEC_AVY_CL_ID,  -- [ETL_BLOCK] from ETL Notes block PRODUCT_INFORMATION
    apacash.AVY_CGY                          AS CASH_AVY_CGY,  -- [ETL_BLOCK] from ETL Notes block APACASH
    apacash.AVY_TP                           AS CASH_AVY_TP,  -- [ETL_BLOCK] from ETL Notes block APACASH
    apacash.AVY_CL_ID                        AS CSH_AVY_CL_ID,  -- [ETL_BLOCK] from ETL Notes block APACASH
    SYSDATE                                  AS CRT_DTM,  -- [ETL_DEFAULT] system-managed
    'ODI_ETL'                                AS CRT_USR_NM,  -- [ETL_DEFAULT] system-managed
    0                                        AS SESS_NO,  -- [ETL_DEFAULT] system-managed
    t.SRC_ENTR_DTM                           AS SRC_ENTR_DTM,  -- [ODI] ODI projection (matched DRD)
    t.AR_ID                                  AS AR_ID,  -- [ODI] ODI projection (matched DRD)
    product_information.PD_ID                AS SEC_PD_ID,  -- [ETL_BLOCK] from ETL Notes block PRODUCT_INFORMATION
    apacash.PD_ID                            AS CASH_PD_ID,  -- [ETL_BLOCK] from ETL Notes block APACASH
    apacash.BKR_AR_ID
AR_ID                  AS BKR_AR_ID,  -- [ETL_BLOCK] from ETL Notes block APACASH
    a.OFST_AR_ID                             AS OFST_AR_ID,  -- [DRD_AD] JOIN from DRD col-AD
    t.BR_CODE                                AS BR_CD,  -- [ODI] ODI projection (matched DRD)
    t.FA_NUM                                 AS FA_NUM,  -- [ODI] ODI projection (matched DRD)
    t.SRC_CRT_USRNM                          AS SRC_CRT_USRNM,  -- [ODI] ODI projection (matched DRD)
    t.ORIG_TD                                AS ORIG_TD,  -- [ODI] ODI projection (matched DRD)
    sptd.SRC_PCS_TP_CD                       AS SRC_PCS_TP_CD,  -- [DRD_AD] JOIN from DRD col-AD
    sptd.SRC_PCS_TP_NM                       AS SRC_PCS_TP_NM,  -- [DRD_AD] JOIN from DRD col-AD
    cd.CCY_DIM_ID                            AS CCY_DIM_ID,  -- [DRD_AD] JOIN from DRD col-AD
    a.TXN_ISO_CCY_CODE                       AS CCY_CD,  -- [FALLBACK] plain pass-through (no DRD AD or ODI hint)
    a.STM_BASE_ISO_CCY_CODE                  AS SBC_CCY_CD,  -- [DRD_AD] JOIN from DRD col-AD
    a.SRC_EFF_DT                             AS SRC_EFF_DT,  -- [DRD_AD] JOIN from DRD col-AD
    t.DOL_IND_ID                             AS DOL_IND_ID,  -- [ODI] ODI projection (matched DRD)
    cv.CL_VAL_CODE                           AS DOL_IND_CD,  -- [DRD_AD] JOIN from DRD col-AD
    cv.CL_VAL_NM                             AS DOL_IND_NM,  -- [DRD_AD] JOIN from DRD col-AD
    t.OMS_ORDR_KEY                           AS OMS_ORDR_KEY,  -- [ODI] ODI projection (matched DRD)
    t.EXG_CODE                               AS EXG_CD,  -- [ODI] ODI projection (matched DRD)
    ed.EXG_NM                                AS EXG_NM,  -- [DRD_AD] JOIN from DRD col-AD
    atd.ACG_TP_CD                            AS ACG_TP_CD,  -- [DRD_AD] JOIN from DRD col-AD
    atd.ACG_TP_NM                            AS ACG_TP_NM,  -- [DRD_AD] JOIN from DRD col-AD
    cptd.CASH_POS_TP_CD                      AS CASH_POS_TP_CD,  -- [DRD_AD] JOIN from DRD col-AD
    cptd.CASH_POS_TP_NM                      AS CASH_POS_TP_NM,  -- [DRD_AD] JOIN from DRD col-AD
    lccrtd.LGCY_CNCL_CMPLN_RSN_TP_CD         AS LGCY_CNCL_CMPLN_RSN_TP_CD,  -- [DRD_AD] JOIN from DRD col-AD
    lccrtd.LGCY_CNCL_CMPLN_RSN_TP_NM         AS LGCY_CNCL_CMPLN_RSN_TP_NM,  -- [DRD_AD] JOIN from DRD col-AD
    lccstd.LGCY_CNCL_CMPLN_SRC_TP_CD         AS LGCY_CNCL_CMPLN_SRC_TP_CD,  -- [DRD_AD] JOIN from DRD col-AD
    lccstd.LGCY_CNCL_CMPLN_SRC_TP_NM         AS LGCY_CNCL_CMPLN_SRC_TP_NM,  -- [DRD_AD] JOIN from DRD col-AD
    lmtd.LGCY_MKT_TP_CD                      AS LGCY_MKT_TP_CD,  -- [DRD_AD] JOIN from DRD col-AD
    lmtd.LGCY_MKT_TP_NM                      AS LGCY_MKT_TP_NM,  -- [DRD_AD] JOIN from DRD col-AD
    product_information.LGCY_TRD_CPCTY_TP_CD
CL_VAL_CODE AS LGCY_TRD_CPCTY_TP_CD,  -- [ETL_BLOCK] from ETL Notes block PRODUCT_INFORMATION
    product_information.LGCY_TRD_CPCTY_TP_NM AS LGCY_TRD_CPCTY_TP_NM,  -- [ETL_BLOCK] from ETL Notes block PRODUCT_INFORMATION
    sectd.SRC_ENTR_CNL_TP_CD                 AS SRC_ENTR_CNL_TP_CD,  -- [DRD_AD] JOIN from DRD col-AD
    sectd.SRC_ENTR_CNL_TP_NM                 AS SRC_ENTR_CNL_TP_NM,  -- [DRD_AD] JOIN from DRD col-AD
    tstd.TRD_SLCT_TP_CD                      AS TRD_SLCT_TP_CD,  -- [DRD_AD] JOIN from DRD col-AD
    tstd.TRD_SLCT_TP_NM                      AS TRD_SLCT_TP_NM,  -- [DRD_AD] JOIN from DRD col-AD
    apacash.CL_VAL_NM                        AS SALE_CHRG_RATE_TP_NM,  -- [ETL_BLOCK] from ETL Notes block APACASH
    apacash.CL_VAL_NM                        AS CASH_DB_CR_NM,  -- [ETL_BLOCK] from ETL Notes block APACASH
    product_information.CL_VAL_NM            AS SEC_DB_CR_NM,  -- [ETL_BLOCK] from ETL Notes block PRODUCT_INFORMATION
    ssd.SRC_STM_CD                           AS SRC_STM_CD,  -- [DRD_AD] JOIN from DRD col-AD
    TRUNC(SYSDATE)                           AS BATCH_DT,  -- [ETL_DEFAULT] system-managed
    apacash.CIRD_PD_ID                       AS CASH_CIRD_PD_ID,  -- [ETL_BLOCK] from ETL Notes block APACASH
    ccpm.CIRD_PD_ID                          AS SEC_CIRD_PD_ID,  -- [DRD_AD] JOIN from DRD col-AD
    'Y'                                      AS ACTV_F,  -- [ETL_DEFAULT] system-managed
    t.SRC_TXN_CODE                           AS SRC_TXN_CODE,  -- [ODI] ODI projection (matched DRD)
    t.OMS_EXEC_TP_ID                         AS OMS_EXEC_TP_ID,  -- [ODI] ODI projection (matched DRD)
    cv.CL_VAL_CODE                           AS OMS_EXEC_TP_CD,  -- [DRD_AD] JOIN from DRD col-AD
    cv.CL_VAL_NM                             AS OMS_EXEC_TP_NM,  -- [DRD_AD] JOIN from DRD col-AD
    cv.DSC                                   AS OMS_EXEC_TP_DSC,  -- [DRD_AD] JOIN from DRD col-AD
    a.CLNT_FRIENDLY_DESC                     AS CLNT_FRIENDLY_DSC,  -- [DRD_AD] JOIN from DRD col-AD
    t.ORIG_SRC_STM_ID                        AS ORIG_SRC_STM_ID,  -- [ODI] ODI projection (matched DRD)
    t.ORIG_SRC_STM_CODE                      AS ORIG_SRC_STM_CD,  -- [ODI] ODI projection (matched DRD)
    a.ACG_TP_ID                              AS ACG_TP_ID,  -- [DRD_AD] JOIN from DRD col-AD
    apacash.APA_EXT_QUALFR                   AS CASH_APA_EXT_QUALFR,  -- [ETL_BLOCK] from ETL Notes block APACASH
    a.CASH_POS_TP_ID                         AS CASH_POS_TP_ID,  -- [DRD_AD] JOIN from DRD col-AD
    apacash.SALE_CHRG_RATE                   AS SALE_CHRG_RATE_MULTI_NUM,  -- [ETL_BLOCK] from ETL Notes block APACASH
    product_information.ORIG_SRC_STM_CD      AS AR_ORIG_SRC_STM_CD,  -- [ETL_BLOCK] from ETL Notes block PRODUCT_INFORMATION
    product_information.MF_DRC_EXT_AC_NUM    AS MF_AC_NUM,  -- [ETL_BLOCK] from ETL Notes block PRODUCT_INFORMATION
    product_information.ORIG_SRC_STM_AR_ID   AS OFST_ORIG_SRC_STM_AR_ID,  -- [ETL_BLOCK] from ETL Notes block PRODUCT_INFORMATION
    product_information.ORIG_SRC_STM_CD      AS OFST_AR_ORIG_SRC_STM_CD,  -- [ETL_BLOCK] from ETL Notes block PRODUCT_INFORMATION
    product_information.SETL_TP_CD           AS OFST_AR_SETL_TP_CD,  -- [ETL_BLOCK] from ETL Notes block PRODUCT_INFORMATION
    product_information.SETL_TP              AS OFST_AR_SETL_TP_DSC,  -- [ETL_BLOCK] from ETL Notes block PRODUCT_INFORMATION
    product_information.SETL_TP_CD           AS AR_SETL_TP_CD,  -- [ETL_BLOCK] from ETL Notes block PRODUCT_INFORMATION
    product_information.SETL_TP              AS AR_SETL_TP_DSC,  -- [ETL_BLOCK] from ETL Notes block PRODUCT_INFORMATION
    product_information.ORIG_SRC_STM_AR_ID   AS ORIG_SRC_STM_AR_ID,  -- [ETL_BLOCK] from ETL Notes block PRODUCT_INFORMATION
    apacash.DSPL_AVY_CGY                     AS CASH_SIMP_DSPL_AVY_CGY,  -- [ETL_BLOCK] from ETL Notes block APACASH
    apacash.DSPL_AVY_TP                      AS CASH_SIMP_DSPL_AVY_TP,  -- [ETL_BLOCK] from ETL Notes block APACASH
    product_information.DSPL_AVY_CGY         AS SCR_SIMP_DSPL_AVY_CGY,  -- [ETL_BLOCK] from ETL Notes block PRODUCT_INFORMATION
    product_information.DSPL_AVY_TP          AS SCR_SIMP_DSPL_AVY_TP,  -- [ETL_BLOCK] from ETL Notes block PRODUCT_INFORMATION
    t.SRC_TXN_TP                             AS SHDW_TXN_TP_CD,  -- [ODI] ODI projection (matched DRD)
    t.SRC_ACTN_CODE                          AS IMP_SRC_ACTN_CD,  -- [ODI] ODI projection (matched DRD)
    t.SRC_BUY_SELL_MULTI_ID                  AS SIS_DLTD_EV_ID,  -- [ODI] ODI projection (matched DRD)
    t.USR_ID                                 AS SIS_USR_ID,  -- [ODI] ODI projection (matched DRD)
    t.SRC_PRIM_CL                            AS SIS_AC_CL_CD,  -- [ODI] ODI projection (matched DRD)
    t.SRC_CNCL_RSN_ID                        AS SRC_CNCL_RSN_ID,  -- [ODI] ODI projection (matched DRD)
    t.SRC_TXN_SEQ_NUM                        AS SRC_TXN_SEQ_NUM,  -- [ODI] ODI projection (matched DRD)
    t.DVDN_RCRD_DT                           AS DVDN_RCRD_DT,  -- [ODI] ODI projection (matched DRD)
    t.SALE_PSN_NUM                           AS OWN_IMP_FA_NUM,  -- [ODI] ODI projection (matched DRD)
    product_information.FA_NUM               AS OWN_FA_NUM,  -- [ETL_BLOCK] from ETL Notes block PRODUCT_INFORMATION
    t.ORIG_SRC_STM_CODE                      AS ACAT_CNTRA_FIRM_CLRG_NUM,  -- [FALLBACK] plain pass-through (no DRD AD or ODI hint)
    t.ORIG_SRC_STM_CODE                      AS MM_ALT_ID,  -- [FALLBACK] plain pass-through (no DRD AD or ODI hint)
    jaf.SRC_STM_ID                           AS SRC_STM_ID,  -- [ODI] ODI projection (matched DRD)
    t.SRC_CXL_REV                            AS SRC_CNCL_X_RVSN_CD,  -- [ODI] ODI projection (matched DRD)
    t.SRC_OPT_CLS                            AS SRC_OPT_CLSS_CD,  -- [ODI] ODI projection (matched DRD)
    t.TXN_REPL_CNT                           AS TXN_RCNCL_REPL_CNT,  -- [ODI] ODI projection (matched DRD)
    t.TXN_ST_ID                              AS TXN_RCNCL_ST_ID,  -- [ODI] ODI projection (matched DRD)
    t.LGCY_CNCL_CMPLN_RSN_TP_ID              AS LGCY_CNCL_CMPLN_RSN_TP_ID,  -- [ODI] ODI projection (matched DRD)
    t.LGCY_CNCL_CMPLN_SRC_TP_ID              AS LGCY_CNCL_CMPLN_SRC_TP_ID,  -- [ODI] ODI projection (matched DRD)
    t.LGCY_MKT_TP_ID                         AS LGCY_MKT_TP_ID,  -- [ODI] ODI projection (matched DRD)
    t.LGCY_TRD_CPCTY_TP_ID                   AS LGCY_TRD_CPCTY_TP_ID,  -- [ODI] ODI projection (matched DRD)
    t.SRC_STM_ID (FROM T2)                   AS REL_TXN_SRC_STM_ID,  -- [DRD_AD] JOIN from DRD col-AD
    t.SRC_ENTR_CNL_TP_ID                     AS SRC_ENTR_CNL_TP_ID,  -- [ODI] ODI projection (matched DRD)
    t.SRC_PCS_TP_ID                          AS SRC_PCS_TP_ID,  -- [ODI] ODI projection (matched DRD)
    t.TRD_SLCT_TP_ID                         AS TRD_SLCT_TP_ID,  -- [ODI] ODI projection (matched DRD)
    'ODI_ETL'                                AS LAST_UDT_USR_NM,  -- [ETL_DEFAULT] system-managed
    SYSDATE                                  AS LAST_UDT_DTM,  -- [ETL_DEFAULT] system-managed
    tr.TXN_RLTNP_TP_ID                       AS REL_TXN_RLTNP_TP_ID,  -- [DRD_AD] JOIN from DRD col-AD
    ab.BROKER_NAME                           AS ACAT_CNTRA_FIRM_NM,  -- [DRD_AD] JOIN from DRD col-AD
    ab.BROKER_SHORT_NAME                     AS ACAT_CNTRA_FIRM_SHRT_NM,  -- [DRD_AD] JOIN from DRD col-AD
    ab.BROKER_ID_TYPE                        AS ACAT_CNTRA_FIRM_CLRG_ID_TP_CD,  -- [DRD_AD] JOIN from DRD col-AD
    cv.CL_VAL_NM                             AS SIS_DLTD_EV_NM,  -- [DRD_AD] JOIN from DRD col-AD
    cv.CL_VAL_CODE                           AS SRC_CNCL_RSN_CD,  -- [DRD_AD] JOIN from DRD col-AD
    cv.CL_VAL_NM                             AS SRC_CNCL_RSN_NM,  -- [DRD_AD] JOIN from DRD col-AD
    cv.CL_VAL_CODE                           AS TXN_RCNCL_ST_CD,  -- [DRD_AD] JOIN from DRD col-AD
    cv.CL_VAL_NM                             AS TXN_RCNCL_ST_NM,  -- [DRD_AD] JOIN from DRD col-AD
    cv.CL_VAL_CODE                           AS REL_TXN_RLTNP_TP_CD,  -- [DRD_AD] JOIN from DRD col-AD
    cv.CL_VAL_NM                             AS REL_TXN_RLTNP_TP_NM,  -- [DRD_AD] JOIN from DRD col-AD
    ssd.SRC_STM_NM                           AS SRC_STM_NM,  -- [DRD_AD] JOIN from DRD col-AD
    ssd2.SRC_STM_CD                          AS REL_TXN_SRC_STM_CD,  -- [DRD_AD] JOIN from DRD col-AD
    product_information.SRC_TXN_TP_NM        AS SHDW_TXN_TP_NM,  -- [ETL_BLOCK] from ETL Notes block PRODUCT_INFORMATION
    ial.DESC_TEXT                            AS IMP_SRC_ACTN_NM,  -- [DRD_AD] JOIN from DRD col-AD
    product_information.FA_NUMBER_ENTITY_CODE AS OWN_FA_NUM_ENT_CD,  -- [ETL_BLOCK] from ETL Notes block PRODUCT_INFORMATION
    fnv.RESPONSIBLE_PARTY_EMPLOYEE_ID        AS FA_OWN_EMPE_ID,  -- [ODI] ODI projection (matched DRD)
    product_information.ENTITY_ENTERPRISE_ID AS OWN_FA_NUM_ENT_ENTP_ID,  -- [ETL_BLOCK] from ETL Notes block PRODUCT_INFORMATION
    f.FIP_ORIG_AMT                           AS AGRT_ORIG_FEES,  -- [DRD_AD] JOIN from DRD col-AD
    f.FIP_STMT_AMT                           AS AGRT_STMT_FEES,  -- [DRD_AD] JOIN from DRD col-AD
    cv.CL_VAL_CODE                           AS DRVD_TRD_CPCTY_CD,  -- [ODI] ODI projection (matched DRD)
    cv.CL_VAL_NM                             AS DRVD_TRD_CPCTY_NM,  -- [ODI] ODI projection (matched DRD)
    t.DRVD_TRD_CPCTY_TP_ID                   AS DRVD_TRD_CPCTY_ID,  -- [ODI] ODI projection (matched DRD)
    product_information.OPT_SYMB             AS SCR_OPT_SYMB,  -- [ETL_BLOCK] from ETL Notes block PRODUCT_INFORMATION
    t.ADL_TRD_INSR                           AS ADL_TRD_INSR,  -- [ODI] ODI projection (matched DRD)
    product_information.TRD_FCTR_RATE        AS TRD_FCTR_RATE,  -- [ETL_BLOCK] from ETL Notes block PRODUCT_INFORMATION
    product_information.MRKUP_RATE           AS MRKUP_RATE,  -- [ETL_BLOCK] from ETL Notes block PRODUCT_INFORMATION
    apacash.STD_CMSN_AMT                     AS STD_CMSN_AMT,  -- [ETL_BLOCK] from ETL Notes block APACASH
    f.STM_BASE_CCY_AMT                       AS ACT_CMSN_AMT,  -- [FALLBACK] plain pass-through (no DRD AD or ODI hint)
    f.STM_BASE_CCY_AMT                       AS TRD_PCS_FEE_AMT,  -- [FALLBACK] plain pass-through (no DRD AD or ODI hint)
    f.STM_BASE_CCY_AMT                       AS SEC_FEE_AMT,  -- [FALLBACK] plain pass-through (no DRD AD or ODI hint)
    f.STM_BASE_CCY_AMT                       AS ACR_INT_AMT,  -- [FALLBACK] plain pass-through (no DRD AD or ODI hint)
    f.STM_BASE_CCY_AMT                       AS CNCSN_AMT,  -- [FALLBACK] plain pass-through (no DRD AD or ODI hint)
    f.STM_BASE_CCY_AMT                       AS CDSC_AMT,  -- [FALLBACK] plain pass-through (no DRD AD or ODI hint)
    f.STM_BASE_CCY_AMT                       AS OTHR_FEE_AMT,  -- [FALLBACK] plain pass-through (no DRD AD or ODI hint)
    NULL /* TODO: no DRD spec, no ODI hint */ AS TRD_CNCLD_F,  -- [FALLBACK] no source resolved
    product_information.SYMB                 AS SYMB,  -- [ETL_BLOCK] from ETL Notes block PRODUCT_INFORMATION
    product_information.ISIN                 AS ISIN,  -- [ETL_BLOCK] from ETL Notes block PRODUCT_INFORMATION
    tstcl.SRC_TAX_CODE                       AS TXN_SRC_TAX_CD,  -- [FALLBACK] plain pass-through (no DRD AD or ODI hint)
    tstcl.SRC_TAX_CODE_DSC                   AS TXN_SRC_TAX_CD_DSC,  -- [FALLBACK] plain pass-through (no DRD AD or ODI hint)
    t.TM_PRC_DSCTN_F                         AS TM_PRC_DISCRETION_F,  -- [ODI] ODI projection (matched DRD)
    apacash.NNA_CGY_ID                       AS CASH_NNA_CGY_ID,  -- [ETL_BLOCK] from ETL Notes block APACASH
    apacash.NNA_CGY_NM                       AS CASH_NNA_CGY_NM,  -- [ETL_BLOCK] from ETL Notes block APACASH
    product_information.NNA_CGY_ID           AS SCR_NNA_CGY_ID,  -- [ETL_BLOCK] from ETL Notes block PRODUCT_INFORMATION
    product_information.NNA_CGY_NM           AS SCR_NNA_CGY_NM,  -- [ETL_BLOCK] from ETL Notes block PRODUCT_INFORMATION
    a.YIELD                                  AS YLD,  -- [FALLBACK] plain pass-through (no DRD AD or ODI hint)
    a.YIELD_TO_WORST                         AS YTW,  -- [FALLBACK] plain pass-through (no DRD AD or ODI hint)
    a.YIELD_TO_WORST_CD                      AS YTW_CD,  -- [FALLBACK] plain pass-through (no DRD AD or ODI hint)
    ad.ORIG_SRC_STM_AR_ID                    AS BKR_AC_NUM,  -- [FALLBACK] plain pass-through (no DRD AD or ODI hint)
    cv.CL_VAL_CODE                           AS SIS_DLTD_EV_CD,  -- [DRD_AD] JOIN from DRD col-AD
    t.ORIG_TD                                AS DB_CARD_TXN_DT,  -- [FALLBACK] plain pass-through (no DRD AD or ODI hint)
    c.CCY_CODE                               AS DB_CARD_ORIG_CCY_CD,  -- [FALLBACK] plain pass-through (no DRD AD or ODI hint)
    c.CCY_NM                                 AS DB_CARD_ORIG_CCY,  -- [FALLBACK] plain pass-through (no DRD AD or ODI hint)
    cv.CL_VAL_CODE                           AS SDIRA_TXN_TP_CD,  -- [FALLBACK] plain pass-through (no DRD AD or ODI hint)
    cv.CL_VAL_NM                             AS SDIRA_TXN_TP,  -- [FALLBACK] plain pass-through (no DRD AD or ODI hint)
    t.TRD_NUM                                AS SDIRA_TXN_YR,  -- [FALLBACK] plain pass-through (no DRD AD or ODI hint)
    c.CCY_NM                                 AS TXN_CCY,  -- [FALLBACK] plain pass-through (no DRD AD or ODI hint)
    ad.IRA_F                                 AS BKR_IRA_F,  -- [FALLBACK] plain pass-through (no DRD AD or ODI hint)
    ad.ERISSA_F                              AS BKR_ERISA_F,  -- [FALLBACK] plain pass-through (no DRD AD or ODI hint)
    ad.ORIG_SRC_STM_CD                       AS BKR_ORIG_SRC_STM_CD,  -- [FALLBACK] plain pass-through (no DRD AD or ODI hint)
    ad.ABC_CLSS_CD                           AS BKR_ABC_CLSS_CD,  -- [FALLBACK] plain pass-through (no DRD AD or ODI hint)
    ad.ABC_CLSS_NM                           AS BKR_ABC_CLSS,  -- [FALLBACK] plain pass-through (no DRD AD or ODI hint)
    ad.AR_CGY_CD                             AS AC_CGY_CD,  -- [DRD_AD] JOIN from DRD col-AD
    ad.AR_CGY_CD                             AS BKR_AC_CGY_CD,  -- [FALLBACK] plain pass-through (no DRD AD or ODI hint)
    ad.AR_CGY                                AS AC_CGY,  -- [DRD_AD] JOIN from DRD col-AD
    ad.AR_CGY                                AS BKR_AC_CGY,  -- [FALLBACK] plain pass-through (no DRD AD or ODI hint)
    ad.BSN_LINE_AFFLT                        AS BKR_BSN_LINE_AFFLT,  -- [FALLBACK] plain pass-through (no DRD AD or ODI hint)
    ad.BSN_LINE_AFFLT_CD                     AS BKR_BSN_LINE_AFFLT_CD,  -- [FALLBACK] plain pass-through (no DRD AD or ODI hint)
    ad.TST_AR_F                              AS TST_AC_F,  -- [DRD_AD] JOIN from DRD col-AD
    ad.TST_AR_F                              AS BKR_TST_AC_F,  -- [FALLBACK] plain pass-through (no DRD AD or ODI hint)
    ad.TAX_RPT_PARTY_ID                      AS TAX_RPT_CLNT_ID,  -- [DRD_AD] JOIN from DRD col-AD
    ad.TAX_RPT_PARTY_ID                      AS BKR_TAX_RPT_CLNT_ID,  -- [FALLBACK] plain pass-through (no DRD AD or ODI hint)
    ad.TAX_AC_F                              AS TAX_AC_F,  -- [DRD_AD] JOIN from DRD col-AD
    ad.TAX_AC_F                              AS BKR_TAX_AC_F,  -- [FALLBACK] plain pass-through (no DRD AD or ODI hint)
    ad.RJ_TAX_RPT_RSPL_F                     AS BKR_RJ_TAX_RPT_RSPL_F,  -- [FALLBACK] plain pass-through (no DRD AD or ODI hint)
    ad.RJ_BSN_UNIT_CD                        AS RJ_BSN_UNIT_CD,  -- [DRD_AD] JOIN from DRD col-AD
    ad.RJ_BSN_UNIT_CD                        AS BKR_RJ_BSN_UNIT_CD,  -- [FALLBACK] plain pass-through (no DRD AD or ODI hint)
    ad.RJ_BSN_UNIT                           AS RJ_BSN_UNIT,  -- [DRD_AD] JOIN from DRD col-AD
    ad.RJ_BSN_UNIT                           AS BKR_RJ_BSN_UNIT,  -- [FALLBACK] plain pass-through (no DRD AD or ODI hint)
    ad.OWNSHP_TP_CD                          AS AC_OWNSHP_TP_CD,  -- [DRD_AD] JOIN from DRD col-AD
    ad.OWNSHP_TP_CD                          AS BKR_AC_OWNSHP_TP_CD,  -- [FALLBACK] plain pass-through (no DRD AD or ODI hint)
    ad.OWNSHP_TP                             AS AC_OWNSHP_TP,  -- [DRD_AD] JOIN from DRD col-AD
    ad.OWNSHP_TP                             AS BKR_AC_OWNSHP_TP,  -- [FALLBACK] plain pass-through (no DRD AD or ODI hint)
    ad.FIRM_AC_F                             AS BKR_FIRM_AC_F,  -- [FALLBACK] plain pass-through (no DRD AD or ODI hint)
    ad.FEE_BASE_F                            AS BKR_FEE_BASE_AC_F,  -- [FALLBACK] plain pass-through (no DRD AD or ODI hint)
    ad.BSN_LINE_AFFLT_CD                     AS BKR_RJ_TRUST_F,  -- [FALLBACK] plain pass-through (no DRD AD or ODI hint)
    fnv.FA_NUMBER                            AS OWN_PRIM_FA_NUM,  -- [FALLBACK] plain pass-through (no DRD AD or ODI hint)
    pr.CSS_PERSON_ID                         AS OWN_FA_CSS_PSN_ID,  -- [FALLBACK] plain pass-through (no DRD AD or ODI hint)
    pbsv.CURRENT_ADVISOR_FLAG                AS OWN_FA_CRN_ADV_F,  -- [FALLBACK] plain pass-through (no DRD AD or ODI hint)
    pr.DEPARTMENT_BRANCH_CODE                AS OWN_FA_DEPT_BR_CD,  -- [FALLBACK] plain pass-through (no DRD AD or ODI hint)
    padsv.DISCRETIONARY_INDICATOR            AS OWN_FA_DSCR_F,  -- [DRD_AD] JOIN from DRD col-AD
    padsv.DISCRETIONARY_STATUS               AS OWN_FA_DSCR_ST,  -- [DRD_AD] JOIN from DRD col-AD
    padsv.DISCRETIONARY_STATUS_CODE          AS OWN_FA_DSCR_ST_CD,  -- [DRD_AD] JOIN from DRD col-AD
    pr.FINRA_CRD_CLASS_CODE                  AS OWN_FA_FINRA_CRD_CLSS_CD,  -- [FALLBACK] plain pass-through (no DRD AD or ODI hint)
    pr.HR_STATUS_CODE                        AS OWN_FA_HR_ST_CD,  -- [FALLBACK] plain pass-through (no DRD AD or ODI hint)
    pr.PRODUCER_FLAG                         AS OWN_FA_PRODUCER_F,  -- [FALLBACK] plain pass-through (no DRD AD or ODI hint)
    pbsv.QUALIFIED_ADVISOR_FLAG              AS OWN_FA_QUALF_ADV_F,  -- [FALLBACK] plain pass-through (no DRD AD or ODI hint)
    eedv.ENTITY_BRANCH_CODE                  AS OWN_FA_ENT_BR_CD,  -- [FALLBACK] plain pass-through (no DRD AD or ODI hint)
    eedv.ENTITY_BUSINESS_STATUS              AS OWN_FA_ENT_BSN_ST,  -- [FALLBACK] plain pass-through (no DRD AD or ODI hint)
    eedv.ENTITY_DIVISION_CODE                AS OWN_FA_ENT_DIV_CD,  -- [FALLBACK] plain pass-through (no DRD AD or ODI hint)
    eedv.ENTITY_DIVISION_DESCRIPTION         AS OWN_FA_ENT_DIV_DSC,  -- [FALLBACK] plain pass-through (no DRD AD or ODI hint)
    eedv.ENTITY_DIVISION_NODE                AS OWN_FA_ENT_DIV_NODE,  -- [FALLBACK] plain pass-through (no DRD AD or ODI hint)
    eedv.ENTITY_MAIN_BRANCH_STATE            AS OWN_FA_ENT_MAIN_BR_STE,  -- [FALLBACK] plain pass-through (no DRD AD or ODI hint)
    eedv.ENTITY_OSJ                          AS OWN_FA_ENT_OSJ,  -- [FALLBACK] plain pass-through (no DRD AD or ODI hint)
    eerdv.ENTITY_RETAIL_BUSINESS_MODEL_CODE  AS OWN_FA_ENT_RTL_HIER_BSN_MODL_CD,  -- [FALLBACK] plain pass-through (no DRD AD or ODI hint)
    eerdv.ENTITY_RETAIL_BUSINESS_MODEL_DESCRIPTION AS OWN_FA_ENT_RTL_HIER_BSN_MODL_DSC,  -- [FALLBACK] plain pass-through (no DRD AD or ODI hint)
    eerdv.ENTITY_RETAIL_SALES_LOB_CODE       AS OWN_FA_ENT_RTL_SALE_HIER_LOB_CD,  -- [FALLBACK] plain pass-through (no DRD AD or ODI hint)
    eerdv.ENTITY_RETAIL_SALES_LOB_DESCRIPTION AS OWN_FA_ENT_RTL_SALE_HIER_LOB_DSC,  -- [FALLBACK] plain pass-through (no DRD AD or ODI hint)
    eerdv.ENTITY_RETAIL_REPORTING_UNIT_CODE  AS OWN_FA_ENT_RTL_HIER_RPT_UNIT_CD,  -- [FALLBACK] plain pass-through (no DRD AD or ODI hint)
    eerdv.ENTITY_RETAIL_REPORTING_UNIT_DESCRIPTION AS OWN_FA_ENT_RTL_HIER_RPT_UNIT_DSC,  -- [FALLBACK] plain pass-through (no DRD AD or ODI hint)
    eerdv.ENTITY_RETAIL_SALES_DIVISION_CODE  AS OWN_FA_ENT_RTL_SALE_DIV_CD,  -- [FALLBACK] plain pass-through (no DRD AD or ODI hint)
    eerdv.ENTITY_RETAIL_SALES_REGION_CODE    AS OWN_FA_ENT_RTL_SALE_HIER_RGON_CD,  -- [FALLBACK] plain pass-through (no DRD AD or ODI hint)
    eerdv.ENTITY_RETAIL_SALES_REGION_DESCRIPTION AS OWN_FA_ENT_RTL_SALE_HIER_RGON_DSC,  -- [FALLBACK] plain pass-through (no DRD AD or ODI hint)
    eerdv.ENTITY_RETAIL_TERRITORY_CODE       AS OWN_FA_ENT_RTL_HIER_TERR_CD,  -- [FALLBACK] plain pass-through (no DRD AD or ODI hint)
    eerdv.ENTITY_RETAIL_TERRITORY_DESCRIPTION AS OWN_FA_ENT_RTL_HIER_TERR_DSC,  -- [FALLBACK] plain pass-through (no DRD AD or ODI hint)
    eerdv2.ENTITY_RISK_BUSINESS_UNIT_CODE    AS OWN_FA_ENT_RSK_HIER_BSN_UNIT_CD,  -- [FALLBACK] plain pass-through (no DRD AD or ODI hint)
    eerdv2.ENTITY_RISK_BUSINESS_UNIT_DESCRIPTION AS OWN_FA_ENT_RSK_HIER_BSN_UNIT_DSC,  -- [FALLBACK] plain pass-through (no DRD AD or ODI hint)
    eedv.ENTITY_RJAS_ID_BOOLEAN              AS OWN_FA_ENT_RJAS_ID_F,  -- [FALLBACK] plain pass-through (no DRD AD or ODI hint)
    eedv.ENTITY_SUBDIVISION_CODE             AS OWN_FA_ENT_SUBDIV_CD,  -- [FALLBACK] plain pass-through (no DRD AD or ODI hint)
    eedv.ENTITY_SUBDIVISION_DESCRIPTION      AS OWN_FA_ENT_SUBDIV_DSC,  -- [FALLBACK] plain pass-through (no DRD AD or ODI hint)
    eedv.ENTITY_SUBSIDIARY                   AS OWN_FA_ENT_SUBS,  -- [FALLBACK] plain pass-through (no DRD AD or ODI hint)
    eedv.ENTITY_SUBTYPE                      AS OWN_FA_ENT_SBTP,  -- [FALLBACK] plain pass-through (no DRD AD or ODI hint)
    eedv.ENTITY_SUBTYPE_CODE                 AS OWN_FA_ENT_SBTP_CD,  -- [FALLBACK] plain pass-through (no DRD AD or ODI hint)
    eedv.ENTITY_TYPE                         AS OWN_FA_ENT_TP,  -- [FALLBACK] plain pass-through (no DRD AD or ODI hint)
    eedv.ENTITY_TYPE_CODE                    AS OWN_FA_ENT_TP_CD,  -- [FALLBACK] plain pass-through (no DRD AD or ODI hint)
    eedv.LOB_ALEX_BROWN_BOOLEAN              AS OWN_FA_ENT_LOB_AB_F,  -- [FALLBACK] plain pass-through (no DRD AD or ODI hint)
    eedv.LOB_AMS_BOOLEAN                     AS OWN_FA_ENT_LOB_AMS_F,  -- [FALLBACK] plain pass-through (no DRD AD or ODI hint)
    eedv.LOB_BUSINESS_MODEL                  AS OWN_FA_ENT_LOB_BSN_MODL,  -- [FALLBACK] plain pass-through (no DRD AD or ODI hint)
    eedv.ENTITY_BUSINESS_OPEN_DATE           AS OWN_FA_ENT_BSN_OPN_DT,  -- [FALLBACK] plain pass-through (no DRD AD or ODI hint)
    eedv.ENTITY_CODE_LONG                    AS OWN_FA_ENT_LONG_CD,  -- [FALLBACK] plain pass-through (no DRD AD or ODI hint)
    eedv.ENTITY_CODE_SHORT                   AS OWN_FA_ENT_SHRT_CD,  -- [FALLBACK] plain pass-through (no DRD AD or ODI hint)
    eedv.ENTITY_CSS_ID                       AS OWN_FA_ENT_CSS_ID,  -- [FALLBACK] plain pass-through (no DRD AD or ODI hint)
    eerdv.ENTITY_RETAIL_SALES_COMPLEX_CODE   AS OWN_FA_ENT_RTL_SALE_CPX_CD,  -- [FALLBACK] plain pass-through (no DRD AD or ODI hint)
    ipd.EQTY_SECT_LVL_4                      AS EQTY_IDY,  -- [FALLBACK] plain pass-through (no DRD AD or ODI hint)
    ipd.EQTY_SECT_LVL_4_CD                   AS EQTY_IDY_CD,  -- [FALLBACK] plain pass-through (no DRD AD or ODI hint)
    ipd.EQTY_SECT_LVL_3                      AS EQTY_IDY_GRP,  -- [FALLBACK] plain pass-through (no DRD AD or ODI hint)
    ipd.EQTY_SECT_LVL_3_CD                   AS EQTY_IDY_GRP_CD,  -- [FALLBACK] plain pass-through (no DRD AD or ODI hint)
    ipd.EQTY_SECT_LVL_2                      AS EQTY_SECT,  -- [FALLBACK] plain pass-through (no DRD AD or ODI hint)
    ipd.EQTY_SECT_LVL_2_CD                   AS EQTY_SECT_CD,  -- [FALLBACK] plain pass-through (no DRD AD or ODI hint)
    ipd.EQTY_SECT_LVL_1                      AS EQTY_SUP_SECT,  -- [FALLBACK] plain pass-through (no DRD AD or ODI hint)
    ipd.EQTY_SECT_LVL_1_CD                   AS EQTY_SUP_SECT_CD,  -- [FALLBACK] plain pass-through (no DRD AD or ODI hint)
    ipd.FIRM_MODL_LVL_2                      AS MODL_STRTG_DTL_AST_CLSS,  -- [FALLBACK] plain pass-through (no DRD AD or ODI hint)
    ipd.FIRM_MODL_LVL_2_CD                   AS MODL_STRTG_DTL_AST_CLSS_CD,  -- [FALLBACK] plain pass-through (no DRD AD or ODI hint)
    ipd.FIRM_MODL_LVL_1                      AS MODL_STRTG_SMY_AST_CLSS,  -- [FALLBACK] plain pass-through (no DRD AD or ODI hint)
    ipd.FIRM_MODL_LVL_1_CD                   AS MODL_STRTG_SMY_AST_CLSS_CD,  -- [FALLBACK] plain pass-through (no DRD AD or ODI hint)
    product_information.PD_CMPOS_DSC         AS PD_CMPOS_DSC,  -- [ETL_BLOCK] from ETL Notes block PRODUCT_INFORMATION
    product_information.PD_NM                AS PD_SHRT_NM,  -- [ETL_BLOCK] from ETL Notes block PRODUCT_INFORMATION
    product_information.PD_DSC               AS PD_DSC,  -- [ETL_BLOCK] from ETL Notes block PRODUCT_INFORMATION
    ipd.RPT_CL_LVL_1                         AS RPT_CL_LVL_1,  -- [FALLBACK] plain pass-through (no DRD AD or ODI hint)
    ipd.RPT_CL_LVL_2                         AS RPT_CL_LVL_2,  -- [FALLBACK] plain pass-through (no DRD AD or ODI hint)
    ipd.FIRM_RPT_LVL_2                       AS RPT_STRTG_DTL_AST_CLSS,  -- [FALLBACK] plain pass-through (no DRD AD or ODI hint)
    ipd.FIRM_RPT_LVL_2_CD                    AS RPT_STRTG_DTL_AST_CLSS_CD,  -- [FALLBACK] plain pass-through (no DRD AD or ODI hint)
    ipd.FIRM_RPT_LVL_1                       AS RPT_STRTG_SMY_AST_CLSS,  -- [FALLBACK] plain pass-through (no DRD AD or ODI hint)
    ipd.FIRM_RPT_LVL_1_CD                    AS RPT_STRTG_SMY_AST_CLSS_CD,  -- [FALLBACK] plain pass-through (no DRD AD or ODI hint)
    ipd.FND_FAM                              AS FND_FAM,  -- [FALLBACK] plain pass-through (no DRD AD or ODI hint)
    ipd.SHR_CLSS_TP_CD                       AS SHR_CLSS_TP_CD,  -- [FALLBACK] plain pass-through (no DRD AD or ODI hint)
    ipd.SHR_CLSS_TP_NM                       AS SHR_CLSS_TP,  -- [FALLBACK] plain pass-through (no DRD AD or ODI hint)
    ipd.IMT_CL_LVL_1                         AS IMT_CL_LVL_1,  -- [FALLBACK] plain pass-through (no DRD AD or ODI hint)
    ipd.IMT_CL_LVL_1_CD                      AS IMT_CL_LVL_1_CD,  -- [FALLBACK] plain pass-through (no DRD AD or ODI hint)
    ipd.IMT_CL_LVL_2                         AS IMT_CL_LVL_2,  -- [FALLBACK] plain pass-through (no DRD AD or ODI hint)
    ipd.IMT_CL_LVL_2_CD                      AS IMT_CL_LVL_2_CD,  -- [FALLBACK] plain pass-through (no DRD AD or ODI hint)
    ipd.IMT_CL_LVL_3                         AS IMT_CL_LVL_3,  -- [FALLBACK] plain pass-through (no DRD AD or ODI hint)
    ipd.IMT_CL_LVL_3_CD                      AS IMT_CL_LVL_3_CD,  -- [FALLBACK] plain pass-through (no DRD AD or ODI hint)
    ipd.IMT_CL_LVL_4                         AS IMT_CL_LVL_4,  -- [FALLBACK] plain pass-through (no DRD AD or ODI hint)
    ipd.IMT_CL_LVL_4_CD                      AS IMT_CL_LVL_4_CD,  -- [FALLBACK] plain pass-through (no DRD AD or ODI hint)
    ipd.IMT_CL_LVL_5                         AS IMT_CL_LVL_5,  -- [FALLBACK] plain pass-through (no DRD AD or ODI hint)
    ipd.IMT_CL_LVL_5_CD                      AS IMT_CL_LVL_5_CD,  -- [FALLBACK] plain pass-through (no DRD AD or ODI hint)
    fnv.FA_NUMBER_TYPE_CODE                  AS OWN_FA_NUM_TP_CD,  -- [DRD_AD] JOIN from DRD col-AD
    csvv.CODE_VALUE_DESCRIPTION              AS OWN_FA_NUM_TP,  -- [DRD_AD] JOIN from DRD col-AD
    apacash.ORIG_QTY                         AS BOND_ACRTN_DCN_AMT,  -- [ETL_BLOCK] from ETL Notes block APACASH
    apacash.ORIG_QTY                         AS BOND_AMRZ_PREM_AMT,  -- [ETL_BLOCK] from ETL Notes block APACASH
    apacash.ORIG_QTY                         AS RJ_TRUST_BOOK_VAL_AMT,  -- [ETL_BLOCK] from ETL Notes block APACASH
    apacash.ORIG_QTY                         AS RJ_TRUST_RLZD_TAX_GAIN_OR_LOSS_AMT,  -- [ETL_BLOCK] from ETL Notes block APACASH
    product_information.ORIG_QTY             AS BFR_REPYMT_FACE_VAL_AMT,  -- [ETL_BLOCK] from ETL Notes block PRODUCT_INFORMATION
    product_information.ORIG_QTY             AS BFR_INCM_PYMT_FACE_VAL_AMT,  -- [ETL_BLOCK] from ETL Notes block PRODUCT_INFORMATION
    product_information.ORIG_QTY             AS BASE_POS_QTY,  -- [ETL_BLOCK] from ETL Notes block PRODUCT_INFORMATION
    product_information.ORIG_QTY             AS NO_SIS_SCR_MVMT_TXN_QTY,  -- [ETL_BLOCK] from ETL Notes block PRODUCT_INFORMATION
    product_information.SCR_PRC_IN_TXN_CCY   AS NO_SIS_SCR_MVMT_TXN_PRC,  -- [ETL_BLOCK] from ETL Notes block PRODUCT_INFORMATION
    product_information.ORIG_QTY             AS REIVS_SHR_QTY,  -- [ETL_BLOCK] from ETL Notes block PRODUCT_INFORMATION
    product_information.SCR_PRC_IN_TXN_CCY   AS REIVS_PRC  -- [ETL_BLOCK] from ETL Notes block PRODUCT_INFORMATION
FROM CCAL_REPL_OWNER.TXN t
LEFT JOIN CIRD_OWNER.EXG_DIM ed ON ed.EXG_CD = t.exg_code
LEFT JOIN COMMON_OWNER.ACG_TP_DIM atd ON AP.ACG_TP_ID = atd.ACG_TP_ID
LEFT JOIN COMMON_OWNER.CASH_POS_TP_DIM cptd ON ap.CASH_POS_TP_ID = cptd.CASH_POS_TP_ID
LEFT JOIN CIRD_OWNER.CCY_DIM cd ON ap.stm_base_iso_ccy_code = cd.ccy_cd
LEFT JOIN TRANSACTIONS_OWNER.LGCY_CNCL_CMPLN_RSN_TP_DIM lccrtd ON ld.lgcy_cncl_cmpln_rsn_tp_id = t.lgcy_cncl_cmpln_rsn_tp_id
LEFT JOIN TRANSACTIONS_OWNER.LGCY_CNCL_CMPLN_SRC_TP_DIM lccstd ON ld.lgcy_cncl_cmpln_src_tp_id = t.lgcy_cncl_cmpln_src_tp_id
LEFT JOIN TRANSACTIONS_OWNER.LGCY_MKT_TP_DIM lmtd ON lmtd.lgcy_mkt_tp_id = t.lgcy_mkt_tp_id
LEFT JOIN TRANSACTIONS_OWNER.LGCY_TRD_CPCTY_TP_DIM ltctd ON t.lgcy_trd_cpcty_tp_id = ltctd.lgcy_trd_cpcty_tp_id
LEFT JOIN TRANSACTIONS_OWNER.SRC_PCS_TP_DIM sptd ON t.src_pcs_tp_id = sptd.src_pcs_tp_id
LEFT JOIN TRANSACTIONS_OWNER.SRC_ENTR_CNL_TP_DIM sectd ON t.src_entr_cnl_tp_id = sectd.src_entr_cnl_tp_id
LEFT JOIN TRANSACTIONS_OWNER.TRD_SLCT_TP_DIM tstd ON t.trd_slct_tp_id = tstd.trd_slct_tp_id
LEFT JOIN COMMON_OWNER.SRC_STM_DIM ssd ON ssd.src_stm_id = t.src_stm_id
LEFT JOIN CCAL_REPL_OWNER.SRC_STM_DIM ssd2 ON t2.src_stm_id = stm.src_stm_id
LEFT JOIN COMMON_OWNER.DATE_DIM dd ON t.td = dd.cal_dt
LEFT JOIN CCAL_REPL_OWNER.TXN_RLTNP tr ON t.txn_id = tr.src_txn_id
LEFT JOIN CCAL_REPL_OWNER.APA a ON ap.exec_id = t.txn_id
LEFT JOIN CCAL_REPL_OWNER.CL_VAL cv ON cv.cl_val_id = t.txn_tp_id
LEFT JOIN CCAL_REPL_OWNER.CCAL_CIRD_PD_MAP ccpm ON ccpm.ccal_pd_id = ap.pd_id
LEFT JOIN CCAL_REPL_OWNER.J$AVY_FACT jaf ON 1=0 /* TODO: no DRD AD ON clause; patch manually */
LEFT JOIN CCAL_REPL_OWNER.TXN t ON tr.trgt_txn_id = t2.txn_id
LEFT JOIN CCAL_REPL_OWNER.ACATS_BROKER ab ON b.broker_id = t.orig_src_stm_code
LEFT JOIN CCAL_REPL_OWNER.IMPCT_ACTION_LKU ial ON t.src_actn_code = impct_action_lku.action_code
LEFT JOIN SSDS_DAL_OWNER.FA_NUMBER_V fnv ON 1=0 /* TODO: no DRD AD ON clause; patch manually */
LEFT JOIN CCAL_REPL_OWNER.FIP f ON f.apa_id = ap.apa_id
LEFT JOIN CCAL_REPL_OWNER.TXN_SRC_TAX_CODE_LKUP tstcl ON 1=0 /* TODO: no DRD AD ON clause; patch manually */
LEFT JOIN CCSI_OWNER.AR_DIM ad ON 1=0 /* TODO: no DRD AD ON clause; patch manually */
LEFT JOIN REFERENCE_REPL_OWNER.CCY c ON 1=0 /* TODO: no DRD AD ON clause; patch manually */
LEFT JOIN SSDS_DAL_OWNER.PERSON_RV pr ON 1=0 /* TODO: no DRD AD ON clause; patch manually */
LEFT JOIN SSDS_DAL_OWNER.PERSON_BROKERAGE_SUBDIMENSION_V pbsv ON 1=0 /* TODO: no DRD AD ON clause; patch manually */
LEFT JOIN SSDS_DAL_OWNER.PERSON_AMS_DISCRETIONARY_STATUS_V padsv ON brk_own_resp_ams_disc.EMPLOYEE_ID = fa_number_v1.responsible_party_employee_id
LEFT JOIN SSDS_DAL_OWNER.ENTERPRISE_ENTITY_DIM_V eedv ON 1=0 /* TODO: no DRD AD ON clause; patch manually */
LEFT JOIN SSDS_DAL_OWNER.ENTERPRISE_ENTITY_RETAIL_DIMENSION_V eerdv ON 1=0 /* TODO: no DRD AD ON clause; patch manually */
LEFT JOIN SSDS_DAL_OWNER.ENTERPRISE_ENTITY_RISK_DIMENSION_V eerdv2 ON 1=0 /* TODO: no DRD AD ON clause; patch manually */
LEFT JOIN CIRD_OWNER.IMT_PD_DIM ipd ON 1=0 /* TODO: no DRD AD ON clause; patch manually */
LEFT JOIN SSDS_DAL_OWNER.CODE_SET_VALUE_V csvv ON CODE_SET_VALUE_V.CODE_VALUE_ID = FA_NUMBER_V.FA_NUMBER_TYPE_CODE_ID;
