-- Generated by drd_first_emitter v1
-- Target: IKOROSTELEV.AVY_FACT_SIDE
-- Columns: 369  Joins: 176  CTEs: 2
-- Provenance: DRD_EXISTS_DERIVED_FLAG=1, DRD_INLINE_FALLBACK=2, DRD_PHYSICAL=119, DRD_PHYSICAL_CASE=11, DRD_PHYSICAL_FALLBACK=1, ETL_DEFAULT=7, NULL_FALLBACK=2, NULL_UNIMPLEMENTED_PROSE=2, ODI=223, ODI_T_ALIAS=1

-- ETL Notes block(s) referenced by some DRD col-AD cells; the
-- emitter projects from each column's physical DRD source_attribute
-- and annotates the projection with the referenced block name so
-- the operator can apply the prose filter rule (e.g. APASEC/APACSH
-- subset selection) by hand.
-- ETL_BLOCK[PRODUCT_INFORMATION]:
--   (Security source CUSIP, Security Product Id, Security CIRD Product Id, Security Option Symbol, Symbol, ISIN, Product Composite Description, Product Short Name, Product Description)
--   If there is atleast 1 APASEC, consider above fields from that APASEC
--   If there is an iAPASEC but no APASEC, consider above fields from iAPASEC
--
--   Source Effective Date:
--   If there is only iAPASEC or only iAPACSH, grab source effective date from the iAPASEC/iAPACSH
--   If there is atleast 1 APASEC or APACSH, grab source effective date from that APASEC/APACSH
--   Updates from below user names should be skipped by main process (Product Backlog Item 1937973: Skip Activity updates from additional usernames)
--   CCAL_PKG_TXN_RECON_REPL (EOD CCAL Recon Replay)
--   PERF_MAP_CF_MASTER_STG_PROC (Cash Flow Generation)
--   CCAL_PKG_TXN_POS_RECON_STS_UPD (EOD CCAL Recon)
--   CCAL_PERF_PKG_CF_MSTR_LOAD_RJTRST  (Cash Flow Generation)
--   CCAL_PKG_TXN_POS_RECON (EOD CCAL Recon)
--   CCAL_PKG_TXN_RECON_RJTRUST_1 (EOD CCAL Recon)
--   PERF_PKG_CF_MSTR_LOAD (Cash Flow Generation)
--   CCAL_PKG_TXN_RECON_SHADOW_1 (EOD CCAL Recon)
--   CCAL_PKG_LOAD_TXN_AY_CL_1 (Activity Reclassification)
--   CCAL_PKG_LOAD_TXN_AY_CL_2 (Activity Reclassification)
--   CCAL_PKG_LOAD_TXN_AY_CL_3 (Activity Reclassification)
--   CCAL_PKG_LOAD_TXN_AY_CL_4 (Activity Reclassification)
--   CCAL_PKG_LOAD_TXN_AY_CL_5 (Activity Reclassification)
--   CCAL_PKG_LOAD_TXN_AY_CL_6 (Activity Reclassification)
--   CCAL_PKG_LOAD_TXN_AY_CL_7 (Activity Reclassification)
--   CCAL_PKG_LOAD_TXN_AY_CL_8 (Activity Reclassification)
--   CCAL_PKG_LOAD_TXN_AY_CL_9 (Activity Reclassification)
--   CCAL_PKG_LOAD_TXN_AY_CL_10 (Activity Reclassification)
--   Update Trade Cancelled Flag on original trade when cancellation arrives (Product Backlog Item 2030710: Add columns available in DWH and missing in Lighthouse for Trade Activity)
-- ETL_BLOCK[APACASH]:
--   Check for regexp_like(cv.cl_val_code,'^APACSH[0-7][0-9]')
--   For a Transaction, 
--   If only one record exists then consider that record.
--   If 2 records exists ( 
--        If (one record is 'APACSH04' & other is 'APACSH11') 
--             then consider skip 'APACSH04' record and load 'APACSH11' but use the values to
--             (1) calculate aggregated value from APA.TXN_AMT fields from 'APACSH04' and 'APACSH11' and store it in Cash Transaction Amount and Cash System base currency amount
--             (2) populate sales charge attributes from 'APACSH04' for 5 attributes (Sales Charge Rate Multiplier Number, Sales Charge Rate, Sales Charge Rate Type Code, Sales Charge Rate Type Id, Sales Charge Rate Type Name)
--        else Drop those 2 records exception entire transaction
--   )
--
--   APASEC :
--   Check for cl_val_Code like '^APASEC[0-7][0-9]' THEN consider as 'Security' record.
--
--   iAPASEC/iAPACSH:
--   Refer to below section for further filter criteria on iAPASEC/iAPACSH. Applicable to both iAPACSH and iAPASEC.
TRUNCATE TABLE IKOROSTELEV.AVY_FACT_SIDE;
INSERT /*+ APPEND PARALLEL(8) */ INTO IKOROSTELEV.AVY_FACT_SIDE (
    EXG_DIM_ID,
    AR_DIM_ID,
    OFST_AR_DIM_ID,
    ACG_TP_DIM_ID,
    CASH_POS_TP_DIM_ID,
    SBC_CCY_DIM_ID,
    SEC_PD_DIM_ID,
    CASH_PD_DIM_ID,
    LGCY_CNCL_CMPLN_RSN_DIM_ID,
    LGCY_CNCL_CMPLN_SRC_DIM_ID,
    LGCY_MKT_TP_DIM_ID,
    LGCY_TRD_CPCTY_TP_DIM_ID,
    SRC_PCS_TP_DIM_ID,
    SRC_ENTR_CNL_TP_DIM_ID,
    TRD_SLCT_TP_DIM_ID,
    TXN_SRC_STM_DIM_ID,
    REL_TXN_SRC_STM_DIM_ID,
    BKR_AR_DIM_ID,
    TD_DIM_ID,
    TD,
    SD_DIM_ID,
    SD,
    BKG_DT,
    ORIG_BKG_DT,
    EXEC_DTM,
    TXN_ID,
    REL_TXN_ID,
    TRD_NUM,
    ORIG_TRD_NUM,
    TXN_SRC_KEY,
    SEC_APA_ID,
    CSH_APA_ID,
    SEC_PRC_IN_TXN_CCY,
    SEC_TXN_AMT,
    CASH_TXN_AMT,
    SEC_ORIG_QTY,
    SEC_SRC_PRC_IN_SBC,
    SALE_CHRG_RATE_PCT,
    SALE_CHRG_RATE_TP_ID,
    SALE_CHRG_RATE_TP_CD,
    SEC_SBC_AMT,
    CASH_SBC_AMT,
    SBC_CCY_CALC_DT,
    SBC_EXG_RATE,
    CASH_DB_CR_CD,
    SEC_DB_CR_CD,
    SEC_SRC_SEQ_NUM,
    SEC_APA_EXT_QUALFR,
    SEC_DSC_TRAILER_1,
    SEC_ALT_DSC_TRAILER_2,
    BUY_SELL_IND,
    CF_GEN_F,
    TXN_CL_F,
    OPT_CLSS_CD,
    SEC_SRC_CUSIP,
    CASH_DSC_TRAILER_1,
    CASH_ALT_DSC_TRAILER_2,
    CASH_SRC_SEQ_NUM,
    TXN_TP_ID,
    TXN_TP_CD,
    TXN_TP_NM,
    TXN_TP_DSC,
    TXN_SBTP_ID,
    TXN_SUB_TP_NM,
    TXN_SUB_TP_CD,
    TXN_SUB_TP_DSC,
    EXEC_TP_ID,
    EXEC_TP_CD,
    EXEC_TP_NM,
    EXEC_TP_DSC,
    EXEC_SBTP_CD,
    EXEC_SBTP_NM,
    EXEC_SBTP_DSC,
    EXEC_SBTP_ID,
    SEC_APA_TP_ID,
    SCR_APA_TP_CD,
    SCR_APA_TP_NM,
    SCR_APA_TP_DSC,
    CSH_APA_TP_ID,
    CASH_APA_TP_CD,
    CASH_APA_TP_NM,
    CASH_APA_TP_DSC,
    SCR_AVY_CGY,
    SCR_AVY_TP,
    SEC_AVY_CL_ID,
    CASH_AVY_CGY,
    CASH_AVY_TP,
    CSH_AVY_CL_ID,
    CRT_DTM,
    CRT_USR_NM,
    SESS_NO,
    SRC_ENTR_DTM,
    AR_ID,
    SEC_PD_ID,
    CASH_PD_ID,
    BKR_AR_ID,
    OFST_AR_ID,
    BR_CD,
    FA_NUM,
    SRC_CRT_USRNM,
    ORIG_TD,
    SRC_PCS_TP_CD,
    SRC_PCS_TP_NM,
    CCY_DIM_ID,
    CCY_CD,
    SBC_CCY_CD,
    SRC_EFF_DT,
    DOL_IND_ID,
    DOL_IND_CD,
    DOL_IND_NM,
    OMS_ORDR_KEY,
    EXG_CD,
    EXG_NM,
    ACG_TP_CD,
    ACG_TP_NM,
    CASH_POS_TP_CD,
    CASH_POS_TP_NM,
    LGCY_CNCL_CMPLN_RSN_TP_CD,
    LGCY_CNCL_CMPLN_RSN_TP_NM,
    LGCY_CNCL_CMPLN_SRC_TP_CD,
    LGCY_CNCL_CMPLN_SRC_TP_NM,
    LGCY_MKT_TP_CD,
    LGCY_MKT_TP_NM,
    LGCY_TRD_CPCTY_TP_CD,
    LGCY_TRD_CPCTY_TP_NM,
    SRC_ENTR_CNL_TP_CD,
    SRC_ENTR_CNL_TP_NM,
    TRD_SLCT_TP_CD,
    TRD_SLCT_TP_NM,
    SALE_CHRG_RATE_TP_NM,
    CASH_DB_CR_NM,
    SEC_DB_CR_NM,
    SRC_STM_CD,
    BATCH_DT,
    CASH_CIRD_PD_ID,
    SEC_CIRD_PD_ID,
    ACTV_F,
    SRC_TXN_CODE,
    OMS_EXEC_TP_ID,
    OMS_EXEC_TP_CD,
    OMS_EXEC_TP_NM,
    OMS_EXEC_TP_DSC,
    CLNT_FRIENDLY_DSC,
    ORIG_SRC_STM_ID,
    ORIG_SRC_STM_CD,
    ACG_TP_ID,
    CASH_APA_EXT_QUALFR,
    CASH_POS_TP_ID,
    SALE_CHRG_RATE_MULTI_NUM,
    AR_ORIG_SRC_STM_CD,
    MF_AC_NUM,
    OFST_ORIG_SRC_STM_AR_ID,
    OFST_AR_ORIG_SRC_STM_CD,
    OFST_AR_SETL_TP_CD,
    OFST_AR_SETL_TP_DSC,
    AR_SETL_TP_CD,
    AR_SETL_TP_DSC,
    ORIG_SRC_STM_AR_ID,
    CASH_SIMP_DSPL_AVY_CGY,
    CASH_SIMP_DSPL_AVY_TP,
    SCR_SIMP_DSPL_AVY_CGY,
    SCR_SIMP_DSPL_AVY_TP,
    SHDW_TXN_TP_CD,
    IMP_SRC_ACTN_CD,
    SIS_DLTD_EV_ID,
    SIS_USR_ID,
    SIS_AC_CL_CD,
    SRC_CNCL_RSN_ID,
    SRC_TXN_SEQ_NUM,
    DVDN_RCRD_DT,
    OWN_IMP_FA_NUM,
    OWN_FA_NUM,
    ACAT_CNTRA_FIRM_CLRG_NUM,
    MM_ALT_ID,
    SRC_STM_ID,
    SRC_CNCL_X_RVSN_CD,
    SRC_OPT_CLSS_CD,
    TXN_RCNCL_REPL_CNT,
    TXN_RCNCL_ST_ID,
    LGCY_CNCL_CMPLN_RSN_TP_ID,
    LGCY_CNCL_CMPLN_SRC_TP_ID,
    LGCY_MKT_TP_ID,
    LGCY_TRD_CPCTY_TP_ID,
    REL_TXN_SRC_STM_ID,
    SRC_ENTR_CNL_TP_ID,
    SRC_PCS_TP_ID,
    TRD_SLCT_TP_ID,
    LAST_UDT_USR_NM,
    LAST_UDT_DTM,
    REL_TXN_RLTNP_TP_ID,
    ACAT_CNTRA_FIRM_NM,
    ACAT_CNTRA_FIRM_SHRT_NM,
    ACAT_CNTRA_FIRM_CLRG_ID_TP_CD,
    SIS_DLTD_EV_NM,
    SRC_CNCL_RSN_CD,
    SRC_CNCL_RSN_NM,
    TXN_RCNCL_ST_CD,
    TXN_RCNCL_ST_NM,
    REL_TXN_RLTNP_TP_CD,
    REL_TXN_RLTNP_TP_NM,
    SRC_STM_NM,
    REL_TXN_SRC_STM_CD,
    SHDW_TXN_TP_NM,
    IMP_SRC_ACTN_NM,
    OWN_FA_NUM_ENT_CD,
    FA_OWN_EMPE_ID,
    OWN_FA_NUM_ENT_ENTP_ID,
    AGRT_ORIG_FEES,
    AGRT_STMT_FEES,
    DRVD_TRD_CPCTY_CD,
    DRVD_TRD_CPCTY_NM,
    DRVD_TRD_CPCTY_ID,
    SCR_OPT_SYMB,
    ADL_TRD_INSR,
    TRD_FCTR_RATE,
    MRKUP_RATE,
    STD_CMSN_AMT,
    ACT_CMSN_AMT,
    TRD_PCS_FEE_AMT,
    SEC_FEE_AMT,
    ACR_INT_AMT,
    CNCSN_AMT,
    CDSC_AMT,
    OTHR_FEE_AMT,
    TRD_CNCLD_F,
    SYMB,
    ISIN,
    TXN_SRC_TAX_CD,
    TXN_SRC_TAX_CD_DSC,
    TM_PRC_DISCRETION_F,
    CASH_NNA_CGY_ID,
    CASH_NNA_CGY_NM,
    SCR_NNA_CGY_ID,
    SCR_NNA_CGY_NM,
    YLD,
    YTW,
    YTW_CD,
    BKR_AC_NUM,
    SIS_DLTD_EV_CD,
    DB_CARD_TXN_DT,
    DB_CARD_ORIG_CCY_CD,
    DB_CARD_ORIG_CCY,
    SDIRA_TXN_TP_CD,
    SDIRA_TXN_TP,
    SDIRA_TXN_YR,
    TXN_CCY,
    BKR_IRA_F,
    BKR_ERISA_F,
    BKR_ORIG_SRC_STM_CD,
    BKR_ABC_CLSS_CD,
    BKR_ABC_CLSS,
    AC_CGY_CD,
    BKR_AC_CGY_CD,
    AC_CGY,
    BKR_AC_CGY,
    BKR_BSN_LINE_AFFLT,
    BKR_BSN_LINE_AFFLT_CD,
    TST_AC_F,
    BKR_TST_AC_F,
    TAX_RPT_CLNT_ID,
    BKR_TAX_RPT_CLNT_ID,
    TAX_AC_F,
    BKR_TAX_AC_F,
    BKR_RJ_TAX_RPT_RSPL_F,
    RJ_BSN_UNIT_CD,
    BKR_RJ_BSN_UNIT_CD,
    RJ_BSN_UNIT,
    BKR_RJ_BSN_UNIT,
    AC_OWNSHP_TP_CD,
    BKR_AC_OWNSHP_TP_CD,
    AC_OWNSHP_TP,
    BKR_AC_OWNSHP_TP,
    BKR_FIRM_AC_F,
    BKR_FEE_BASE_AC_F,
    BKR_RJ_TRUST_F,
    OWN_PRIM_FA_NUM,
    OWN_FA_CSS_PSN_ID,
    OWN_FA_CRN_ADV_F,
    OWN_FA_DEPT_BR_CD,
    OWN_FA_DSCR_F,
    OWN_FA_DSCR_ST,
    OWN_FA_DSCR_ST_CD,
    OWN_FA_FINRA_CRD_CLSS_CD,
    OWN_FA_HR_ST_CD,
    OWN_FA_PRODUCER_F,
    OWN_FA_QUALF_ADV_F,
    OWN_FA_ENT_BR_CD,
    OWN_FA_ENT_BSN_ST,
    OWN_FA_ENT_DIV_CD,
    OWN_FA_ENT_DIV_DSC,
    OWN_FA_ENT_DIV_NODE,
    OWN_FA_ENT_MAIN_BR_STE,
    OWN_FA_ENT_OSJ,
    OWN_FA_ENT_RTL_HIER_BSN_MODL_CD,
    OWN_FA_ENT_RTL_HIER_BSN_MODL_DSC,
    OWN_FA_ENT_RTL_SALE_HIER_LOB_CD,
    OWN_FA_ENT_RTL_SALE_HIER_LOB_DSC,
    OWN_FA_ENT_RTL_HIER_RPT_UNIT_CD,
    OWN_FA_ENT_RTL_HIER_RPT_UNIT_DSC,
    OWN_FA_ENT_RTL_SALE_DIV_CD,
    OWN_FA_ENT_RTL_SALE_HIER_RGON_CD,
    OWN_FA_ENT_RTL_SALE_HIER_RGON_DSC,
    OWN_FA_ENT_RTL_HIER_TERR_CD,
    OWN_FA_ENT_RTL_HIER_TERR_DSC,
    OWN_FA_ENT_RSK_HIER_BSN_UNIT_CD,
    OWN_FA_ENT_RSK_HIER_BSN_UNIT_DSC,
    OWN_FA_ENT_RJAS_ID_F,
    OWN_FA_ENT_SUBDIV_CD,
    OWN_FA_ENT_SUBDIV_DSC,
    OWN_FA_ENT_SUBS,
    OWN_FA_ENT_SBTP,
    OWN_FA_ENT_SBTP_CD,
    OWN_FA_ENT_TP,
    OWN_FA_ENT_TP_CD,
    OWN_FA_ENT_LOB_AB_F,
    OWN_FA_ENT_LOB_AMS_F,
    OWN_FA_ENT_LOB_BSN_MODL,
    OWN_FA_ENT_BSN_OPN_DT,
    OWN_FA_ENT_LONG_CD,
    OWN_FA_ENT_SHRT_CD,
    OWN_FA_ENT_CSS_ID,
    OWN_FA_ENT_RTL_SALE_CPX_CD,
    EQTY_IDY,
    EQTY_IDY_CD,
    EQTY_IDY_GRP,
    EQTY_IDY_GRP_CD,
    EQTY_SECT,
    EQTY_SECT_CD,
    EQTY_SUP_SECT,
    EQTY_SUP_SECT_CD,
    MODL_STRTG_DTL_AST_CLSS,
    MODL_STRTG_DTL_AST_CLSS_CD,
    MODL_STRTG_SMY_AST_CLSS,
    MODL_STRTG_SMY_AST_CLSS_CD,
    PD_CMPOS_DSC,
    PD_SHRT_NM,
    PD_DSC,
    RPT_CL_LVL_1,
    RPT_CL_LVL_2,
    RPT_STRTG_DTL_AST_CLSS,
    RPT_STRTG_DTL_AST_CLSS_CD,
    RPT_STRTG_SMY_AST_CLSS,
    RPT_STRTG_SMY_AST_CLSS_CD,
    FND_FAM,
    SHR_CLSS_TP_CD,
    SHR_CLSS_TP,
    IMT_CL_LVL_1,
    IMT_CL_LVL_1_CD,
    IMT_CL_LVL_2,
    IMT_CL_LVL_2_CD,
    IMT_CL_LVL_3,
    IMT_CL_LVL_3_CD,
    IMT_CL_LVL_4,
    IMT_CL_LVL_4_CD,
    IMT_CL_LVL_5,
    IMT_CL_LVL_5_CD,
    OWN_FA_NUM_TP_CD,
    OWN_FA_NUM_TP,
    BOND_ACRTN_DCN_AMT,
    BOND_AMRZ_PREM_AMT,
    RJ_TRUST_BOOK_VAL_AMT,
    RJ_TRUST_RLZD_TAX_GAIN_OR_LOSS_AMT,
    BFR_REPYMT_FACE_VAL_AMT,
    BFR_INCM_PYMT_FACE_VAL_AMT,
    BASE_POS_QTY,
    NO_SIS_SCR_MVMT_TXN_QTY,
    NO_SIS_SCR_MVMT_TXN_PRC,
    REIVS_SHR_QTY,
    REIVS_PRC
)
SELECT /*+ PARALLEL(8) */
    exg_dim.EXG_DIM_ID                       AS EXG_DIM_ID,  -- [DRD_PHYSICAL] DRD source CIRD_OWNER.EXG_DIM.EXG_DIM_ID
    ar_dim.AR_DIM_ID                         AS AR_DIM_ID,  -- [DRD_PHYSICAL] DRD source CCSI_OWNER.AR_DIM.AR_DIM_ID /* see ETL block PRODUCT_INFORMATION in header */
    ofst_ar_dim.AR_DIM_ID                    AS OFST_AR_DIM_ID,  -- [DRD_PHYSICAL] DRD source CCSI_OWNER.AR_DIM.AR_DIM_ID /* see ETL block PRODUCT_INFORMATION in header */
    acg_tp_dim.ACG_TP_DIM_ID                 AS ACG_TP_DIM_ID,  -- [DRD_PHYSICAL] DRD source COMMON_OWNER.ACG_TP_DIM.ACG_TP_DIM_ID
    cash_pos_tp_dim.CASH_POS_TP_DIM_ID       AS CASH_POS_TP_DIM_ID,  -- [DRD_PHYSICAL] DRD source COMMON_OWNER.CASH_POS_TP_DIM.CASH_POS_TP_DIM_ID
    sec_ccy_dim.CCY_DIM_ID                   AS SBC_CCY_DIM_ID,  -- [DRD_PHYSICAL] DRD source CIRD_OWNER.CCY_DIM.CCY_DIM_ID
    sec_imt_pd_dim.IMT_PD_DIM_ID             AS SEC_PD_DIM_ID,  -- [DRD_PHYSICAL] DRD source CIRD_OWNER.IMT_PD_DIM.IMT_PD_DIM_ID /* see ETL block PRODUCT_INFORMATION in header */
    sec_imt_pd_dim.IMT_PD_DIM_ID             AS CASH_PD_DIM_ID,  -- [DRD_PHYSICAL] DRD source CIRD_OWNER.IMT_PD_DIM.IMT_PD_DIM_ID /* see ETL block APACASH in header */
    lccrtd.LGCY_CNCL_CMPLN_RSN_TP_DIM_ID     AS LGCY_CNCL_CMPLN_RSN_DIM_ID,  -- [DRD_PHYSICAL] DRD source TRANSACTIONS_OWNER.LGCY_CNCL_CMPLN_RSN_TP_DIM.LGCY_CNCL_CMPLN_RSN_TP_DIM_ID
    lccstd.LGCY_CNCL_CMPLN_SRC_TP_DIM_ID     AS LGCY_CNCL_CMPLN_SRC_DIM_ID,  -- [DRD_PHYSICAL] DRD source TRANSACTIONS_OWNER.LGCY_CNCL_CMPLN_SRC_TP_DIM.LGCY_CNCL_CMPLN_SRC_TP_DIM_ID
    lmtd.LGCY_MKT_TP_DIM_ID                  AS LGCY_MKT_TP_DIM_ID,  -- [DRD_PHYSICAL] DRD source TRANSACTIONS_OWNER.LGCY_MKT_TP_DIM.LGCY_MKT_TP_DIM_ID
    ltctd2.LGCY_TRD_CPCTY_TP_DIM_ID          AS LGCY_TRD_CPCTY_TP_DIM_ID,  -- [DRD_PHYSICAL] DRD source TRANSACTIONS_OWNER.LGCY_TRD_CPCTY_TP_DIM.LGCY_TRD_CPCTY_TP_DIM_ID
    sptd.SRC_PCS_TP_DIM_ID                   AS SRC_PCS_TP_DIM_ID,  -- [DRD_PHYSICAL] DRD source TRANSACTIONS_OWNER.SRC_PCS_TP_DIM.SRC_PCS_TP_DIM_ID
    sectd.SRC_ENTR_CNL_TP_DIM_ID             AS SRC_ENTR_CNL_TP_DIM_ID,  -- [DRD_PHYSICAL] DRD source TRANSACTIONS_OWNER.SRC_ENTR_CNL_TP_DIM.SRC_ENTR_CNL_TP_DIM_ID
    tstd.TRD_SLCT_TP_DIM_ID                  AS TRD_SLCT_TP_DIM_ID,  -- [DRD_PHYSICAL] DRD source TRANSACTIONS_OWNER.TRD_SLCT_TP_DIM.TRD_SLCT_TP_DIM_ID
    src_stm_dim.SRC_STM_DIM_ID               AS TXN_SRC_STM_DIM_ID,  -- [DRD_PHYSICAL] DRD source COMMON_OWNER.SRC_STM_DIM.SRC_STM_DIM_ID
    src_stm_dim.SRC_STM_DIM_ID               AS REL_TXN_SRC_STM_DIM_ID,  -- [DRD_PHYSICAL] DRD source COMMON_OWNER.SRC_STM_DIM.SRC_STM_DIM_ID
    bkr_ar_dim.AR_DIM_ID                     AS BKR_AR_DIM_ID,  -- [DRD_PHYSICAL] DRD source CCSI_OWNER.AR_DIM.AR_DIM_ID /* see ETL block PRODUCT_INFORMATION in header */
    td_date_dim.DT_DIM_ID                    AS TD_DIM_ID,  -- [DRD_PHYSICAL] DRD source COMMON_OWNER.DATE_DIM.DT_DIM_ID
    t.TD                                     AS TD,  -- [ODI] ODI staging chain -> CCAL_REPL_OWNER.TXN.TD
    td_date_dim.DT_DIM_ID                    AS SD_DIM_ID,  -- [DRD_PHYSICAL] DRD source COMMON_OWNER.DATE_DIM.DT_DIM_ID
    t.SD                                     AS SD,  -- [ODI] ODI staging chain -> CCAL_REPL_OWNER.TXN.SD
    t.BKG_DT                                 AS BKG_DT,  -- [ODI] ODI staging chain -> CCAL_REPL_OWNER.TXN.BKG_DT
    t.ORIG_BKG_DT                            AS ORIG_BKG_DT,  -- [ODI] ODI staging chain -> CCAL_REPL_OWNER.TXN.ORIG_BKG_DT
    t.EXEC_DTM                               AS EXEC_DTM,  -- [ODI] ODI staging chain -> CCAL_REPL_OWNER.TXN.EXEC_DTM
    t.TXN_ID                                 AS TXN_ID,  -- [ODI] ODI staging chain -> CCAL_REPL_OWNER.TXN.TXN_ID
    txn_rltnp.TRGT_TXN_ID                    AS REL_TXN_ID,  -- [ODI] ODI staging chain -> CCAL_REPL_OWNER.TXN_RLTNP.TRGT_TXN_ID
    t.TRD_NUM                                AS TRD_NUM,  -- [ODI] ODI staging chain -> CCAL_REPL_OWNER.TXN.TRD_NUM
    t.ORIG_TRD_NUM                           AS ORIG_TRD_NUM,  -- [ODI] ODI staging chain -> CCAL_REPL_OWNER.TXN.ORIG_TRD_NUM
    t.TXN_SRC_KEY                            AS TXN_SRC_KEY,  -- [ODI] ODI staging chain -> CCAL_REPL_OWNER.TXN.TXN_SRC_KEY
    apa.APA_ID                               AS SEC_APA_ID,  -- [ODI] ODI staging chain -> CCAL_REPL_OWNER.APA.APA_ID /* see ETL block PRODUCT_INFORMATION in header */
    apa.APA_ID                               AS CSH_APA_ID,  -- [ODI] ODI staging chain -> CCAL_REPL_OWNER.APA.APA_ID /* see ETL block APACASH in header */
    apa.SCR_PRC_IN_TXN_CCY                   AS SEC_PRC_IN_TXN_CCY,  -- [ODI] ODI staging chain -> CCAL_REPL_OWNER.APA.SCR_PRC_IN_TXN_CCY /* see ETL block PRODUCT_INFORMATION in header */
    apa.TXN_AMT                              AS SEC_TXN_AMT,  -- [ODI] ODI staging chain -> CCAL_REPL_OWNER.APA.TXN_AMT /* see ETL block PRODUCT_INFORMATION in header */
    apa.TXN_AMT                              AS CASH_TXN_AMT,  -- [ODI] ODI staging chain -> CCAL_REPL_OWNER.APA.TXN_AMT /* see ETL block APACASH in header */
    apa.ORIG_QTY                             AS SEC_ORIG_QTY,  -- [ODI] ODI staging chain -> CCAL_REPL_OWNER.APA.ORIG_QTY /* see ETL block PRODUCT_INFORMATION in header */
    apa.SCR_PRC_IN_SBC                       AS SEC_SRC_PRC_IN_SBC,  -- [ODI] ODI staging chain -> CCAL_REPL_OWNER.APA.SCR_PRC_IN_SBC /* see ETL block PRODUCT_INFORMATION in header */
    apa.SALE_CHRG_RATE                       AS SALE_CHRG_RATE_PCT,  -- [DRD_PHYSICAL] DRD source CCAL_REPL_OWNER.APA.SALE_CHRG_RATE /* see ETL block APACASH in header */
    apa.SALE_CHRG_RATE_TP_ID                 AS SALE_CHRG_RATE_TP_ID,  -- [ODI] ODI staging chain -> CCAL_REPL_OWNER.APA.SALE_CHRG_RATE_TP_ID /* see ETL block APACASH in header */
    sale_charge_rate_type.CL_VAL_CODE        AS SALE_CHRG_RATE_TP_CD,  -- [ODI] ODI staging chain -> CCAL_REPL_OWNER.CL_VAL.CL_VAL_CODE /* see ETL block APACASH in header */
    apa.STM_BASE_CCY_AMT                     AS SEC_SBC_AMT,  -- [ODI] ODI staging chain -> CCAL_REPL_OWNER.APA.STM_BASE_CCY_AMT /* see ETL block PRODUCT_INFORMATION in header */
    apa.STM_BASE_CCY_AMT                     AS CASH_SBC_AMT,  -- [ODI] ODI staging chain -> CCAL_REPL_OWNER.APA.STM_BASE_CCY_AMT /* see ETL block APACASH in header */
    apa.STM_BASE_CCY_CLC_DTM                 AS SBC_CCY_CALC_DT,  -- [ODI] ODI staging chain -> CCAL_REPL_OWNER.APA.STM_BASE_CCY_CLC_DTM
    apa.STM_BASE_CCY_EXG_RATE                AS SBC_EXG_RATE,  -- [ODI] ODI staging chain -> CCAL_REPL_OWNER.APA.STM_BASE_CCY_EXG_RATE
    debit_credit_types.CL_VAL_CODE           AS CASH_DB_CR_CD,  -- [ODI] ODI staging chain -> CCAL_REPL_OWNER.CL_VAL.CL_VAL_CODE /* see ETL block APACASH in header */
    debit_credit_types.CL_VAL_CODE           AS SEC_DB_CR_CD,  -- [ODI] ODI staging chain -> CCAL_REPL_OWNER.CL_VAL.CL_VAL_CODE /* see ETL block PRODUCT_INFORMATION in header */
    apa.SRC_SEQ_NUM                          AS SEC_SRC_SEQ_NUM,  -- [ODI] ODI staging chain -> CCAL_REPL_OWNER.APA.SRC_SEQ_NUM /* see ETL block PRODUCT_INFORMATION in header */
    apa.APA_EXT_QUALFR                       AS SEC_APA_EXT_QUALFR,  -- [ODI] ODI staging chain -> CCAL_REPL_OWNER.APA.APA_EXT_QUALFR /* see ETL block PRODUCT_INFORMATION in header */
    apa.APA_DSC                              AS SEC_DSC_TRAILER_1,  -- [ODI] ODI staging chain -> CCAL_REPL_OWNER.APA.APA_DSC /* see ETL block PRODUCT_INFORMATION in header */
    apa.ALT_DSC                              AS SEC_ALT_DSC_TRAILER_2,  -- [ODI] ODI staging chain -> CCAL_REPL_OWNER.APA.ALT_DSC /* see ETL block PRODUCT_INFORMATION in header */
    t.BUY_SELL_IND                           AS BUY_SELL_IND,  -- [ODI] ODI staging chain -> CCAL_REPL_OWNER.TXN.BUY_SELL_IND
    t.CF_GEN_F                               AS CF_GEN_F,  -- [ODI] ODI staging chain -> CCAL_REPL_OWNER.TXN.CF_GEN_F
    t.TXN_CL_F                               AS TXN_CL_F,  -- [ODI] ODI staging chain -> CCAL_REPL_OWNER.TXN.TXN_CL_F
    t.OPTS_CLSS_CODE                         AS OPT_CLSS_CD,  -- [ODI] ODI staging chain -> CCAL_REPL_OWNER.TXN.OPTS_CLSS_CODE
    apa.SRC_PD_ID                            AS SEC_SRC_CUSIP,  -- [ODI] ODI staging chain -> CCAL_REPL_OWNER.APA.SRC_PD_ID /* see ETL block PRODUCT_INFORMATION in header */
    apa.APA_DSC                              AS CASH_DSC_TRAILER_1,  -- [ODI] ODI staging chain -> CCAL_REPL_OWNER.APA.APA_DSC /* see ETL block APACASH in header */
    apa.ALT_DSC                              AS CASH_ALT_DSC_TRAILER_2,  -- [ODI] ODI staging chain -> CCAL_REPL_OWNER.APA.ALT_DSC /* see ETL block APACASH in header */
    apa.SRC_SEQ_NUM                          AS CASH_SRC_SEQ_NUM,  -- [ODI] ODI staging chain -> CCAL_REPL_OWNER.APA.SRC_SEQ_NUM /* see ETL block APACASH in header */
    t.TXN_TP_ID                              AS TXN_TP_ID,  -- [ODI] ODI staging chain -> CCAL_REPL_OWNER.TXN.TXN_TP_ID
    transaction_type.CL_VAL_CODE             AS TXN_TP_CD,  -- [ODI] ODI staging chain -> CCAL_REPL_OWNER.CL_VAL.CL_VAL_CODE
    transaction_type.CL_VAL_NM               AS TXN_TP_NM,  -- [ODI] ODI staging chain -> CCAL_REPL_OWNER.CL_VAL.CL_VAL_NM
    transaction_type.DSC                     AS TXN_TP_DSC,  -- [ODI] ODI staging chain -> CCAL_REPL_OWNER.CL_VAL.DSC
    t.TXN_SBTP_ID                            AS TXN_SBTP_ID,  -- [ODI] ODI staging chain -> CCAL_REPL_OWNER.TXN.TXN_SBTP_ID
    transaction_subtype.CL_VAL_NM            AS TXN_SUB_TP_NM,  -- [ODI] ODI staging chain -> CCAL_REPL_OWNER.CL_VAL.CL_VAL_NM
    transaction_subtype.CL_VAL_CODE          AS TXN_SUB_TP_CD,  -- [ODI] ODI staging chain -> CCAL_REPL_OWNER.CL_VAL.CL_VAL_CODE
    transaction_subtype.DSC                  AS TXN_SUB_TP_DSC,  -- [ODI] ODI staging chain -> CCAL_REPL_OWNER.CL_VAL.DSC
    t.EXEC_TP_ID                             AS EXEC_TP_ID,  -- [ODI] ODI staging chain -> CCAL_REPL_OWNER.TXN.EXEC_TP_ID
    execution_type.CL_VAL_CODE               AS EXEC_TP_CD,  -- [ODI] ODI staging chain -> CCAL_REPL_OWNER.CL_VAL.CL_VAL_CODE
    execution_type.CL_VAL_NM                 AS EXEC_TP_NM,  -- [ODI] ODI staging chain -> CCAL_REPL_OWNER.CL_VAL.CL_VAL_NM
    execution_type.DSC                       AS EXEC_TP_DSC,  -- [ODI] ODI staging chain -> CCAL_REPL_OWNER.CL_VAL.DSC
    execution_subtype.CL_VAL_CODE            AS EXEC_SBTP_CD,  -- [ODI] ODI staging chain -> CCAL_REPL_OWNER.CL_VAL.CL_VAL_CODE
    execution_subtype.CL_VAL_NM              AS EXEC_SBTP_NM,  -- [ODI] ODI staging chain -> CCAL_REPL_OWNER.CL_VAL.CL_VAL_NM
    execution_subtype.DSC                    AS EXEC_SBTP_DSC,  -- [ODI] ODI staging chain -> CCAL_REPL_OWNER.CL_VAL.DSC
    t.EXEC_SBTP_ID                           AS EXEC_SBTP_ID,  -- [ODI] ODI staging chain -> CCAL_REPL_OWNER.TXN.EXEC_SBTP_ID
    apa.APA_TP_ID                            AS SEC_APA_TP_ID,  -- [ODI] ODI staging chain -> CCAL_REPL_OWNER.APA.APA_TP_ID /* see ETL block PRODUCT_INFORMATION in header */
    asset_package_type.CL_VAL_CODE           AS SCR_APA_TP_CD,  -- [ODI] ODI staging chain -> CCAL_REPL_OWNER.CL_VAL.CL_VAL_CODE /* see ETL block PRODUCT_INFORMATION in header */
    asset_package_type.CL_VAL_NM             AS SCR_APA_TP_NM,  -- [ODI] ODI staging chain -> CCAL_REPL_OWNER.CL_VAL.CL_VAL_NM /* see ETL block PRODUCT_INFORMATION in header */
    asset_package_type.DSC                   AS SCR_APA_TP_DSC,  -- [ODI] ODI staging chain -> CCAL_REPL_OWNER.CL_VAL.DSC /* see ETL block PRODUCT_INFORMATION in header */
    apa.APA_TP_ID                            AS CSH_APA_TP_ID,  -- [ODI] ODI staging chain -> CCAL_REPL_OWNER.APA.APA_TP_ID /* see ETL block APACASH in header */
    asset_package_type.CL_VAL_CODE           AS CASH_APA_TP_CD,  -- [ODI] ODI staging chain -> CCAL_REPL_OWNER.CL_VAL.CL_VAL_CODE /* see ETL block APACASH in header */
    asset_package_type.CL_VAL_NM             AS CASH_APA_TP_NM,  -- [ODI] ODI staging chain -> CCAL_REPL_OWNER.CL_VAL.CL_VAL_NM /* see ETL block APACASH in header */
    asset_package_type.DSC                   AS CASH_APA_TP_DSC,  -- [ODI] ODI staging chain -> CCAL_REPL_OWNER.CL_VAL.DSC /* see ETL block APACASH in header */
    avy_cl.AVY_CGY                           AS SCR_AVY_CGY,  -- [ODI] ODI staging chain -> CCAL_REPL_OWNER.AVY_CL.AVY_CGY /* see ETL block PRODUCT_INFORMATION in header */
    avy_cl.AVY_TP                            AS SCR_AVY_TP,  -- [ODI] ODI staging chain -> CCAL_REPL_OWNER.AVY_CL.AVY_TP /* see ETL block PRODUCT_INFORMATION in header */
    txn_avy_cl.AVY_CL_ID                     AS SEC_AVY_CL_ID,  -- [ODI] ODI staging chain -> CCAL_REPL_OWNER.TXN_AVY_CL.AVY_CL_ID /* see ETL block PRODUCT_INFORMATION in header */
    avy_cl.AVY_CGY                           AS CASH_AVY_CGY,  -- [ODI] ODI staging chain -> CCAL_REPL_OWNER.AVY_CL.AVY_CGY /* see ETL block APACASH in header */
    avy_cl.AVY_TP                            AS CASH_AVY_TP,  -- [ODI] ODI staging chain -> CCAL_REPL_OWNER.AVY_CL.AVY_TP /* see ETL block APACASH in header */
    txn_avy_cl.AVY_CL_ID                     AS CSH_AVY_CL_ID,  -- [ODI] ODI staging chain -> CCAL_REPL_OWNER.TXN_AVY_CL.AVY_CL_ID /* see ETL block APACASH in header */
    SYSDATE                                  AS CRT_DTM,  -- [ETL_DEFAULT] system-managed
    'ETL'                                    AS CRT_USR_NM,  -- [ETL_DEFAULT] system-managed
    0                                        AS SESS_NO,  -- [ETL_DEFAULT] system-managed
    t.SRC_ENTR_DTM                           AS SRC_ENTR_DTM,  -- [ODI] ODI staging chain -> CCAL_REPL_OWNER.TXN.SRC_ENTR_DTM
    t.AR_ID                                  AS AR_ID,  -- [ODI] ODI staging chain -> CCAL_REPL_OWNER.TXN.AR_ID
    apa.PD_ID                                AS SEC_PD_ID,  -- [ODI] ODI staging chain -> CCAL_REPL_OWNER.APA.PD_ID /* see ETL block PRODUCT_INFORMATION in header */
    apa.PD_ID                                AS CASH_PD_ID,  -- [ODI] ODI staging chain -> CCAL_REPL_OWNER.APA.PD_ID /* see ETL block APACASH in header */
    apa.BKR_AR_ID                            AS BKR_AR_ID,  -- [DRD_PHYSICAL] DRD source CCAL_REPL_OWNER.APA.BKR_AR_ID /* see ETL block APACASH in header */
    apa.OFST_AR_ID                           AS OFST_AR_ID,  -- [DRD_PHYSICAL] DRD source CCAL_REPL_OWNER.APA.OFST_AR_ID
    t.BR_CODE                                AS BR_CD,  -- [ODI] ODI staging chain -> CCAL_REPL_OWNER.TXN.BR_CODE
    t.FA_NUM                                 AS FA_NUM,  -- [ODI] ODI staging chain -> CCAL_REPL_OWNER.TXN.FA_NUM
    t.SRC_CRT_USRNM                          AS SRC_CRT_USRNM,  -- [ODI] ODI staging chain -> CCAL_REPL_OWNER.TXN.SRC_CRT_USRNM
    t.ORIG_TD                                AS ORIG_TD,  -- [ODI] ODI staging chain -> CCAL_REPL_OWNER.TXN.ORIG_TD
    src_pcs_tp_dim.SRC_PCS_TP_CD             AS SRC_PCS_TP_CD,  -- [ODI] ODI staging chain -> SSDS_TRANSACTIONS_OWNER.SRC_PCS_TP_DIM.SRC_PCS_TP_CD
    src_pcs_tp_dim.SRC_PCS_TP_NM             AS SRC_PCS_TP_NM,  -- [ODI] ODI staging chain -> SSDS_TRANSACTIONS_OWNER.SRC_PCS_TP_DIM.SRC_PCS_TP_NM
    ccy_dim.CCY_DIM_ID                       AS CCY_DIM_ID,  -- [DRD_PHYSICAL] DRD source CIRD_OWNER.CCY_DIM.CCY_DIM_ID
    apa.TXN_ISO_CCY_CODE                     AS CCY_CD,  -- [DRD_PHYSICAL] DRD source CCAL_REPL_OWNER.APA.TXN_ISO_CCY_CODE
    apa.STM_BASE_ISO_CCY_CODE                AS SBC_CCY_CD,  -- [DRD_PHYSICAL] DRD source CCAL_REPL_OWNER.APA.STM_BASE_ISO_CCY_CODE
    apa.SRC_EFF_DT                           AS SRC_EFF_DT,  -- [DRD_PHYSICAL] DRD source CCAL_REPL_OWNER.APA.SRC_EFF_DT
    t.DOL_IND_ID                             AS DOL_IND_ID,  -- [ODI] ODI staging chain -> CCAL_REPL_OWNER.TXN.DOL_IND_ID
    cd_cl_val.CL_VAL_CODE                    AS DOL_IND_CD,  -- [ODI] ODI staging chain -> CCAL_REPL_OWNER.CL_VAL.CL_VAL_CODE
    cd_cl_val.CL_VAL_NM                      AS DOL_IND_NM,  -- [ODI] ODI staging chain -> CCAL_REPL_OWNER.CL_VAL.CL_VAL_NM
    t.OMS_ORDR_KEY                           AS OMS_ORDR_KEY,  -- [ODI] ODI staging chain -> CCAL_REPL_OWNER.TXN.OMS_ORDR_KEY
    t.EXG_CODE                               AS EXG_CD,  -- [ODI] ODI staging chain -> CCAL_REPL_OWNER.TXN.EXG_CODE
    exg_dim.EXG_NM                           AS EXG_NM,  -- [ODI] ODI staging chain -> CIRD_OWNER.EXG_DIM.EXG_NM
    acg_tp_dim.ACG_TP_CD                     AS ACG_TP_CD,  -- [DRD_PHYSICAL] DRD source COMMON_OWNER.ACG_TP_DIM.ACG_TP_CD
    acg_tp_dim.ACG_TP_NM                     AS ACG_TP_NM,  -- [DRD_PHYSICAL] DRD source COMMON_OWNER.ACG_TP_DIM.ACG_TP_NM
    cash_pos_tp_dim.CASH_POS_TP_CD           AS CASH_POS_TP_CD,  -- [ODI] ODI staging chain -> COMMON_OWNER.CASH_POS_TP_DIM.CASH_POS_TP_CD
    cash_pos_tp_dim.CASH_POS_TP_NM           AS CASH_POS_TP_NM,  -- [ODI] ODI staging chain -> COMMON_OWNER.CASH_POS_TP_DIM.CASH_POS_TP_NM
    lgcy_cncl_cmpln_rsn_tp_dim.LGCY_CNCL_CMPLN_RSN_TP_CD AS LGCY_CNCL_CMPLN_RSN_TP_CD,  -- [ODI] ODI staging chain -> SSDS_TRANSACTIONS_OWNER.LGCY_CNCL_CMPLN_RSN_TP_DIM.LGCY_CNCL_CMPLN_RSN_TP_CD
    lgcy_cncl_cmpln_rsn_tp_dim.LGCY_CNCL_CMPLN_RSN_TP_NM AS LGCY_CNCL_CMPLN_RSN_TP_NM,  -- [ODI] ODI staging chain -> SSDS_TRANSACTIONS_OWNER.LGCY_CNCL_CMPLN_RSN_TP_DIM.LGCY_CNCL_CMPLN_RSN_TP_NM
    lgcy_cncl_cmpln_src_tp_dim.LGCY_CNCL_CMPLN_SRC_TP_CD AS LGCY_CNCL_CMPLN_SRC_TP_CD,  -- [ODI] ODI staging chain -> SSDS_TRANSACTIONS_OWNER.LGCY_CNCL_CMPLN_SRC_TP_DIM.LGCY_CNCL_CMPLN_SRC_TP_CD
    lgcy_cncl_cmpln_src_tp_dim.LGCY_CNCL_CMPLN_SRC_TP_NM AS LGCY_CNCL_CMPLN_SRC_TP_NM,  -- [ODI] ODI staging chain -> SSDS_TRANSACTIONS_OWNER.LGCY_CNCL_CMPLN_SRC_TP_DIM.LGCY_CNCL_CMPLN_SRC_TP_NM
    lgcy_mkt_tp_dim.LGCY_MKT_TP_CD           AS LGCY_MKT_TP_CD,  -- [ODI] ODI staging chain -> SSDS_TRANSACTIONS_OWNER.LGCY_MKT_TP_DIM.LGCY_MKT_TP_CD
    lgcy_mkt_tp_dim.LGCY_MKT_TP_NM           AS LGCY_MKT_TP_NM,  -- [ODI] ODI staging chain -> SSDS_TRANSACTIONS_OWNER.LGCY_MKT_TP_DIM.LGCY_MKT_TP_NM
    ltctd2.LGCY_TRD_CPCTY_TP_CD              AS LGCY_TRD_CPCTY_TP_CD,  -- [DRD_PHYSICAL] DRD source TRANSACTIONS_OWNER.LGCY_TRD_CPCTY_TP_DIM.LGCY_TRD_CPCTY_TP_CD /* see ETL block PRODUCT_INFORMATION in header */
    ltctd2.LGCY_TRD_CPCTY_TP_NM              AS LGCY_TRD_CPCTY_TP_NM,  -- [DRD_PHYSICAL] DRD source TRANSACTIONS_OWNER.LGCY_TRD_CPCTY_TP_DIM.LGCY_TRD_CPCTY_TP_NM /* see ETL block PRODUCT_INFORMATION in header */
    src_entr_cnl_tp_dim.SRC_ENTR_CNL_TP_CD   AS SRC_ENTR_CNL_TP_CD,  -- [ODI] ODI staging chain -> SSDS_TRANSACTIONS_OWNER.SRC_ENTR_CNL_TP_DIM.SRC_ENTR_CNL_TP_CD
    src_entr_cnl_tp_dim.SRC_ENTR_CNL_TP_NM   AS SRC_ENTR_CNL_TP_NM,  -- [ODI] ODI staging chain -> SSDS_TRANSACTIONS_OWNER.SRC_ENTR_CNL_TP_DIM.SRC_ENTR_CNL_TP_NM
    trd_slct_tp_dim.TRD_SLCT_TP_CD           AS TRD_SLCT_TP_CD,  -- [ODI] ODI staging chain -> SSDS_TRANSACTIONS_OWNER.TRD_SLCT_TP_DIM.TRD_SLCT_TP_CD
    trd_slct_tp_dim.TRD_SLCT_TP_NM           AS TRD_SLCT_TP_NM,  -- [ODI] ODI staging chain -> SSDS_TRANSACTIONS_OWNER.TRD_SLCT_TP_DIM.TRD_SLCT_TP_NM
    sale_charge_rate_type.CL_VAL_NM          AS SALE_CHRG_RATE_TP_NM,  -- [ODI] ODI staging chain -> CCAL_REPL_OWNER.CL_VAL.CL_VAL_NM /* see ETL block APACASH in header */
    debit_credit_types.CL_VAL_NM             AS CASH_DB_CR_NM,  -- [ODI] ODI staging chain -> CCAL_REPL_OWNER.CL_VAL.CL_VAL_NM /* see ETL block APACASH in header */
    debit_credit_types.CL_VAL_NM             AS SEC_DB_CR_NM,  -- [ODI] ODI staging chain -> CCAL_REPL_OWNER.CL_VAL.CL_VAL_NM /* see ETL block PRODUCT_INFORMATION in header */
    src_stm_dim.SRC_STM_CD                   AS SRC_STM_CD,  -- [ODI] ODI staging chain -> COMMON_OWNER.SRC_STM_DIM.SRC_STM_CD
    TRUNC(SYSDATE)                           AS BATCH_DT,  -- [ETL_DEFAULT] system-managed
    ccal_cird_pd_map.CIRD_PD_ID              AS CASH_CIRD_PD_ID,  -- [ODI] ODI staging chain -> CCAL_REPL_OWNER.CCAL_CIRD_PD_MAP.CIRD_PD_ID /* see ETL block APACASH in header */
    ccal_cird_pd_map.CIRD_PD_ID              AS SEC_CIRD_PD_ID,  -- [ODI] ODI staging chain -> CCAL_REPL_OWNER.CCAL_CIRD_PD_MAP.CIRD_PD_ID
    'Y'                                      AS ACTV_F,  -- [ETL_DEFAULT] system-managed
    t.SRC_TXN_CODE                           AS SRC_TXN_CODE,  -- [ODI] ODI staging chain -> CCAL_REPL_OWNER.TXN.SRC_TXN_CODE
    t.OMS_EXEC_TP_ID                         AS OMS_EXEC_TP_ID,  -- [ODI] ODI staging chain -> CCAL_REPL_OWNER.TXN.OMS_EXEC_TP_ID
    oms_exec_tp.CL_VAL_CODE                  AS OMS_EXEC_TP_CD,  -- [ODI] ODI staging chain -> CCAL_REPL_OWNER.CL_VAL.CL_VAL_CODE
    oms_exec_tp.CL_VAL_NM                    AS OMS_EXEC_TP_NM,  -- [ODI] ODI staging chain -> CCAL_REPL_OWNER.CL_VAL.CL_VAL_NM
    oms_exec_tp.DSC                          AS OMS_EXEC_TP_DSC,  -- [ODI] ODI staging chain -> CCAL_REPL_OWNER.CL_VAL.DSC
    apa.CLNT_FRIENDLY_DESC                   AS CLNT_FRIENDLY_DSC,  -- [DRD_PHYSICAL] DRD source CCAL_REPL_OWNER.APA.CLNT_FRIENDLY_DESC
    t.ORIG_SRC_STM_ID                        AS ORIG_SRC_STM_ID,  -- [ODI] ODI staging chain -> CCAL_REPL_OWNER.TXN.ORIG_SRC_STM_ID
    t.ORIG_SRC_STM_CODE                      AS ORIG_SRC_STM_CD,  -- [ODI] ODI staging chain -> CCAL_REPL_OWNER.TXN.ORIG_SRC_STM_CODE
    apa.ACG_TP_ID                            AS ACG_TP_ID,  -- [DRD_PHYSICAL] DRD source CCAL_REPL_OWNER.APA.ACG_TP_ID
    apa.APA_EXT_QUALFR                       AS CASH_APA_EXT_QUALFR,  -- [ODI] ODI staging chain -> CCAL_REPL_OWNER.APA.APA_EXT_QUALFR /* see ETL block APACASH in header */
    apa.CASH_POS_TP_ID                       AS CASH_POS_TP_ID,  -- [ODI] ODI staging chain -> CCAL_REPL_OWNER.APA.CASH_POS_TP_ID
    apa.SALE_CHRG_RATE                       AS SALE_CHRG_RATE_MULTI_NUM,  -- [DRD_PHYSICAL] DRD source CCAL_REPL_OWNER.APA.SALE_CHRG_RATE /* see ETL block APACASH in header */
    ar_dim.ORIG_SRC_STM_CD                   AS AR_ORIG_SRC_STM_CD,  -- [ODI] ODI staging chain -> CCSI_OWNER.AR_DIM.ORIG_SRC_STM_CD /* see ETL block PRODUCT_INFORMATION in header */
    ar_dim.MF_DRC_EXT_AC_NUM                 AS MF_AC_NUM,  -- [ODI] ODI staging chain -> CCSI_OWNER.AR_DIM.MF_DRC_EXT_AC_NUM /* see ETL block PRODUCT_INFORMATION in header */
    ofst_ar_dim.ORIG_SRC_STM_AR_ID           AS OFST_ORIG_SRC_STM_AR_ID,  -- [DRD_PHYSICAL] DRD source CCSI_OWNER.AR_DIM.ORIG_SRC_STM_AR_ID /* see ETL block PRODUCT_INFORMATION in header */
    ofst_ar_dim.ORIG_SRC_STM_CD              AS OFST_AR_ORIG_SRC_STM_CD,  -- [DRD_PHYSICAL] DRD source CCSI_OWNER.AR_DIM.ORIG_SRC_STM_CD /* see ETL block PRODUCT_INFORMATION in header */
    ofst_ar_dim.SETL_TP_CD                   AS OFST_AR_SETL_TP_CD,  -- [DRD_PHYSICAL] DRD source CCSI_OWNER.AR_DIM.SETL_TP_CD /* see ETL block PRODUCT_INFORMATION in header */
    ofst_ar_dim.SETL_TP                      AS OFST_AR_SETL_TP_DSC,  -- [DRD_PHYSICAL] DRD source CCSI_OWNER.AR_DIM.SETL_TP /* see ETL block PRODUCT_INFORMATION in header */
    ar_dim.SETL_TP_CD                        AS AR_SETL_TP_CD,  -- [ODI] ODI staging chain -> CCSI_OWNER.AR_DIM.SETL_TP_CD /* see ETL block PRODUCT_INFORMATION in header */
    ar_dim.SETL_TP                           AS AR_SETL_TP_DSC,  -- [ODI] ODI staging chain -> CCSI_OWNER.AR_DIM.SETL_TP /* see ETL block PRODUCT_INFORMATION in header */
    ar_dim.ORIG_SRC_STM_AR_ID                AS ORIG_SRC_STM_AR_ID,  -- [DRD_PHYSICAL] DRD source CCSI_OWNER.AR_DIM.ORIG_SRC_STM_AR_ID /* see ETL block PRODUCT_INFORMATION in header */
    avy_cl.DSPL_AVY_CGY                      AS CASH_SIMP_DSPL_AVY_CGY,  -- [ODI] ODI staging chain -> CCAL_REPL_OWNER.AVY_CL.DSPL_AVY_CGY /* see ETL block APACASH in header */
    avy_cl.DSPL_AVY_TP                       AS CASH_SIMP_DSPL_AVY_TP,  -- [ODI] ODI staging chain -> CCAL_REPL_OWNER.AVY_CL.DSPL_AVY_TP /* see ETL block APACASH in header */
    avy_cl.DSPL_AVY_CGY                      AS SCR_SIMP_DSPL_AVY_CGY,  -- [ODI] ODI staging chain -> CCAL_REPL_OWNER.AVY_CL.DSPL_AVY_CGY /* see ETL block PRODUCT_INFORMATION in header */
    avy_cl.DSPL_AVY_TP                       AS SCR_SIMP_DSPL_AVY_TP,  -- [ODI] ODI staging chain -> CCAL_REPL_OWNER.AVY_CL.DSPL_AVY_TP /* see ETL block PRODUCT_INFORMATION in header */
    t.SRC_TXN_TP                             AS SHDW_TXN_TP_CD,  -- [ODI] ODI staging chain -> CCAL_REPL_OWNER.TXN.SRC_TXN_TP
    t.SRC_ACTN_CODE                          AS IMP_SRC_ACTN_CD,  -- [ODI] ODI staging chain -> CCAL_REPL_OWNER.TXN.SRC_ACTN_CODE
    t.SRC_BUY_SELL_MULTI_ID                  AS SIS_DLTD_EV_ID,  -- [ODI] ODI staging chain -> CCAL_REPL_OWNER.TXN.SRC_BUY_SELL_MULTI_ID
    t.USR_ID                                 AS SIS_USR_ID,  -- [ODI] ODI staging chain -> CCAL_REPL_OWNER.TXN.USR_ID
    t.SRC_PRIM_CL                            AS SIS_AC_CL_CD,  -- [ODI] ODI staging chain -> CCAL_REPL_OWNER.TXN.SRC_PRIM_CL
    t.SRC_CNCL_RSN_ID                        AS SRC_CNCL_RSN_ID,  -- [ODI] ODI staging chain -> CCAL_REPL_OWNER.TXN.SRC_CNCL_RSN_ID
    t.SRC_TXN_SEQ_NUM                        AS SRC_TXN_SEQ_NUM,  -- [ODI] ODI staging chain -> CCAL_REPL_OWNER.TXN.SRC_TXN_SEQ_NUM
    t.DVDN_RCRD_DT                           AS DVDN_RCRD_DT,  -- [ODI] ODI staging chain -> CCAL_REPL_OWNER.TXN.DVDN_RCRD_DT
    t.SALE_PSN_NUM                           AS OWN_IMP_FA_NUM,  -- [ODI] ODI staging chain -> CCAL_REPL_OWNER.TXN.SALE_PSN_NUM
    ar_grp_subdim.FA_NUM                     AS OWN_FA_NUM,  -- [ODI] ODI staging chain -> CCSI_OWNER.AR_GRP_SUBDIM.FA_NUM /* see ETL block PRODUCT_INFORMATION in header */
    t.ORIG_SRC_STM_CODE                      AS ACAT_CNTRA_FIRM_CLRG_NUM,  -- [DRD_PHYSICAL] DRD source CCAL_REPL_OWNER.TXN.ORIG_SRC_STM_CODE
    t.ORIG_SRC_STM_CODE                      AS MM_ALT_ID,  -- [DRD_PHYSICAL] DRD source CCAL_REPL_OWNER.TXN.ORIG_SRC_STM_CODE
    t.SRC_STM_ID                             AS SRC_STM_ID,  -- [DRD_PHYSICAL_FALLBACK] DRD physical source CCAL_REPL_OWNER.TXN.SRC_STM_ID (ODI ref to CCAL_REPL_OWNER.J$AVY_FACT skipped: no JOIN)
    t.SRC_CXL_REV                            AS SRC_CNCL_X_RVSN_CD,  -- [ODI] ODI staging chain -> CCAL_REPL_OWNER.TXN.SRC_CXL_REV
    t.SRC_OPT_CLS                            AS SRC_OPT_CLSS_CD,  -- [ODI] ODI staging chain -> CCAL_REPL_OWNER.TXN.SRC_OPT_CLS
    t.TXN_REPL_CNT                           AS TXN_RCNCL_REPL_CNT,  -- [ODI] ODI staging chain -> CCAL_REPL_OWNER.TXN.TXN_REPL_CNT
    t.TXN_ST_ID                              AS TXN_RCNCL_ST_ID,  -- [ODI] ODI staging chain -> CCAL_REPL_OWNER.TXN.TXN_ST_ID
    t.LGCY_CNCL_CMPLN_RSN_TP_ID              AS LGCY_CNCL_CMPLN_RSN_TP_ID,  -- [ODI] ODI staging chain -> CCAL_REPL_OWNER.TXN.LGCY_CNCL_CMPLN_RSN_TP_ID
    t.LGCY_CNCL_CMPLN_SRC_TP_ID              AS LGCY_CNCL_CMPLN_SRC_TP_ID,  -- [ODI] ODI staging chain -> CCAL_REPL_OWNER.TXN.LGCY_CNCL_CMPLN_SRC_TP_ID
    t.LGCY_MKT_TP_ID                         AS LGCY_MKT_TP_ID,  -- [ODI] ODI staging chain -> CCAL_REPL_OWNER.TXN.LGCY_MKT_TP_ID
    t.LGCY_TRD_CPCTY_TP_ID                   AS LGCY_TRD_CPCTY_TP_ID,  -- [ODI] ODI staging chain -> CCAL_REPL_OWNER.TXN.LGCY_TRD_CPCTY_TP_ID
    TXN_RLTNP_TXN.SRC_STM_ID                 AS REL_TXN_SRC_STM_ID,  -- [ODI_T_ALIAS] ODI staging chain -> CCAL_REPL_OWNER.TXN.SRC_STM_ID (T-alias hint: T2)
    t.SRC_ENTR_CNL_TP_ID                     AS SRC_ENTR_CNL_TP_ID,  -- [ODI] ODI staging chain -> CCAL_REPL_OWNER.TXN.SRC_ENTR_CNL_TP_ID
    t.SRC_PCS_TP_ID                          AS SRC_PCS_TP_ID,  -- [ODI] ODI staging chain -> CCAL_REPL_OWNER.TXN.SRC_PCS_TP_ID
    t.TRD_SLCT_TP_ID                         AS TRD_SLCT_TP_ID,  -- [ODI] ODI staging chain -> CCAL_REPL_OWNER.TXN.TRD_SLCT_TP_ID
    'ETL'                                    AS LAST_UDT_USR_NM,  -- [ETL_DEFAULT] system-managed
    SYSDATE                                  AS LAST_UDT_DTM,  -- [ETL_DEFAULT] system-managed
    txn_rltnp.TXN_RLTNP_TP_ID                AS REL_TXN_RLTNP_TP_ID,  -- [ODI] ODI staging chain -> CCAL_REPL_OWNER.TXN_RLTNP.TXN_RLTNP_TP_ID
    acats_broker.BROKER_NAME                 AS ACAT_CNTRA_FIRM_NM,  -- [DRD_PHYSICAL] DRD source CCAL_REPL_OWNER.ACATS_BROKER.BROKER_NAME
    acats_broker.BROKER_SHORT_NAME           AS ACAT_CNTRA_FIRM_SHRT_NM,  -- [DRD_PHYSICAL] DRD source CCAL_REPL_OWNER.ACATS_BROKER.BROKER_SHORT_NAME
    acats_broker.BROKER_ID_TYPE              AS ACAT_CNTRA_FIRM_CLRG_ID_TP_CD,  -- [DRD_PHYSICAL] DRD source CCAL_REPL_OWNER.ACATS_BROKER.BROKER_ID_TYPE
    sis_dltd_ev.CL_VAL_NM                    AS SIS_DLTD_EV_NM,  -- [ODI] ODI staging chain -> CCAL_REPL_OWNER.CL_VAL.CL_VAL_NM
    src_cncl_rsn.CL_VAL_CODE                 AS SRC_CNCL_RSN_CD,  -- [ODI] ODI staging chain -> CCAL_REPL_OWNER.CL_VAL.CL_VAL_CODE
    src_cncl_rsn.CL_VAL_NM                   AS SRC_CNCL_RSN_NM,  -- [ODI] ODI staging chain -> CCAL_REPL_OWNER.CL_VAL.CL_VAL_NM
    txn_rcncl_st.CL_VAL_CODE                 AS TXN_RCNCL_ST_CD,  -- [ODI] ODI staging chain -> CCAL_REPL_OWNER.CL_VAL.CL_VAL_CODE
    txn_rcncl_st.CL_VAL_NM                   AS TXN_RCNCL_ST_NM,  -- [ODI] ODI staging chain -> CCAL_REPL_OWNER.CL_VAL.CL_VAL_NM
    rel_txn_rltnp_tp.CL_VAL_CODE             AS REL_TXN_RLTNP_TP_CD,  -- [ODI] ODI staging chain -> CCAL_REPL_OWNER.CL_VAL.CL_VAL_CODE
    rel_txn_rltnp_tp.CL_VAL_NM               AS REL_TXN_RLTNP_TP_NM,  -- [ODI] ODI staging chain -> CCAL_REPL_OWNER.CL_VAL.CL_VAL_NM
    src_stm_dim.SRC_STM_NM                   AS SRC_STM_NM,  -- [ODI] ODI staging chain -> COMMON_OWNER.SRC_STM_DIM.SRC_STM_NM
    src_stm_dim.SRC_STM_CD                   AS REL_TXN_SRC_STM_CD,  -- [ODI] ODI staging chain -> COMMON_OWNER.SRC_STM_DIM.SRC_STM_CD
    shdw_txn_tp.SRC_TXN_TP_NM                AS SHDW_TXN_TP_NM,  -- [ODI] ODI staging chain -> CCAL_REPL_OWNER.SHDW_TXN_TP.SRC_TXN_TP_NM /* see ETL block PRODUCT_INFORMATION in header */
    impct_action_lku.DESC_TEXT               AS IMP_SRC_ACTN_NM,  -- [ODI] ODI staging chain -> REFERENCE_REPL_OWNER.IMPCT_ACTION_LKU.DESC_TEXT
    fa_number_v.FA_NUMBER_ENTITY_CODE        AS OWN_FA_NUM_ENT_CD,  -- [ODI] ODI staging chain -> SSDS_DAL_OWNER.FA_NUMBER_V.FA_NUMBER_ENTITY_CODE /* see ETL block PRODUCT_INFORMATION in header */
    fa_number_v.RESPONSIBLE_PARTY_EMPLOYEE_ID AS FA_OWN_EMPE_ID,  -- [ODI] ODI staging chain -> SSDS_DAL_OWNER.FA_NUMBER_V.RESPONSIBLE_PARTY_EMPLOYEE_ID
    enterprise_entity_dim_v.ENTITY_ENTERPRISE_ID AS OWN_FA_NUM_ENT_ENTP_ID,  -- [ODI] ODI staging chain -> SSDS_DAL_OWNER.ENTERPRISE_ENTITY_DIM_V.ENTITY_ENTERPRISE_ID /* see ETL block PRODUCT_INFORMATION in header */
    NULL                                     AS AGRT_ORIG_FEES,  -- [NULL_FALLBACK] no DRD source attribute and no ODI projection found
    NULL                                     AS AGRT_STMT_FEES,  -- [NULL_FALLBACK] no DRD source attribute and no ODI projection found
    drvd_trd_cpcty.CL_VAL_CODE               AS DRVD_TRD_CPCTY_CD,  -- [ODI] ODI staging chain -> CCAL_REPL_OWNER.CL_VAL.CL_VAL_CODE
    drvd_trd_cpcty.CL_VAL_NM                 AS DRVD_TRD_CPCTY_NM,  -- [ODI] ODI staging chain -> CCAL_REPL_OWNER.CL_VAL.CL_VAL_NM
    t.DRVD_TRD_CPCTY_TP_ID                   AS DRVD_TRD_CPCTY_ID,  -- [ODI] ODI staging chain -> CCAL_REPL_OWNER.TXN.DRVD_TRD_CPCTY_TP_ID
    apa.OPT_SYMB                             AS SCR_OPT_SYMB,  -- [ODI] ODI staging chain -> CCAL_REPL_OWNER.APA.OPT_SYMB /* see ETL block PRODUCT_INFORMATION in header */
    t.ADL_TRD_INSR                           AS ADL_TRD_INSR,  -- [ODI] ODI staging chain -> CCAL_REPL_OWNER.TXN.ADL_TRD_INSR
    apa.TRD_FCTR_RATE                        AS TRD_FCTR_RATE,  -- [ODI] ODI staging chain -> CCAL_REPL_OWNER.APA.TRD_FCTR_RATE /* see ETL block PRODUCT_INFORMATION in header */
    apa.MRKUP_RATE                           AS MRKUP_RATE,  -- [ODI] ODI staging chain -> CCAL_REPL_OWNER.APA.MRKUP_RATE /* see ETL block PRODUCT_INFORMATION in header */
    apa.STD_CMSN_AMT                         AS STD_CMSN_AMT,  -- [ODI] ODI staging chain -> CCAL_REPL_OWNER.APA.STD_CMSN_AMT /* see ETL block APACASH in header */
    fip.STM_BASE_CCY_AMT                     AS ACT_CMSN_AMT,  -- [DRD_PHYSICAL] DRD source CCAL_REPL_OWNER.FIP.STM_BASE_CCY_AMT
    fip.STM_BASE_CCY_AMT                     AS TRD_PCS_FEE_AMT,  -- [DRD_PHYSICAL] DRD source CCAL_REPL_OWNER.FIP.STM_BASE_CCY_AMT
    fip.STM_BASE_CCY_AMT                     AS SEC_FEE_AMT,  -- [DRD_PHYSICAL] DRD source CCAL_REPL_OWNER.FIP.STM_BASE_CCY_AMT
    fip.STM_BASE_CCY_AMT                     AS ACR_INT_AMT,  -- [DRD_PHYSICAL] DRD source CCAL_REPL_OWNER.FIP.STM_BASE_CCY_AMT
    fip.STM_BASE_CCY_AMT                     AS CNCSN_AMT,  -- [DRD_PHYSICAL] DRD source CCAL_REPL_OWNER.FIP.STM_BASE_CCY_AMT
    fip.STM_BASE_CCY_AMT                     AS CDSC_AMT,  -- [DRD_PHYSICAL] DRD source CCAL_REPL_OWNER.FIP.STM_BASE_CCY_AMT
    fip.STM_BASE_CCY_AMT                     AS OTHR_FEE_AMT,  -- [DRD_PHYSICAL] DRD source CCAL_REPL_OWNER.FIP.STM_BASE_CCY_AMT
    CASE WHEN EXISTS (SELECT 1 FROM CCAL_REPL_OWNER.TXN_RLTNP WHERE TXN.TXN_ID = TXN_RLTNP.TRGT_TXN_ID AND TXN_RLTNP_TP_ID = 69 AND TXN_RLTNP.TRGT_TXN_ID <> TXN_RLTNP.SRC_TXN_ID) THEN 'Y' ELSE NULL END AS TRD_CNCLD_F,  -- [DRD_EXISTS_DERIVED_FLAG] derived flag: EXISTS(CCAL_REPL_OWNER.TXN_RLTNP, set 'Y')
    apa.SYMB                                 AS SYMB,  -- [ODI] ODI staging chain -> CCAL_REPL_OWNER.APA.SYMB /* see ETL block PRODUCT_INFORMATION in header */
    apa.ISIN                                 AS ISIN,  -- [ODI] ODI staging chain -> CCAL_REPL_OWNER.APA.ISIN /* see ETL block PRODUCT_INFORMATION in header */
    txn_src_tax_code_lkup.SRC_TAX_CODE       AS TXN_SRC_TAX_CD,  -- [ODI] ODI staging chain -> CCAL_REPL_OWNER.TXN_SRC_TAX_CODE_LKUP.SRC_TAX_CODE
    txn_src_tax_code_lkup.SRC_TAX_CODE_DSC   AS TXN_SRC_TAX_CD_DSC,  -- [ODI] ODI staging chain -> CCAL_REPL_OWNER.TXN_SRC_TAX_CODE_LKUP.SRC_TAX_CODE_DSC
    t.TM_PRC_DSCTN_F                         AS TM_PRC_DISCRETION_F,  -- [ODI] ODI staging chain -> CCAL_REPL_OWNER.TXN.TM_PRC_DSCTN_F
    txn_avy_cl.NNA_CGY_ID                    AS CASH_NNA_CGY_ID,  -- [ODI] ODI staging chain -> CCAL_REPL_OWNER.TXN_AVY_CL.NNA_CGY_ID /* see ETL block APACASH in header */
    nna_cgy.NNA_CGY_NM                       AS CASH_NNA_CGY_NM,  -- [ODI] ODI staging chain -> CCAL_REPL_OWNER.NNA_CGY.NNA_CGY_NM /* see ETL block APACASH in header */
    txn_avy_cl.NNA_CGY_ID                    AS SCR_NNA_CGY_ID,  -- [ODI] ODI staging chain -> CCAL_REPL_OWNER.TXN_AVY_CL.NNA_CGY_ID /* see ETL block PRODUCT_INFORMATION in header */
    nna_cgy.NNA_CGY_NM                       AS SCR_NNA_CGY_NM,  -- [ODI] ODI staging chain -> CCAL_REPL_OWNER.NNA_CGY.NNA_CGY_NM /* see ETL block PRODUCT_INFORMATION in header */
    apa.YLD                                  AS YLD,  -- [ODI] ODI staging chain -> CCAL_REPL_OWNER.APA.YLD
    apa.YTW                                  AS YTW,  -- [ODI] ODI staging chain -> CCAL_REPL_OWNER.APA.YTW
    apa.YTW_CD                               AS YTW_CD,  -- [ODI] ODI staging chain -> CCAL_REPL_OWNER.APA.YTW_CD
    ar__bkr.ORIG_SRC_STM_AR_ID               AS BKR_AC_NUM,  -- [DRD_PHYSICAL] DRD source CCSI_OWNER.AR_DIM.ORIG_SRC_STM_AR_ID
    sis_dltd_ev.CL_VAL_CODE                  AS SIS_DLTD_EV_CD,  -- [DRD_PHYSICAL] DRD source CCAL_REPL_OWNER.CL_VAL.CL_VAL_CODE
    t.ORIG_TD                                AS DB_CARD_TXN_DT,  -- [ODI] ODI staging chain -> CCAL_REPL_OWNER.TXN.ORIG_TD
    ccy.CCY_CODE                             AS DB_CARD_ORIG_CCY_CD,  -- [ODI] ODI staging chain -> REFERENCE_REPL_OWNER.CCY.CCY_CODE
    ccy.CCY_NM                               AS DB_CARD_ORIG_CCY,  -- [ODI] ODI staging chain -> REFERENCE_REPL_OWNER.CCY.CCY_NM
    NULL                                     AS SDIRA_TXN_TP_CD,  -- [NULL_UNIMPLEMENTED_PROSE] DRD prose describes a derivation that is not auto-generatable from CCAL_REPL_OWNER.CL_VAL (multi-role lookup; no matching role for target SDIRA_TXN_TP_CD). Source DRD rule needs operator implementation.
    NULL                                     AS SDIRA_TXN_TP,  -- [NULL_UNIMPLEMENTED_PROSE] DRD prose describes a derivation that is not auto-generatable from CCAL_REPL_OWNER.CL_VAL (multi-role lookup; no matching role for target SDIRA_TXN_TP). Source DRD rule needs operator implementation.
    t.TRD_NUM                                AS SDIRA_TXN_YR,  -- [ODI] ODI staging chain -> CCAL_REPL_OWNER.TXN.TRD_NUM
    ccy.CCY_NM                               AS TXN_CCY,  -- [DRD_PHYSICAL] DRD source REFERENCE_REPL_OWNER.CCY.CCY_NM
    ar__bkr2.IRA_F                           AS BKR_IRA_F,  -- [DRD_PHYSICAL] DRD source CCSI_OWNER.AR_DIM.IRA_F
    ar__bkr3.ERISSA_F                        AS BKR_ERISA_F,  -- [DRD_PHYSICAL] DRD source CCSI_OWNER.AR_DIM.ERISSA_F
    ar__bkr4.ORIG_SRC_STM_CD                 AS BKR_ORIG_SRC_STM_CD,  -- [DRD_PHYSICAL] DRD source CCSI_OWNER.AR_DIM.ORIG_SRC_STM_CD
    ar__bkr5.ABC_CLSS_CD                     AS BKR_ABC_CLSS_CD,  -- [DRD_PHYSICAL] DRD source CCSI_OWNER.AR_DIM.ABC_CLSS_CD
    ar__bkr6.ABC_CLSS_NM                     AS BKR_ABC_CLSS,  -- [DRD_PHYSICAL] DRD source CCSI_OWNER.AR_DIM.ABC_CLSS_NM
    ar_dim.AR_CGY_CD                         AS AC_CGY_CD,  -- [ODI] ODI staging chain -> CCSI_OWNER.AR_DIM.AR_CGY_CD
    ar__bkr7.AR_CGY_CD                       AS BKR_AC_CGY_CD,  -- [DRD_PHYSICAL] DRD source CCSI_OWNER.AR_DIM.AR_CGY_CD
    ar_dim.AR_CGY                            AS AC_CGY,  -- [ODI] ODI staging chain -> CCSI_OWNER.AR_DIM.AR_CGY
    ar__bkr8.AR_CGY                          AS BKR_AC_CGY,  -- [DRD_PHYSICAL] DRD source CCSI_OWNER.AR_DIM.AR_CGY
    ar__bkr9.BSN_LINE_AFFLT                  AS BKR_BSN_LINE_AFFLT,  -- [DRD_PHYSICAL] DRD source CCSI_OWNER.AR_DIM.BSN_LINE_AFFLT
    ar__bkr10.BSN_LINE_AFFLT_CD              AS BKR_BSN_LINE_AFFLT_CD,  -- [DRD_PHYSICAL] DRD source CCSI_OWNER.AR_DIM.BSN_LINE_AFFLT_CD
    ar_dim.TST_AR_F                          AS TST_AC_F,  -- [ODI] ODI staging chain -> CCSI_OWNER.AR_DIM.TST_AR_F
    ar__bkr11.TST_AR_F                       AS BKR_TST_AC_F,  -- [DRD_PHYSICAL] DRD source CCSI_OWNER.AR_DIM.TST_AR_F
    ar_dim.TAX_RPT_PARTY_ID                  AS TAX_RPT_CLNT_ID,  -- [ODI] ODI staging chain -> CCSI_OWNER.AR_DIM.TAX_RPT_PARTY_ID
    ar__bkr12.TAX_RPT_PARTY_ID               AS BKR_TAX_RPT_CLNT_ID,  -- [DRD_PHYSICAL] DRD source CCSI_OWNER.AR_DIM.TAX_RPT_PARTY_ID
    ar_dim.TAX_AC_F                          AS TAX_AC_F,  -- [ODI] ODI staging chain -> CCSI_OWNER.AR_DIM.TAX_AC_F
    ar__bkr13.TAX_AC_F                       AS BKR_TAX_AC_F,  -- [DRD_PHYSICAL] DRD source CCSI_OWNER.AR_DIM.TAX_AC_F
    ar__bkr14.RJ_TAX_RPT_RSPL_F              AS BKR_RJ_TAX_RPT_RSPL_F,  -- [DRD_PHYSICAL] DRD source CCSI_OWNER.AR_DIM.RJ_TAX_RPT_RSPL_F
    ar_dim.RJ_BSN_UNIT_CD                    AS RJ_BSN_UNIT_CD,  -- [ODI] ODI staging chain -> CCSI_OWNER.AR_DIM.RJ_BSN_UNIT_CD
    ar__bkr15.RJ_BSN_UNIT_CD                 AS BKR_RJ_BSN_UNIT_CD,  -- [DRD_PHYSICAL] DRD source CCSI_OWNER.AR_DIM.RJ_BSN_UNIT_CD
    ar_dim.RJ_BSN_UNIT                       AS RJ_BSN_UNIT,  -- [ODI] ODI staging chain -> CCSI_OWNER.AR_DIM.RJ_BSN_UNIT
    ar__bkr16.RJ_BSN_UNIT                    AS BKR_RJ_BSN_UNIT,  -- [DRD_PHYSICAL] DRD source CCSI_OWNER.AR_DIM.RJ_BSN_UNIT
    ar_dim.OWNSHP_TP_CD                      AS AC_OWNSHP_TP_CD,  -- [ODI] ODI staging chain -> CCSI_OWNER.AR_DIM.OWNSHP_TP_CD
    ar__bkr17.OWNSHP_TP_CD                   AS BKR_AC_OWNSHP_TP_CD,  -- [DRD_PHYSICAL] DRD source CCSI_OWNER.AR_DIM.OWNSHP_TP_CD
    ar_dim.OWNSHP_TP                         AS AC_OWNSHP_TP,  -- [ODI] ODI staging chain -> CCSI_OWNER.AR_DIM.OWNSHP_TP
    ar__bkr18.OWNSHP_TP                      AS BKR_AC_OWNSHP_TP,  -- [DRD_PHYSICAL] DRD source CCSI_OWNER.AR_DIM.OWNSHP_TP
    ar__bkr19.FIRM_AC_F                      AS BKR_FIRM_AC_F,  -- [DRD_PHYSICAL] DRD source CCSI_OWNER.AR_DIM.FIRM_AC_F
    ar__bkr20.FEE_BASE_F                     AS BKR_FEE_BASE_AC_F,  -- [DRD_PHYSICAL] DRD source CCSI_OWNER.AR_DIM.FEE_BASE_F
    ar__bkr21.BSN_LINE_AFFLT_CD              AS BKR_RJ_TRUST_F,  -- [DRD_PHYSICAL] DRD source CCSI_OWNER.AR_DIM.BSN_LINE_AFFLT_CD
    fa_number_v.FA_NUMBER                    AS OWN_PRIM_FA_NUM,  -- [DRD_PHYSICAL] DRD source SSDS_DAL_OWNER.FA_NUMBER_V.FA_NUMBER
    pr.CSS_PERSON_ID                         AS OWN_FA_CSS_PSN_ID,  -- [DRD_PHYSICAL] DRD source SSDS_DAL_OWNER.PERSON_RV.CSS_PERSON_ID
    pbsv.CURRENT_ADVISOR_FLAG                AS OWN_FA_CRN_ADV_F,  -- [DRD_PHYSICAL] DRD source SSDS_DAL_OWNER.PERSON_BROKERAGE_SUBDIMENSION_V.CURRENT_ADVISOR_FLAG
    pr.DEPARTMENT_BRANCH_CODE                AS OWN_FA_DEPT_BR_CD,  -- [DRD_PHYSICAL] DRD source SSDS_DAL_OWNER.PERSON_RV.DEPARTMENT_BRANCH_CODE
    padsv.DISCRETIONARY_INDICATOR            AS OWN_FA_DSCR_F,  -- [DRD_PHYSICAL] DRD source SSDS_DAL_OWNER.PERSON_AMS_DISCRETIONARY_STATUS_V.DISCRETIONARY_INDICATOR
    padsv.DISCRETIONARY_STATUS               AS OWN_FA_DSCR_ST,  -- [DRD_PHYSICAL] DRD source SSDS_DAL_OWNER.PERSON_AMS_DISCRETIONARY_STATUS_V.DISCRETIONARY_STATUS
    padsv.DISCRETIONARY_STATUS_CODE          AS OWN_FA_DSCR_ST_CD,  -- [DRD_PHYSICAL] DRD source SSDS_DAL_OWNER.PERSON_AMS_DISCRETIONARY_STATUS_V.DISCRETIONARY_STATUS_CODE
    pr.FINRA_CRD_CLASS_CODE                  AS OWN_FA_FINRA_CRD_CLSS_CD,  -- [DRD_PHYSICAL] DRD source SSDS_DAL_OWNER.PERSON_RV.FINRA_CRD_CLASS_CODE
    pr.HR_STATUS_CODE                        AS OWN_FA_HR_ST_CD,  -- [DRD_PHYSICAL] DRD source SSDS_DAL_OWNER.PERSON_RV.HR_STATUS_CODE
    pr.PRODUCER_FLAG                         AS OWN_FA_PRODUCER_F,  -- [DRD_PHYSICAL] DRD source SSDS_DAL_OWNER.PERSON_RV.PRODUCER_FLAG
    pbsv.QUALIFIED_ADVISOR_FLAG              AS OWN_FA_QUALF_ADV_F,  -- [DRD_PHYSICAL] DRD source SSDS_DAL_OWNER.PERSON_BROKERAGE_SUBDIMENSION_V.QUALIFIED_ADVISOR_FLAG
    enterprise_entity_dim_v.ENTITY_BRANCH_CODE AS OWN_FA_ENT_BR_CD,  -- [DRD_PHYSICAL] DRD source SSDS_DAL_OWNER.ENTERPRISE_ENTITY_DIM_V.ENTITY_BRANCH_CODE
    enterprise_entity_dim_v.ENTITY_BUSINESS_STATUS AS OWN_FA_ENT_BSN_ST,  -- [DRD_PHYSICAL] DRD source SSDS_DAL_OWNER.ENTERPRISE_ENTITY_DIM_V.ENTITY_BUSINESS_STATUS
    enterprise_entity_dim_v.ENTITY_DIVISION_CODE AS OWN_FA_ENT_DIV_CD,  -- [DRD_PHYSICAL] DRD source SSDS_DAL_OWNER.ENTERPRISE_ENTITY_DIM_V.ENTITY_DIVISION_CODE
    enterprise_entity_dim_v.ENTITY_DIVISION_DESCRIPTION AS OWN_FA_ENT_DIV_DSC,  -- [DRD_PHYSICAL] DRD source SSDS_DAL_OWNER.ENTERPRISE_ENTITY_DIM_V.ENTITY_DIVISION_DESCRIPTION
    enterprise_entity_dim_v.ENTITY_DIVISION_NODE AS OWN_FA_ENT_DIV_NODE,  -- [DRD_PHYSICAL] DRD source SSDS_DAL_OWNER.ENTERPRISE_ENTITY_DIM_V.ENTITY_DIVISION_NODE
    enterprise_entity_dim_v.ENTITY_MAIN_BRANCH_STATE AS OWN_FA_ENT_MAIN_BR_STE,  -- [DRD_PHYSICAL] DRD source SSDS_DAL_OWNER.ENTERPRISE_ENTITY_DIM_V.ENTITY_MAIN_BRANCH_STATE
    enterprise_entity_dim_v.ENTITY_OSJ       AS OWN_FA_ENT_OSJ,  -- [DRD_PHYSICAL] DRD source SSDS_DAL_OWNER.ENTERPRISE_ENTITY_DIM_V.ENTITY_OSJ
    eerdv.ENTITY_RETAIL_BUSINESS_MODEL_CODE  AS OWN_FA_ENT_RTL_HIER_BSN_MODL_CD,  -- [DRD_PHYSICAL] DRD source SSDS_DAL_OWNER.ENTERPRISE_ENTITY_RETAIL_DIMENSION_V.ENTITY_RETAIL_BUSINESS_MODEL_CODE
    eerdv.ENTITY_RETAIL_BUSINESS_MODEL_DESCRIPTION AS OWN_FA_ENT_RTL_HIER_BSN_MODL_DSC,  -- [DRD_PHYSICAL] DRD source SSDS_DAL_OWNER.ENTERPRISE_ENTITY_RETAIL_DIMENSION_V.ENTITY_RETAIL_BUSINESS_MODEL_DESCRIPTION
    eerdv.ENTITY_RETAIL_SALES_LOB_CODE       AS OWN_FA_ENT_RTL_SALE_HIER_LOB_CD,  -- [DRD_PHYSICAL] DRD source SSDS_DAL_OWNER.ENTERPRISE_ENTITY_RETAIL_DIMENSION_V.ENTITY_RETAIL_SALES_LOB_CODE
    eerdv.ENTITY_RETAIL_SALES_LOB_DESCRIPTION AS OWN_FA_ENT_RTL_SALE_HIER_LOB_DSC,  -- [DRD_PHYSICAL] DRD source SSDS_DAL_OWNER.ENTERPRISE_ENTITY_RETAIL_DIMENSION_V.ENTITY_RETAIL_SALES_LOB_DESCRIPTION
    eerdv.ENTITY_RETAIL_REPORTING_UNIT_CODE  AS OWN_FA_ENT_RTL_HIER_RPT_UNIT_CD,  -- [DRD_PHYSICAL] DRD source SSDS_DAL_OWNER.ENTERPRISE_ENTITY_RETAIL_DIMENSION_V.ENTITY_RETAIL_REPORTING_UNIT_CODE
    eerdv.ENTITY_RETAIL_REPORTING_UNIT_DESCRIPTION AS OWN_FA_ENT_RTL_HIER_RPT_UNIT_DSC,  -- [DRD_PHYSICAL] DRD source SSDS_DAL_OWNER.ENTERPRISE_ENTITY_RETAIL_DIMENSION_V.ENTITY_RETAIL_REPORTING_UNIT_DESCRIPTION
    eerdv.ENTITY_RETAIL_SALES_DIVISION_CODE  AS OWN_FA_ENT_RTL_SALE_DIV_CD,  -- [DRD_PHYSICAL] DRD source SSDS_DAL_OWNER.ENTERPRISE_ENTITY_RETAIL_DIMENSION_V.ENTITY_RETAIL_SALES_DIVISION_CODE
    eerdv.ENTITY_RETAIL_SALES_REGION_CODE    AS OWN_FA_ENT_RTL_SALE_HIER_RGON_CD,  -- [DRD_PHYSICAL] DRD source SSDS_DAL_OWNER.ENTERPRISE_ENTITY_RETAIL_DIMENSION_V.ENTITY_RETAIL_SALES_REGION_CODE
    eerdv.ENTITY_RETAIL_SALES_REGION_DESCRIPTION AS OWN_FA_ENT_RTL_SALE_HIER_RGON_DSC,  -- [DRD_PHYSICAL] DRD source SSDS_DAL_OWNER.ENTERPRISE_ENTITY_RETAIL_DIMENSION_V.ENTITY_RETAIL_SALES_REGION_DESCRIPTION
    eerdv.ENTITY_RETAIL_TERRITORY_CODE       AS OWN_FA_ENT_RTL_HIER_TERR_CD,  -- [DRD_PHYSICAL] DRD source SSDS_DAL_OWNER.ENTERPRISE_ENTITY_RETAIL_DIMENSION_V.ENTITY_RETAIL_TERRITORY_CODE
    eerdv.ENTITY_RETAIL_TERRITORY_DESCRIPTION AS OWN_FA_ENT_RTL_HIER_TERR_DSC,  -- [DRD_PHYSICAL] DRD source SSDS_DAL_OWNER.ENTERPRISE_ENTITY_RETAIL_DIMENSION_V.ENTITY_RETAIL_TERRITORY_DESCRIPTION
    ar_grp_subdim.ENTITY_RISK_BUSINESS_UNIT_CODE AS OWN_FA_ENT_RSK_HIER_BSN_UNIT_CD,  -- [DRD_INLINE_FALLBACK] DRD inline join CCSI_OWNER.AR_GRP_SUBDIM.ENTITY_RISK_BUSINESS_UNIT_CODE (ODI ref to SSDS_DAL_OWNER.ENTERPRISE_ENTITY_RISK_DIM skipped: no JOIN)
    ar_grp_subdim.ENTITY_RISK_BUSINESS_UNIT_DESCRIPTION AS OWN_FA_ENT_RSK_HIER_BSN_UNIT_DSC,  -- [DRD_INLINE_FALLBACK] DRD inline join CCSI_OWNER.AR_GRP_SUBDIM.ENTITY_RISK_BUSINESS_UNIT_DESCRIPTION (ODI ref to SSDS_DAL_OWNER.ENTERPRISE_ENTITY_RISK_DIM skipped: no JOIN)
    enterprise_entity_dim_v.ENTITY_RJAS_ID_BOOLEAN AS OWN_FA_ENT_RJAS_ID_F,  -- [DRD_PHYSICAL] DRD source SSDS_DAL_OWNER.ENTERPRISE_ENTITY_DIM_V.ENTITY_RJAS_ID_BOOLEAN
    enterprise_entity_dim_v.ENTITY_SUBDIVISION_CODE AS OWN_FA_ENT_SUBDIV_CD,  -- [DRD_PHYSICAL] DRD source SSDS_DAL_OWNER.ENTERPRISE_ENTITY_DIM_V.ENTITY_SUBDIVISION_CODE
    enterprise_entity_dim_v.ENTITY_SUBDIVISION_DESCRIPTION AS OWN_FA_ENT_SUBDIV_DSC,  -- [DRD_PHYSICAL] DRD source SSDS_DAL_OWNER.ENTERPRISE_ENTITY_DIM_V.ENTITY_SUBDIVISION_DESCRIPTION
    enterprise_entity_dim_v.ENTITY_SUBSIDIARY AS OWN_FA_ENT_SUBS,  -- [DRD_PHYSICAL] DRD source SSDS_DAL_OWNER.ENTERPRISE_ENTITY_DIM_V.ENTITY_SUBSIDIARY
    enterprise_entity_dim_v.ENTITY_SUBTYPE   AS OWN_FA_ENT_SBTP,  -- [DRD_PHYSICAL] DRD source SSDS_DAL_OWNER.ENTERPRISE_ENTITY_DIM_V.ENTITY_SUBTYPE
    enterprise_entity_dim_v.ENTITY_SUBTYPE_CODE AS OWN_FA_ENT_SBTP_CD,  -- [DRD_PHYSICAL] DRD source SSDS_DAL_OWNER.ENTERPRISE_ENTITY_DIM_V.ENTITY_SUBTYPE_CODE
    enterprise_entity_dim_v.ENTITY_TYPE      AS OWN_FA_ENT_TP,  -- [DRD_PHYSICAL] DRD source SSDS_DAL_OWNER.ENTERPRISE_ENTITY_DIM_V.ENTITY_TYPE
    enterprise_entity_dim_v.ENTITY_TYPE_CODE AS OWN_FA_ENT_TP_CD,  -- [DRD_PHYSICAL] DRD source SSDS_DAL_OWNER.ENTERPRISE_ENTITY_DIM_V.ENTITY_TYPE_CODE
    enterprise_entity_dim_v.LOB_ALEX_BROWN_BOOLEAN AS OWN_FA_ENT_LOB_AB_F,  -- [DRD_PHYSICAL] DRD source SSDS_DAL_OWNER.ENTERPRISE_ENTITY_DIM_V.LOB_ALEX_BROWN_BOOLEAN
    enterprise_entity_dim_v.LOB_AMS_BOOLEAN  AS OWN_FA_ENT_LOB_AMS_F,  -- [DRD_PHYSICAL] DRD source SSDS_DAL_OWNER.ENTERPRISE_ENTITY_DIM_V.LOB_AMS_BOOLEAN
    enterprise_entity_dim_v.LOB_BUSINESS_MODEL AS OWN_FA_ENT_LOB_BSN_MODL,  -- [DRD_PHYSICAL] DRD source SSDS_DAL_OWNER.ENTERPRISE_ENTITY_DIM_V.LOB_BUSINESS_MODEL
    enterprise_entity_dim_v.ENTITY_BUSINESS_OPEN_DATE AS OWN_FA_ENT_BSN_OPN_DT,  -- [DRD_PHYSICAL] DRD source SSDS_DAL_OWNER.ENTERPRISE_ENTITY_DIM_V.ENTITY_BUSINESS_OPEN_DATE
    enterprise_entity_dim_v.ENTITY_CODE_LONG AS OWN_FA_ENT_LONG_CD,  -- [DRD_PHYSICAL] DRD source SSDS_DAL_OWNER.ENTERPRISE_ENTITY_DIM_V.ENTITY_CODE_LONG
    enterprise_entity_dim_v.ENTITY_CODE_SHORT AS OWN_FA_ENT_SHRT_CD,  -- [DRD_PHYSICAL] DRD source SSDS_DAL_OWNER.ENTERPRISE_ENTITY_DIM_V.ENTITY_CODE_SHORT
    enterprise_entity_dim_v.ENTITY_CSS_ID    AS OWN_FA_ENT_CSS_ID,  -- [DRD_PHYSICAL] DRD source SSDS_DAL_OWNER.ENTERPRISE_ENTITY_DIM_V.ENTITY_CSS_ID
    eerdv.ENTITY_RETAIL_SALES_COMPLEX_CODE   AS OWN_FA_ENT_RTL_SALE_CPX_CD,  -- [DRD_PHYSICAL] DRD source SSDS_DAL_OWNER.ENTERPRISE_ENTITY_RETAIL_DIMENSION_V.ENTITY_RETAIL_SALES_COMPLEX_CODE
    imt_pd_dim.EQTY_SECT_LVL_4               AS EQTY_IDY,  -- [ODI] ODI staging chain -> CIRD_OWNER.IMT_PD_DIM.EQTY_SECT_LVL_4
    imt_pd_dim.EQTY_SECT_LVL_4_CD            AS EQTY_IDY_CD,  -- [ODI] ODI staging chain -> CIRD_OWNER.IMT_PD_DIM.EQTY_SECT_LVL_4_CD
    imt_pd_dim.EQTY_SECT_LVL_3               AS EQTY_IDY_GRP,  -- [ODI] ODI staging chain -> CIRD_OWNER.IMT_PD_DIM.EQTY_SECT_LVL_3
    imt_pd_dim.EQTY_SECT_LVL_3_CD            AS EQTY_IDY_GRP_CD,  -- [ODI] ODI staging chain -> CIRD_OWNER.IMT_PD_DIM.EQTY_SECT_LVL_3_CD
    imt_pd_dim.EQTY_SECT_LVL_2               AS EQTY_SECT,  -- [ODI] ODI staging chain -> CIRD_OWNER.IMT_PD_DIM.EQTY_SECT_LVL_2
    imt_pd_dim.EQTY_SECT_LVL_2_CD            AS EQTY_SECT_CD,  -- [ODI] ODI staging chain -> CIRD_OWNER.IMT_PD_DIM.EQTY_SECT_LVL_2_CD
    imt_pd_dim.EQTY_SECT_LVL_1               AS EQTY_SUP_SECT,  -- [ODI] ODI staging chain -> CIRD_OWNER.IMT_PD_DIM.EQTY_SECT_LVL_1
    imt_pd_dim.EQTY_SECT_LVL_1_CD            AS EQTY_SUP_SECT_CD,  -- [ODI] ODI staging chain -> CIRD_OWNER.IMT_PD_DIM.EQTY_SECT_LVL_1_CD
    imt_pd_dim.FIRM_MODL_LVL_2               AS MODL_STRTG_DTL_AST_CLSS,  -- [ODI] ODI staging chain -> CIRD_OWNER.IMT_PD_DIM.FIRM_MODL_LVL_2
    imt_pd_dim.FIRM_MODL_LVL_2_CD            AS MODL_STRTG_DTL_AST_CLSS_CD,  -- [ODI] ODI staging chain -> CIRD_OWNER.IMT_PD_DIM.FIRM_MODL_LVL_2_CD
    imt_pd_dim.FIRM_MODL_LVL_1               AS MODL_STRTG_SMY_AST_CLSS,  -- [ODI] ODI staging chain -> CIRD_OWNER.IMT_PD_DIM.FIRM_MODL_LVL_1
    imt_pd_dim.FIRM_MODL_LVL_1_CD            AS MODL_STRTG_SMY_AST_CLSS_CD,  -- [ODI] ODI staging chain -> CIRD_OWNER.IMT_PD_DIM.FIRM_MODL_LVL_1_CD
    apa.PD_CMPOS_DSC                         AS PD_CMPOS_DSC,  -- [ODI] ODI staging chain -> CCAL_REPL_OWNER.APA.PD_CMPOS_DSC /* see ETL block PRODUCT_INFORMATION in header */
    imt_pd_dim.PD_NM                         AS PD_SHRT_NM,  -- [ODI] ODI staging chain -> CIRD_OWNER.IMT_PD_DIM.PD_NM /* see ETL block PRODUCT_INFORMATION in header */
    imt_pd_dim.PD_DSC                        AS PD_DSC,  -- [ODI] ODI staging chain -> CIRD_OWNER.IMT_PD_DIM.PD_DSC /* see ETL block PRODUCT_INFORMATION in header */
    imt_pd_dim.RPT_CL_LVL_1                  AS RPT_CL_LVL_1,  -- [ODI] ODI staging chain -> CIRD_OWNER.IMT_PD_DIM.RPT_CL_LVL_1
    imt_pd_dim.RPT_CL_LVL_2                  AS RPT_CL_LVL_2,  -- [ODI] ODI staging chain -> CIRD_OWNER.IMT_PD_DIM.RPT_CL_LVL_2
    imt_pd_dim.FIRM_RPT_LVL_2                AS RPT_STRTG_DTL_AST_CLSS,  -- [ODI] ODI staging chain -> CIRD_OWNER.IMT_PD_DIM.FIRM_RPT_LVL_2
    imt_pd_dim.FIRM_RPT_LVL_2_CD             AS RPT_STRTG_DTL_AST_CLSS_CD,  -- [ODI] ODI staging chain -> CIRD_OWNER.IMT_PD_DIM.FIRM_RPT_LVL_2_CD
    imt_pd_dim.FIRM_RPT_LVL_1                AS RPT_STRTG_SMY_AST_CLSS,  -- [ODI] ODI staging chain -> CIRD_OWNER.IMT_PD_DIM.FIRM_RPT_LVL_1
    imt_pd_dim.FIRM_RPT_LVL_1_CD             AS RPT_STRTG_SMY_AST_CLSS_CD,  -- [ODI] ODI staging chain -> CIRD_OWNER.IMT_PD_DIM.FIRM_RPT_LVL_1_CD
    imt_pd_dim.FND_FAM                       AS FND_FAM,  -- [ODI] ODI staging chain -> CIRD_OWNER.IMT_PD_DIM.FND_FAM
    imt_pd_dim.SHR_CLSS_TP_CD                AS SHR_CLSS_TP_CD,  -- [ODI] ODI staging chain -> CIRD_OWNER.IMT_PD_DIM.SHR_CLSS_TP_CD
    imt_pd_dim.SHR_CLSS_TP_NM                AS SHR_CLSS_TP,  -- [ODI] ODI staging chain -> CIRD_OWNER.IMT_PD_DIM.SHR_CLSS_TP_NM
    imt_pd_dim.IMT_CL_LVL_1                  AS IMT_CL_LVL_1,  -- [ODI] ODI staging chain -> CIRD_OWNER.IMT_PD_DIM.IMT_CL_LVL_1
    imt_pd_dim.IMT_CL_LVL_1_CD               AS IMT_CL_LVL_1_CD,  -- [ODI] ODI staging chain -> CIRD_OWNER.IMT_PD_DIM.IMT_CL_LVL_1_CD
    imt_pd_dim.IMT_CL_LVL_2                  AS IMT_CL_LVL_2,  -- [ODI] ODI staging chain -> CIRD_OWNER.IMT_PD_DIM.IMT_CL_LVL_2
    imt_pd_dim.IMT_CL_LVL_2_CD               AS IMT_CL_LVL_2_CD,  -- [ODI] ODI staging chain -> CIRD_OWNER.IMT_PD_DIM.IMT_CL_LVL_2_CD
    imt_pd_dim.IMT_CL_LVL_3                  AS IMT_CL_LVL_3,  -- [ODI] ODI staging chain -> CIRD_OWNER.IMT_PD_DIM.IMT_CL_LVL_3
    imt_pd_dim.IMT_CL_LVL_3_CD               AS IMT_CL_LVL_3_CD,  -- [ODI] ODI staging chain -> CIRD_OWNER.IMT_PD_DIM.IMT_CL_LVL_3_CD
    imt_pd_dim.IMT_CL_LVL_4                  AS IMT_CL_LVL_4,  -- [ODI] ODI staging chain -> CIRD_OWNER.IMT_PD_DIM.IMT_CL_LVL_4
    imt_pd_dim.IMT_CL_LVL_4_CD               AS IMT_CL_LVL_4_CD,  -- [ODI] ODI staging chain -> CIRD_OWNER.IMT_PD_DIM.IMT_CL_LVL_4_CD
    imt_pd_dim.IMT_CL_LVL_5                  AS IMT_CL_LVL_5,  -- [ODI] ODI staging chain -> CIRD_OWNER.IMT_PD_DIM.IMT_CL_LVL_5
    imt_pd_dim.IMT_CL_LVL_5_CD               AS IMT_CL_LVL_5_CD,  -- [ODI] ODI staging chain -> CIRD_OWNER.IMT_PD_DIM.IMT_CL_LVL_5_CD
    fa_number_v.FA_NUMBER_TYPE_CODE          AS OWN_FA_NUM_TP_CD,  -- [ODI] ODI staging chain -> SSDS_DAL_OWNER.FA_NUMBER_V.FA_NUMBER_TYPE_CODE
    code_set_value_v.CODE_VALUE_DESCRIPTION  AS OWN_FA_NUM_TP,  -- [ODI] ODI staging chain -> SSDS_DAL_OWNER.CODE_SET_VALUE_V.CODE_VALUE_DESCRIPTION
    CASE WHEN cv.CL_VAL_CODE = 'APACSH82' THEN apa.ORIG_QTY ELSE NULL END AS BOND_ACRTN_DCN_AMT,  -- [DRD_PHYSICAL_CASE] DRD source CCAL_REPL_OWNER.APA.ORIG_QTY (applicable only for APACSH82) /* see ETL block APACASH in header */
    CASE WHEN cv.CL_VAL_CODE = 'APACSH83' THEN apa.ORIG_QTY ELSE NULL END AS BOND_AMRZ_PREM_AMT,  -- [DRD_PHYSICAL_CASE] DRD source CCAL_REPL_OWNER.APA.ORIG_QTY (applicable only for APACSH83) /* see ETL block APACASH in header */
    CASE WHEN cv.CL_VAL_CODE = 'APACSH84' THEN apa.ORIG_QTY ELSE NULL END AS RJ_TRUST_BOOK_VAL_AMT,  -- [DRD_PHYSICAL_CASE] DRD source CCAL_REPL_OWNER.APA.ORIG_QTY (applicable only for APACSH84) /* see ETL block APACASH in header */
    CASE WHEN cv.CL_VAL_CODE = 'APACSH85' THEN apa.ORIG_QTY ELSE NULL END AS RJ_TRUST_RLZD_TAX_GAIN_OR_LOSS_AMT,  -- [DRD_PHYSICAL_CASE] DRD source CCAL_REPL_OWNER.APA.ORIG_QTY (applicable only for APACSH85) /* see ETL block APACASH in header */
    CASE WHEN CL_VAL.CL_VAL_CODE = 'APASEC81' THEN apa.ORIG_QTY ELSE NULL END AS BFR_REPYMT_FACE_VAL_AMT,  -- [DRD_PHYSICAL_CASE] DRD source CCAL_REPL_OWNER.APA.ORIG_QTY (applicable only for APASEC81) /* see ETL block PRODUCT_INFORMATION in header */
    CASE WHEN CL_VAL.CL_VAL_CODE = 'APASEC83' THEN apa.ORIG_QTY ELSE NULL END AS BFR_INCM_PYMT_FACE_VAL_AMT,  -- [DRD_PHYSICAL_CASE] DRD source CCAL_REPL_OWNER.APA.ORIG_QTY (applicable only for APASEC83) /* see ETL block PRODUCT_INFORMATION in header */
    CASE WHEN CL_VAL.CL_VAL_CODE = 'APASEC91' THEN apa.ORIG_QTY ELSE NULL END AS BASE_POS_QTY,  -- [DRD_PHYSICAL_CASE] DRD source CCAL_REPL_OWNER.APA.ORIG_QTY (applicable only for APASEC91) /* see ETL block PRODUCT_INFORMATION in header */
    CASE WHEN CL_VAL.CL_VAL_CODE = 'APASEC93' THEN apa.ORIG_QTY ELSE NULL END AS NO_SIS_SCR_MVMT_TXN_QTY,  -- [DRD_PHYSICAL_CASE] DRD source CCAL_REPL_OWNER.APA.ORIG_QTY (applicable only for APASEC93) /* see ETL block PRODUCT_INFORMATION in header */
    CASE WHEN CL_VAL.CL_VAL_CODE = 'APASEC93' THEN apa.SCR_PRC_IN_TXN_CCY ELSE NULL END AS NO_SIS_SCR_MVMT_TXN_PRC,  -- [DRD_PHYSICAL_CASE] DRD source CCAL_REPL_OWNER.APA.SCR_PRC_IN_TXN_CCY (applicable only for APASEC93) /* see ETL block PRODUCT_INFORMATION in header */
    CASE WHEN CL_VAL.CL_VAL_CODE = 'APASEC94' THEN apa.ORIG_QTY ELSE NULL END AS REIVS_SHR_QTY,  -- [DRD_PHYSICAL_CASE] DRD source CCAL_REPL_OWNER.APA.ORIG_QTY (applicable only for APASEC94) /* see ETL block PRODUCT_INFORMATION in header */
    CASE WHEN CL_VAL.CL_VAL_CODE = 'APASEC94' THEN apa.SCR_PRC_IN_TXN_CCY ELSE NULL END AS REIVS_PRC  -- [DRD_PHYSICAL_CASE] DRD source CCAL_REPL_OWNER.APA.SCR_PRC_IN_TXN_CCY (applicable only for APASEC94) /* see ETL block PRODUCT_INFORMATION in header */
FROM CCAL_REPL_OWNER.TXN t
LEFT JOIN CCAL_REPL_OWNER.TXN TXN ON J_AVY_FACT.TXN_ID = TXN.TXN_ID
LEFT JOIN CCAL_REPL_OWNER.APA APA ON TXN.TXN_ID = APA.EXEC_ID AND apa.exec_id = t.txn_id
LEFT JOIN CCAL_REPL_OWNER.TXN_AVY_CL TXN_AVY_CL ON TXN.TXN_ID = TXN_AVY_CL.TXN_ID AND APA.EXEC_ID = TXN_AVY_CL.EXEC_ID AND APA.APA_ID = TXN_AVY_CL.APA_ID AND txn_avy_cl.txn_id = t.txn_id AND apa.apa_id = txn_avy_cl.apa_id
LEFT JOIN CCAL_REPL_OWNER.AVY_CL AVY_CL ON TXN_AVY_CL.AVY_CL_ID = AVY_CL.AVY_CL_ID AND avy_cl.avy_cl_id = txn_avy_cl.avy_cl_id
LEFT JOIN CIRD_OWNER.IMT_PD_DIM SEC_IMT_PD_DIM ON APA.PD_ID = SEC_IMT_PD_DIM.CCAL_PD_ID AND sec_imt_pd_dim.CCAL_PD_ID = apa.PD_ID AND ap.pd_id = sec_imt_pd_dim.ccal_pd_id
LEFT JOIN CIRD_OWNER.CCY_DIM SEC_CCY_DIM ON APA.STM_BASE_ISO_CCY_CODE = SEC_CCY_DIM.CCY_CD AND apa.stm_base_iso_ccy_code = sec_ccy_dim.ccy_cd
LEFT JOIN COMMON_OWNER.ACG_TP_DIM ACG_TP_DIM ON APA.ACG_TP_ID = ACG_TP_DIM.ACG_TP_ID AND apa.ACG_TP_ID = acg_tp_dim.ACG_TP_ID
LEFT JOIN CCSI_OWNER.AR_DIM OFST_AR_DIM ON APA.OFST_AR_ID = OFST_AR_DIM.AR_ID AND apa.OFST_AR_ID = ofst_ar_dim.AR_ID
LEFT JOIN CCAL_REPL_OWNER.CL_VAL ASSET_PACKAGE_TYPE ON APA.APA_TP_ID = ASSET_PACKAGE_TYPE.CL_VAL_ID AND apa.APA_TP_ID = asset_package_type.CL_VAL_ID
LEFT JOIN CCAL_REPL_OWNER.CL_VAL DEBIT_CREDIT_TYPES ON APA.DB_CR_ID = DEBIT_CREDIT_TYPES.CL_VAL_ID AND apa.db_cr_id = debit_credit_types.cl_val_id AND debit_credit_types.cl_val_id = apa.db_cr_id
LEFT JOIN COMMON_OWNER.CASH_POS_TP_DIM CASH_POS_TP_DIM ON APA.CASH_POS_TP_ID = CASH_POS_TP_DIM.CASH_POS_TP_ID AND apa.CASH_POS_TP_ID = cash_pos_tp_dim.CASH_POS_TP_ID
LEFT JOIN CCAL_REPL_OWNER.CL_VAL SALE_CHARGE_RATE_TYPE ON APA.SALE_CHRG_RATE_TP_ID = SALE_CHARGE_RATE_TYPE.CL_VAL_ID AND sale_charge_rate_type.cl_val_id = apa.sale_chrg_rate_tp_id
LEFT JOIN CCAL_REPL_OWNER.CCAL_CIRD_PD_MAP CCAL_CIRD_PD_MAP ON APA.PD_ID = CCAL_CIRD_PD_MAP.CCAL_PD_ID AND apa.pd_id = ccal_cird_pd_map.ccal_pd_id AND ccal_cird_pd_map.ccal_pd_id = apa.pd_id AND ap.pd_id = ccal_cird_pd_map.ccal_pd_id
LEFT JOIN CIRD_OWNER.IMT_PD_DIM IMT_PD_DIM ON CCAL_CIRD_PD_MAP.CIRD_PD_ID = IMT_PD_DIM.CIRD_PD_ID AND ccal_cird_pd_map.cird_pd_id = imt_pd_dim.cird_pd_id
LEFT JOIN CIRD_OWNER.CCY_DIM CCY_DIM ON APA.TXN_ISO_CCY_CODE = CCY_DIM.CCY_CD AND ccy_dim.ccy_cd = apa.txn_iso_ccy_code
LEFT JOIN CCAL_REPL_OWNER.FIP FIP ON APA.APA_ID = FIP.APA_ID
LEFT JOIN CCAL_REPL_OWNER.NNA_CGY NNA_CGY ON TXN_AVY_CL.NNA_CGY_ID = NNA_CGY.NNA_CGY_ID
LEFT JOIN REFERENCE_REPL_OWNER.CCY CCY ON APA.ORIG_CCY_ID = CCY.CCY_ISO_NUM_CODE AND apa.orig_ccy_id = ccy.CCY_ISO_NUM_CODE AND apa.txn_iso_ccy_code = ccy.CCY_CODE
LEFT JOIN CCAL_REPL_OWNER.CL_VAL TRANSACTION_TYPE ON TXN.TXN_TP_ID = TRANSACTION_TYPE.CL_VAL_ID AND transaction_type.cl_val_id = t.txn_tp_id
LEFT JOIN CCAL_REPL_OWNER.CL_VAL TRANSACTION_SUBTYPE ON TXN.TXN_SBTP_ID = TRANSACTION_SUBTYPE.CL_VAL_ID AND transaction_subtype.cl_val_id = t.txn_sbtp_id
LEFT JOIN CCAL_REPL_OWNER.CL_VAL EXECUTION_SUBTYPE ON TXN.EXEC_SBTP_ID = EXECUTION_SUBTYPE.CL_VAL_ID AND t.EXEC_SBTP_ID = execution_subtype.CL_VAL_ID
LEFT JOIN CCAL_REPL_OWNER.CL_VAL EXECUTION_TYPE ON TXN.EXEC_TP_ID = EXECUTION_TYPE.CL_VAL_ID AND t.EXEC_TP_ID = execution_type.CL_VAL_ID
LEFT JOIN COMMON_OWNER.DATE_DIM TD_DATE_DIM ON TXN.TD= TD_DATE_DIM.CAL_DT AND t.td = td_date_dim.cal_dt
LEFT JOIN COMMON_OWNER.DATE_DIM SD_DATE_DIM ON TXN.SD = SD_DATE_DIM.CAL_DT
LEFT JOIN COMMON_OWNER.SRC_STM_DIM SRC_STM_DIM ON TXN.SRC_STM_ID = SRC_STM_DIM.SRC_STM_ID AND src_stm_dim.src_stm_id = t.src_stm_id AND t.src_stm_id = src_stm_dim.src_stm_id
LEFT JOIN SSDS_TRANSACTIONS_OWNER.TRD_SLCT_TP_DIM TRD_SLCT_TP_DIM ON TXN.TRD_SLCT_TP_ID = TRD_SLCT_TP_DIM.TRD_SLCT_TP_ID
LEFT JOIN SSDS_TRANSACTIONS_OWNER.SRC_ENTR_CNL_TP_DIM SRC_ENTR_CNL_TP_DIM ON TXN.SRC_ENTR_CNL_TP_ID = SRC_ENTR_CNL_TP_DIM.SRC_ENTR_CNL_TP_ID
LEFT JOIN SSDS_TRANSACTIONS_OWNER.SRC_PCS_TP_DIM SRC_PCS_TP_DIM ON TXN.SRC_PCS_TP_ID = SRC_PCS_TP_DIM.SRC_PCS_TP_ID
LEFT JOIN SSDS_TRANSACTIONS_OWNER.LGCY_TRD_CPCTY_TP_DIM LGCY_TRD_CPCTY_TP_DIM ON TXN.LGCY_TRD_CPCTY_TP_ID = LGCY_TRD_CPCTY_TP_DIM.LGCY_TRD_CPCTY_TP_ID
LEFT JOIN SSDS_TRANSACTIONS_OWNER.LGCY_MKT_TP_DIM LGCY_MKT_TP_DIM ON TXN.LGCY_MKT_TP_ID = LGCY_MKT_TP_DIM.LGCY_MKT_TP_ID
LEFT JOIN SSDS_TRANSACTIONS_OWNER.LGCY_CNCL_CMPLN_SRC_TP_DIM LGCY_CNCL_CMPLN_SRC_TP_DIM ON TXN.LGCY_CNCL_CMPLN_SRC_TP_ID = LGCY_CNCL_CMPLN_SRC_TP_DIM.LGCY_CNCL_CMPLN_SRC_TP_ID
LEFT JOIN SSDS_TRANSACTIONS_OWNER.LGCY_CNCL_CMPLN_RSN_TP_DIM LGCY_CNCL_CMPLN_RSN_TP_DIM ON TXN.LGCY_CNCL_CMPLN_RSN_TP_ID = LGCY_CNCL_CMPLN_RSN_TP_DIM.LGCY_CNCL_CMPLN_RSN_TP_ID
LEFT JOIN CIRD_OWNER.EXG_DIM EXG_DIM ON TXN.EXG_CODE = EXG_DIM.EXG_CD AND exg_dim.EXG_CD = t.exg_code
LEFT JOIN CCAL_REPL_OWNER.TXN_RLTNP TXN_RLTNP ON TXN.TXN_ID = TXN_RLTNP.SRC_TXN_ID AND t.txn_id = txn_rltnp.src_txn_id
LEFT JOIN CCAL_REPL_OWNER.CL_VAL CD_CL_VAL ON TXN.DOL_IND_ID = CD_CL_VAL.CL_VAL_ID AND t.dol_ind_id = cd_cl_val.cl_val_id
LEFT JOIN CCAL_REPL_OWNER.CL_VAL OMS_EXEC_TP ON TXN.OMS_EXEC_TP_ID = OMS_EXEC_TP.CL_VAL_ID AND oms_exec_tp.cl_val_id = t.oms_exec_tp_id
LEFT JOIN COMMON_OWNER.SRC_STM_DIM ORIG_SRC_STM_DIM ON TXN.ORIG_SRC_STM_ID =ORIG_SRC_STM_DIM.SRC_STM_ID
LEFT JOIN CCAL_REPL_OWNER.TXN TXN_RLTNP_TXN ON TXN_RLTNP.TRGT_TXN_ID = TXN_RLTNP_TXN.TXN_ID
LEFT JOIN CCAL_REPL_OWNER.ACATS_BROKER ACATS_BROKER ON TXN.ORIG_SRC_STM_CODE = ACATS_BROKER.BROKER_ID AND b.broker_id = t.orig_src_stm_code AND acats_broker.broker_id = t.orig_src_stm_code
LEFT JOIN CCAL_REPL_OWNER.CL_VAL SIS_DLTD_EV ON TXN.SRC_BUY_SELL_MULTI_ID = SIS_DLTD_EV.CL_VAL_ID AND sis_dltd_ev.cl_val_id = t.SRC_BUY_SELL_MULTI_ID
LEFT JOIN CCAL_REPL_OWNER.CL_VAL SRC_CNCL_RSN ON TXN.SRC_CNCL_RSN_ID = SRC_CNCL_RSN.CL_VAL_ID AND cl_val.cl_val_id = t.SRC_CNCL_RSN_ID
LEFT JOIN CCAL_REPL_OWNER.CL_VAL TXN_RCNCL_ST ON TXN.TXN_ST_ID = TXN_RCNCL_ST.CL_VAL_ID AND txn_rcncl_st.cl_val_id = t.txn_st_id
LEFT JOIN CCAL_REPL_OWNER.CL_VAL REL_TXN_RLTNP_TP ON TXN_RLTNP.TXN_RLTNP_TP_ID = REL_TXN_RLTNP_TP.CL_VAL_ID AND cl_val_id = txn_rltnp.TXN_RLTNP_TP_ID
LEFT JOIN COMMON_OWNER.SRC_STM_DIM TXN_RLTNP_SRC_STM_DIM ON TXN_RLTNP_TXN.SRC_STM_ID = TXN_RLTNP_SRC_STM_DIM.SRC_STM_ID
LEFT JOIN CCAL_REPL_OWNER.SHDW_TXN_TP SHDW_TXN_TP ON TXN.SRC_TXN_TP = SHDW_TXN_TP.SRC_TXN_TP
LEFT JOIN REFERENCE_REPL_OWNER.IMPCT_ACTION_LKU IMPCT_ACTION_LKU ON TXN.SRC_ACTN_CODE = IMPCT_ACTION_LKU.ACTION_CODE
LEFT JOIN CCSI_OWNER.AR_GRP_SUBDIM AR_GRP_SUBDIM ON TXN.AR_ID = AR_GRP_SUBDIM.AR_ID AND ar_grp_subdim.AR_ID = t.AR_ID AND t.AR_ID = ar_grp_subdim.AR_ID AND ar_grp_subdim.ar_id = t.ar_id
LEFT JOIN CCSI_OWNER.AR_DIM AR_DIM ON TXN.AR_ID = AR_DIM.AR_ID AND ar_dim.AR_ID = t.AR_ID AND t.ar_id = ar_dim.ar_id
LEFT JOIN CCSI_OWNER.AR_AC_SUBDIM AR_AC_SUBDIM ON TXN.AR_ID = AR_AC_SUBDIM.AR_ID AND APA_CASH.AC_ID = AR_AC_SUBDIM.DEP_AC_SETUP_ID AND ar_ac_subdim.ar_id = t.ar_id AND ar_ac_subdim.dep_ac_setup_id = apa.ac_id
LEFT JOIN CCAL_REPL_OWNER.CL_VAL IMPACT_TRD_LGCY_TRD_CPCTY_TP_DIM ON TXN.LGCY_TRD_CPCTY_TP_ID = IMPACT_TRD_LGCY_TRD_CPCTY_TP_DIM.CL_VAL_ID AND impact_trd_lgcy_trd_cpcty_tp_dim.cl_val_id = t.lgcy_trd_cpcty_tp_id
LEFT JOIN CCAL_REPL_OWNER.CL_VAL DRVD_TRD_CPCTY ON TXN.DRVD_TRD_CPCTY_TP_ID = DRVD_TRD_CPCTY.CL_VAL_ID
LEFT JOIN CCAL_REPL_OWNER.TXN_RLTNP TXN_RLTNP1 ON TXN.TXN_ID = TXN_RLTNP1.TRGT_TXN_ID
LEFT JOIN CCAL_REPL_OWNER.TXN_SRC_TAX_CODE_LKUP TXN_SRC_TAX_CODE_LKUP ON TXN.SRC_TAX_CODE_ID = TXN_SRC_TAX_CODE_LKUP.SRC_TAX_CODE_ID
LEFT JOIN SSDS_DAL_OWNER.FA_NUMBER_V FA_NUMBER_V ON AR_GRP_SUBDIM.FA_NUM = FA_NUMBER_V.FA_NUMBER AND AVY_FACT_STEP3_STG_RT.OWN_FA_NUM = FA_NUMBER_V.FA_NUMBER AND fa_number_v.FA_NUMBER = OWN_FA_NUM AND fa_number_v.responsible_party_employee_id = fa_number_v.responsible_party_employee_id AND AR_GRP_SUBDIM.FA_NUM = fa_number_v.FA_NUMBER
LEFT JOIN SSDS_DAL_OWNER.CODE_SET_VALUE_V CODE_SET_VALUE_V ON FA_NUMBER_V.FA_NUMBER_TYPE_CODE_ID = CODE_SET_VALUE_V.CODE_VALUE_ID AND code_set_value_v.CODE_VALUE_ID = fa_number_v.FA_NUMBER_TYPE_CODE_ID
LEFT JOIN SSDS_DAL_OWNER.ENTERPRISE_ENTITY_DIM_V ENTERPRISE_ENTITY_DIM_V ON FA_NUMBER_V.FA_NUMBER_ENTITY_CODE = ENTERPRISE_ENTITY_DIM_V.ENTITY_CODE_LONG AND enterprise_entity_dim_v.Entity_code_long = OWN_FA_NUM_ENT_CD AND enterprise_entity_dim_v.entity_code_long = fa_number_v.fa_number_entity_code
LEFT JOIN CCSI_OWNER.AR_DIM BKR_AR_DIM ON AVY_FACT_STEP3_STG_RT.BKR_AR_ID = BKR_AR_DIM.AR_ID
LEFT JOIN CCSI_REPL_OWNER.AR_DIM ad2 ON ad2.AR_ID = apa.OFST_AR_ID
LEFT JOIN TRANSACTIONS_OWNER.LGCY_CNCL_CMPLN_RSN_TP_DIM lccrtd ON lccrtd.lgcy_cncl_cmpln_rsn_tp_id = t.lgcy_cncl_cmpln_rsn_tp_id
LEFT JOIN TRANSACTIONS_OWNER.LGCY_CNCL_CMPLN_SRC_TP_DIM lccstd ON lccstd.lgcy_cncl_cmpln_src_tp_id = t.lgcy_cncl_cmpln_src_tp_id
LEFT JOIN TRANSACTIONS_OWNER.LGCY_MKT_TP_DIM lmtd ON lmtd.lgcy_mkt_tp_id = t.lgcy_mkt_tp_id
LEFT JOIN TRANSACTIONS_OWNER.LGCY_TRD_CPCTY_TP_DIM ltctd2 ON t.lgcy_trd_cpcty_tp_id = ltctd2.lgcy_trd_cpcty_tp_id
LEFT JOIN TRANSACTIONS_OWNER.SRC_PCS_TP_DIM sptd ON t.src_pcs_tp_id = sptd.src_pcs_tp_id
LEFT JOIN TRANSACTIONS_OWNER.SRC_ENTR_CNL_TP_DIM sectd ON t.src_entr_cnl_tp_id = sectd.src_entr_cnl_tp_id
LEFT JOIN TRANSACTIONS_OWNER.TRD_SLCT_TP_DIM tstd ON t.trd_slct_tp_id = tstd.trd_slct_tp_id
LEFT JOIN CCAL_REPL_OWNER.SRC_STM_DIM ssd ON t.src_stm_id = ssd.src_stm_id
LEFT JOIN COMMON_OWNER.DT_DIM dd ON t.sd = dd.cal_dt
LEFT JOIN CCAL_REPL_OWNER.AR_DIM ad ON t.AR_ID = ad.AR_ID
LEFT JOIN CCAL_REPL_OWNER.J$TXN jt ON jt.txn_id = t.txn_id
LEFT JOIN CCAL_REPL_OWNER.IMPCT_ACTION_LKU ial ON t.src_actn_code = impct_action_lku.action_code
LEFT JOIN CCSI_OWNER.AR_DIM ar__bkr ON ar_grp_subdim.linked_bkr_ar_id = ar__bkr.ar_id
LEFT JOIN CCSI_OWNER.AR_DIM ar__bkr2 ON ar_grp_subdim.linked_bkr_ar_id = ar__bkr2.ar_id
LEFT JOIN CCSI_OWNER.AR_DIM ar__bkr3 ON ar_grp_subdim.linked_bkr_ar_id = ar__bkr3.ar_id
LEFT JOIN CCSI_OWNER.AR_DIM ar__bkr4 ON ar_grp_subdim.linked_bkr_ar_id = ar__bkr4.ar_id
LEFT JOIN CCSI_OWNER.AR_DIM ar__bkr5 ON ar_grp_subdim.linked_bkr_ar_id = ar__bkr5.ar_id
LEFT JOIN CCSI_OWNER.AR_DIM ar__bkr6 ON ar_grp_subdim.linked_bkr_ar_id = ar__bkr6.ar_id
LEFT JOIN CCSI_OWNER.AR_DIM ar__bkr7 ON ar_grp_subdim.linked_bkr_ar_id = ar__bkr7.ar_id
LEFT JOIN CCSI_OWNER.AR_DIM ar__bkr8 ON ar_grp_subdim.linked_bkr_ar_id = ar__bkr8.ar_id
LEFT JOIN CCSI_OWNER.AR_DIM ar__bkr9 ON ar_grp_subdim.linked_bkr_ar_id = ar__bkr9.ar_id
LEFT JOIN CCSI_OWNER.AR_DIM ar__bkr10 ON ar_grp_subdim.linked_bkr_ar_id = ar__bkr10.ar_id
LEFT JOIN CCSI_OWNER.AR_DIM ar__bkr11 ON ar_grp_subdim.linked_bkr_ar_id = ar__bkr11.ar_id
LEFT JOIN CCSI_OWNER.AR_DIM ar__bkr12 ON ar_grp_subdim.linked_bkr_ar_id = ar__bkr12.ar_id
LEFT JOIN CCSI_OWNER.AR_DIM ar__bkr13 ON ar_grp_subdim.linked_bkr_ar_id = ar__bkr13.ar_id
LEFT JOIN CCSI_OWNER.AR_DIM ar__bkr14 ON ar_grp_subdim.linked_bkr_ar_id = ar__bkr14.ar_id
LEFT JOIN CCSI_OWNER.AR_DIM ar__bkr15 ON ar_grp_subdim.linked_bkr_ar_id = ar__bkr15.ar_id
LEFT JOIN CCSI_OWNER.AR_DIM ar__bkr16 ON ar_grp_subdim.linked_bkr_ar_id = ar__bkr16.ar_id
LEFT JOIN CCSI_OWNER.AR_DIM ar__bkr17 ON ar_grp_subdim.linked_bkr_ar_id = ar__bkr17.ar_id
LEFT JOIN CCSI_OWNER.AR_DIM ar__bkr18 ON ar_grp_subdim.linked_bkr_ar_id = ar__bkr18.ar_id
LEFT JOIN CCSI_OWNER.AR_DIM ar__bkr19 ON ar_grp_subdim.linked_bkr_ar_id = ar__bkr19.ar_id
LEFT JOIN CCSI_OWNER.AR_DIM ar__bkr20 ON ar_grp_subdim.linked_bkr_ar_id = ar__bkr20.ar_id
LEFT JOIN CCSI_OWNER.AR_DIM ar__bkr21 ON ar_grp_subdim.linked_bkr_ar_id = ar__bkr21.ar_id
LEFT JOIN CCSI_OWNER.AR_DIM ar__own ON ar_grp_subdim.linked_bkr_ar_id = ar__own.ar_id
LEFT JOIN CCSI_OWNER.AR_DIM ar__own2 ON ar_grp_subdim.linked_bkr_ar_id = ar__own2.ar_id
LEFT JOIN SSDS_DAL_OWNER.PERSON_RV pr ON pr.EMPLOYEE_ID = fa_number_v.responsible_party_employee_id
LEFT JOIN CCSI_OWNER.AR_DIM ar__own3 ON ar_grp_subdim.linked_bkr_ar_id = ar__own3.ar_id
LEFT JOIN SSDS_DAL_OWNER.PERSON_BROKERAGE_SUBDIMENSION_V pbsv ON brk_own_psn_brk.EMPLOYEE_ID = fa_number_v.responsible_party_employee_id
LEFT JOIN CCSI_OWNER.AR_DIM ar__own4 ON ar_grp_subdim.linked_bkr_ar_id = ar__own4.ar_id
LEFT JOIN CCSI_OWNER.AR_DIM ar__own5 ON ar_grp_subdim.linked_bkr_ar_id = ar__own5.ar_id
LEFT JOIN SSDS_DAL_OWNER.PERSON_AMS_DISCRETIONARY_STATUS_V padsv ON padsv.EMPLOYEE_ID = fa_number_v.responsible_party_employee_id
LEFT JOIN CCSI_OWNER.AR_DIM ar__own6 ON ar_grp_subdim.linked_bkr_ar_id = ar__own6.ar_id
LEFT JOIN CCSI_OWNER.AR_DIM ar__own7 ON ar_grp_subdim.linked_bkr_ar_id = ar__own7.ar_id
LEFT JOIN CCSI_OWNER.AR_DIM ar__own8 ON ar_grp_subdim.linked_bkr_ar_id = ar__own8.ar_id
LEFT JOIN CCSI_OWNER.AR_DIM ar__own9 ON ar_grp_subdim.linked_bkr_ar_id = ar__own9.ar_id
LEFT JOIN CCSI_OWNER.AR_DIM ar__own10 ON ar_grp_subdim.linked_bkr_ar_id = ar__own10.ar_id
LEFT JOIN CCSI_OWNER.AR_DIM ar__own11 ON ar_grp_subdim.linked_bkr_ar_id = ar__own11.ar_id
LEFT JOIN CCSI_OWNER.AR_DIM ar__own12 ON ar_grp_subdim.linked_bkr_ar_id = ar__own12.ar_id
LEFT JOIN CCSI_OWNER.AR_DIM ar__own13 ON ar_grp_subdim.linked_bkr_ar_id = ar__own13.ar_id
LEFT JOIN CCSI_OWNER.AR_DIM ar__own14 ON ar_grp_subdim.linked_bkr_ar_id = ar__own14.ar_id
LEFT JOIN CCSI_OWNER.AR_DIM ar__own15 ON ar_grp_subdim.linked_bkr_ar_id = ar__own15.ar_id
LEFT JOIN CCSI_OWNER.AR_DIM ar__own16 ON ar_grp_subdim.linked_bkr_ar_id = ar__own16.ar_id
LEFT JOIN CCSI_OWNER.AR_DIM ar__own17 ON ar_grp_subdim.linked_bkr_ar_id = ar__own17.ar_id
LEFT JOIN CCSI_OWNER.AR_DIM ar__own18 ON ar_grp_subdim.linked_bkr_ar_id = ar__own18.ar_id
LEFT JOIN CCSI_OWNER.AR_DIM ar__own19 ON ar_grp_subdim.linked_bkr_ar_id = ar__own19.ar_id
LEFT JOIN SSDS_DAL_OWNER.ENTERPRISE_ENTITY_RETAIL_DIMENSION_V eerdv ON eerdv.entity_enterprise_id = enterprise_entity_dim_v.entity_enterprise_id
LEFT JOIN CCSI_OWNER.AR_DIM ar__own20 ON ar_grp_subdim.linked_bkr_ar_id = ar__own20.ar_id
LEFT JOIN CCSI_OWNER.AR_DIM ar__own21 ON ar_grp_subdim.linked_bkr_ar_id = ar__own21.ar_id
LEFT JOIN CCSI_OWNER.AR_DIM ar__own22 ON ar_grp_subdim.linked_bkr_ar_id = ar__own22.ar_id
LEFT JOIN CCSI_OWNER.AR_DIM ar__own23 ON ar_grp_subdim.linked_bkr_ar_id = ar__own23.ar_id
LEFT JOIN CCSI_OWNER.AR_DIM ar__own24 ON ar_grp_subdim.linked_bkr_ar_id = ar__own24.ar_id
LEFT JOIN CCSI_OWNER.AR_DIM ar__own25 ON ar_grp_subdim.linked_bkr_ar_id = ar__own25.ar_id
LEFT JOIN CCSI_OWNER.AR_DIM ar__own26 ON ar_grp_subdim.linked_bkr_ar_id = ar__own26.ar_id
LEFT JOIN CCSI_OWNER.AR_DIM ar__own27 ON ar_grp_subdim.linked_bkr_ar_id = ar__own27.ar_id
LEFT JOIN CCSI_OWNER.AR_DIM ar__own28 ON ar_grp_subdim.linked_bkr_ar_id = ar__own28.ar_id
LEFT JOIN CCSI_OWNER.AR_DIM ar__own29 ON ar_grp_subdim.linked_bkr_ar_id = ar__own29.ar_id
LEFT JOIN CCSI_OWNER.AR_DIM ar__own30 ON ar_grp_subdim.linked_bkr_ar_id = ar__own30.ar_id
LEFT JOIN SSDS_DAL_OWNER.ENTERPRISE_ENTITY_RISK_DIMENSION_V eerdv2 ON enterprise_entity_dim_v.entity_enterprise_id = eerdv2.entity_enterprise_id
LEFT JOIN CCSI_OWNER.AR_DIM ar__own31 ON ar_grp_subdim.linked_bkr_ar_id = ar__own31.ar_id
LEFT JOIN CCSI_OWNER.AR_DIM ar__own32 ON ar_grp_subdim.linked_bkr_ar_id = ar__own32.ar_id
LEFT JOIN CCSI_OWNER.AR_DIM ar__own33 ON ar_grp_subdim.linked_bkr_ar_id = ar__own33.ar_id
LEFT JOIN CCSI_OWNER.AR_DIM ar__own34 ON ar_grp_subdim.linked_bkr_ar_id = ar__own34.ar_id
LEFT JOIN CCSI_OWNER.AR_DIM ar__own35 ON ar_grp_subdim.linked_bkr_ar_id = ar__own35.ar_id
LEFT JOIN CCSI_OWNER.AR_DIM ar__own36 ON ar_grp_subdim.linked_bkr_ar_id = ar__own36.ar_id
LEFT JOIN CCSI_OWNER.AR_DIM ar__own37 ON ar_grp_subdim.linked_bkr_ar_id = ar__own37.ar_id
LEFT JOIN CCSI_OWNER.AR_DIM ar__own38 ON ar_grp_subdim.linked_bkr_ar_id = ar__own38.ar_id
LEFT JOIN CCSI_OWNER.AR_DIM ar__own39 ON ar_grp_subdim.linked_bkr_ar_id = ar__own39.ar_id
LEFT JOIN CCSI_OWNER.AR_DIM ar__own40 ON ar_grp_subdim.linked_bkr_ar_id = ar__own40.ar_id
LEFT JOIN CCSI_OWNER.AR_DIM ar__own41 ON ar_grp_subdim.linked_bkr_ar_id = ar__own41.ar_id
LEFT JOIN CCSI_OWNER.AR_DIM ar__own42 ON ar_grp_subdim.linked_bkr_ar_id = ar__own42.ar_id
LEFT JOIN CCSI_OWNER.AR_DIM ar__own43 ON ar_grp_subdim.linked_bkr_ar_id = ar__own43.ar_id
LEFT JOIN CCSI_OWNER.AR_DIM ar__own44 ON ar_grp_subdim.linked_bkr_ar_id = ar__own44.ar_id
LEFT JOIN CCSI_OWNER.AR_DIM ar__own45 ON ar_grp_subdim.linked_bkr_ar_id = ar__own45.ar_id
LEFT JOIN CCSI_OWNER.AR_DIM ar__own46 ON ar_grp_subdim.linked_bkr_ar_id = ar__own46.ar_id
LEFT JOIN CCSI_OWNER.AR_DIM ar__own47 ON ar_grp_subdim.linked_bkr_ar_id = ar__own47.ar_id
LEFT JOIN CIRD_OWNER.IMT_PD_DIM imt_eqty ON ap.pd_id = imt_eqty.cird_pd_id
LEFT JOIN CIRD_OWNER.IMT_PD_DIM imt_eqty2 ON ap.pd_id = imt_eqty2.cird_pd_id
LEFT JOIN CIRD_OWNER.IMT_PD_DIM imt_eqty3 ON ap.pd_id = imt_eqty3.cird_pd_id
LEFT JOIN CIRD_OWNER.IMT_PD_DIM imt_eqty4 ON ap.pd_id = imt_eqty4.cird_pd_id
LEFT JOIN CIRD_OWNER.IMT_PD_DIM imt_eqty5 ON ap.pd_id = imt_eqty5.cird_pd_id
LEFT JOIN CIRD_OWNER.IMT_PD_DIM imt_eqty6 ON ap.pd_id = imt_eqty6.cird_pd_id
LEFT JOIN CIRD_OWNER.IMT_PD_DIM imt_eqty7 ON ap.pd_id = imt_eqty7.cird_pd_id
LEFT JOIN CIRD_OWNER.IMT_PD_DIM imt_eqty8 ON ap.pd_id = imt_eqty8.cird_pd_id
LEFT JOIN CIRD_OWNER.IMT_PD_DIM imt_modl ON ap.pd_id = imt_modl.cird_pd_id
LEFT JOIN CIRD_OWNER.IMT_PD_DIM imt_modl2 ON ap.pd_id = imt_modl2.cird_pd_id
LEFT JOIN CIRD_OWNER.IMT_PD_DIM imt_modl3 ON ap.pd_id = imt_modl3.cird_pd_id
LEFT JOIN CIRD_OWNER.IMT_PD_DIM imt_modl4 ON ap.pd_id = imt_modl4.cird_pd_id
LEFT JOIN CIRD_OWNER.IMT_PD_DIM imt_pd ON ap.pd_id = imt_pd.cird_pd_id
LEFT JOIN CIRD_OWNER.IMT_PD_DIM imt_pd2 ON ap.pd_id = imt_pd2.cird_pd_id
LEFT JOIN CIRD_OWNER.IMT_PD_DIM imt_rpt ON ap.pd_id = imt_rpt.cird_pd_id
LEFT JOIN CIRD_OWNER.IMT_PD_DIM imt_rpt2 ON ap.pd_id = imt_rpt2.cird_pd_id
LEFT JOIN CIRD_OWNER.IMT_PD_DIM imt_rpt3 ON ap.pd_id = imt_rpt3.cird_pd_id
LEFT JOIN CIRD_OWNER.IMT_PD_DIM imt_rpt4 ON ap.pd_id = imt_rpt4.cird_pd_id
LEFT JOIN CIRD_OWNER.IMT_PD_DIM imt_rpt5 ON ap.pd_id = imt_rpt5.cird_pd_id
LEFT JOIN CIRD_OWNER.IMT_PD_DIM imt_rpt6 ON ap.pd_id = imt_rpt6.cird_pd_id
LEFT JOIN CIRD_OWNER.IMT_PD_DIM imt_fnd ON ap.pd_id = imt_fnd.cird_pd_id
LEFT JOIN CIRD_OWNER.IMT_PD_DIM imt_shr ON ap.pd_id = imt_shr.cird_pd_id
LEFT JOIN CIRD_OWNER.IMT_PD_DIM imt_shr2 ON ap.pd_id = imt_shr2.cird_pd_id
LEFT JOIN CIRD_OWNER.IMT_PD_DIM imt_imt ON ap.pd_id = imt_imt.cird_pd_id
LEFT JOIN CIRD_OWNER.IMT_PD_DIM imt_imt2 ON ap.pd_id = imt_imt2.cird_pd_id
LEFT JOIN CIRD_OWNER.IMT_PD_DIM imt_imt3 ON ap.pd_id = imt_imt3.cird_pd_id
LEFT JOIN CIRD_OWNER.IMT_PD_DIM imt_imt4 ON ap.pd_id = imt_imt4.cird_pd_id
LEFT JOIN CIRD_OWNER.IMT_PD_DIM imt_imt5 ON ap.pd_id = imt_imt5.cird_pd_id
LEFT JOIN CIRD_OWNER.IMT_PD_DIM imt_imt6 ON ap.pd_id = imt_imt6.cird_pd_id
LEFT JOIN CIRD_OWNER.IMT_PD_DIM imt_imt7 ON ap.pd_id = imt_imt7.cird_pd_id
LEFT JOIN CIRD_OWNER.IMT_PD_DIM imt_imt8 ON ap.pd_id = imt_imt8.cird_pd_id
LEFT JOIN CIRD_OWNER.IMT_PD_DIM imt_imt9 ON ap.pd_id = imt_imt9.cird_pd_id
LEFT JOIN CIRD_OWNER.IMT_PD_DIM imt_imt10 ON ap.pd_id = imt_imt10.cird_pd_id;
