#!/usr/bin/env python3
"""
generate_independent_reports.py

v16.6.5 Excel workbook report generator.

Always creates one real Excel workbook:

  independent_reports/independent_reports.xlsx

Workbook tabs:
  1. Summary
  2. DRD vs ODI File 1
  3. DRD vs ODI File 2
  4. DRD vs ODI1 vs ODI2
  5. ODI1 vs ODI2 Columns
  6. ODI1 vs ODI2 SQL Blocks

No CSV files are generated by default.
"""

from __future__ import annotations

import argparse
import csv
import json
import re
from collections import Counter
from pathlib import Path
from typing import Dict, List, Sequence


REPORT_COLUMNS_DRD_ODI = [
    "Area / Columns",
    "Conclusion",
    "Difference Type",
    "Mapping Logic",
    "ODI XML Logic",
    "Recommended Action",
]

REPORT_COLUMNS_THREE_WAY = [
    "Area / Columns",
    "Conclusion",
    "Difference Type",
    "DRD Mapping Logic",
    "ODI File 1 XML Logic",
    "ODI File 2 XML Logic",
    "Recommended Action",
]

REPORT_COLUMNS_ODI_ODI = [
    "Area / Columns",
    "Conclusion",
    "Difference Type",
    "DRD Mapping Logic",
    "ODI File 1 XML Logic",
    "ODI File 2 XML Logic",
    "Recommended Action",
]


def clean(x) -> str:
    return (x or "").replace("\r\n", "\n").replace("\r", "\n").strip()


def short_text(x: str, limit: int = 12000) -> str:
    s = clean(x)
    return s if len(s) <= limit else s[:limit - 40] + "\n...[truncated]..."


def read_csv(path: Path) -> List[Dict[str, str]]:
    if not path.exists():
        return []
    with path.open(newline="", encoding="utf-8-sig") as f:
        return list(csv.DictReader(f))


def parse_area_columns(area: str) -> List[str]:
    area = clean(area)
    cols = re.findall(r"`([^`]+)`", area)
    if not cols and re.fullmatch(r"[A-Z0-9_#$]+", area):
        cols = [area]
    return [c.strip().upper() for c in cols if c.strip()]


def build_drd_logic_map(rows: Sequence[Dict[str, str]]) -> Dict[str, str]:
    out: Dict[str, str] = {}
    for r in rows:
        area = clean(r.get("Area / Columns", ""))
        logic = clean(r.get("Mapping Logic", "") or r.get("DRD Mapping Logic", ""))
        if not area or not logic:
            continue
        for col in parse_area_columns(area):
            out[col] = logic
    return out


def independent_conclusion(row: Dict[str, str]) -> str:
    conclusion = clean(row.get("Conclusion", ""))
    diff = clean(row.get("Difference Type", ""))
    area = clean(row.get("Area / Columns", ""))

    if "missing" in diff.lower() or "not present" in conclusion.lower():
        return "Mismatch. Mapping logic is not implemented in the ODI XML final/resolved lineage."
    if "source drift" in diff.lower():
        return "Review required. ODI source or lineage differs from the mapping rule."
    if "case" in diff.lower():
        return "Review required. CASE/transformation logic differs from the mapping rule."
    if "structural" in diff.lower() or "column count" in diff.lower() or "final target" in area.lower():
        return "Review required. Structural target-load behavior differs from the mapping contract."
    return "Review required. ODI XML logic should be validated against the mapping rule."


def recommended_action(row: Dict[str, str]) -> str:
    diff = clean(row.get("Difference Type", ""))
    if "missing" in diff.lower():
        return "Implement the required mapping logic in ODI or document an approved exception."
    if "source drift" in diff.lower():
        return "Validate source lineage against the mapping rule. Update ODI or document an approved exception."
    if "structural" in diff.lower() or "column count" in diff.lower():
        return "Validate target-load contract and column list. Update ODI/DRD or document an approved exception."
    return "Review and approve, or update ODI to match the mapping rule."


def normalize_drd_vs_odi_rows(rows: Sequence[Dict[str, str]]) -> List[Dict[str, str]]:
    out: List[Dict[str, str]] = []
    for r in rows:
        area = clean(r.get("Area / Columns", ""))
        if not area:
            continue
        out.append({
            "Area / Columns": area,
            "Conclusion": independent_conclusion(r),
            "Difference Type": clean(r.get("Difference Type", "")),
            "Mapping Logic": clean(r.get("Mapping Logic", "")),
            "ODI XML Logic": clean(r.get("ODI XML Logic", "")),
            "Recommended Action": recommended_action(r),
        })
    return out


def statuses_for_area(area: str, delta_by_col: Dict[str, Dict[str, str]]) -> List[str]:
    statuses = []
    for col in parse_area_columns(area):
        if col in delta_by_col:
            statuses.append(clean(delta_by_col[col].get("delta_status", "")))
    return statuses


def status_label_for_area(area: str, delta_by_col: Dict[str, Dict[str, str]]) -> str:
    statuses = statuses_for_area(area, delta_by_col)
    if not statuses:
        return ""
    uniq = list(dict.fromkeys(statuses))
    if len(uniq) == 1:
        return uniq[0]
    return "MIXED: " + " | ".join(uniq)


def filter_file2_rows(rows: Sequence[Dict[str, str]], delta_rows: Sequence[Dict[str, str]]) -> List[Dict[str, str]]:
    """
    Standalone File 2 report:
    omit rows whose all columns were proven equivalent/no-active-mismatch for File 2.
    Keep still-open, candidates, structural/grouped rows.
    """
    delta_by_col = {clean(r.get("target_column", "")).upper(): r for r in delta_rows if clean(r.get("target_column", ""))}
    omit_statuses = {"FIXED_BY_RESOLVED_RULE_PROOF", "UNCHANGED_NO_ACTIVE_MISMATCH_BY_V16_6"}
    kept = []
    for r in rows:
        cols = parse_area_columns(r.get("Area / Columns", ""))
        statuses = statuses_for_area(r.get("Area / Columns", ""), delta_by_col)
        if cols and statuses and all(s in omit_statuses for s in statuses):
            continue
        kept.append(r)
    return kept


def three_way_conclusion(area: str, delta_by_col: Dict[str, Dict[str, str]]) -> str:
    statuses = statuses_for_area(area, delta_by_col)
    status_set = set(statuses)
    if not statuses:
        return "Review required. This grouped/structural item cannot be resolved to a single target-column delta."
    if status_set <= {"FIXED_BY_RESOLVED_RULE_PROOF", "UNCHANGED_NO_ACTIVE_MISMATCH_BY_V16_6"}:
        return "ODI File 2 appears aligned for this mapping item; ODI File 1 shows a difference against the mapping."
    if "STILL_OPEN" in status_set:
        return "Still open. ODI File 2 still does not fully implement this mapping item."
    if "FIX_CANDIDATE_UPSTREAM_CHANGED" in status_set:
        return "Review required. ODI File 2 has related upstream changes, but equivalence to the mapping rule is not fully proven."
    return "Review required. Compare DRD logic against both ODI implementations."


def three_way_difference_type(area: str, original_row: Dict[str, str], delta_by_col: Dict[str, Dict[str, str]]) -> str:
    base = clean(original_row.get("Difference Type", ""))
    label = status_label_for_area(area, delta_by_col)
    return f"{base} | {label}" if label else base


def three_way_action(area: str, delta_by_col: Dict[str, Dict[str, str]]) -> str:
    statuses = statuses_for_area(area, delta_by_col)
    status_set = set(statuses)
    if not statuses:
        return "Manually validate structural/grouped behavior against both ODI files and the DRD mapping."
    if status_set <= {"FIXED_BY_RESOLVED_RULE_PROOF", "UNCHANGED_NO_ACTIVE_MISMATCH_BY_V16_6"}:
        return "Use ODI File 2 behavior as the candidate implementation; keep File 1 as historical comparison evidence."
    if "STILL_OPEN" in status_set:
        return "Update ODI File 2 or document an approved exception."
    if "FIX_CANDIDATE_UPSTREAM_CHANGED" in status_set:
        return "Manually validate File 2 upstream logic against the DRD rule; if equivalent, mark accepted."
    return "Review and approve the intended ODI implementation."


def build_three_way_report(original_rows: Sequence[Dict[str, str]], fixed_rows: Sequence[Dict[str, str]], delta_rows: Sequence[Dict[str, str]]) -> List[Dict[str, str]]:
    fixed_by_area = {clean(r.get("Area / Columns", "")): r for r in fixed_rows}
    delta_by_col = {clean(r.get("target_column", "")).upper(): r for r in delta_rows if clean(r.get("target_column", ""))}
    out = []
    for r in original_rows:
        area = clean(r.get("Area / Columns", ""))
        if not area:
            continue
        fixed = fixed_by_area.get(area, {})
        out.append({
            "Area / Columns": area,
            "Conclusion": three_way_conclusion(area, delta_by_col),
            "Difference Type": three_way_difference_type(area, r, delta_by_col),
            "DRD Mapping Logic": clean(r.get("Mapping Logic", "")),
            "ODI File 1 XML Logic": clean(r.get("ODI XML Logic", "")),
            "ODI File 2 XML Logic": clean(fixed.get("ODI XML Logic", "")),
            "Recommended Action": three_way_action(area, delta_by_col),
        })
    return out


def odi_column_conclusion(status: str) -> str:
    if status == "CHANGED":
        return "Different ODI implementation detected for the same target column."
    if status == "ADDED_IN_FIXED":
        return "Column exists in ODI File 2 but not in ODI File 1."
    if status == "REMOVED_IN_FIXED":
        return "Column exists in ODI File 1 but not in ODI File 2."
    if status == "NO_RESOLVED_LINEAGE":
        return "Resolved lineage was not available for one or both ODI files."
    return "No difference detected."


def odi_sql_conclusion(status: str) -> str:
    if status == "CHANGED":
        return "SQL block differs between ODI File 1 and ODI File 2."
    if status == "ADDED_IN_FIXED":
        return "SQL block exists in ODI File 2 but not in ODI File 1."
    if status == "REMOVED_IN_FIXED":
        return "SQL block exists in ODI File 1 but not in ODI File 2."
    return "No difference detected."


def odi_action(status: str) -> str:
    if status in {"CHANGED", "ADDED_IN_FIXED", "REMOVED_IN_FIXED", "NO_RESOLVED_LINEAGE"}:
        return "Review whether this ODI change is expected. Validate target output impact and document approval."
    return "No action."


def build_odi_vs_odi_columns(rows: Sequence[Dict[str, str]], drd_logic_by_col: Dict[str, str]) -> List[Dict[str, str]]:
    out = []
    for r in rows:
        status = clean(r.get("xml_delta_status", ""))
        if status == "UNCHANGED":
            continue
        col = clean(r.get("target_column", ""))
        old_parts, new_parts = [], []
        if r.get("original_final_expression"):
            old_parts.append("Final expression:\n" + clean(r.get("original_final_expression")))
        if r.get("original_resolved_expression"):
            old_parts.append("Resolved expression:\n" + clean(r.get("original_resolved_expression")))
        if r.get("original_lineage_path"):
            old_parts.append("Lineage path:\n" + clean(r.get("original_lineage_path")))
        if r.get("fixed_final_expression"):
            new_parts.append("Final expression:\n" + clean(r.get("fixed_final_expression")))
        if r.get("fixed_resolved_expression"):
            new_parts.append("Resolved expression:\n" + clean(r.get("fixed_resolved_expression")))
        if r.get("fixed_lineage_path"):
            new_parts.append("Lineage path:\n" + clean(r.get("fixed_lineage_path")))
        out.append({
            "Area / Columns": col,
            "Conclusion": odi_column_conclusion(status),
            "Difference Type": "Resolved multi-step lineage " + status.lower().replace("_", " "),
            "DRD Mapping Logic": drd_logic_by_col.get(col.upper(), ""),
            "ODI File 1 XML Logic": short_text("\n\n".join(old_parts)),
            "ODI File 2 XML Logic": short_text("\n\n".join(new_parts)),
            "Recommended Action": odi_action(status),
        })
    return out


def build_odi_vs_odi_sql(rows: Sequence[Dict[str, str]]) -> List[Dict[str, str]]:
    out = []
    for r in rows:
        status = clean(r.get("sql_delta_status", ""))
        if status == "UNCHANGED":
            continue
        area = f"Step {r.get('step_no','')} / Task {r.get('task_no','')}"
        if r.get("task_name"):
            area += f" / {r.get('task_name')}"
        out.append({
            "Area / Columns": clean(area),
            "Conclusion": odi_sql_conclusion(status),
            "Difference Type": "SQL block " + status.lower().replace("_", " "),
            "DRD Mapping Logic": "Not applicable: SQL block-level ODI1 vs ODI2 comparison.",
            "ODI File 1 XML Logic": short_text(r.get("original_sql_excerpt", ""), 12000),
            "ODI File 2 XML Logic": short_text(r.get("fixed_sql_excerpt", ""), 12000),
            "Recommended Action": odi_action(status),
        })
    return out


def create_xlsx(path: Path, report1, report2, report3, report4, report5, summary: Dict[str, object]) -> None:
    from openpyxl import Workbook
    from openpyxl.styles import Alignment, Border, Font, PatternFill, Side
    from openpyxl.utils import get_column_letter
    from openpyxl.worksheet.table import Table, TableStyleInfo

    wb = Workbook()
    ws = wb.active
    ws.title = "Summary"

    summary_rows = [
        ["Mode", "v16.6.5 Excel workbook independent reports"],
        ["DRD vs ODI File 1 rows", len(report1)],
        ["DRD vs ODI File 2 rows", len(report2)],
        ["DRD vs ODI1 vs ODI2 rows", len(report3)],
        ["ODI1 vs ODI2 column rows", len(report4)],
        ["ODI1 vs ODI2 SQL block rows", len(report5)],
        ["Column lineage status counts", json.dumps(summary.get("column_lineage_status_counts", {}), ensure_ascii=False)],
        ["SQL block status counts", json.dumps(summary.get("sql_block_status_counts", {}), ensure_ascii=False)],
        ["Note", "Generated automatically by compare_drd_odi_v16_6_generic_rule_proof.py"],
    ]

    ws.append(["Metric", "Value"])
    for row in summary_rows:
        ws.append(row)

    dark_fill = PatternFill("solid", fgColor="1F4E78")
    header_fill = PatternFill("solid", fgColor="D9EAF7")
    thin = Side(style="thin", color="D9E2F3")

    for cell in ws[1]:
        cell.fill = dark_fill
        cell.font = Font(bold=True, color="FFFFFF")
        cell.alignment = Alignment(horizontal="center", vertical="center", wrap_text=True)
    for row in ws.iter_rows():
        for cell in row:
            cell.alignment = Alignment(vertical="top", wrap_text=True)
            cell.border = Border(left=thin, right=thin, top=thin, bottom=thin)
    ws.column_dimensions["A"].width = 38
    ws.column_dimensions["B"].width = 112

    def write_sheet(name: str, rows: Sequence[Dict[str, str]], headers: Sequence[str], widths: Sequence[int]) -> None:
        sh = wb.create_sheet(name)
        sh.append(list(headers))
        for r in rows:
            sh.append([r.get(h, "") for h in headers])
        for cell in sh[1]:
            cell.fill = header_fill
            cell.font = Font(bold=True)
            cell.alignment = Alignment(horizontal="center", vertical="center", wrap_text=True)
        for row in sh.iter_rows():
            for cell in row:
                cell.alignment = Alignment(vertical="top", wrap_text=True)
                cell.border = Border(left=thin, right=thin, top=thin, bottom=thin)
        for i, width in enumerate(widths, start=1):
            sh.column_dimensions[get_column_letter(i)].width = width
        sh.freeze_panes = "A2"
        sh.row_dimensions[1].height = 30
        for idx in range(2, min(len(rows) + 2, 302)):
            sh.row_dimensions[idx].height = 105
        if rows:
            ref = f"A1:{get_column_letter(len(headers))}{len(rows) + 1}"
            table_name = re.sub(r"[^A-Za-z0-9_]", "_", name)[:20] + "_T"
            tab = Table(displayName=table_name, ref=ref)
            tab.tableStyleInfo = TableStyleInfo(name="TableStyleMedium2", showRowStripes=True, showColumnStripes=False)
            sh.add_table(tab)

    write_sheet("DRD vs ODI File 1", report1, REPORT_COLUMNS_DRD_ODI, [30, 44, 34, 78, 98, 54])
    write_sheet("DRD vs ODI File 2", report2, REPORT_COLUMNS_DRD_ODI, [30, 44, 34, 78, 98, 54])
    write_sheet("DRD vs ODI1 vs ODI2", report3, REPORT_COLUMNS_THREE_WAY, [30, 44, 40, 78, 98, 98, 54])
    write_sheet("ODI1 vs ODI2 Columns", report4, REPORT_COLUMNS_ODI_ODI, [30, 44, 34, 78, 98, 98, 54])
    write_sheet("ODI1 vs ODI2 SQL Blocks", report5, REPORT_COLUMNS_ODI_ODI, [30, 44, 34, 78, 98, 98, 54])

    wb.save(path)


def generate_reports(out_dir: Path) -> Dict[str, object]:
    original_rows = read_csv(out_dir / "original_v15_mismatch_rows.csv")
    fixed_rows = read_csv(out_dir / "fixed_v15_mismatch_rows.csv")
    delta_rows = read_csv(out_dir / "delta_report_v16_6_generic_rule_proof.csv")
    if not delta_rows:
        delta_rows = read_csv(out_dir / "delta_report_fixed_still_open_regression.csv")
    resolved_delta_rows = read_csv(out_dir / "original_vs_fixed_resolved_xml_delta.csv")
    sql_delta_rows = read_csv(out_dir / "sql_block_differences.csv")

    reports_dir = out_dir / "independent_reports"
    reports_dir.mkdir(parents=True, exist_ok=True)

    report1 = normalize_drd_vs_odi_rows(original_rows)
    report2 = normalize_drd_vs_odi_rows(filter_file2_rows(fixed_rows, delta_rows))
    report3 = build_three_way_report(original_rows, fixed_rows, delta_rows)
    drd_logic_by_col = build_drd_logic_map(original_rows + fixed_rows)
    report4 = build_odi_vs_odi_columns(resolved_delta_rows, drd_logic_by_col)
    report5 = build_odi_vs_odi_sql(sql_delta_rows)

    summary = {
        "mode": "v16.6.5 Excel workbook independent reports",
        "drd_vs_odi_file_1_rows": len(report1),
        "drd_vs_odi_file_2_rows": len(report2),
        "drd_vs_odi1_vs_odi2_rows": len(report3),
        "odi1_vs_odi2_column_rows": len(report4),
        "odi1_vs_odi2_sql_block_rows": len(report5),
        "column_lineage_status_counts": dict(Counter(r.get("xml_delta_status", "") for r in resolved_delta_rows)),
        "sql_block_status_counts": dict(Counter(r.get("sql_delta_status", "") for r in sql_delta_rows)),
        "excel_file": "independent_reports.xlsx",
    }

    create_xlsx(reports_dir / "independent_reports.xlsx", report1, report2, report3, report4, report5, summary)
    (reports_dir / "summary.json").write_text(json.dumps(summary, indent=2, ensure_ascii=False), encoding="utf-8")
    return summary


def main(argv=None) -> int:
    p = argparse.ArgumentParser(description="Generate v16.6.5 Excel independent reports from a compare output directory")
    p.add_argument("--out-dir", required=True)
    args = p.parse_args(argv)
    summary = generate_reports(Path(args.out_dir).expanduser().resolve())
    print(json.dumps(summary, indent=2, ensure_ascii=False))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
