#!/usr/bin/env python3
"""
api_report_builder.py

Builds API-friendly JSON reports from the Excel workbooks generated by the
DRD/ODI/INSERT full-cycle flow.

The API representation mirrors workbook tabs and is intended for downstream
tools, dashboards, CI gates, and lightweight HTTP serving.

Outputs:
  final_reports/api/
    manifest.json
    openapi_contract.json
    step1_compare_report.json
    step4_full_cycle_report.json
    step1/tabs/*.json
    step4/tabs/*.json
"""
from __future__ import annotations

import argparse
import json
import re
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Dict, List, Sequence


def clean_name(name: str) -> str:
    s = re.sub(r"[^A-Za-z0-9_]+", "_", name.strip()).strip("_")
    return s or "sheet"


def cell_value(v):
    if v is None:
        return ""
    return v


def workbook_to_payload(xlsx_path: Path, report_id: str, report_type: str, metadata: Dict[str, Any] | None = None) -> Dict[str, Any]:
    try:
        from openpyxl import load_workbook
    except Exception as exc:
        raise RuntimeError("openpyxl is required for API report generation. Install with: pip install openpyxl") from exc

    wb = load_workbook(xlsx_path, read_only=True, data_only=True)
    tabs = []
    for ws in wb.worksheets:
        rows = list(ws.iter_rows(values_only=True))
        if not rows:
            tabs.append({
                "name": ws.title,
                "safe_name": clean_name(ws.title),
                "headers": [],
                "rows": [],
                "row_count": 0,
                "column_count": 0,
            })
            continue
        # First non-empty row is treated as header. This matches our generated workbooks.
        header_idx = 0
        for idx, row in enumerate(rows):
            if any(cell is not None and str(cell).strip() for cell in row):
                header_idx = idx
                break
        headers = [str(cell_value(c)).strip() if str(cell_value(c)).strip() else f"column_{i+1}" for i, c in enumerate(rows[header_idx])]
        data_rows = []
        for row in rows[header_idx + 1:]:
            if not any(cell is not None and str(cell).strip() for cell in row):
                continue
            # Pad/truncate to header length
            values = list(row[:len(headers)]) + [None] * max(0, len(headers) - len(row))
            data_rows.append({headers[i]: cell_value(values[i]) for i in range(len(headers))})
        tabs.append({
            "name": ws.title,
            "safe_name": clean_name(ws.title),
            "headers": headers,
            "rows": data_rows,
            "row_count": len(data_rows),
            "column_count": len(headers),
        })

    return {
        "report_id": report_id,
        "report_type": report_type,
        "source_workbook": str(xlsx_path),
        "generated_at_utc": datetime.now(timezone.utc).isoformat(),
        "metadata": metadata or {},
        "tab_count": len(tabs),
        "tabs": tabs,
    }


def write_json(path: Path, payload: Any) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(payload, indent=2, ensure_ascii=False), encoding="utf-8")


def write_tab_files(api_dir: Path, phase: str, payload: Dict[str, Any]) -> List[str]:
    files = []
    tab_dir = api_dir / phase / "tabs"
    tab_dir.mkdir(parents=True, exist_ok=True)
    for tab in payload.get("tabs", []):
        tab_payload = {
            "report_id": payload.get("report_id"),
            "report_type": payload.get("report_type"),
            "phase": phase,
            "tab": tab,
        }
        p = tab_dir / f"{tab['safe_name']}.json"
        write_json(p, tab_payload)
        files.append(str(p))
    return files


def read_json_if_exists(path: Path) -> Any:
    if path.exists():
        try:
            return json.loads(path.read_text(encoding="utf-8"))
        except Exception:
            return {"_error": f"Failed to parse {path}"}
    return None


def build_openapi_contract() -> Dict[str, Any]:
    return {
        "openapi": "3.0.3",
        "info": {
            "title": "DRD/ODI/Generated INSERT Full-Cycle Report API",
            "version": "17.5",
        },
        "paths": {
            "/manifest": {"get": {"summary": "Get API report manifest"}},
            "/step1": {"get": {"summary": "Get Step 1 DRD/ODI compare report"}},
            "/step1/tabs/{tab}": {"get": {"summary": "Get a Step 1 tab by safe tab name"}},
            "/step4": {"get": {"summary": "Get Step 4 full-cycle report"}},
            "/step4/tabs/{tab}": {"get": {"summary": "Get a Step 4 tab by safe tab name"}},
            "/health": {"get": {"summary": "Health check"}},
        },
        "components": {
            "schemas": {
                "Report": {
                    "type": "object",
                    "properties": {
                        "report_id": {"type": "string"},
                        "report_type": {"type": "string"},
                        "metadata": {"type": "object"},
                        "tabs": {"type": "array"},
                    },
                }
            }
        },
    }


def build_api_reports(
    api_dir: Path,
    step1_workbook: Path | None = None,
    step4_workbook: Path | None = None,
    compare_out: Path | None = None,
    insert_out: Path | None = None,
    final_dir: Path | None = None,
    mode: str = "both",
) -> Dict[str, Any]:
    api_dir.mkdir(parents=True, exist_ok=True)
    generated_files: List[str] = []

    common_meta: Dict[str, Any] = {
        "version": "17.5",
        "report_mode": mode,
        "compare_out": str(compare_out) if compare_out else "",
        "insert_out": str(insert_out) if insert_out else "",
        "final_dir": str(final_dir) if final_dir else "",
    }

    if insert_out:
        common_meta["insert_final_consistency_summary"] = read_json_if_exists(insert_out / "final_consistency_summary.json")
        common_meta["insert_hardcode_gate_report"] = read_json_if_exists(insert_out / "hardcode_gate_report.json")

    step1_payload = None
    step4_payload = None
    if step1_workbook and step1_workbook.exists():
        step1_payload = workbook_to_payload(
            step1_workbook,
            report_id="step1_compare_report",
            report_type="DRD/ODI comparison",
            metadata=common_meta,
        )
        p = api_dir / "step1_compare_report.json"
        write_json(p, step1_payload)
        generated_files.append(str(p))
        generated_files.extend(write_tab_files(api_dir, "step1", step1_payload))

    if step4_workbook and step4_workbook.exists():
        step4_meta = dict(common_meta)
        if final_dir:
            step4_meta["full_cycle_summary"] = read_json_if_exists(final_dir / "full_cycle_summary.json")
        step4_payload = workbook_to_payload(
            step4_workbook,
            report_id="step4_full_cycle_report",
            report_type="DRD/ODI/generated INSERT full-cycle comparison",
            metadata=step4_meta,
        )
        p = api_dir / "step4_full_cycle_report.json"
        write_json(p, step4_payload)
        generated_files.append(str(p))
        generated_files.extend(write_tab_files(api_dir, "step4", step4_payload))

    contract = build_openapi_contract()
    write_json(api_dir / "openapi_contract.json", contract)
    generated_files.append(str(api_dir / "openapi_contract.json"))

    manifest = {
        "version": "17.5",
        "report_mode": mode,
        "generated_at_utc": datetime.now(timezone.utc).isoformat(),
        "api_dir": str(api_dir),
        "reports": {
            "step1": {
                "json": str(api_dir / "step1_compare_report.json") if step1_payload else "",
                "tab_count": step1_payload.get("tab_count") if step1_payload else 0,
                "tabs": [t["safe_name"] for t in step1_payload.get("tabs", [])] if step1_payload else [],
            },
            "step4": {
                "json": str(api_dir / "step4_full_cycle_report.json") if step4_payload else "",
                "tab_count": step4_payload.get("tab_count") if step4_payload else 0,
                "tabs": [t["safe_name"] for t in step4_payload.get("tabs", [])] if step4_payload else [],
            },
        },
        "openapi_contract": str(api_dir / "openapi_contract.json"),
        "generated_files": generated_files,
    }
    write_json(api_dir / "manifest.json", manifest)
    return manifest


def main(argv=None) -> int:
    p = argparse.ArgumentParser(description="Build API JSON reports from full-cycle Excel workbooks")
    p.add_argument("--api-dir", required=True)
    p.add_argument("--step1-workbook", default="")
    p.add_argument("--step4-workbook", default="")
    p.add_argument("--compare-out", default="")
    p.add_argument("--insert-out", default="")
    p.add_argument("--final-dir", default="")
    p.add_argument("--mode", default="both")
    args = p.parse_args(argv)

    manifest = build_api_reports(
        api_dir=Path(args.api_dir).expanduser().resolve(),
        step1_workbook=Path(args.step1_workbook).expanduser().resolve() if args.step1_workbook else None,
        step4_workbook=Path(args.step4_workbook).expanduser().resolve() if args.step4_workbook else None,
        compare_out=Path(args.compare_out).expanduser().resolve() if args.compare_out else None,
        insert_out=Path(args.insert_out).expanduser().resolve() if args.insert_out else None,
        final_dir=Path(args.final_dir).expanduser().resolve() if args.final_dir else None,
        mode=args.mode,
    )
    print(json.dumps(manifest, indent=2, ensure_ascii=False))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
