"""Generate proper per-attribute test suites using DRD flow result data."""
import json
import urllib.request
import os
import sys

BASE = "http://127.0.0.1:8550/api/tests"
DRD_PATH = r"H:\Documents\DRD_Activity_Fact.xlsx"
DRD_RESULT_PATH = r"C:\GIT_Repo\db-testing-tool\data\drd_flow_result.json"

def post_json(path, data):
    body = json.dumps(data).encode()
    req = urllib.request.Request(f"{BASE}{path}", data=body, headers={"Content-Type": "application/json"}, method="POST")
    with urllib.request.urlopen(req, timeout=120) as resp:
        return json.loads(resp.read())


# Step 1: Load DRD flow result (already generated by orchestrator)
print("Step 1: Loading DRD orchestrator result...")
with open(DRD_RESULT_PATH, encoding="utf-8") as f:
    drd_result = json.load(f)

plan = drd_result.get("plan", {})
sql_data = drd_result.get("sql", {})
cte_sql = sql_data.get("cte", "") or ""
insert_sql = sql_data.get("insert_select", "") or ""
source_select = sql_data.get("source_select", "") or ""
primary_source = plan.get("primary_source", [])
joins = plan.get("joins", [])
unresolved = plan.get("unresolved", [])

print(f"  Primary source: {'.'.join(primary_source)}")
print(f"  Joins: {len(joins)}")
print(f"  CTE SQL: {len(cte_sql)} chars")
print(f"  INSERT SQL: {len(insert_sql)} chars")

# Step 2: Parse DRD directly to get column mappings
print("\nStep 2: Parsing DRD for column mappings...")
sys.path.insert(0, r"C:\GIT_Repo\db-testing-tool")
from app.services.drd_import_service import parse_drd_file

with open(DRD_PATH, "rb") as f:
    drd_bytes = f.read()

parse_result = parse_drd_file(
    file_bytes=drd_bytes,
    filename="DRD_Activity_Fact.xlsx",
    selected_fields=["logical_name", "physical_name", "source_schema", "source_table", "source_attribute", "transformation", "notes"],
    target_schema="TRANSACTIONS_OWNER",
    target_table="AVY_FACT",
    source_datasource_id=2,
    target_datasource_id=3,
)

column_mappings = parse_result.get("column_mappings", [])
print(f"  Column mappings: {len(column_mappings)}")
if column_mappings:
    print(f"  Sample keys: {list(column_mappings[0].keys())[:8]}")

# Build analysis_rows from column_mappings
analysis_rows = []
for cm in column_mappings:
    col = (cm.get("physical_name") or "").strip().upper()
    if not col:
        continue
    analysis_rows.append({
        "column": col,
        "physical_name": col,
        "source_schema": (cm.get("source_schema") or "").strip().upper(),
        "source_table": (cm.get("source_table") or "").strip().upper(),
        "source_attribute": (cm.get("source_attribute") or "").strip().upper(),
        "transformation": (cm.get("transformation") or "").strip(),
        "generated_expression": "",  # will be derived from SQL
    })

print(f"  Analysis rows built: {len(analysis_rows)}")

# Step 3: Delete old summary tests
print("\nStep 3: Removing old summary tests (IDs 590-613)...")
for tid in range(590, 614):
    try:
        req = urllib.request.Request(f"{BASE}/{tid}", method="DELETE")
        urllib.request.urlopen(req)
    except Exception:
        pass
print("  Done")

# Step 4: Generate CT_TEST
print("\nStep 4: Generating CT_TEST per-attribute suite...")
payload = {
    "analysis_rows": analysis_rows,
    "generated_sql": cte_sql,  # Use CTE mode for CT
    "target_schema": "TRANSACTIONS_OWNER",
    "target_table": "AVY_FACT",
    "source_datasource_id": 2,
    "target_datasource_id": 3,
    "pbi_id": "PBI2674782",
    "suite_prefix": "CT",
    "folder_name": "CT_TEST",
    "grain_columns": ["TXN_ID"],
}
ct_suite = post_json("/control-table/generate-attribute-tests", payload)
print(f"  Created {ct_suite['count']} tests in folder '{ct_suite['folder_name']}' (ID {ct_suite['folder_id']})")

# Step 5: Generate DRD_TEST
print("\nStep 5: Generating DRD_TEST per-attribute suite...")
payload["suite_prefix"] = "DRD"
payload["folder_name"] = "DRD_TEST"
payload["generated_sql"] = insert_sql  # Use INSERT mode for DRD
drd_suite = post_json("/control-table/generate-attribute-tests", payload)
print(f"  Created {drd_suite['count']} tests in folder '{drd_suite['folder_name']}' (ID {drd_suite['folder_id']})")

# Step 6: Generate CHAT_TEST
print("\nStep 6: Generating CHAT_TEST per-attribute suite...")
payload["suite_prefix"] = "CHAT"
payload["folder_name"] = "CHAT_TEST"
payload["generated_sql"] = source_select or cte_sql  # Use source_select for Chat
chat_suite = post_json("/control-table/generate-attribute-tests", payload)
print(f"  Created {chat_suite['count']} tests in folder '{chat_suite['folder_name']}' (ID {chat_suite['folder_id']})")

# Summary
print(f"\n{'='*60}")
print(f"DONE - Per-Attribute Test Suites Generated (PBI2674782)")
print(f"{'='*60}")
print(f"CT_TEST:   {ct_suite['count']} tests (folder {ct_suite['folder_id']})")
print(f"DRD_TEST:  {drd_suite['count']} tests (folder {drd_suite['folder_id']})")
print(f"CHAT_TEST: {chat_suite['count']} tests (folder {chat_suite['folder_id']})")
print(f"Total:     {ct_suite['count'] + drd_suite['count'] + chat_suite['count']} attribute-level tests")

# Save summary
summary = {
    "ct_suite": ct_suite,
    "drd_suite": drd_suite,
    "chat_suite": chat_suite,
}
with open(os.path.join(os.path.dirname(__file__), "..", "data", "attribute_test_suites_summary.json"), "w") as f:
    json.dump(summary, f, indent=2, default=str)
print("\nSummary saved to data/attribute_test_suites_summary.json")
print("\nStep 3: Generating CT_TEST per-attribute suite...")
payload = {
    "analysis_rows": analysis_rows,
    "generated_sql": generated_sql,
    "target_schema": "TRANSACTIONS_OWNER",
    "target_table": "AVY_FACT",
    "source_datasource_id": 2,
    "target_datasource_id": 3,
    "pbi_id": "PBI2674782",
    "suite_prefix": "CT",
    "folder_name": "CT_TEST",
    "grain_columns": ["TXN_ID"],
}
ct_suite = post_json("/control-table/generate-attribute-tests", payload)
print(f"  Created {ct_suite['count']} tests in folder '{ct_suite['folder_name']}' (ID {ct_suite['folder_id']})")

# Step 4: Generate DRD_TEST per-attribute suite
print("\nStep 4: Generating DRD_TEST per-attribute suite...")
payload["suite_prefix"] = "DRD"
payload["folder_name"] = "DRD_TEST"
drd_suite = post_json("/control-table/generate-attribute-tests", payload)
print(f"  Created {drd_suite['count']} tests in folder '{drd_suite['folder_name']}' (ID {drd_suite['folder_id']})")

# Step 5: Generate CHAT_TEST per-attribute suite
print("\nStep 5: Generating CHAT_TEST per-attribute suite...")
payload["suite_prefix"] = "CHAT"
payload["folder_name"] = "CHAT_TEST"
chat_suite = post_json("/control-table/generate-attribute-tests", payload)
print(f"  Created {chat_suite['count']} tests in folder '{chat_suite['folder_name']}' (ID {chat_suite['folder_id']})")

# Summary
print(f"\n{'='*60}")
print(f"DONE - Per-Attribute Test Suites Generated (PBI2674782)")
print(f"{'='*60}")
print(f"CT_TEST:   {ct_suite['count']} tests (folder {ct_suite['folder_id']})")
print(f"DRD_TEST:  {drd_suite['count']} tests (folder {drd_suite['folder_id']})")
print(f"CHAT_TEST: {chat_suite['count']} tests (folder {chat_suite['folder_id']})")
print(f"Total:     {ct_suite['count'] + drd_suite['count'] + chat_suite['count']} attribute-level tests")

# Save summary
summary = {
    "ct_suite": ct_suite,
    "drd_suite": drd_suite,
    "chat_suite": chat_suite,
}
with open(os.path.join(os.path.dirname(__file__), "data", "attribute_test_suites_summary.json"), "w") as f:
    json.dump(summary, f, indent=2)
print("\nSummary saved to data/attribute_test_suites_summary.json")
