-- Generated by comparator_driven_emitter v2 (DRD-driven; ODI verifies)
-- Source per row: DRD source_table.source_attribute (NOT ODI staging).
-- Operator-locked architecture (2026-05-30 Phase 7.6).
-- DRD declares 83 target columns;
-- 79 MATCHED/ALIAS_DRIFT (DRD verified by ODI);
-- 0 REAL_MISMATCH (DRD used; ODI divergent);
-- 2 UNRESOLVABLE (DRD used; ODI complex);
-- 0 SOURCE_MISSING (DRD used; ODI gap);
-- 3 RECOVERED_FROM_PROSE (DRD prose; ODI's SQL realization projected with marker);
-- 4 ODI_HELPER_FILL (DRD silent; ODI's self-contained value projected as helper to match ODI + avoid NULL);
-- 0 RECOVERED_FROM_PROSE_UNRUNNABLE (DRD prose; ODI expr refs staging alias not in FROM; NULL'd to stay runnable);
-- 0 COMPLEX_DRD_EXPRESSION (DRD prose; no ODI expr available; NULL'd);
-- 2 NULL total (no DRD source or prose-only DRD);
-- 0 NOT NULL constraint risk;
-- 1 JOIN clauses auto-derived from DRD;
-- 6 JOIN clauses need operator-supplied ON predicate.

INSERT INTO IKOROSTELEV.CLS_TAX_LOTS_NON_BKR_FACT (
    ACG_TP_CD,
    ACG_TP_ID,
    ACG_TP_NM,
    ACQ_DT,
    ADJ_COST,
    ADJ_COST_GAIN_LOSS,
    ADJ_COST_GAIN_LOSS_PCT,
    ADJ_COST_NOT_ACRT_F,
    AR_ID,
    CCAL_PD_ID,
    CCY_CD,
    CIRD_PD_ID,
    CLS_DT,
    CLS_PRC_FCTR,
    CLS_TXN_EV_TP,
    COST_AMT,
    COST_BSS_LEGS_CVR_CD,
    CTF_NUM,
    CTF_NUM_PFX,
    DISALWD_WASH_SALE_AMT,
    DSPN_DT,
    DSPN_PRC,
    DSPN_PROCD,
    DSPN_MTH_CD,
    EXG_RATE,
    FAIR_MKT_VAL_OF_GIFT_OR_INHTN,
    GAIN_LOSS_AMT,
    GIFT_DT,
    LIFE_TO_DTD_MKT_DCN,
    LONG_SHRT_POS_CD,
    LOSS_NOT_ALWD_F,
    MISS_COST_BSS_F,
    OPN_AMT,
    OPN_PRC_FCTR,
    OPN_TXN_EV_TP,
    ORIG_EV_TP,
    ORIG_PRC,
    ORIG_PROCD,
    ORIG_TXN_TP_CD,
    POS_INCPTN_DT,
    PREM_AMT,
    QTY,
    RLZD_CLS_F,
    RLZD_PROCD_AMT,
    RVST_LOT_F,
    SBC_ADJ_COST,
    SBC_CLS_PRC_FCTR,
    SBC_COST_AMT,
    SBC_DISALWD_WASH_SALE_AMT,
    SBC_FAIR_MKT_VAL,
    SBC_OPN_PRC_FCTR,
    SBC_ORIG_PRC,
    SBC_ORIG_PROCD,
    SBC_UC,
    SD,
    SRC_RCRD_TP_CD,
    SRC_STM_CD,
    SRC_STM_ID,
    SRC_STM_NM,
    TAX_LOT_EXT_REFR_KEY_PRIM,
    TAX_LOT_EXT_REFR_KEY_QTRNY,
    TAX_LOT_EXT_REFR_KEY_SCDY,
    TAX_LOT_EXT_REFR_KEY_TRTY,
    TRD_NUM,
    TXN_INTT_DT,
    TXN_TP_CD,
    UC,
    WASH_SALE_F,
    WASH_SALE_TP,
    ZERO_COST_BSS_F,
    OPN_DT,
    ADJ_COST_GAIN_AMT,
    ADJ_COST_LOSS_AMT,
    TERM_TP_CD,
    MISS_ADJ_COST_F,
    IRS_1099B_REPORTABLE_F,
    POS_CLS_TP,
    SESN_NUM,
    CRT_DTM,
    CRT_USR_NM,
    LAST_UDT_DTM,
    LAST_UDT_USR_NM
)
SELECT
    t.ACG_TP_CODE                 AS ACG_TP_CD,  -- [MATCHED] DRD source verified against ODI (ODI projects CLOSE_TAX_LOT_NONBKR_RJTRUST_TGT.ACG_TP_CODE)
    acg_tp_dim.ACG_TP_ID          AS ACG_TP_ID,  -- [MATCHED] DRD source verified against ODI (ODI projects ACG_TP_DIM.ACG_TP_ID)
    acg_tp_dim.ACG_TP_DSC         AS ACG_TP_NM,  -- [MATCHED] DRD source verified against ODI (ODI projects ACG_TP_DIM.ACG_TP_DSC)
    t.TD                          AS ACQ_DT,  -- [MATCHED] DRD source verified against ODI (ODI projects CLOSE_TAX_LOT_NONBKR_RJTRUST_TGT.TD)
    t.SBC_OPN_ADJ_COST_AMT        AS ADJ_COST,  -- [MATCHED] DRD source verified against ODI (ODI projects .SBC_OPN_ADJ_COST_AMT)
    t.ADJCOSTGAINLOSSAMT          AS ADJ_COST_GAIN_LOSS,  -- [MATCHED] DRD source verified against ODI (ODI projects CLOSE_TAX_LOT_NONBKR_RJTRUST_TGT.ADJCOSTGAINLOSSAMT)
    t.ADJCOSTGAINLOSSPCT          AS ADJ_COST_GAIN_LOSS_PCT,  -- [MATCHED] DRD source verified against ODI (ODI projects CLOSE_TAX_LOT_NONBKR_RJTRUST_TGT.ADJCOSTGAINLOSSPCT)
    (NULL)                        AS ADJ_COST_NOT_ACRT_F,  -- [RECOVERED_FROM_PROSE] DRD wrote intent as English: 'NULL'; comparator MATCHED ODI's SQL realization: 'NULL'.  All alias prefixes resolve in our FROM graph.
    t.AR_ID                       AS AR_ID,  -- [MATCHED] DRD source verified against ODI (ODI projects CLOSE_TAX_LOT_NONBKR_RJTRUST_TGT.AR_ID)
    NULL,  -- [DB_RESOLVED_NULL] SUB_LOT_MSTR.CCAL_PD_ID (table absent on DB) is not a column of its table (DB-confirmed) for CCAL_PD_ID; NULL'd to run -- operator: map to the correct source column.
    t.NML_ISO_CCY_CODE            AS CCY_CD,  -- [MATCHED] DRD source verified against ODI (ODI projects CLOSE_TAX_LOT_NONBKR_RJTRUST_TGT.NML_ISO_CCY_CODE)
    ccal_cird_pd_map.CIRD_PD_ID   AS CIRD_PD_ID,  -- [MATCHED] DRD source verified against ODI (ODI projects CCAL_CIRD_PD_MAP_1.CIRD_PD_ID)
    t.CLSDT                       AS CLS_DT,  -- [MATCHED] DRD source verified against ODI (ODI projects CLOSE_TAX_LOT_NONBKR_RJTRUST_TGT.CLSDT)
    t.SBC_CLS_PRC_FCTR            AS CLS_PRC_FCTR,  -- [MATCHED] DRD source verified against ODI (ODI projects CLOSE_TAX_LOT_NONBKR_RJTRUST_TGT.SBC_CLS_PRC_FCTR)
    cl_val.CL_VAL_NM              AS CLS_TXN_EV_TP,  -- [MATCHED] DRD source verified against ODI (ODI projects CL_VAL3_1.CL_VAL_NM)
    t.NML_CCY_OPN_COST_AMT        AS COST_AMT,  -- [MATCHED] DRD source verified against ODI (ODI projects .NML_CCY_OPN_COST_AMT)
    t.ISCOVERED                   AS COST_BSS_LEGS_CVR_CD,  -- [MATCHED] DRD source verified against ODI (ODI projects CLOSE_TAX_LOT_NONBKR_RJTRUST_TGT.ISCOVERED)
    t.TAX_LOT_CTF_NUM             AS CTF_NUM,  -- [MATCHED] DRD source verified against ODI (ODI projects CLOSE_TAX_LOT_NONBKR_RJTRUST_TGT.TAX_LOT_CTF_NUM)
    t.TAX_LOT_CTF_NUM_PFX         AS CTF_NUM_PFX,  -- [MATCHED] DRD source verified against ODI (ODI projects CLOSE_TAX_LOT_NONBKR_RJTRUST_TGT.TAX_LOT_CTF_NUM_PFX)
    t.SBC_WASH_SALE_AMT           AS DISALWD_WASH_SALE_AMT,  -- [MATCHED] DRD source verified against ODI (ODI projects .SBC_WASH_SALE_AMT)
    t.TXN_INTT_DT                 AS DSPN_DT,  -- [MATCHED] DRD source verified against ODI (ODI projects CLOSE_TAX_LOT_NONBKR_RJTRUST_TGT.TXN_INTT_DT)
    t.NML_CCY_RLZD_PRC            AS DSPN_PRC,  -- [MATCHED] DRD source verified against ODI (ODI projects CLOSE_TAX_LOT_NONBKR_RJTRUST_TGT.NML_CCY_RLZD_PRC)
    t.NML_CCY_RLZD_PROCD_AMT      AS DSPN_PROCD,  -- [MATCHED] DRD source verified against ODI (ODI projects CLOSE_TAX_LOT_NONBKR_RJTRUST_TGT.NML_CCY_RLZD_PROCD_AMT)
    cl_val.CL_VAL_NM              AS DSPN_MTH_CD,  -- [MATCHED] DRD source verified against ODI (ODI projects .CL_VAL_NM)
    t.SBC_EXG_RATE                AS EXG_RATE,  -- [MATCHED] DRD source verified against ODI (ODI projects CLOSE_TAX_LOT_NONBKR_RJTRUST_TGT.SBC_EXG_RATE)
    t.NML_CCY_OPN_FAIR_MKT_VAL_AMT AS FAIR_MKT_VAL_OF_GIFT_OR_INHTN,  -- [MATCHED] DRD source verified against ODI (ODI projects .NML_CCY_OPN_FAIR_MKT_VAL_AMT)
    t.NML_CCY_RLZD_GAIN_LOSS_AMT  AS GAIN_LOSS_AMT,  -- [MATCHED] DRD source verified against ODI (ODI projects CLOSE_TAX_LOT_NONBKR_RJTRUST_TGT.NML_CCY_RLZD_GAIN_LOSS_AMT)
    t.GIFT_DT                     AS GIFT_DT,  -- [MATCHED] DRD source verified against ODI (ODI projects CLOSE_TAX_LOT_NONBKR_RJTRUST_TGT.GIFT_DT)
    (NULL)                        AS LIFE_TO_DTD_MKT_DCN,  -- [RECOVERED_FROM_PROSE] DRD wrote intent as English: 'NULL'; comparator MATCHED ODI's SQL realization: 'NULL'.  All alias prefixes resolve in our FROM graph.
    t.POS_LONG_SHRT_CODE          AS LONG_SHRT_POS_CD,  -- [MATCHED] DRD source verified against ODI (ODI projects CLOSE_TAX_LOT_NONBKR_RJTRUST_TGT.POS_LONG_SHRT_CODE)
    t.SBC_WASH_SALE_AMT           AS LOSS_NOT_ALWD_F,  -- [UNRESOLVABLE] DRD source used; ODI emits complex expression: 'NULL'. Operator should confirm equivalence.
    t.MISS_COST_F                 AS MISS_COST_BSS_F,  -- [MATCHED] DRD source verified against ODI (ODI projects CLOSE_TAX_LOT_NONBKR_RJTRUST_TGT.MISS_COST_F)
    t.OPNAMT                      AS OPN_AMT,  -- [MATCHED] DRD source verified against ODI (ODI projects CLOSE_TAX_LOT_NONBKR_RJTRUST_TGT.OPNAMT)
    t.SBC_OPN_PRC_FCTR            AS OPN_PRC_FCTR,  -- [MATCHED] DRD source verified against ODI (ODI projects .SBC_OPN_PRC_FCTR)
    cl_val.CL_VAL_NM              AS OPN_TXN_EV_TP,  -- [MATCHED] DRD source verified against ODI (ODI projects .)
    cl_val.CL_VAL_NM              AS ORIG_EV_TP,  -- [MATCHED] DRD source verified against ODI (ODI projects .)
    t.SBC_ORIG_PRC                AS ORIG_PRC,  -- [MATCHED] DRD source verified against ODI (ODI projects CLOSE_TAX_LOT_NONBKR_RJTRUST_TGT.SBC_ORIG_PRC)
    t.SBC_ORIG_PROCD_AMT          AS ORIG_PROCD,  -- [MATCHED] DRD source verified against ODI (ODI projects .SBC_ORIG_PROCD_AMT)
    cl_val.CL_VAL_NM              AS ORIG_TXN_TP_CD,  -- [MATCHED] DRD source verified against ODI (ODI projects .)
    t.POS_INCPTN_DT               AS POS_INCPTN_DT,  -- [MATCHED] DRD source verified against ODI (ODI projects CLOSE_TAX_LOT_NONBKR_RJTRUST_TGT.POS_INCPTN_DT)
    (NULL)                        AS PREM_AMT,  -- [RECOVERED_FROM_PROSE] DRD wrote intent as English: 'NULL'; comparator MATCHED ODI's SQL realization: 'NULL'.  All alias prefixes resolve in our FROM graph.
    t.SUB_LOT_QTY                 AS QTY,  -- [MATCHED] DRD source verified against ODI (ODI projects CLOSE_TAX_LOT_NONBKR_RJTRUST_TGT.SUB_LOT_QTY)
    t.RLZD_GAIN_LOSS_F            AS RLZD_CLS_F,  -- [MATCHED] DRD source verified against ODI (ODI projects CLOSE_TAX_LOT_NONBKR_RJTRUST_TGT.RLZD_GAIN_LOSS_F)
    t.NML_CCY_RLZD_PROCD_AMT      AS RLZD_PROCD_AMT,  -- [MATCHED] DRD source verified against ODI (ODI projects CLOSE_TAX_LOT_NONBKR_RJTRUST_TGT.NML_CCY_RLZD_PROCD_AMT)
    t.RVST_F                      AS RVST_LOT_F,  -- [MATCHED] DRD source verified against ODI (ODI projects CLOSE_TAX_LOT_NONBKR_RJTRUST_TGT.RVST_F)
    t.SBC_OPN_ADJ_COST_AMT        AS SBC_ADJ_COST,  -- [MATCHED] DRD source verified against ODI (ODI projects .SBC_OPN_ADJ_COST_AMT)
    t.SBC_CLS_PRC_FCTR            AS SBC_CLS_PRC_FCTR,  -- [MATCHED] DRD source verified against ODI (ODI projects CLOSE_TAX_LOT_NONBKR_RJTRUST_TGT.SBC_CLS_PRC_FCTR)
    t.SBC_OPN_COST_AMT            AS SBC_COST_AMT,  -- [MATCHED] DRD source verified against ODI (ODI projects .SBC_OPN_COST_AMT)
    t.NML_CCY_WASH_SALE_AMT       AS SBC_DISALWD_WASH_SALE_AMT,  -- [MATCHED] DRD source verified against ODI (ODI projects .NML_CCY_WASH_SALE_AMT)
    t.NML_CCY_OPN_FAIR_MKT_VAL_AMT AS SBC_FAIR_MKT_VAL,  -- [MATCHED] DRD source verified against ODI (ODI projects .NML_CCY_OPN_FAIR_MKT_VAL_AMT)
    t.SBC_OPN_PRC_FCTR            AS SBC_OPN_PRC_FCTR,  -- [MATCHED] DRD source verified against ODI (ODI projects .SBC_OPN_PRC_FCTR)
    t.SBC_ORIG_PRC                AS SBC_ORIG_PRC,  -- [MATCHED] DRD source verified against ODI (ODI projects .SBC_ORIG_PRC)
    t.SBC_ORIG_PROCD_AMT          AS SBC_ORIG_PROCD,  -- [MATCHED] DRD source verified against ODI (ODI projects .SBC_ORIG_PROCD_AMT)
    t.SBC_OPN_PER_UC_AMT          AS SBC_UC,  -- [MATCHED] DRD source verified against ODI (ODI projects .SBC_OPN_PER_UC_AMT)
    t.SD                          AS SD,  -- [MATCHED] DRD source verified against ODI (ODI projects CLOSE_TAX_LOT_NONBKR_RJTRUST_TGT.SD)
    cl_val.CL_VAL_CODE            AS SRC_RCRD_TP_CD,  -- [MATCHED] DRD source verified against ODI (ODI projects CL_VAL2.CL_VAL_CODE)
    src_stm_dim.SRC_STM_CD        AS SRC_STM_CD,  -- [MATCHED] DRD source verified against ODI (ODI projects .)
    NULL,  -- [DB_RESOLVED_NULL] SUB_LOT_MSTR_2.SRC_STM_ID (table absent on DB) is not a column of its table (DB-confirmed) for SRC_STM_ID; NULL'd to run -- operator: map to the correct source column.
    src_stm_dim.SRC_STM_NM        AS SRC_STM_NM,  -- [MATCHED] DRD source verified against ODI (ODI projects .)
    t.SUB_LOT_EXT_REFR_KEY_PRIM   AS TAX_LOT_EXT_REFR_KEY_PRIM,  -- [MATCHED] DRD source verified against ODI (ODI projects CLOSE_TAX_LOT_NONBKR_RJTRUST_TGT.SUB_LOT_EXT_REFR_KEY_PRIM)
    t.SUB_LOT_EXT_REFR_KEY_QTRNY  AS TAX_LOT_EXT_REFR_KEY_QTRNY,  -- [MATCHED] DRD source verified against ODI (ODI projects CLOSE_TAX_LOT_NONBKR_RJTRUST_TGT.SUB_LOT_EXT_REFR_KEY_QTRNY)
    t.SUB_LOT_EXT_REFR_KEY_SCDY   AS TAX_LOT_EXT_REFR_KEY_SCDY,  -- [MATCHED] DRD source verified against ODI (ODI projects CLOSE_TAX_LOT_NONBKR_RJTRUST_TGT.SUB_LOT_EXT_REFR_KEY_SCDY)
    t.SUB_LOT_EXT_REFR_KEY_TRTY   AS TAX_LOT_EXT_REFR_KEY_TRTY,  -- [MATCHED] DRD source verified against ODI (ODI projects CLOSE_TAX_LOT_NONBKR_RJTRUST_TGT.SUB_LOT_EXT_REFR_KEY_TRTY)
    t.TRD_NUM                     AS TRD_NUM,  -- [MATCHED] DRD source verified against ODI (ODI projects CLOSE_TAX_LOT_NONBKR_RJTRUST_TGT.TRD_NUM)
    t.TXN_INTT_DT                 AS TXN_INTT_DT,  -- [MATCHED] DRD source verified against ODI (ODI projects CLOSE_TAX_LOT_NONBKR_RJTRUST_TGT.TXN_INTT_DT)
    cl_val_2.CL_VAL_CODE          AS TXN_TP_CD,  -- [MATCHED] DRD source verified against ODI (ODI projects CL_VAL1_1.CL_VAL_CODE)
    t.SBC_OPN_PER_UC_AMT          AS UC,  -- [MATCHED] DRD source verified against ODI (ODI projects .SBC_OPN_PER_UC_AMT)
    t.WASH_SALE_F                 AS WASH_SALE_F,  -- [MATCHED] DRD source verified against ODI (ODI projects CLOSE_TAX_LOT_NONBKR_RJTRUST_TGT.WASH_SALE_F)
    t.WASHSALETP                  AS WASH_SALE_TP,  -- [UNRESOLVABLE] DRD source used; ODI emits complex expression: "CASE   \nWHEN CLOSE_TAX_LOT_NONBKR_RJTRUST_TGT.WASH_SALE_F ='". Operator should confirm equivalence.
    t.ZERO_BSS_IND_F              AS ZERO_COST_BSS_F,  -- [MATCHED] DRD source verified against ODI (ODI projects .ZERO_BSS_IND_F)
    t.OPNDT                       AS OPN_DT,  -- [MATCHED] DRD source verified against ODI (ODI projects CLOSE_TAX_LOT_NONBKR_RJTRUST_TGT.OPNDT)
    t.ADJCOSTGAINAMT              AS ADJ_COST_GAIN_AMT,  -- [MATCHED] DRD source verified against ODI (ODI projects CLOSE_TAX_LOT_NONBKR_RJTRUST_TGT.ADJCOSTGAINAMT)
    t.ADJCOSTLOSSAMT              AS ADJ_COST_LOSS_AMT,  -- [MATCHED] DRD source verified against ODI (ODI projects CLOSE_TAX_LOT_NONBKR_RJTRUST_TGT.ADJCOSTLOSSAMT)
    t.TERMTP                      AS TERM_TP_CD,  -- [MATCHED] DRD source verified against ODI (ODI projects CLOSE_TAX_LOT_NONBKR_RJTRUST_TGT.TERMTP)
    t.HASMISSADJCOST              AS MISS_ADJ_COST_F,  -- [MATCHED] DRD source verified against ODI (ODI projects CLOSE_TAX_LOT_NONBKR_RJTRUST_TGT.HASMISSADJCOST)
    t.ISCOVERED                   AS IRS_1099B_REPORTABLE_F,  -- [MATCHED] DRD source verified against ODI (ODI projects CLOSE_TAX_LOT_NONBKR_RJTRUST_TGT.ISCOVERED)
    t.OPN_CLS                     AS POS_CLS_TP,  -- [MATCHED] DRD source verified against ODI (ODI projects .)
    NULL                          AS SESN_NUM,  -- DRD did not state a source for SESN_NUM; projecting NULL.  Operator must populate DRD.
    (SYSDATE)                     AS CRT_DTM,  -- [ODI_HELPER_FILL] DRD silent for CRT_DTM; ODI populates it as 'SYSDATE' (self-contained) -- using ODI realization (helper) to match ODI and avoid a spurious NULL.
    ('SESS_NAME')                 AS CRT_USR_NM,  -- [ODI_HELPER_FILL] DRD silent for CRT_USR_NM; ODI populates it as "'SESS_NAME'" (self-contained) -- using ODI realization (helper) to match ODI and avoid a spurious NULL.
    (SYSTIMESTAMP)                AS LAST_UDT_DTM,  -- [ODI_HELPER_FILL] DRD silent for LAST_UDT_DTM; ODI populates it as 'SYSTIMESTAMP' (self-contained) -- using ODI realization (helper) to match ODI and avoid a spurious NULL.
    ('SESS_NAME')                 AS LAST_UDT_USR_NM  -- [ODI_HELPER_FILL] DRD silent for LAST_UDT_USR_NM; ODI populates it as "'SESS_NAME'" (self-contained) -- using ODI realization (helper) to match ODI and avoid a spurious NULL.
FROM TAXLOT_STG_OWNER.CLOSE_TAX_LOT_NONBKR_RJTRUST_TGT t
  -- TODO: replace CROSS JOIN with operator-supplied ON clause for COMMON_OWNER.ACG_TP_DIM
  CROSS JOIN COMMON_OWNER.ACG_TP_DIM acg_tp_dim
  JOIN CCAL_REPL_OWNER.CCAL_CIRD_PD_MAP ccal_cird_pd_map ON ccal_cird_pd_map.CCAL_PD_ID = t.CCAL_PD_ID AND ccal_cird_pd_map.ACTV_F = 'Y'
  -- TODO: replace CROSS JOIN with operator-supplied ON clause for CCAL_REPL_OWNER.CL_VAL
  CROSS JOIN CCAL_REPL_OWNER.CL_VAL cl_val
  -- TODO: replace CROSS JOIN with operator-supplied ON clause for COMMON_OWNER.SRC_STM_DIM
  CROSS JOIN COMMON_OWNER.SRC_STM_DIM src_stm_dim
  -- TODO: replace CROSS JOIN with operator-supplied ON clause for TAXLOT_STG_OWNER.CL_VAL
  CROSS JOIN CCAL_REPL_OWNER.CL_VAL cl_val_2