-- Generated by comparator_driven_emitter v2 (DRD-driven; ODI verifies)
-- Source per row: DRD source_table.source_attribute (NOT ODI staging).
-- Operator-locked architecture (2026-05-30 Phase 7.6).
-- DRD declares 66 target columns;
-- 62 MATCHED/ALIAS_DRIFT (DRD verified by ODI);
-- 0 REAL_MISMATCH (DRD used; ODI divergent);
-- 0 UNRESOLVABLE (DRD used; ODI complex);
-- 0 SOURCE_MISSING (DRD used; ODI gap);
-- 3 RECOVERED_FROM_PROSE (DRD prose; ODI's SQL realization projected with marker);
-- 3 ODI_HELPER_FILL (DRD silent; ODI's self-contained value projected as helper to match ODI + avoid NULL);
-- 4 RECOVERED_FROM_PROSE_UNRUNNABLE (DRD prose; ODI expr refs staging alias not in FROM; NULL'd to stay runnable);
-- 0 COMPLEX_DRD_EXPRESSION (DRD prose; no ODI expr available; NULL'd);
-- 4 NULL total (no DRD source or prose-only DRD);
-- 0 NOT NULL constraint risk;
-- 3 JOIN clauses auto-derived from DRD;
-- 3 JOIN clauses need operator-supplied ON predicate.

INSERT INTO IKOROSTELEV.OPN_TAX_LOTS_NON_BKR_FACT (
    SRC_STM_CD,
    AR_ID,
    CIRD_PD_ID,
    CCAL_PD_ID,
    ACG_TP_CD,
    TAX_LOT_EXT_REFR_KEY_PRIM,
    TAX_LOT_EXT_REFR_KEY_SCDY,
    TAX_LOT_EXT_REFR_KEY_TRTY,
    TAX_LOT_EXT_REFR_KEY_QTRNY,
    END_DT,
    EFF_DT,
    ACG_TP_NM,
    ACQ_DT,
    ADJ_COST,
    CCY_CD,
    CTF_NUM,
    CTF_NUM_PFX,
    COST_BSS_LEGS_CVR_CD,
    DISALWD_WASH_SALE_AMT,
    EXG_RATE,
    FAIR_MKT_VAL_OF_GIFT_OR_INHTN,
    GIFT_DT,
    POS_INCPTN_DT,
    LONG_SHRT_POS_CD,
    LOSS_NOT_ALWD_F,
    LIFE_TO_DTD_MKT_DCN,
    MISS_COST_BSS_F,
    ADJ_COST_NOT_ACRT_F,
    OPN_PRC_FCTR,
    OPN_TXN_EV_TP,
    COST_AMT,
    ORIG_EV_TP,
    ORIG_PRC,
    ORIG_PROCD,
    ORIG_TXN_TP_CD,
    PREM_AMT,
    QTY,
    SRC_RCRD_TP_CD,
    RVST_LOT_F,
    SD,
    TRD_NUM,
    TXN_INTT_DT,
    TXN_TP_CD,
    UC,
    SBC_UC,
    WASH_SALE_F,
    ZERO_COST_BSS_F,
    WASH_SALE_TP,
    SBC_DISALWD_WASH_SALE_AMT,
    SBC_ADJ_COST,
    SBC_FAIR_MKT_VAL,
    SBC_OPN_PRC_FCTR,
    SBC_COST_AMT,
    SBC_ORIG_PRC,
    SBC_ORIG_PROCD,
    SRC_STM_ID,
    SRC_STM_NM,
    ACG_TP_ID,
    TAX_LOT_TP,
    COST_BSS_LEGS_CVR_F,
    MISS_IVS_COST_F,
    SESN_NUM,
    CRT_DTM,
    CRT_USR_NM,
    LAST_UDT_DTM,
    LAST_UDT_USR_NM
)
SELECT
    src_stm_dim.SRC_STM_CD        AS SRC_STM_CD,  -- [MATCHED] DRD source verified against ODI (ODI projects SRC_STM_DIM.SRC_STM_CD)
    t.AR_ID                       AS AR_ID,  -- [MATCHED] DRD source verified against ODI (ODI projects OPN_TAX_LOTS_NONBKR_TGT.AR_ID)
    ccal_cird_pd_map.CIRD_PD_ID   AS CIRD_PD_ID,  -- [MATCHED] DRD source verified against ODI (ODI projects CCAL_CIRD_PD_MAP_1.CIRD_PD_ID)
    t.CCAL_PD_ID                  AS CCAL_PD_ID,  -- [MATCHED] DRD source verified against ODI (ODI projects OPN_TAX_LOTS_NONBKR_TGT.CCAL_PD_ID)
    t.AC_TP_CODE                  AS ACG_TP_CD,  -- [MATCHED] DRD source verified against ODI (ODI projects OPN_TAX_LOTS_NONBKR_TGT.AC_TP_CODE)
    t.TAX_LOT_EXT_REFR_KEY_PRIM   AS TAX_LOT_EXT_REFR_KEY_PRIM,  -- [MATCHED] DRD source verified against ODI (ODI projects OPN_TAX_LOTS_NONBKR_TGT.TAX_LOT_EXT_REFR_KEY_PRIM)
    t.TAX_LOT_EXT_REFR_KEY_SCDY   AS TAX_LOT_EXT_REFR_KEY_SCDY,  -- [MATCHED] DRD source verified against ODI (ODI projects OPN_TAX_LOTS_NONBKR_TGT.TAX_LOT_EXT_REFR_KEY_SCDY)
    t.TAX_LOT_EXT_REFR_KEY_TRTY   AS TAX_LOT_EXT_REFR_KEY_TRTY,  -- [MATCHED] DRD source verified against ODI (ODI projects OPN_TAX_LOTS_NONBKR_TGT.TAX_LOT_EXT_REFR_KEY_TRTY)
    t.TAX_LOT_EXT_REFR_KEY_QTRNY  AS TAX_LOT_EXT_REFR_KEY_QTRNY,  -- [MATCHED] DRD source verified against ODI (ODI projects OPN_TAX_LOTS_NONBKR_TGT.TAX_LOT_EXT_REFR_KEY_QTRNY)
    t.EFF_TO_DT                   AS END_DT,  -- [MATCHED] DRD source verified against ODI (ODI projects OPN_TAX_LOTS_NONBKR_TGT.EFF_TO_DT)
    t.EFF_FM_DT                   AS EFF_DT,  -- [MATCHED] DRD source verified against ODI (ODI projects OPN_TAX_LOTS_NONBKR_TGT.EFF_FM_DT)
    acg_tp_dim.ACG_TP_NM          AS ACG_TP_NM,  -- [MATCHED] DRD source verified against ODI (ODI projects ACG_TP_DIM.ACG_TP_NM)
    t.ACQ_DT                      AS ACQ_DT,  -- [MATCHED] DRD source verified against ODI (ODI projects OPN_TAX_LOTS_NONBKR_TGT.ACQ_DT)
    t.SBC_ASOF_ADJ_COST_AMT       AS ADJ_COST,  -- [MATCHED] DRD source verified against ODI (ODI projects .SBC_ASOF_ADJ_COST_AMT)
    t.STM_BASE_ISO_CCY_CODE       AS CCY_CD,  -- [MATCHED] DRD source verified against ODI (ODI projects OPN_TAX_LOTS_NONBKR_TGT.STM_BASE_ISO_CCY_CODE)
    t.TAX_LOT_CTF_NUM             AS CTF_NUM,  -- [MATCHED] DRD source verified against ODI (ODI projects OPN_TAX_LOTS_NONBKR_TGT.TAX_LOT_CTF_NUM)
    t.TAX_LOT_CTF_NUM_PFX         AS CTF_NUM_PFX,  -- [MATCHED] DRD source verified against ODI (ODI projects OPN_TAX_LOTS_NONBKR_TGT.TAX_LOT_CTF_NUM_PFX)
    t.CVRD_UNCVRD                 AS COST_BSS_LEGS_CVR_CD,  -- [MATCHED] DRD source verified against ODI (ODI projects OPN_TAX_LOTS_NONBKR_TGT.CVRD_UNCVRD)
    t.SBC_WASH_SALE_AMT           AS DISALWD_WASH_SALE_AMT,  -- [MATCHED] DRD source verified against ODI (ODI projects OPN_TAX_LOTS_NONBKR_TGT.SBC_WASH_SALE_AMT)
    t.SBC_EXG_RATE                AS EXG_RATE,  -- [MATCHED] DRD source verified against ODI (ODI projects OPN_TAX_LOTS_NONBKR_TGT.SBC_EXG_RATE)
    t.SBC_ASOF_FAIR_MKT_VAL_AMT   AS FAIR_MKT_VAL_OF_GIFT_OR_INHTN,  -- [MATCHED] DRD source verified against ODI (ODI projects .SBC_ASOF_FAIR_MKT_VAL_AMT)
    t.GIFT_DT                     AS GIFT_DT,  -- [MATCHED] DRD source verified against ODI (ODI projects OPN_TAX_LOTS_NONBKR_TGT.GIFT_DT)
    t.POS_INCPTN_DT               AS POS_INCPTN_DT,  -- [MATCHED] DRD source verified against ODI (ODI projects OPN_TAX_LOTS_NONBKR_TGT.POS_INCPTN_DT)
    t.POS_LONG_SHRT_CODE          AS LONG_SHRT_POS_CD,  -- [MATCHED] DRD source verified against ODI (ODI projects OPN_TAX_LOTS_NONBKR_TGT.POS_LONG_SHRT_CODE)
    (NULL)                        AS LOSS_NOT_ALWD_F,  -- [RECOVERED_FROM_PROSE] DRD wrote intent as English: 'NULL'; comparator MATCHED ODI's SQL realization: 'NULL'.  All alias prefixes resolve in our FROM graph.
    (NULL)                        AS LIFE_TO_DTD_MKT_DCN,  -- [RECOVERED_FROM_PROSE] DRD wrote intent as English: 'NULL'; comparator MATCHED ODI's SQL realization: 'NULL'.  All alias prefixes resolve in our FROM graph.
    t.MISS_COST_F                 AS MISS_COST_BSS_F,  -- [MATCHED] DRD source verified against ODI (ODI projects .MISS_COST_F)
    t.NULL_BSS_F                  AS ADJ_COST_NOT_ACRT_F,  -- [MATCHED] DRD source verified against ODI (ODI projects OPN_TAX_LOTS_NONBKR_TGT.NULL_BSS_F)
    t.SBC_OPN_PRC_FCTR            AS OPN_PRC_FCTR,  -- [MATCHED] DRD source verified against ODI (ODI projects .SBC_OPN_PRC_FCTR)
    cl_val.CL_VAL_NM              AS OPN_TXN_EV_TP,  -- [MATCHED] DRD source verified against ODI (ODI projects CL_VAL1.CL_VAL_NM)
    t.NML_ASOF_CRN_COST_AMT       AS COST_AMT,  -- [MATCHED] DRD source verified against ODI (ODI projects .NML_ASOF_CRN_COST_AMT)
    NULL,  -- [DB_RESOLVED_NULL] T.ORIG_EV_TP is not a column of its table (DB-confirmed) for ORIG_EV_TP; NULL'd to run -- operator: map to the correct source column.
    t.SBC_ORIG_PRC                AS ORIG_PRC,  -- [MATCHED] DRD source verified against ODI (ODI projects .SBC_ORIG_PRC)
    t.SBC_ORIG_PROCD_AMT          AS ORIG_PROCD,  -- [MATCHED] DRD source verified against ODI (ODI projects .SBC_ORIG_PROCD_AMT)
    NULL,  -- [DB_RESOLVED_NULL] T.ORIG_TXN_TP_CD is not a column of its table (DB-confirmed) for ORIG_TXN_TP_CD; NULL'd to run -- operator: map to the correct source column.
    (null)                        AS PREM_AMT,  -- [RECOVERED_FROM_PROSE] DRD wrote intent as English: 'NULL'; comparator MATCHED ODI's SQL realization: 'null'.  All alias prefixes resolve in our FROM graph.
    t.TAX_LOT_ASOF_QTY            AS QTY,  -- [MATCHED] DRD source verified against ODI (ODI projects OPN_TAX_LOTS_NONBKR_TGT.TAX_LOT_ASOF_QTY)
    cl_val_2.CL_VAL_CODE          AS SRC_RCRD_TP_CD,  -- [MATCHED] DRD source verified against ODI (ODI projects CL_VAL.CL_VAL_CODE)
    t.RVST_F                      AS RVST_LOT_F,  -- [MATCHED] DRD source verified against ODI (ODI projects OPN_TAX_LOTS_NONBKR_TGT.RVST_F)
    t.SD                          AS SD,  -- [MATCHED] DRD source verified against ODI (ODI projects OPN_TAX_LOTS_NONBKR_TGT.SD)
    t.TRD_NUM                     AS TRD_NUM,  -- [MATCHED] DRD source verified against ODI (ODI projects OPN_TAX_LOTS_NONBKR_TGT.TRD_NUM)
    t.TXN_INIT_DT                 AS TXN_INTT_DT,  -- [MATCHED] DRD source verified against ODI (ODI projects OPN_TAX_LOTS_NONBKR_TGT.TXN_INIT_DT)
    NULL,  -- [DB_RESOLVED_NULL] T.TXN_TP_CD is not a column of its table (DB-confirmed) for TXN_TP_CD; NULL'd to run -- operator: map to the correct source column.
    t.SBC_OPN_PER_UC_AMT          AS UC,  -- [MATCHED] DRD source verified against ODI (ODI projects .SBC_OPN_PER_UC_AMT)
    t.SBC_OPN_PER_UC_AMT          AS SBC_UC,  -- [MATCHED] DRD source verified against ODI (ODI projects .SBC_OPN_PER_UC_AMT)
    t.WASH_SALE_F                 AS WASH_SALE_F,  -- [MATCHED] DRD source verified against ODI (ODI projects OPN_TAX_LOTS_NONBKR_TGT.WASH_SALE_F)
    t.ZERO_BSS_IND_F              AS ZERO_COST_BSS_F,  -- [MATCHED] DRD source verified against ODI (ODI projects OPN_TAX_LOTS_NONBKR_TGT.ZERO_BSS_IND_F)
    (CASE   
WHEN t.WASH_SALE_F ='Y' 
AND t.SBC_WASH_SALE_AMT = 0    THEN 'CBW' 
WHEN t.WASH_SALE_F ='Y' 
AND t.SBC_WASH_SALE_AMT > 0    THEN 'BOTHW' 
WHEN t.WASH_SALE_F <> 'Y' 
AND t.SBC_WASH_SALE_AMT > 0    THEN 'GLW' 
else null
END) AS WASH_SALE_TP,  -- [ODI_HELPER_FILL] DRD silent for WASH_SALE_TP; ODI populates it as "CASE    WHEN OPN_TAX_LOTS_NONBKR_TGT.WASH_SALE_F ='Y'  AND OPN_TAX_LOTS_NONBKR_T" (staging alias(es) OPN_TAX_LOTS_NONBKR_TGT normalized to base 't') -- using ODI realization (helper) to match ODI and avoid a spurious NULL.
    t.SBC_WASH_SALE_AMT           AS SBC_DISALWD_WASH_SALE_AMT,  -- [MATCHED] DRD source verified against ODI (ODI projects OPN_TAX_LOTS_NONBKR_TGT.SBC_WASH_SALE_AMT)
    t.SBC_ASOF_ADJ_COST_AMT       AS SBC_ADJ_COST,  -- [MATCHED] DRD source verified against ODI (ODI projects .SBC_ASOF_ADJ_COST_AMT)
    t.SBC_ASOF_FAIR_MKT_VAL_AMT   AS SBC_FAIR_MKT_VAL,  -- [MATCHED] DRD source verified against ODI (ODI projects .SBC_ASOF_FAIR_MKT_VAL_AMT)
    t.SBC_OPN_PRC_FCTR            AS SBC_OPN_PRC_FCTR,  -- [MATCHED] DRD source verified against ODI (ODI projects .SBC_OPN_PRC_FCTR)
    t.SBC_OPN_COST_AMT            AS SBC_COST_AMT,  -- [MATCHED] DRD source verified against ODI (ODI projects .SBC_OPN_COST_AMT)
    t.SBC_ORIG_PRC                AS SBC_ORIG_PRC,  -- [MATCHED] DRD source verified against ODI (ODI projects .SBC_ORIG_PRC)
    t.SBC_ORIG_PROCD_AMT          AS SBC_ORIG_PROCD,  -- [MATCHED] DRD source verified against ODI (ODI projects .SBC_ORIG_PROCD_AMT)
    t.SRC_STM_ID                  AS SRC_STM_ID,  -- [MATCHED] DRD source verified against ODI (ODI projects SRC_STM_DIM.SRC_STM_ID)
    src_stm_dim.SRC_STM_NM        AS SRC_STM_NM,  -- [MATCHED] DRD source verified against ODI (ODI projects SRC_STM_DIM.SRC_STM_NM)
    acg_tp_dim.ACG_TP_ID          AS ACG_TP_ID,  -- [MATCHED] DRD source verified against ODI (ODI projects ACG_TP_DIM.ACG_TP_ID)
    cl_val_3.CL_VAL_NM            AS TAX_LOT_TP,  -- [MATCHED] DRD source verified against ODI (ODI projects CL_VAL3.CL_VAL_NM)
    t.CVRD_UNCVRD                 AS COST_BSS_LEGS_CVR_F,  -- [MATCHED] DRD source verified against ODI (ODI projects .CVRD_UNCVRD)
    NULL                          AS MISS_IVS_COST_F,  -- [RECOVERED_FROM_PROSE_UNRUNNABLE] comparator MATCHED ODI's SQL realization 'S.MISS_IVS_COST_F' but it references ODI staging alias(es) S absent from our DRD-driven FROM graph; projecting NULL so the INSERT runs.  Operator: restructure DRD source into table.column form to project a value.
    NULL                          AS SESN_NUM,  -- [RECOVERED_FROM_PROSE_UNRUNNABLE] comparator MATCHED ODI's SQL realization 'S.SESN_NUM' but it references ODI staging alias(es) S absent from our DRD-driven FROM graph; projecting NULL so the INSERT runs.  Operator: restructure DRD source into table.column form to project a value.
    NULL                          AS CRT_DTM,  -- [RECOVERED_FROM_PROSE_UNRUNNABLE] comparator MATCHED ODI's SQL realization 'S.CRT_DTM' but it references ODI staging alias(es) S absent from our DRD-driven FROM graph; projecting NULL so the INSERT runs.  Operator: restructure DRD source into table.column form to project a value.
    (t.CRT_USR_NM)                AS CRT_USR_NM,  -- [ODI_HELPER_FILL] comparator MATCHED ODI 'OPN_TAX_LOTS_NONBKR_TGT.CRT_USR_NM'; ODI staging alias(es) OPN_TAX_LOTS_NONBKR_TGT normalized to DRD base alias 't' (pass-through rooted at base) -- projecting to match ODI.
    NULL                          AS LAST_UDT_DTM,  -- [RECOVERED_FROM_PROSE_UNRUNNABLE] comparator MATCHED ODI's SQL realization 'S.LAST_UDT_DTM' but it references ODI staging alias(es) S absent from our DRD-driven FROM graph; projecting NULL so the INSERT runs.  Operator: restructure DRD source into table.column form to project a value.
    (t.LAST_UDT_USR_NM)           AS LAST_UDT_USR_NM  -- [ODI_HELPER_FILL] comparator MATCHED ODI 'OPN_TAX_LOTS_NONBKR_TGT.LAST_UDT_USR_NM'; ODI staging alias(es) OPN_TAX_LOTS_NONBKR_TGT normalized to DRD base alias 't' (pass-through rooted at base) -- projecting to match ODI.
FROM TAXLOT_STG_OWNER.OPN_TAX_LOTS_NONBKR_TGT t
  JOIN COMMON_OWNER.SRC_STM_DIM src_stm_dim ON src_stm_dim.SRC_STM_ID = t.SRC_STM_ID
  JOIN CCAL_REPL_OWNER.CCAL_CIRD_PD_MAP ccal_cird_pd_map ON ccal_cird_pd_map.CCAL_PD_ID = t.CCAL_PD_ID AND ccal_cird_pd_map.ACTV_F = 'Y'
  -- TODO: replace CROSS JOIN with operator-supplied ON clause for COMMON_OWNER.ACG_TP_DIM
  CROSS JOIN COMMON_OWNER.ACG_TP_DIM acg_tp_dim
  -- TODO: replace CROSS JOIN with operator-supplied ON clause for CCAL_REPL_OWNER.CL_VAL
  CROSS JOIN CCAL_REPL_OWNER.CL_VAL cl_val
  -- TODO: replace CROSS JOIN with operator-supplied ON clause for CL_VAL
  CROSS JOIN CCAL_REPL_OWNER.CL_VAL cl_val_2
  JOIN CCAL_REPL_OWNER.CL_VAL cl_val_3 ON cl_val_3.CL_VAL_ID = t.TAX_LOT_TXN_TP_ID AND cl_val_3.CL_SCM_ID = 84