-- Generated by comparator_driven_emitter v2 (DRD-driven; ODI verifies)
-- Source per row: DRD source_table.source_attribute (NOT ODI staging).
-- Operator-locked architecture (2026-05-30 Phase 7.6).
-- DRD declares 371 target columns;
-- 366 MATCHED/ALIAS_DRIFT (DRD verified by ODI);
-- 0 REAL_MISMATCH (DRD used; ODI divergent);
-- 0 UNRESOLVABLE (DRD used; ODI complex);
-- 4 SOURCE_MISSING (DRD used; ODI gap);
-- 1 RECOVERED_FROM_PROSE (DRD prose; ODI's SQL realization projected with marker);
-- 2 ODI_HELPER_FILL (DRD silent; ODI's self-contained value projected as helper to match ODI + avoid NULL);
-- 1 RECOVERED_FROM_PROSE_UNRUNNABLE (DRD prose; ODI expr refs staging alias not in FROM; NULL'd to stay runnable);
-- 0 COMPLEX_DRD_EXPRESSION (DRD prose; no ODI expr available; NULL'd);
-- 1 NULL total (no DRD source or prose-only DRD);
-- 0 NOT NULL constraint risk;
-- 22 JOIN clauses auto-derived from DRD;
-- 19 JOIN clauses need operator-supplied ON predicate.

INSERT INTO IKOROSTELEV.AVY_FACT_SIDE (
    SHDW_TXN_TP_CD,
    SHDW_TXN_TP_NM,
    IMP_SRC_ACTN_CD,
    IMP_SRC_ACTN_NM,
    SIS_DLTD_EV_ID,
    SIS_DLTD_EV_NM,
    SIS_USR_ID,
    SIS_AC_CL_CD,
    SRC_CNCL_RSN_ID,
    SRC_CNCL_RSN_CD,
    SRC_CNCL_RSN_NM,
    SRC_TXN_SEQ_NUM,
    DVDN_RCRD_DT,
    OWN_IMP_FA_NUM,
    OWN_FA_NUM,
    OWN_FA_NUM_ENT_CD,
    FA_OWN_EMPE_ID,
    OWN_FA_NUM_ENT_ENTP_ID,
    ACAT_CNTRA_FIRM_CLRG_NUM,
    ACAT_CNTRA_FIRM_NM,
    ACAT_CNTRA_FIRM_SHRT_NM,
    ACAT_CNTRA_FIRM_CLRG_ID_TP_CD,
    MM_ALT_ID,
    AR_ORIG_SRC_STM_CD,
    SRC_STM_ID,
    SRC_STM_NM,
    SRC_CNCL_X_RVSN_CD,
    SRC_OPT_CLSS_CD,
    TXN_RCNCL_REPL_CNT,
    TXN_RCNCL_ST_ID,
    TXN_RCNCL_ST_CD,
    TXN_RCNCL_ST_NM,
    MF_AC_NUM,
    OFST_ORIG_SRC_STM_AR_ID,
    OFST_AR_ORIG_SRC_STM_CD,
    OFST_AR_SETL_TP_CD,
    OFST_AR_SETL_TP_DSC,
    AR_SETL_TP_CD,
    AR_SETL_TP_DSC,
    ORIG_SRC_STM_AR_ID,
    TD_DIM_ID,
    EXG_DIM_ID,
    ACG_TP_CD,
    ACG_TP_DIM_ID,
    ACG_TP_NM,
    ACG_TP_ID,
    ACTV_F,
    AR_ID,
    BATCH_DT,
    BKG_DT,
    BR_CD,
    BKR_AR_ID,
    BUY_SELL_IND,
    CASH_AVY_CGY,
    CASH_SIMP_DSPL_AVY_CGY,
    CSH_AVY_CL_ID,
    CASH_AVY_TP,
    CASH_SIMP_DSPL_AVY_TP,
    CASH_ALT_DSC_TRAILER_2,
    CASH_APA_EXT_QUALFR,
    CSH_APA_ID,
    CASH_APA_TP_CD,
    CASH_APA_TP_DSC,
    CSH_APA_TP_ID,
    CASH_APA_TP_NM,
    CASH_CIRD_PD_ID,
    CASH_DB_CR_CD,
    CASH_DB_CR_NM,
    CASH_DSC_TRAILER_1,
    CF_GEN_F,
    CASH_POS_TP_CD,
    CASH_POS_TP_DIM_ID,
    CASH_POS_TP_NM,
    CASH_POS_TP_ID,
    CASH_PD_ID,
    CASH_PD_DIM_ID,
    CASH_SRC_SEQ_NUM,
    CASH_SBC_AMT,
    CASH_TXN_AMT,
    CLNT_FRIENDLY_DSC,
    CRT_DTM,
    CRT_USR_NM,
    CCY_CD,
    CCY_DIM_ID,
    DOL_IND_CD,
    DOL_IND_ID,
    DOL_IND_NM,
    EXG_CD,
    EXG_NM,
    EXEC_DTM,
    EXEC_SBTP_CD,
    EXEC_SBTP_DSC,
    EXEC_SBTP_ID,
    EXEC_SBTP_NM,
    EXEC_TP_CD,
    EXEC_TP_DSC,
    EXEC_TP_ID,
    EXEC_TP_NM,
    FA_NUM,
    LGCY_CNCL_CMPLN_RSN_TP_CD,
    LGCY_CNCL_CMPLN_RSN_DIM_ID,
    LGCY_CNCL_CMPLN_RSN_TP_NM,
    LGCY_CNCL_CMPLN_RSN_TP_ID,
    LGCY_CNCL_CMPLN_SRC_TP_CD,
    LGCY_CNCL_CMPLN_SRC_DIM_ID,
    LGCY_CNCL_CMPLN_SRC_TP_NM,
    LGCY_CNCL_CMPLN_SRC_TP_ID,
    LGCY_MKT_TP_CD,
    LGCY_MKT_TP_DIM_ID,
    LGCY_MKT_TP_NM,
    LGCY_MKT_TP_ID,
    LGCY_TRD_CPCTY_TP_CD,
    LGCY_TRD_CPCTY_TP_DIM_ID,
    LGCY_TRD_CPCTY_TP_NM,
    LGCY_TRD_CPCTY_TP_ID,
    OFST_AR_ID,
    OPT_CLSS_CD,
    OMS_EXEC_TP_CD,
    OMS_EXEC_TP_DSC,
    OMS_EXEC_TP_ID,
    OMS_EXEC_TP_NM,
    OMS_ORDR_KEY,
    ORIG_BKG_DT,
    ORIG_TRD_NUM,
    ORIG_TD,
    REL_TXN_SRC_STM_DIM_ID,
    REL_TXN_SRC_STM_ID,
    REL_TXN_SRC_STM_CD,
    REL_TXN_RLTNP_TP_ID,
    REL_TXN_RLTNP_TP_CD,
    REL_TXN_RLTNP_TP_NM,
    SALE_CHRG_RATE_MULTI_NUM,
    SALE_CHRG_RATE_PCT,
    SALE_CHRG_RATE_TP_CD,
    SALE_CHRG_RATE_TP_ID,
    SALE_CHRG_RATE_TP_NM,
    SCR_AVY_CGY,
    SCR_SIMP_DSPL_AVY_CGY,
    SEC_AVY_CL_ID,
    SCR_AVY_TP,
    SCR_SIMP_DSPL_AVY_TP,
    SEC_ALT_DSC_TRAILER_2,
    SEC_APA_EXT_QUALFR,
    SEC_APA_ID,
    SCR_APA_TP_CD,
    SCR_APA_TP_DSC,
    SEC_APA_TP_ID,
    SCR_APA_TP_NM,
    SEC_CIRD_PD_ID,
    SEC_DB_CR_CD,
    SEC_DB_CR_NM,
    SEC_DSC_TRAILER_1,
    SEC_ORIG_QTY,
    SEC_SRC_CUSIP,
    SEC_PD_ID,
    SEC_PD_DIM_ID,
    SEC_PRC_IN_TXN_CCY,
    SEC_SRC_PRC_IN_SBC,
    SEC_SRC_SEQ_NUM,
    SEC_SBC_AMT,
    SEC_TXN_AMT,
    SD,
    SD_DIM_ID,
    SRC_CRT_USRNM,
    SRC_EFF_DT,
    SRC_ENTR_CNL_TP_CD,
    SRC_ENTR_CNL_TP_DIM_ID,
    SRC_ENTR_CNL_TP_NM,
    SRC_ENTR_CNL_TP_ID,
    SRC_ENTR_DTM,
    SRC_PCS_TP_DIM_ID,
    SRC_PCS_TP_ID,
    SRC_PCS_TP_CD,
    SRC_PCS_TP_NM,
    SRC_STM_CD,
    TXN_SRC_STM_DIM_ID,
    SRC_TXN_CODE,
    SBC_CCY_CALC_DT,
    SBC_CCY_CD,
    SBC_CCY_DIM_ID,
    SBC_EXG_RATE,
    REL_TXN_ID,
    TD,
    TRD_NUM,
    TRD_SLCT_TP_DIM_ID,
    TRD_SLCT_TP_ID,
    TRD_SLCT_TP_CD,
    TRD_SLCT_TP_NM,
    TXN_CL_F,
    TXN_ID,
    TXN_SRC_KEY,
    TXN_SUB_TP_CD,
    TXN_SUB_TP_DSC,
    TXN_SBTP_ID,
    TXN_SUB_TP_NM,
    TXN_TP_CD,
    TXN_TP_DSC,
    TXN_TP_ID,
    TXN_TP_NM,
    ORIG_SRC_STM_ID,
    ORIG_SRC_STM_CD,
    BKR_AR_DIM_ID,
    OFST_AR_DIM_ID,
    AR_DIM_ID,
    LAST_UDT_USR_NM,
    LAST_UDT_DTM,
    SESS_NO,
    SCR_OPT_SYMB,
    DRVD_TRD_CPCTY_CD,
    DRVD_TRD_CPCTY_NM,
    DRVD_TRD_CPCTY_ID,
    ADL_TRD_INSR,
    TRD_FCTR_RATE,
    MRKUP_RATE,
    STD_CMSN_AMT,
    ACT_CMSN_AMT,
    TRD_PCS_FEE_AMT,
    SEC_FEE_AMT,
    ACR_INT_AMT,
    CNCSN_AMT,
    CDSC_AMT,
    OTHR_FEE_AMT,
    TRD_CNCLD_F,
    SYMB,
    ISIN,
    TXN_SRC_TAX_CD,
    TXN_SRC_TAX_CD_DSC,
    TM_PRC_DISCRETION_F,
    CASH_NNA_CGY_ID,
    CASH_NNA_CGY_NM,
    SCR_NNA_CGY_ID,
    SCR_NNA_CGY_NM,
    YLD,
    YTW,
    YTW_CD,
    BKR_AC_NUM,
    SIS_DLTD_EV_CD,
    DB_CARD_TXN_DT,
    DB_CARD_ORIG_CCY_CD,
    DB_CARD_ORIG_CCY,
    SDIRA_TXN_TP_CD,
    SDIRA_TXN_TP,
    SDIRA_TXN_YR,
    TXN_CCY,
    BKR_IRA_F,
    BKR_ERISA_F,
    BKR_ORIG_SRC_STM_CD,
    BKR_ABC_CLSS_CD,
    BKR_ABC_CLSS,
    AC_CGY_CD,
    BKR_AC_CGY_CD,
    AC_CGY,
    BKR_AC_CGY,
    BKR_BSN_LINE_AFFLT,
    BKR_BSN_LINE_AFFLT_CD,
    TST_AC_F,
    BKR_TST_AC_F,
    TAX_RPT_CLNT_ID,
    BKR_TAX_RPT_CLNT_ID,
    TAX_AC_F,
    BKR_TAX_AC_F,
    BKR_RJ_TAX_RPT_RSPL_F,
    RJ_BSN_UNIT_CD,
    BKR_RJ_BSN_UNIT_CD,
    RJ_BSN_UNIT,
    BKR_RJ_BSN_UNIT,
    AC_OWNSHP_TP_CD,
    BKR_AC_OWNSHP_TP_CD,
    AC_OWNSHP_TP,
    BKR_AC_OWNSHP_TP,
    BKR_FIRM_AC_F,
    BKR_FEE_BASE_AC_F,
    BKR_RJ_TRUST_F,
    OWN_PRIM_FA_NUM,
    OWN_FA_CSS_PSN_ID,
    OWN_FA_CRN_ADV_F,
    OWN_FA_DEPT_BR_CD,
    OWN_FA_DSCR_F,
    OWN_FA_DSCR_ST,
    OWN_FA_DSCR_ST_CD,
    OWN_FA_FINRA_CRD_CLSS_CD,
    OWN_FA_HR_ST_CD,
    OWN_FA_PRODUCER_F,
    OWN_FA_QUALF_ADV_F,
    OWN_FA_ENT_BR_CD,
    OWN_FA_ENT_BSN_ST,
    OWN_FA_ENT_DIV_CD,
    OWN_FA_ENT_DIV_DSC,
    OWN_FA_ENT_DIV_NODE,
    OWN_FA_ENT_MAIN_BR_STE,
    OWN_FA_ENT_OSJ,
    OWN_FA_ENT_RTL_HIER_BSN_MODL_CD,
    OWN_FA_ENT_RTL_HIER_BSN_MODL_DSC,
    OWN_FA_ENT_RTL_SALE_HIER_LOB_CD,
    OWN_FA_ENT_RTL_SALE_HIER_LOB_DSC,
    OWN_FA_ENT_RTL_HIER_RPT_UNIT_CD,
    OWN_FA_ENT_RTL_HIER_RPT_UNIT_DSC,
    OWN_FA_ENT_RTL_SALE_DIV_CD,
    OWN_FA_ENT_RTL_SALE_HIER_RGON_CD,
    OWN_FA_ENT_RTL_SALE_HIER_RGON_DSC,
    OWN_FA_ENT_RTL_HIER_TERR_CD,
    OWN_FA_ENT_RTL_HIER_TERR_DSC,
    OWN_FA_ENT_RSK_HIER_BSN_UNIT_CD,
    OWN_FA_ENT_RSK_HIER_BSN_UNIT_DSC,
    OWN_FA_ENT_RJAS_ID_F,
    OWN_FA_ENT_SUBDIV_CD,
    OWN_FA_ENT_SUBDIV_DSC,
    OWN_FA_ENT_SUBS,
    OWN_FA_ENT_SBTP,
    OWN_FA_ENT_SBTP_CD,
    OWN_FA_ENT_TP,
    OWN_FA_ENT_TP_CD,
    OWN_FA_ENT_LOB_AB_F,
    OWN_FA_ENT_LOB_AMS_F,
    OWN_FA_ENT_LOB_BSN_MODL,
    OWN_FA_ENT_BSN_OPN_DT,
    OWN_FA_ENT_LONG_CD,
    OWN_FA_ENT_SHRT_CD,
    OWN_FA_ENT_CSS_ID,
    OWN_FA_ENT_RTL_SALE_CPX_CD,
    EQTY_IDY,
    EQTY_IDY_CD,
    EQTY_IDY_GRP,
    EQTY_IDY_GRP_CD,
    EQTY_SECT,
    EQTY_SECT_CD,
    EQTY_SUP_SECT,
    EQTY_SUP_SECT_CD,
    MODL_STRTG_DTL_AST_CLSS,
    MODL_STRTG_DTL_AST_CLSS_CD,
    MODL_STRTG_SMY_AST_CLSS,
    MODL_STRTG_SMY_AST_CLSS_CD,
    PD_CMPOS_DSC,
    PD_SHRT_NM,
    PD_DSC,
    RPT_CL_LVL_1,
    RPT_CL_LVL_2,
    RPT_STRTG_DTL_AST_CLSS,
    RPT_STRTG_DTL_AST_CLSS_CD,
    RPT_STRTG_SMY_AST_CLSS,
    RPT_STRTG_SMY_AST_CLSS_CD,
    FND_FAM,
    SHR_CLSS_TP_CD,
    SHR_CLSS_TP,
    IMT_CL_LVL_1,
    IMT_CL_LVL_1_CD,
    IMT_CL_LVL_2,
    IMT_CL_LVL_2_CD,
    IMT_CL_LVL_3,
    IMT_CL_LVL_3_CD,
    IMT_CL_LVL_4,
    IMT_CL_LVL_4_CD,
    IMT_CL_LVL_5,
    IMT_CL_LVL_5_CD,
    OWN_FA_NUM_TP_CD,
    OWN_FA_NUM_TP,
    BOND_ACRTN_DCN_AMT,
    BOND_AMRZ_PREM_AMT,
    RJ_TRUST_BOOK_VAL_AMT,
    RJ_TRUST_RLZD_TAX_GAIN_OR_LOSS_AMT,
    BFR_REPYMT_FACE_VAL_AMT,
    BFR_INCM_PYMT_FACE_VAL_AMT,
    BASE_POS_QTY,
    NO_SIS_SCR_MVMT_TXN_QTY,
    NO_SIS_SCR_MVMT_TXN_PRC,
    REIVS_SHR_QTY,
    REIVS_PRC
)
SELECT
    t.SRC_TXN_TP                  AS SHDW_TXN_TP_CD,  -- [MATCHED] DRD source verified against ODI (ODI projects TXN.SRC_TXN_TP)
    shdw_txn_tp.SRC_TXN_TP_NM     AS SHDW_TXN_TP_NM,  -- [MATCHED] DRD source verified against ODI (ODI projects SHDW_TXN_TP.SRC_TXN_TP_NM)
    t.SRC_ACTN_CODE               AS IMP_SRC_ACTN_CD,  -- [MATCHED] DRD source verified against ODI (ODI projects TXN.SRC_ACTN_CODE)
    impct_action_lku.DESC_TEXT    AS IMP_SRC_ACTN_NM,  -- [MATCHED] DRD source verified against ODI (ODI projects IMPCT_ACTION_LKU.DESC_TEXT)  [DRD-notes: Note to Dev team: IMPCT_ACTION_LKU table exists only in CDS DB but not available in SSDS/Lighthouse DB. [6/3/24]: Modified target data type for Oracle and Redsh]
    t.SRC_BUY_SELL_MULTI_ID       AS SIS_DLTD_EV_ID,  -- [MATCHED] DRD source verified against ODI (ODI projects TXN.SRC_BUY_SELL_MULTI_ID)  [DRD-notes: [6/3/24]: Modified target data type for Oracle and Redshift. PBI 1912566]
    cl_val.CL_VAL_NM              AS SIS_DLTD_EV_NM,  -- [MATCHED] DRD source verified against ODI (ODI projects SIS_DLTD_EV.CL_VAL_NM)  [DRD-notes: [6/3/24]: Modified target data type for Oracle and Redshift. PBI 1912566]
    t.USR_ID                      AS SIS_USR_ID,  -- [MATCHED] DRD source verified against ODI (ODI projects TXN.USR_ID)
    t.SRC_PRIM_CL                 AS SIS_AC_CL_CD,  -- [MATCHED] DRD source verified against ODI (ODI projects TXN.SRC_PRIM_CL)
    t.SRC_CNCL_RSN_ID             AS SRC_CNCL_RSN_ID,  -- [MATCHED] DRD source verified against ODI (ODI projects TXN.SRC_CNCL_RSN_ID)
    cl_val.CL_VAL_CODE            AS SRC_CNCL_RSN_CD,  -- [MATCHED] DRD source verified against ODI (ODI projects SRC_CNCL_RSN.CL_VAL_CODE)  [DRD-notes: [6/3/24]: Modified target data type for Oracle and Redshift. PBI 1912566]
    cl_val.CL_VAL_NM              AS SRC_CNCL_RSN_NM,  -- [MATCHED] DRD source verified against ODI (ODI projects SRC_CNCL_RSN.CL_VAL_NM)
    t.SRC_TXN_SEQ_NUM             AS SRC_TXN_SEQ_NUM,  -- [MATCHED] DRD source verified against ODI (ODI projects TXN.SRC_TXN_SEQ_NUM)
    t.DVDN_RCRD_DT                AS DVDN_RCRD_DT,  -- [MATCHED] DRD source verified against ODI (ODI projects TXN.DVDN_RCRD_DT)
    t.SALE_PSN_NUM                AS OWN_IMP_FA_NUM,  -- [MATCHED] DRD source verified against ODI (ODI projects TXN.SALE_PSN_NUM)
    ar_grp_subdim.FA_NUM          AS OWN_FA_NUM,  -- [MATCHED] DRD source verified against ODI (ODI projects AR_GRP_SUBDIM.FA_NUM)  [DRD-notes: [9/11/24]: Reflected the change to use TXN.TD from Product Backlog Item 1912566: Change join condition and update data types for Activity]
    fa_number_v.FA_NUMBER_ENTITY_CODE AS OWN_FA_NUM_ENT_CD,  -- [MATCHED] DRD source verified against ODI (ODI projects FA_NUMBER_V.FA_NUMBER_ENTITY_CODE)  [DRD-notes: [6/8/24]: Modified target data type for Oracle and Redshift. PBI 1912566 [9/11/24]: Reflected the change to use TXN.TD from Product Backlog Item 1912566: Change]
    fa_number_v.RESPONSIBLE_PARTY_EMPLOYEE_ID AS FA_OWN_EMPE_ID,  -- [MATCHED] DRD source verified against ODI (ODI projects FA_NUMBER_V.RESPONSIBLE_PARTY_EMPLOYEE_ID)  [DRD-notes: [6/8/24]: Modified target data type for Oracle and Redshift. PBI 1912566]
    enterprise_entity_dim_v.ENTITY_ENTERPRISE_ID AS OWN_FA_NUM_ENT_ENTP_ID,  -- [MATCHED] DRD source verified against ODI (ODI projects ENTERPRISE_ENTITY_DIM_V.ENTITY_ENTERPRISE_ID)  [DRD-notes: [6/5/24]: Updated data type from VARCHAR to NUMBER. PBI 1912566 [6/25/24]: As a part of PBI 1912566 ROWNUM logic to pick one record at the very last stage was i]
    t.ORIG_SRC_STM_CODE           AS ACAT_CNTRA_FIRM_CLRG_NUM,  -- [MATCHED] DRD source verified against ODI (ODI projects .ORIG_SRC_STM_CODE)
    acats_broker.BROKER_NAME      AS ACAT_CNTRA_FIRM_NM,  -- [MATCHED] DRD source verified against ODI (ODI projects .BROKER_NAME)  [DRD-notes: Note to Dev team: ACATS_BROKER table is available in CDS DB but not available in SSDS/Lighthouse DB. [11/18/25] Corrected orig_src_stm_id with orig_src_stm_code]
    acats_broker.BROKER_SHORT_NAME AS ACAT_CNTRA_FIRM_SHRT_NM,  -- [MATCHED] DRD source verified against ODI (ODI projects .BROKER_SHORT_NAME)  [DRD-notes: Note to Dev team: ACATS_BROKER table is available in CDS DB but not available in SSDS/Lighthouse DB.]
    acats_broker.BROKER_ID_TYPE   AS ACAT_CNTRA_FIRM_CLRG_ID_TP_CD,  -- [MATCHED] DRD source verified against ODI (ODI projects .BROKER_ID_TYPE)  [DRD-notes: Note to Dev team: ACATS_BROKER table is available in CDS DB but not available in SSDS/Lighthouse DB.]
    t.ORIG_SRC_STM_CODE           AS MM_ALT_ID,  -- [MATCHED] DRD source verified against ODI (ODI projects .ORIG_SRC_STM_CODE)
    ar_dim.ORIG_SRC_STM_CD        AS AR_ORIG_SRC_STM_CD,  -- [MATCHED] DRD source verified against ODI (ODI projects AR_DIM.ORIG_SRC_STM_CD)  [DRD-notes: [9/6/24]: Reflected the change to use TXN.TD from Product Backlog Item 1912566: Change join condition and update data types for Activity. [9/17/24]: Changing to]
    t.SRC_STM_ID                  AS SRC_STM_ID,  -- [MATCHED] DRD source verified against ODI (ODI projects TXN.SRC_STM_ID)
    src_stm_dim.SRC_STM_NM        AS SRC_STM_NM,  -- [MATCHED] DRD source verified against ODI (ODI projects SRC_STM_DIM.SRC_STM_NM)
    t.SRC_CXL_REV                 AS SRC_CNCL_X_RVSN_CD,  -- [MATCHED] DRD source verified against ODI (ODI projects TXN.SRC_CXL_REV)  [DRD-notes: [6/3/24]: Modified data type for Redshift from 255 to 3]
    t.SRC_OPT_CLS                 AS SRC_OPT_CLSS_CD,  -- [MATCHED] DRD source verified against ODI (ODI projects TXN.SRC_OPT_CLS)
    t.TXN_REPL_CNT                AS TXN_RCNCL_REPL_CNT,  -- [MATCHED] DRD source verified against ODI (ODI projects TXN.TXN_REPL_CNT)  [DRD-notes: [7/15/24]: Do not add to the view. Product Backlog Item 1948982: Update columns in Activity Fact and Activity Detail Fact]
    t.TXN_ST_ID                   AS TXN_RCNCL_ST_ID,  -- [MATCHED] DRD source verified against ODI (ODI projects TXN.TXN_ST_ID)  [DRD-notes: [7/15/24]: Do not add to the view. Product Backlog Item 1948982: Update columns in Activity Fact and Activity Detail Fact]
    cl_val_2.CL_VAL_CODE          AS TXN_RCNCL_ST_CD,  -- [MATCHED] DRD source verified against ODI (ODI projects TXN_RCNCL_ST.CL_VAL_CODE)  [DRD-notes: [7/15/24]: Do not add to the view. Product Backlog Item 1948982: Update columns in Activity Fact and Activity Detail Fact]
    cl_val_2.CL_VAL_NM            AS TXN_RCNCL_ST_NM,  -- [MATCHED] DRD source verified against ODI (ODI projects TXN_RCNCL_ST.CL_VAL_NM)  [DRD-notes: [7/15/24]: Do not add to the view. Product Backlog Item 1948982: Update columns in Activity Fact and Activity Detail Fact]
    ar_dim.MF_DRC_EXT_AC_NUM      AS MF_AC_NUM,  -- [MATCHED] DRD source verified against ODI (ODI projects .MF_DRC_EXT_AC_NUM)  [DRD-notes: [9/6/24]: Reflected the change to use TXN.TD from Product Backlog Item 1912566: Change join condition and update data types for Activity. [9/17/24]: Changing to]
    ar_dim.ORIG_SRC_STM_AR_ID     AS OFST_ORIG_SRC_STM_AR_ID,  -- [MATCHED] DRD source verified against ODI (ODI projects OFST_AR_DIM.ORIG_SRC_STM_AR_ID)  [DRD-notes: [9/6/24]: Reflected the change to use TXN.TD from Product Backlog Item 1912566: Change join condition and update data types for Activity]
    ar_dim.ORIG_SRC_STM_CD        AS OFST_AR_ORIG_SRC_STM_CD,  -- [MATCHED] DRD source verified against ODI (ODI projects OFST_AR_DIM.ORIG_SRC_STM_CD)  [DRD-notes: [9/6/24]: Reflected the change to use TXN.TD from Product Backlog Item 1912566: Change join condition and update data types for Activity]
    ar_dim.SETL_TP_CD             AS OFST_AR_SETL_TP_CD,  -- [MATCHED] DRD source verified against ODI (ODI projects OFST_AR_DIM.SETL_TP_CD)  [DRD-notes: [9/6/24]: Reflected the change to use TXN.TD from Product Backlog Item 1912566: Change join condition and update data types for Activity]
    ar_dim.SETL_TP                AS OFST_AR_SETL_TP_DSC,  -- [MATCHED] DRD source verified against ODI (ODI projects OFST_AR_DIM.SETL_TP)  [DRD-notes: [9/6/24]: Reflected the change to use TXN.TD from Product Backlog Item 1912566: Change join condition and update data types for Activity]
    ar_dim.SETL_TP_CD             AS AR_SETL_TP_CD,  -- [MATCHED] DRD source verified against ODI (ODI projects AR_DIM.SETL_TP_CD)  [DRD-notes: [9/6/24]: Reflected the change to use TXN.TD from Product Backlog Item 1912566: Change join condition and update data types for Activity. [9/17/24]: Changing to]
    ar_dim.SETL_TP                AS AR_SETL_TP_DSC,  -- [MATCHED] DRD source verified against ODI (ODI projects AR_DIM.SETL_TP)  [DRD-notes: [9/6/24]: Reflected the change to use TXN.TD from Product Backlog Item 1912566: Change join condition and update data types for Activity. [9/17/24]: Changing to]
    ar_dim.ORIG_SRC_STM_AR_ID     AS ORIG_SRC_STM_AR_ID,  -- [MATCHED] DRD source verified against ODI (ODI projects .ORIG_SRC_STM_AR_ID)  [DRD-notes: [9/6/24]: Updated lookup for RJBNK1 ESP accounts. Product Backlog Item 1998220: Fix Activity issues for Historical Load. Also reflected the change to use TXN.TD]
    date_dim.DT_DIM_ID            AS TD_DIM_ID,  -- [MATCHED] DRD source verified against ODI (ODI projects .DT_DIM_ID)
    exg_dim.EXG_DIM_ID            AS EXG_DIM_ID,  -- [MATCHED] DRD source verified against ODI (ODI projects .EXG_DIM_ID)  [DRD-notes: SELECT e.exg_dim_id FROM CIRD_OWNER.EXG_DIM e, CCAL_REPL_OWNER.txn t where t.EXG_CODE = e.EXG_CD and t.txn_id = ap.exec_id]
    acg_tp_dim.ACG_TP_CD          AS ACG_TP_CD,  -- [MATCHED] DRD source verified against ODI (ODI projects ACG_TP_DIM.ACG_TP_CD)
    acg_tp_dim.ACG_TP_DIM_ID      AS ACG_TP_DIM_ID,  -- [MATCHED] DRD source verified against ODI (ODI projects ACG_TP_DIM.ACG_TP_DIM_ID)
    acg_tp_dim.ACG_TP_NM          AS ACG_TP_NM,  -- [MATCHED] DRD source verified against ODI (ODI projects ACG_TP_DIM.ACG_TP_NM)
    apa.ACG_TP_ID                 AS ACG_TP_ID,  -- [MATCHED] DRD source verified against ODI (ODI projects APA.ACG_TP_ID)
    t.ACTV_F                      AS ACTV_F,  -- [MATCHED] DRD source verified against ODI (ODI projects .ACTV_F)
    t.AR_ID                       AS AR_ID,  -- [MATCHED] DRD source verified against ODI (ODI projects TXN.AR_ID)  [DRD-notes: [9/6/24]: Changed source table from APA to TXN. Product Backlog Item 1998220: Fix Activity issues for Historical Load]
    j$txn.BATCH_DT                AS BATCH_DT,  -- [MATCHED] DRD source verified against ODI (ODI projects J_AVY_FACT.BATCH_DT)
    t.BKG_DT                      AS BKG_DT,  -- [MATCHED] DRD source verified against ODI (ODI projects TXN.BKG_DT)
    t.BR_CODE                     AS BR_CD,  -- [MATCHED] DRD source verified against ODI (ODI projects AVY_FACT_STEP5_STG_RT.BR_CODE)
    apa.BKR_AR_ID                 AS BKR_AR_ID,  -- [MATCHED] DRD source verified against ODI (ODI projects APA.BKR_AR_ID)  [DRD-notes: [9/6/24]: Does not require any ETL. It's a direct map from CCAL. [9/17/24]: There is a logic for SIS AR_IDs. Reflecting the same and changing to use TXN.AR_ID p]
    t.BUY_SELL_IND                AS BUY_SELL_IND,  -- [MATCHED] DRD source verified against ODI (ODI projects TXN.BUY_SELL_IND)  [DRD-notes: [6/3/24]: Modified target data type for Oracle and Redshift. PBI 1912566]
    avy_cl.AVY_CGY                AS CASH_AVY_CGY,  -- [MATCHED] DRD source verified against ODI (ODI projects APA_CASH.AVY_CGY)
    avy_cl.DSPL_AVY_CGY           AS CASH_SIMP_DSPL_AVY_CGY,  -- [MATCHED] DRD source verified against ODI (ODI projects APA_CASH.DSPL_AVY_CGY)
    txn_avy_cl.AVY_CL_ID          AS CSH_AVY_CL_ID,  -- [MATCHED] DRD source verified against ODI (ODI projects APA_CASH.AVY_CL_ID)
    avy_cl.AVY_TP                 AS CASH_AVY_TP,  -- [MATCHED] DRD source verified against ODI (ODI projects APA_CASH.AVY_TP)
    avy_cl.DSPL_AVY_TP            AS CASH_SIMP_DSPL_AVY_TP,  -- [MATCHED] DRD source verified against ODI (ODI projects APA_CASH.DSPL_AVY_TP)
    apa.ALT_DSC                   AS CASH_ALT_DSC_TRAILER_2,  -- [MATCHED] DRD source verified against ODI (ODI projects APA.ALT_DSC)
    apa.APA_EXT_QUALFR            AS CASH_APA_EXT_QUALFR,  -- [MATCHED] DRD source verified against ODI (ODI projects APA_CASH.APA_EXT_QUALFR)
    apa.APA_ID                    AS CSH_APA_ID,  -- [MATCHED] DRD source verified against ODI (ODI projects APA_CASH.APA_ID)
    cl_val.CL_VAL_CODE            AS CASH_APA_TP_CD,  -- [MATCHED] DRD source verified against ODI (ODI projects CL_VAL.CL_VAL_CODE)
    cl_val.DSC                    AS CASH_APA_TP_DSC,  -- [MATCHED] DRD source verified against ODI (ODI projects APA_CASH.APA_TP_DSC)
    apa.APA_TP_ID                 AS CSH_APA_TP_ID,  -- [MATCHED] DRD source verified against ODI (ODI projects APA_CASH.APA_TP_ID)
    cl_val.CL_VAL_NM              AS CASH_APA_TP_NM,  -- [MATCHED] DRD source verified against ODI (ODI projects CL_VAL.CL_VAL_NM)  [DRD-notes: [6/3/24]: Modified target data type for Oracle and Redshift. PBI 1912566]
    ccal_cird_pd_map.CIRD_PD_ID   AS CASH_CIRD_PD_ID,  -- [MATCHED] DRD source verified against ODI (ODI projects APA_CASH.CIRD_PD_ID)
    cl_val.CL_VAL_CODE            AS CASH_DB_CR_CD,  -- [MATCHED] DRD source verified against ODI (ODI projects CL_VAL.CL_VAL_CODE)
    cl_val.CL_VAL_NM              AS CASH_DB_CR_NM,  -- [MATCHED] DRD source verified against ODI (ODI projects CL_VAL.CL_VAL_NM)
    apa.APA_DSC                   AS CASH_DSC_TRAILER_1,  -- [MATCHED] DRD source verified against ODI (ODI projects APA.APA_DSC)
    t.CF_GEN_F                    AS CF_GEN_F,  -- [MATCHED] DRD source verified against ODI (ODI projects TXN.CF_GEN_F)
    cash_pos_tp_dim.CASH_POS_TP_CD AS CASH_POS_TP_CD,  -- [MATCHED] DRD source verified against ODI (ODI projects CASH_POS_TP_DIM.CASH_POS_TP_CD)
    cash_pos_tp_dim.CASH_POS_TP_DIM_ID AS CASH_POS_TP_DIM_ID,  -- [MATCHED] DRD source verified against ODI (ODI projects .CASH_POS_TP_DIM_ID)
    cash_pos_tp_dim.CASH_POS_TP_NM AS CASH_POS_TP_NM,  -- [MATCHED] DRD source verified against ODI (ODI projects CASH_POS_TP_DIM.CASH_POS_TP_NM)
    apa.CASH_POS_TP_ID            AS CASH_POS_TP_ID,  -- [MATCHED] DRD source verified against ODI (ODI projects APA.CASH_POS_TP_ID)
    apa.PD_ID                     AS CASH_PD_ID,  -- [MATCHED] DRD source verified against ODI (ODI projects APA.PD_ID)
    imt_pd_dim.IMT_PD_DIM_ID      AS CASH_PD_DIM_ID,  -- [MATCHED] DRD source verified against ODI (ODI projects .IMT_PD_DIM_ID)  [DRD-notes: [9/6/24]: Reflected the change to use TXN.TD from Product Backlog Item 1912566: Change join condition and update data types for Activity]
    apa.SRC_SEQ_NUM               AS CASH_SRC_SEQ_NUM,  -- [MATCHED] DRD source verified against ODI (ODI projects APA_CASH.SRC_SEQ_NUM)
    apa.STM_BASE_CCY_AMT          AS CASH_SBC_AMT,  -- [MATCHED] DRD source verified against ODI (ODI projects APA.STM_BASE_CCY_AMT)
    apa.TXN_AMT                   AS CASH_TXN_AMT,  -- [MATCHED] DRD source verified against ODI (ODI projects APA_CASH.TXN_AMT)
    apa.CLNT_FRIENDLY_DESC        AS CLNT_FRIENDLY_DSC,  -- [MATCHED] DRD source verified against ODI (ODI projects .CLNT_FRIENDLY_DESC)
    t.CRT_DTM                     AS CRT_DTM,  -- [MATCHED] DRD source verified against ODI (ODI projects AVY_FACT_STEP3_STG_RT.CRT_DTM)
    t.CRT_USR_NM                  AS CRT_USR_NM,  -- [MATCHED] DRD source verified against ODI (ODI projects AVY_FACT_STEP3_STG_RT.CRT_USR_NM)
    apa.TXN_ISO_CCY_CODE          AS CCY_CD,  -- [MATCHED] DRD source verified against ODI (ODI projects .TXN_ISO_CCY_CODE)
    ccy_dim.CCY_DIM_ID            AS CCY_DIM_ID,  -- [MATCHED] DRD source verified against ODI (ODI projects CCY_DIM.CCY_DIM_ID)
    cl_val.CL_VAL_CODE            AS DOL_IND_CD,  -- [MATCHED] DRD source verified against ODI (ODI projects CD_CL_VAL.CL_VAL_CODE)  [DRD-notes: select cv.cl_val_code from  ccal_repl_owner.txn t, ccal_repl_owner.cl_val cv where t.dol_ind_id = cv.cl_val_id and t.txn_id = ap.exec_id]
    t.DOL_IND_ID                  AS DOL_IND_ID,  -- [MATCHED] DRD source verified against ODI (ODI projects TXN.DOL_IND_ID)
    cl_val.CL_VAL_NM              AS DOL_IND_NM,  -- [MATCHED] DRD source verified against ODI (ODI projects CD_CL_VAL.CL_VAL_NM)  [DRD-notes: select cv.cl_val_nm from  ccal_repl_owner.txn t, ccal_repl_owner.cl_val cv where t.dol_ind_id = cv.cl_val_id and t.txn_id = ap.exec_id]
    t.EXG_CODE                    AS EXG_CD,  -- [MATCHED] DRD source verified against ODI (ODI projects TXN.EXG_CODE)  [DRD-notes: [9/6/24]: Updated to be sourced from CCAL. Product Backlog Item 1998220: Fix Activity issues for Historical Load]
    exg_dim.EXG_NM                AS EXG_NM,  -- [MATCHED] DRD source verified against ODI (ODI projects EXG_DIM.EXG_NM)  [DRD-notes: SELECT e.exg_nm FROM CIRD_OWNER.EXG_DIM e, CCAL_REPL_OWNER.txn t where t.EXG_CODE = e.EXG_CD and t.txn_id = ap.exec_id]
    t.EXEC_DTM                    AS EXEC_DTM,  -- [MATCHED] DRD source verified against ODI (ODI projects TXN.EXEC_DTM)
    cl_val.CL_VAL_CODE            AS EXEC_SBTP_CD,  -- [MATCHED] DRD source verified against ODI (ODI projects EXECUTION_SUBTYPE.CL_VAL_CODE)
    cl_val.DSC                    AS EXEC_SBTP_DSC,  -- [MATCHED] DRD source verified against ODI (ODI projects EXECUTION_SUBTYPE.DSC)
    t.EXEC_SBTP_ID                AS EXEC_SBTP_ID,  -- [MATCHED] DRD source verified against ODI (ODI projects TXN.EXEC_SBTP_ID)
    cl_val.CL_VAL_NM              AS EXEC_SBTP_NM,  -- [MATCHED] DRD source verified against ODI (ODI projects EXECUTION_SUBTYPE.CL_VAL_NM)
    cl_val.CL_VAL_CODE            AS EXEC_TP_CD,  -- [MATCHED] DRD source verified against ODI (ODI projects EXECUTION_TYPE.CL_VAL_CODE)
    cl_val.DSC                    AS EXEC_TP_DSC,  -- [MATCHED] DRD source verified against ODI (ODI projects EXECUTION_TYPE.DSC)
    t.EXEC_TP_ID                  AS EXEC_TP_ID,  -- [MATCHED] DRD source verified against ODI (ODI projects TXN.EXEC_TP_ID)
    cl_val.CL_VAL_NM              AS EXEC_TP_NM,  -- [MATCHED] DRD source verified against ODI (ODI projects EXECUTION_TYPE.CL_VAL_NM)
    t.FA_NUM                      AS FA_NUM,  -- [MATCHED] DRD source verified against ODI (ODI projects TXN.FA_NUM)
    lgcy_cncl_cmpln_rsn_tp_dim.LGCY_CNCL_CMPLN_RSN_TP_CD AS LGCY_CNCL_CMPLN_RSN_TP_CD,  -- [MATCHED] DRD source verified against ODI (ODI projects LGCY_CNCL_CMPLN_RSN_TP_DIM.LGCY_CNCL_CMPLN_RSN_TP_CD)
    lgcy_cncl_cmpln_rsn_tp_dim.LGCY_CNCL_CMPLN_RSN_TP_DIM_ID AS LGCY_CNCL_CMPLN_RSN_DIM_ID,  -- [MATCHED] DRD source verified against ODI (ODI projects .LGCY_CNCL_CMPLN_RSN_TP_DIM_ID)  [DRD-notes: select dl.LGCY_CNCL_CMPLN_RSN_TP_ID from ccal_repl_owner.txn t, transactions_owner.LGCY_CNCL_CMPLN_RSN_TP_DIM dl, ccal_repl_owner.apa ap WHERE t.LGCY_CNCL_CMPLN]
    lgcy_cncl_cmpln_rsn_tp_dim.LGCY_CNCL_CMPLN_RSN_TP_NM AS LGCY_CNCL_CMPLN_RSN_TP_NM,  -- [MATCHED] DRD source verified against ODI (ODI projects LGCY_CNCL_CMPLN_RSN_TP_DIM.LGCY_CNCL_CMPLN_RSN_TP_NM)
    t.LGCY_CNCL_CMPLN_RSN_TP_ID   AS LGCY_CNCL_CMPLN_RSN_TP_ID,  -- [MATCHED] DRD source verified against ODI (ODI projects TXN.LGCY_CNCL_CMPLN_RSN_TP_ID)
    lgcy_cncl_cmpln_src_tp_dim.LGCY_CNCL_CMPLN_SRC_TP_CD AS LGCY_CNCL_CMPLN_SRC_TP_CD,  -- [MATCHED] DRD source verified against ODI (ODI projects LGCY_CNCL_CMPLN_SRC_TP_DIM.LGCY_CNCL_CMPLN_SRC_TP_CD)
    lgcy_cncl_cmpln_src_tp_dim.LGCY_CNCL_CMPLN_SRC_TP_DIM_ID AS LGCY_CNCL_CMPLN_SRC_DIM_ID,  -- [MATCHED] DRD source verified against ODI (ODI projects .LGCY_CNCL_CMPLN_SRC_TP_DIM_ID)  [DRD-notes: [6/3/24]: Updated Source Attribute Name from LGCY_CNCL_CMPLN_RSN_DIM_ID to LGCY_CNCL_CMPLN_SRC_TP_DIM_ID]
    lgcy_cncl_cmpln_src_tp_dim.LGCY_CNCL_CMPLN_SRC_TP_NM AS LGCY_CNCL_CMPLN_SRC_TP_NM,  -- [MATCHED] DRD source verified against ODI (ODI projects LGCY_CNCL_CMPLN_SRC_TP_DIM.LGCY_CNCL_CMPLN_SRC_TP_NM)
    t.LGCY_CNCL_CMPLN_SRC_TP_ID   AS LGCY_CNCL_CMPLN_SRC_TP_ID,  -- [MATCHED] DRD source verified against ODI (ODI projects TXN.LGCY_CNCL_CMPLN_SRC_TP_ID)
    lgcy_mkt_tp_dim.LGCY_MKT_TP_CD AS LGCY_MKT_TP_CD,  -- [MATCHED] DRD source verified against ODI (ODI projects LGCY_MKT_TP_DIM.LGCY_MKT_TP_CD)
    lgcy_mkt_tp_dim.LGCY_MKT_TP_DIM_ID AS LGCY_MKT_TP_DIM_ID,  -- [MATCHED] DRD source verified against ODI (ODI projects .LGCY_MKT_TP_DIM_ID)
    lgcy_mkt_tp_dim.LGCY_MKT_TP_NM AS LGCY_MKT_TP_NM,  -- [MATCHED] DRD source verified against ODI (ODI projects LGCY_MKT_TP_DIM.LGCY_MKT_TP_NM)
    t.LGCY_MKT_TP_ID              AS LGCY_MKT_TP_ID,  -- [MATCHED] DRD source verified against ODI (ODI projects TXN.LGCY_MKT_TP_ID)
    lgcy_trd_cpcty_tp_dim.LGCY_TRD_CPCTY_TP_CD AS LGCY_TRD_CPCTY_TP_CD,  -- [MATCHED] DRD source verified against ODI (ODI projects .LGCY_TRD_CPCTY_TP_CD)  [DRD-notes: [10/1/24]: Added condition for INSTBO1 per Product Backlog Item 2033631: Change Trade Capacity lookup to use CL_VAL for Impact Trades]
    lgcy_trd_cpcty_tp_dim.LGCY_TRD_CPCTY_TP_DIM_ID AS LGCY_TRD_CPCTY_TP_DIM_ID,  -- [MATCHED] DRD source verified against ODI (ODI projects .LGCY_TRD_CPCTY_TP_DIM_ID)  [DRD-notes: [10/1/24]: It is expected to have 0 for Impact trades since "Impact Capacity" schema is not in LGCY_TRD_CPCTY_TP_DIM]
    lgcy_trd_cpcty_tp_dim.LGCY_TRD_CPCTY_TP_NM AS LGCY_TRD_CPCTY_TP_NM,  -- [MATCHED] DRD source verified against ODI (ODI projects .LGCY_TRD_CPCTY_TP_NM)  [DRD-notes: [10/1/24]: Added condition for INSTBO1 per Product Backlog Item 2033631: Change Trade Capacity lookup to use CL_VAL for Impact Trades]
    t.LGCY_TRD_CPCTY_TP_ID        AS LGCY_TRD_CPCTY_TP_ID,  -- [MATCHED] DRD source verified against ODI (ODI projects TXN.LGCY_TRD_CPCTY_TP_ID)
    apa.OFST_AR_ID                AS OFST_AR_ID,  -- [MATCHED] DRD source verified against ODI (ODI projects APA.OFST_AR_ID)
    t.OPTS_CLSS_CODE              AS OPT_CLSS_CD,  -- [MATCHED] DRD source verified against ODI (ODI projects TXN.OPTS_CLSS_CODE)  [DRD-notes: [6/3/24]: Modified target data type for Oracle and Redshift. PBI 1912566]
    cl_val.CL_VAL_CODE            AS OMS_EXEC_TP_CD,  -- [MATCHED] DRD source verified against ODI (ODI projects OMS_EXEC_TP.CL_VAL_CODE)
    cl_val.DSC                    AS OMS_EXEC_TP_DSC,  -- [MATCHED] DRD source verified against ODI (ODI projects OMS_EXEC_TP.DSC)
    t.OMS_EXEC_TP_ID              AS OMS_EXEC_TP_ID,  -- [MATCHED] DRD source verified against ODI (ODI projects TXN.OMS_EXEC_TP_ID)
    cl_val.CL_VAL_NM              AS OMS_EXEC_TP_NM,  -- [MATCHED] DRD source verified against ODI (ODI projects OMS_EXEC_TP.CL_VAL_NM)  [DRD-notes: [6/3/24]: Modified target data type for Oracle and Redshift. PBI 1912566]
    t.OMS_ORDR_KEY                AS OMS_ORDR_KEY,  -- [MATCHED] DRD source verified against ODI (ODI projects TXN.OMS_ORDR_KEY)
    t.ORIG_BKG_DT                 AS ORIG_BKG_DT,  -- [MATCHED] DRD source verified against ODI (ODI projects TXN.ORIG_BKG_DT)
    t.ORIG_TRD_NUM                AS ORIG_TRD_NUM,  -- [MATCHED] DRD source verified against ODI (ODI projects TXN.ORIG_TRD_NUM)
    t.ORIG_TD                     AS ORIG_TD,  -- [MATCHED] DRD source verified against ODI (ODI projects TXN.ORIG_TD)
    src_stm_dim.SRC_STM_DIM_ID    AS REL_TXN_SRC_STM_DIM_ID,  -- [MATCHED] DRD source verified against ODI (ODI projects .SRC_STM_DIM_ID)
    t.SRC_STM_ID                  AS REL_TXN_SRC_STM_ID,  -- [MATCHED] DRD source verified against ODI (ODI projects TXN_RLTNP_TXN.SRC_STM_ID)  [DRD-notes: [7/15/24]: Do not add to the view. Product Backlog Item 1948982: Update columns in Activity Fact and Activity Detail Fact]
    src_stm_dim.SRC_STM_CD        AS REL_TXN_SRC_STM_CD,  -- [MATCHED] DRD source verified against ODI (ODI projects TXN_RLTNP_SRC_STM_DIM.SRC_STM_CD)  [DRD-notes: [7/15/24]: Do not add to the view. Product Backlog Item 1948982: Update columns in Activity Fact and Activity Detail Fact]
    txn_rltnp.TXN_RLTNP_TP_ID     AS REL_TXN_RLTNP_TP_ID,  -- [MATCHED] DRD source verified against ODI (ODI projects TXN_RLTNP.TXN_RLTNP_TP_ID)
    cl_val.CL_VAL_CODE            AS REL_TXN_RLTNP_TP_CD,  -- [MATCHED] DRD source verified against ODI (ODI projects REL_TXN_RLTNP_TP.CL_VAL_CODE)
    cl_val.CL_VAL_NM              AS REL_TXN_RLTNP_TP_NM,  -- [MATCHED] DRD source verified against ODI (ODI projects REL_TXN_RLTNP_TP.CL_VAL_NM)
    apa.SALE_CHRG_RATE            AS SALE_CHRG_RATE_MULTI_NUM,  -- [MATCHED] DRD source verified against ODI (ODI projects .SALE_CHRG_RATE)  [DRD-notes: TXN.TXN_ID = APA.EXEC_ID SALE_CHRG_RATE where SALE_CHRG_RATE_TP_ID = 2507 ELSE NULL Ref: Bug 2198208: Sales Charges are not populated for MFL4 trades due to APA]
    apa.SALE_CHRG_RATE            AS SALE_CHRG_RATE_PCT,  -- [MATCHED] DRD source verified against ODI (ODI projects .SALE_CHRG_RATE)  [DRD-notes: Bug 2198208: Sales Charges are not populated for MFL4 trades due to APACSH04 being dropped]
    cl_val.CL_VAL_CODE            AS SALE_CHRG_RATE_TP_CD,  -- [MATCHED] DRD source verified against ODI (ODI projects SALE_CHARGE_RATE_TYPE.CL_VAL_CODE)  [DRD-notes: Bug 2198208: Sales Charges are not populated for MFL4 trades due to APACSH04 being dropped]
    apa.SALE_CHRG_RATE_TP_ID      AS SALE_CHRG_RATE_TP_ID,  -- [MATCHED] DRD source verified against ODI (ODI projects APA.SALE_CHRG_RATE_TP_ID)  [DRD-notes: Bug 2198208: Sales Charges are not populated for MFL4 trades due to APACSH04 being dropped]
    cl_val.CL_VAL_NM              AS SALE_CHRG_RATE_TP_NM,  -- [MATCHED] DRD source verified against ODI (ODI projects SALE_CHARGE_RATE_TYPE.CL_VAL_NM)  [DRD-notes: Bug 2198208: Sales Charges are not populated for MFL4 trades due to APACSH04 being dropped]
    avy_cl.AVY_CGY                AS SCR_AVY_CGY,  -- [MATCHED] DRD source verified against ODI (ODI projects APA_SECURITY.AVY_CGY)
    avy_cl.DSPL_AVY_CGY           AS SCR_SIMP_DSPL_AVY_CGY,  -- [MATCHED] DRD source verified against ODI (ODI projects APA_SECURITY.DSPL_AVY_CGY)
    avy_cl.AVY_CL_ID              AS SEC_AVY_CL_ID,  -- [MATCHED] DRD source verified against ODI (ODI projects APA_SECURITY.AVY_CL_ID)
    avy_cl.AVY_TP                 AS SCR_AVY_TP,  -- [MATCHED] DRD source verified against ODI (ODI projects APA_SECURITY.AVY_TP)
    avy_cl.DSPL_AVY_TP            AS SCR_SIMP_DSPL_AVY_TP,  -- [MATCHED] DRD source verified against ODI (ODI projects APA_SECURITY.DSPL_AVY_TP)
    apa.ALT_DSC                   AS SEC_ALT_DSC_TRAILER_2,  -- [MATCHED] DRD source verified against ODI (ODI projects APA.ALT_DSC)
    apa.APA_EXT_QUALFR            AS SEC_APA_EXT_QUALFR,  -- [MATCHED] DRD source verified against ODI (ODI projects APA_SECURITY.APA_EXT_QUALFR)
    apa.APA_ID                    AS SEC_APA_ID,  -- [MATCHED] DRD source verified against ODI (ODI projects APA_SECURITY.APA_ID)
    cl_val.CL_VAL_CODE            AS SCR_APA_TP_CD,  -- [MATCHED] DRD source verified against ODI (ODI projects CL_VAL.CL_VAL_CODE)
    cl_val.DSC                    AS SCR_APA_TP_DSC,  -- [MATCHED] DRD source verified against ODI (ODI projects APA_SECURITY.APA_TP_DSC)
    apa.APA_TP_ID                 AS SEC_APA_TP_ID,  -- [MATCHED] DRD source verified against ODI (ODI projects APA_SECURITY.APA_TP_ID)
    cl_val.CL_VAL_NM              AS SCR_APA_TP_NM,  -- [MATCHED] DRD source verified against ODI (ODI projects CL_VAL.CL_VAL_NM)  [DRD-notes: [6/3/24]: Modified target data type for Oracle and Redshift. PBI 1912566]
    ccal_cird_pd_map.CIRD_PD_ID   AS SEC_CIRD_PD_ID,  -- [MATCHED] DRD source verified against ODI (ODI projects APA_SECURITY.CIRD_PD_ID)
    cl_val.CL_VAL_CODE            AS SEC_DB_CR_CD,  -- [MATCHED] DRD source verified against ODI (ODI projects CL_VAL.CL_VAL_CODE)
    cl_val.CL_VAL_NM              AS SEC_DB_CR_NM,  -- [MATCHED] DRD source verified against ODI (ODI projects CL_VAL.CL_VAL_NM)
    apa.APA_DSC                   AS SEC_DSC_TRAILER_1,  -- [MATCHED] DRD source verified against ODI (ODI projects APA.APA_DSC)
    apa.ORIG_QTY                  AS SEC_ORIG_QTY,  -- [MATCHED] DRD source verified against ODI (ODI projects APA.ORIG_QTY)
    apa.SRC_PD_ID                 AS SEC_SRC_CUSIP,  -- [MATCHED] DRD source verified against ODI (ODI projects APA.SRC_PD_ID)  [DRD-notes: [6/3/24]: Modified target data type for Oracle and Redshift]
    apa.PD_ID                     AS SEC_PD_ID,  -- [MATCHED] DRD source verified against ODI (ODI projects APA.PD_ID)
    imt_pd_dim.IMT_PD_DIM_ID      AS SEC_PD_DIM_ID,  -- [MATCHED] DRD source verified against ODI (ODI projects .IMT_PD_DIM_ID)  [DRD-notes: [9/6/24]: Reflected the change to use TXN.TD from Product Backlog Item 1912566: Change join condition and update data types for Activity]
    apa.SCR_PRC_IN_TXN_CCY        AS SEC_PRC_IN_TXN_CCY,  -- [MATCHED] DRD source verified against ODI (ODI projects APA.SCR_PRC_IN_TXN_CCY)
    apa.SCR_PRC_IN_SBC            AS SEC_SRC_PRC_IN_SBC,  -- [MATCHED] DRD source verified against ODI (ODI projects APA.SCR_PRC_IN_SBC)
    apa.SRC_SEQ_NUM               AS SEC_SRC_SEQ_NUM,  -- [MATCHED] DRD source verified against ODI (ODI projects APA_SECURITY.SRC_SEQ_NUM)
    apa.STM_BASE_CCY_AMT          AS SEC_SBC_AMT,  -- [MATCHED] DRD source verified against ODI (ODI projects APA.STM_BASE_CCY_AMT)
    apa.TXN_AMT                   AS SEC_TXN_AMT,  -- [MATCHED] DRD source verified against ODI (ODI projects APA_SECURITY.TXN_AMT)
    t.SD                          AS SD,  -- [MATCHED] DRD source verified against ODI (ODI projects TXN.SD)
    date_dim.DT_DIM_ID            AS SD_DIM_ID,  -- [MATCHED] DRD source verified against ODI (ODI projects .DT_DIM_ID)
    t.SRC_CRT_USRNM               AS SRC_CRT_USRNM,  -- [MATCHED] DRD source verified against ODI (ODI projects TXN.SRC_CRT_USRNM)
    apa.SRC_EFF_DT                AS SRC_EFF_DT,  -- [MATCHED] DRD source verified against ODI (ODI projects APA.SRC_EFF_DT)
    src_entr_cnl_tp_dim.SRC_ENTR_CNL_TP_CD AS SRC_ENTR_CNL_TP_CD,  -- [MATCHED] DRD source verified against ODI (ODI projects SRC_ENTR_CNL_TP_DIM.SRC_ENTR_CNL_TP_CD)
    src_entr_cnl_tp_dim.SRC_ENTR_CNL_TP_DIM_ID AS SRC_ENTR_CNL_TP_DIM_ID,  -- [MATCHED] DRD source verified against ODI (ODI projects .SRC_ENTR_CNL_TP_DIM_ID)
    src_entr_cnl_tp_dim.SRC_ENTR_CNL_TP_NM AS SRC_ENTR_CNL_TP_NM,  -- [MATCHED] DRD source verified against ODI (ODI projects SRC_ENTR_CNL_TP_DIM.SRC_ENTR_CNL_TP_NM)
    t.SRC_ENTR_CNL_TP_ID          AS SRC_ENTR_CNL_TP_ID,  -- [MATCHED] DRD source verified against ODI (ODI projects TXN.SRC_ENTR_CNL_TP_ID)
    t.SRC_ENTR_DTM                AS SRC_ENTR_DTM,  -- [MATCHED] DRD source verified against ODI (ODI projects TXN.SRC_ENTR_DTM)
    src_pcs_tp_dim.SRC_PCS_TP_DIM_ID AS SRC_PCS_TP_DIM_ID,  -- [MATCHED] DRD source verified against ODI (ODI projects .SRC_PCS_TP_DIM_ID)
    t.SRC_PCS_TP_ID               AS SRC_PCS_TP_ID,  -- [MATCHED] DRD source verified against ODI (ODI projects TXN.SRC_PCS_TP_ID)
    src_pcs_tp_dim.SRC_PCS_TP_CD  AS SRC_PCS_TP_CD,  -- [MATCHED] DRD source verified against ODI (ODI projects SRC_PCS_TP_DIM.SRC_PCS_TP_CD)
    src_pcs_tp_dim.SRC_PCS_TP_NM  AS SRC_PCS_TP_NM,  -- [MATCHED] DRD source verified against ODI (ODI projects SRC_PCS_TP_DIM.SRC_PCS_TP_NM)
    src_stm_dim.SRC_STM_CD        AS SRC_STM_CD,  -- [MATCHED] DRD source verified against ODI (ODI projects SRC_STM_DIM.SRC_STM_CD)
    src_stm_dim.SRC_STM_DIM_ID    AS TXN_SRC_STM_DIM_ID,  -- [MATCHED] DRD source verified against ODI (ODI projects .SRC_STM_DIM_ID)
    t.SRC_TXN_CODE                AS SRC_TXN_CODE,  -- [MATCHED] DRD source verified against ODI (ODI projects TXN.SRC_TXN_CODE)
    apa.STM_BASE_CCY_CLC_DTM      AS SBC_CCY_CALC_DT,  -- [MATCHED] DRD source verified against ODI (ODI projects APA.STM_BASE_CCY_CLC_DTM)
    apa.STM_BASE_ISO_CCY_CODE     AS SBC_CCY_CD,  -- [MATCHED] DRD source verified against ODI (ODI projects .STM_BASE_ISO_CCY_CODE)
    ccy_dim.CCY_DIM_ID            AS SBC_CCY_DIM_ID,  -- [MATCHED] DRD source verified against ODI (ODI projects SEC_CCY_DIM.CCY_DIM_ID)
    apa.STM_BASE_CCY_EXG_RATE     AS SBC_EXG_RATE,  -- [MATCHED] DRD source verified against ODI (ODI projects APA.STM_BASE_CCY_EXG_RATE)
    txn_rltnp.TRGT_TXN_ID         AS REL_TXN_ID,  -- [MATCHED] DRD source verified against ODI (ODI projects TXN_RLTNP.TRGT_TXN_ID)  [DRD-notes: Note to Dev Team: Rename this column only at table level but in SSDS_DAL_OWNER view retain existing name 'TARGET_TRANSACTION_ID' as-is, so that there won't be a]
    t.TD                          AS TD,  -- [MATCHED] DRD source verified against ODI (ODI projects TXN.TD)
    t.TRD_NUM                     AS TRD_NUM,  -- [MATCHED] DRD source verified against ODI (ODI projects TXN.TRD_NUM)
    trd_slct_tp_dim.TRD_SLCT_TP_DIM_ID AS TRD_SLCT_TP_DIM_ID,  -- [MATCHED] DRD source verified against ODI (ODI projects .TRD_SLCT_TP_DIM_ID)  [DRD-notes: https://tfs.rjf.com/tfs/RJ_Git_Collection/CDSIntegration/_workitems/edit/1707564 The change will be to populate all TRD_SLCT_TP_ID = '2380' which indicates Soli]
    t.TRD_SLCT_TP_ID              AS TRD_SLCT_TP_ID,  -- [MATCHED] DRD source verified against ODI (ODI projects TXN.TRD_SLCT_TP_ID)  [DRD-notes: https://tfs.rjf.com/tfs/RJ_Git_Collection/CDSIntegration/_workitems/edit/1707564 The change will be to populate all TRD_SLCT_TP_ID = '2380' which indicates Soli]
    trd_slct_tp_dim.TRD_SLCT_TP_CD AS TRD_SLCT_TP_CD,  -- [MATCHED] DRD source verified against ODI (ODI projects TRD_SLCT_TP_DIM.TRD_SLCT_TP_CD)  [DRD-notes: https://tfs.rjf.com/tfs/RJ_Git_Collection/CDSIntegration/_workitems/edit/1707564 The change will be to populate all TRD_SLCT_TP_ID = '2380' which indicates Soli]
    trd_slct_tp_dim.TRD_SLCT_TP_NM AS TRD_SLCT_TP_NM,  -- [MATCHED] DRD source verified against ODI (ODI projects TRD_SLCT_TP_DIM.TRD_SLCT_TP_NM)
    t.TXN_CL_F                    AS TXN_CL_F,  -- [MATCHED] DRD source verified against ODI (ODI projects TXN.TXN_CL_F)
    t.TXN_ID                      AS TXN_ID,  -- [MATCHED] DRD source verified against ODI (ODI projects TXN.TXN_ID)
    t.TXN_SRC_KEY                 AS TXN_SRC_KEY,  -- [MATCHED] DRD source verified against ODI (ODI projects TXN.TXN_SRC_KEY)
    cl_val.CL_VAL_CODE            AS TXN_SUB_TP_CD,  -- [MATCHED] DRD source verified against ODI (ODI projects TRANSACTION_SUBTYPE.CL_VAL_CODE)
    cl_val.DSC                    AS TXN_SUB_TP_DSC,  -- [MATCHED] DRD source verified against ODI (ODI projects TRANSACTION_SUBTYPE.DSC)
    t.TXN_SBTP_ID                 AS TXN_SBTP_ID,  -- [MATCHED] DRD source verified against ODI (ODI projects TXN.TXN_SBTP_ID)
    cl_val.CL_VAL_NM              AS TXN_SUB_TP_NM,  -- [MATCHED] DRD source verified against ODI (ODI projects TRANSACTION_SUBTYPE.CL_VAL_NM)
    cl_val.CL_VAL_CODE            AS TXN_TP_CD,  -- [MATCHED] DRD source verified against ODI (ODI projects TRANSACTION_TYPE.CL_VAL_CODE)
    cl_val.DSC                    AS TXN_TP_DSC,  -- [MATCHED] DRD source verified against ODI (ODI projects TRANSACTION_TYPE.DSC)
    t.TXN_TP_ID                   AS TXN_TP_ID,  -- [MATCHED] DRD source verified against ODI (ODI projects TXN.TXN_TP_ID)
    cl_val.CL_VAL_NM              AS TXN_TP_NM,  -- [MATCHED] DRD source verified against ODI (ODI projects TRANSACTION_TYPE.CL_VAL_NM)
    t.ORIG_SRC_STM_ID             AS ORIG_SRC_STM_ID,  -- [MATCHED] DRD source verified against ODI (ODI projects TXN.ORIG_SRC_STM_ID)
    t.ORIG_SRC_STM_CODE           AS ORIG_SRC_STM_CD,  -- [MATCHED] DRD source verified against ODI (ODI projects TXN.ORIG_SRC_STM_CODE)  [DRD-notes: [6/3/24]: Modified target data type for Oracle and Redshift. PBI 1912566. Updated Source Attribute from ORIG_SRC_STM_CD to ORIG_SRC_STM_CODE]
    ar_dim.AR_DIM_ID              AS BKR_AR_DIM_ID,  -- [MATCHED] DRD source verified against ODI (ODI projects .AR_DIM_ID)  [DRD-notes: [9/6/24]: Reflected the change to use TXN.TD from Product Backlog Item 1912566: Change join condition and update data types for Activity. [9/17/24]: NULL in the]
    ar_dim.AR_DIM_ID              AS OFST_AR_DIM_ID,  -- [MATCHED] DRD source verified against ODI (ODI projects OFST_AR_DIM.AR_DIM_ID)  [DRD-notes: [9/6/24]: Reflected the change to use TXN.TD from Product Backlog Item 1912566: Change join condition and update data types for Activity]
    ar_dim.AR_DIM_ID              AS AR_DIM_ID,  -- [MATCHED] DRD source verified against ODI (ODI projects .AR_DIM_ID)  [DRD-notes: [9/6/24]: Reflected the change to use TXN.TD from Product Backlog Item 1912566: Change join condition and update data types for Activity. [9/17/24]: NULL in the]
    ('SESS_NAME')                 AS LAST_UDT_USR_NM,  -- [ODI_HELPER_FILL] DRD silent for LAST_UDT_USR_NM; ODI populates it as "'SESS_NAME'" (self-contained) -- using ODI realization (helper) to match ODI and avoid a spurious NULL.
    (SYSDATE)                     AS LAST_UDT_DTM,  -- [RECOVERED_FROM_PROSE] DRD wrote intent as English: 'Audit column. DEFAULT USER'; comparator MATCHED ODI's SQL realization: 'SYSDATE'.  All alias prefixes resolve in our FROM graph.
    (0)                           AS SESS_NO,  -- [ODI_HELPER_FILL] DRD silent for SESS_NO; ODI populates it as '0' (self-contained) -- using ODI realization (helper) to match ODI and avoid a spurious NULL.
    apa.OPT_SYMB                  AS SCR_OPT_SYMB,  -- [MATCHED] DRD source verified against ODI (ODI projects APA.OPT_SYMB)  [DRD-notes: [10/24/24]: Added new field per Product Backlog Item 2064326: Add Option Symbol attribute to Activity Facts [11/01/24]: Populated Physical Name Attribute]
    cl_val.CL_VAL_CODE            AS DRVD_TRD_CPCTY_CD,  -- [MATCHED] DRD source verified against ODI (ODI projects DRVD_TRD_CPCTY.CL_VAL_CODE)  [DRD-notes: Use CL_SCM_ID = 104]
    cl_val.CL_VAL_NM              AS DRVD_TRD_CPCTY_NM,  -- [MATCHED] DRD source verified against ODI (ODI projects DRVD_TRD_CPCTY.CL_VAL_NM)  [DRD-notes: Use CL_SCM_ID = 104]
    t.DRVD_TRD_CPCTY_TP_ID        AS DRVD_TRD_CPCTY_ID,  -- [MATCHED] DRD source verified against ODI (ODI projects TXN.DRVD_TRD_CPCTY_TP_ID)  [DRD-notes: Per PBI- 2063884]
    t.ADL_TRD_INSR                AS ADL_TRD_INSR,  -- [MATCHED] DRD source verified against ODI (ODI projects TXN.ADL_TRD_INSR)  [DRD-notes: [05/28/25]: Product Backlog Item 2030710: Populate new columns for trade and fee attributes for Activity]
    apa.TRD_FCTR_RATE             AS TRD_FCTR_RATE,  -- [MATCHED] DRD source verified against ODI (ODI projects APA.TRD_FCTR_RATE)  [DRD-notes: [05/28/25]: Product Backlog Item 2030710: Populate new columns for trade and fee attributes for Activity]
    apa.MRKUP_RATE                AS MRKUP_RATE,  -- [MATCHED] DRD source verified against ODI (ODI projects APA.MRKUP_RATE)  [DRD-notes: [05/28/25]: Product Backlog Item 2030710: Populate new columns for trade and fee attributes for Activity]
    apa.STD_CMSN_AMT              AS STD_CMSN_AMT,  -- [MATCHED] DRD source verified against ODI (ODI projects APA.STD_CMSN_AMT)  [DRD-notes: [05/28/25]: Product Backlog Item 2030710: Populate new columns for trade and fee attributes for Activity]
    fip.STM_BASE_CCY_AMT          AS ACT_CMSN_AMT,  -- [MATCHED] DRD source verified against ODI (ODI projects .STM_BASE_CCY_AMT)  [DRD-notes: [05/28/25]: Product Backlog Item 2030710: Populate new columns for trade and fee attributes for Activity]
    fip.STM_BASE_CCY_AMT          AS TRD_PCS_FEE_AMT,  -- [MATCHED] DRD source verified against ODI (ODI projects .STM_BASE_CCY_AMT)  [DRD-notes: [05/28/25]: Product Backlog Item 2030710: Populate new columns for trade and fee attributes for Activity]
    fip.STM_BASE_CCY_AMT          AS SEC_FEE_AMT,  -- [MATCHED] DRD source verified against ODI (ODI projects .STM_BASE_CCY_AMT)  [DRD-notes: [05/28/25]: Product Backlog Item 2030710: Populate new columns for trade and fee attributes for Activity]
    fip.STM_BASE_CCY_AMT          AS ACR_INT_AMT,  -- [MATCHED] DRD source verified against ODI (ODI projects .STM_BASE_CCY_AMT)  [DRD-notes: [05/28/25]: Product Backlog Item 2030710: Populate new columns for trade and fee attributes for Activity]
    fip.STM_BASE_CCY_AMT          AS CNCSN_AMT,  -- [MATCHED] DRD source verified against ODI (ODI projects .STM_BASE_CCY_AMT)  [DRD-notes: [05/28/25]: Product Backlog Item 2030710: Populate new columns for trade and fee attributes for Activity]
    fip.STM_BASE_CCY_AMT          AS CDSC_AMT,  -- [MATCHED] DRD source verified against ODI (ODI projects .STM_BASE_CCY_AMT)  [DRD-notes: [05/28/25]: Product Backlog Item 2030710: Populate new columns for trade and fee attributes for Activity]
    fip.STM_BASE_CCY_AMT          AS OTHR_FEE_AMT,  -- [MATCHED] DRD source verified against ODI (ODI projects .STM_BASE_CCY_AMT)  [DRD-notes: [05/28/25]: Product Backlog Item 2030710: Populate new columns for trade and fee attributes for Activity]
    NULL                          AS TRD_CNCLD_F,  -- [RECOVERED_FROM_PROSE_UNRUNNABLE] comparator MATCHED ODI's SQL realization '(MAX((CASE WHEN TXN_RLTNP.TRGT_TXN_ID IS NOT NULL     AND TX' but it references ODI staging alias(es) TXN_RLTNP1 absent from our DRD-driven FROM graph; projecting NULL so the INSERT runs.  Operator: restructure DRD source into table.column form to project a value.  [DRD-notes: [05/28/25]: Product Backlog Item 2030710: Populate new columns for trade and fee attributes for Activity NOTE: This logic is different from TDS/DWH cancelled_fl]
    apa.SYMB                      AS SYMB,  -- [MATCHED] DRD source verified against ODI (ODI projects APA.SYMB)  [DRD-notes: [06/16/25]: Product Backlog Item 2030710: Populate new columns for trade and fee attributes for Activity]
    apa.ISIN                      AS ISIN,  -- [MATCHED] DRD source verified against ODI (ODI projects APA.ISIN)  [DRD-notes: [06/16/25]: Product Backlog Item 2030710: Populate new columns for trade and fee attributes for Activity]
    txn_src_tax_code_lkup.SRC_TAX_CODE AS TXN_SRC_TAX_CD,  -- [MATCHED] DRD source verified against ODI (ODI projects TXN_SRC_TAX_CODE_LKUP.SRC_TAX_CODE)  [DRD-notes: [8/4/25]: Product Backlog Item 2349114: Add new Tax Code columns in Activity Fact and Activity Detail Fact. Product Backlog Item 2399461: Populate new Tax Code ]
    txn_src_tax_code_lkup.SRC_TAX_CODE_DSC AS TXN_SRC_TAX_CD_DSC,  -- [MATCHED] DRD source verified against ODI (ODI projects TXN_SRC_TAX_CODE_LKUP.SRC_TAX_CODE_DSC)  [DRD-notes: [8/4/25]: Product Backlog Item 2349114: Add new Tax Code columns in Activity Fact and Activity Detail Fact. Product Backlog Item 2399461: Populate new Tax Code ]
    t.TM_PRC_DSCTN_F              AS TM_PRC_DISCRETION_F,  -- [MATCHED] DRD source verified against ODI (ODI projects TXN.TM_PRC_DSCTN_F)
    txn_avy_cl.NNA_CGY_ID         AS CASH_NNA_CGY_ID,  -- [MATCHED] DRD source verified against ODI (ODI projects APA_CASH.NNA_CGY_ID)  [DRD-notes: [11/3/25]: Product Backlog Item 2218755: Add NNA Category columns to Activity Fact and Activity Detail Fact tables Product Backlog Item 2218746: Populate NNA Ca]
    nna_cgy.NNA_CGY_NM            AS CASH_NNA_CGY_NM,  -- [MATCHED] DRD source verified against ODI (ODI projects APA_CASH.NNA_CGY_NM)  [DRD-notes: [11/3/25]: Product Backlog Item 2218755: Add NNA Category columns to Activity Fact and Activity Detail Fact tables Product Backlog Item 2218746: Populate NNA Ca]
    txn_avy_cl.NNA_CGY_ID         AS SCR_NNA_CGY_ID,  -- [MATCHED] DRD source verified against ODI (ODI projects APA_SECURITY.NNA_CGY_ID)  [DRD-notes: [11/3/25]: Product Backlog Item 2218755: Add NNA Category columns to Activity Fact and Activity Detail Fact tables Product Backlog Item 2218746: Populate NNA Ca]
    nna_cgy.NNA_CGY_NM            AS SCR_NNA_CGY_NM,  -- [MATCHED] DRD source verified against ODI (ODI projects APA_SECURITY.NNA_CGY_NM)  [DRD-notes: [11/3/25]: Product Backlog Item 2218755: Add NNA Category columns to Activity Fact and Activity Detail Fact tables Product Backlog Item 2218746: Populate NNA Ca]
    apa.YLD                       AS YLD,  -- [MATCHED] DRD source verified against ODI (ODI projects APA.YLD)
    apa.YTW                       AS YTW,  -- [MATCHED] DRD source verified against ODI (ODI projects APA.YTW)
    apa.YTW_CD                    AS YTW_CD,  -- [MATCHED] DRD source verified against ODI (ODI projects APA.YTW_CD)  [DRD-notes: Expecetd value- “M” = Yield to Maturity “O” = Yield to Par “C” = Yield to Call “P” = Yield to Put “R” = Yield to Pre-refunded blank = Not Applicable]
    ar_dim.ORIG_SRC_STM_AR_ID     AS BKR_AC_NUM,  -- [MATCHED] DRD source verified against ODI (ODI projects BKR_AR_DIM.ORIG_SRC_STM_AR_ID)
    cl_val.CL_VAL_CODE            AS SIS_DLTD_EV_CD,  -- [MATCHED] DRD source verified against ODI (ODI projects CL_VAL.CL_VAL_CODE)
    t.ORIG_TD                     AS DB_CARD_TXN_DT,  -- [MATCHED] DRD source verified against ODI (ODI projects TXN.ORIG_TD)
    ccy.CCY_CODE                  AS DB_CARD_ORIG_CCY_CD,  -- [MATCHED] DRD source verified against ODI (ODI projects CCY.CCY_CODE)
    ccy.CCY_NM                    AS DB_CARD_ORIG_CCY,  -- [MATCHED] DRD source verified against ODI (ODI projects CCY.CCY_NM)
    cl_val.CL_VAL_CODE            AS SDIRA_TXN_TP_CD,  -- [MATCHED] DRD source verified against ODI (ODI projects CL_VAL.CL_VAL_CODE)
    cl_val.CL_VAL_NM              AS SDIRA_TXN_TP,  -- [MATCHED] DRD source verified against ODI (ODI projects CL_VAL.CL_VAL_NM)
    t.TRD_NUM                     AS SDIRA_TXN_YR,  -- [MATCHED] DRD source verified against ODI (ODI projects TXN.TRD_NUM)
    ccy.CCY_NM                    AS TXN_CCY,  -- [MATCHED] DRD source verified against ODI (ODI projects CCY.CCY_NM)
    ar_dim.IRA_F                  AS BKR_IRA_F,  -- [MATCHED] DRD source verified against ODI (ODI projects .IRA_F)
    ar_dim.ERISSA_F               AS BKR_ERISA_F,  -- [MATCHED] DRD source verified against ODI (ODI projects .ERISSA_F)
    ar_dim.ORIG_SRC_STM_CD        AS BKR_ORIG_SRC_STM_CD,  -- [MATCHED] DRD source verified against ODI (ODI projects BKR_AR_DIM.ORIG_SRC_STM_CD)
    ar_dim.ABC_CLSS_CD            AS BKR_ABC_CLSS_CD,  -- [MATCHED] DRD source verified against ODI (ODI projects BKR_AR_DIM.ABC_CLSS_CD)
    ar_dim.ABC_CLSS_NM            AS BKR_ABC_CLSS,  -- [MATCHED] DRD source verified against ODI (ODI projects BKR_AR_DIM.ABC_CLSS_NM)
    ar_dim.AR_CGY_CD              AS AC_CGY_CD,  -- [MATCHED] DRD source verified against ODI (ODI projects AR_DIM.AR_CGY_CD)
    ar_dim.AR_CGY_CD              AS BKR_AC_CGY_CD,  -- [MATCHED] DRD source verified against ODI (ODI projects BKR_AR_DIM.AR_CGY_CD)
    ar_dim.AR_CGY                 AS AC_CGY,  -- [MATCHED] DRD source verified against ODI (ODI projects AR_DIM.AR_CGY)
    ar_dim.AR_CGY                 AS BKR_AC_CGY,  -- [MATCHED] DRD source verified against ODI (ODI projects BKR_AR_DIM.AR_CGY)
    ar_dim.BSN_LINE_AFFLT         AS BKR_BSN_LINE_AFFLT,  -- [MATCHED] DRD source verified against ODI (ODI projects BKR_AR_DIM.BSN_LINE_AFFLT)
    ar_dim.BSN_LINE_AFFLT_CD      AS BKR_BSN_LINE_AFFLT_CD,  -- [MATCHED] DRD source verified against ODI (ODI projects BKR_AR_DIM.BSN_LINE_AFFLT_CD)
    ar_dim.TST_AR_F               AS TST_AC_F,  -- [MATCHED] DRD source verified against ODI (ODI projects AR_DIM.TST_AR_F)
    ar_dim.TST_AR_F               AS BKR_TST_AC_F,  -- [MATCHED] DRD source verified against ODI (ODI projects BKR_AR_DIM.TST_AR_F)
    ar_dim.TAX_RPT_PARTY_ID       AS TAX_RPT_CLNT_ID,  -- [MATCHED] DRD source verified against ODI (ODI projects AR_DIM.TAX_RPT_PARTY_ID)
    ar_dim.TAX_RPT_PARTY_ID       AS BKR_TAX_RPT_CLNT_ID,  -- [MATCHED] DRD source verified against ODI (ODI projects BKR_AR_DIM.TAX_RPT_PARTY_ID)
    ar_dim.TAX_AC_F               AS TAX_AC_F,  -- [MATCHED] DRD source verified against ODI (ODI projects AR_DIM.TAX_AC_F)
    ar_dim.TAX_AC_F               AS BKR_TAX_AC_F,  -- [MATCHED] DRD source verified against ODI (ODI projects BKR_AR_DIM.TAX_AC_F)
    ar_dim.RJ_TAX_RPT_RSPL_F      AS BKR_RJ_TAX_RPT_RSPL_F,  -- [MATCHED] DRD source verified against ODI (ODI projects BKR_AR_DIM.RJ_TAX_RPT_RSPL_F)
    ar_dim.RJ_BSN_UNIT_CD         AS RJ_BSN_UNIT_CD,  -- [MATCHED] DRD source verified against ODI (ODI projects AR_DIM.RJ_BSN_UNIT_CD)
    ar_dim.RJ_BSN_UNIT_CD         AS BKR_RJ_BSN_UNIT_CD,  -- [MATCHED] DRD source verified against ODI (ODI projects BKR_AR_DIM.RJ_BSN_UNIT_CD)
    ar_dim.RJ_BSN_UNIT            AS RJ_BSN_UNIT,  -- [MATCHED] DRD source verified against ODI (ODI projects AR_DIM.RJ_BSN_UNIT)
    ar_dim.RJ_BSN_UNIT            AS BKR_RJ_BSN_UNIT,  -- [MATCHED] DRD source verified against ODI (ODI projects BKR_AR_DIM.RJ_BSN_UNIT)
    ar_dim.OWNSHP_TP_CD           AS AC_OWNSHP_TP_CD,  -- [MATCHED] DRD source verified against ODI (ODI projects AR_DIM.OWNSHP_TP_CD)
    ar_dim.OWNSHP_TP_CD           AS BKR_AC_OWNSHP_TP_CD,  -- [MATCHED] DRD source verified against ODI (ODI projects BKR_AR_DIM.OWNSHP_TP_CD)
    ar_dim.OWNSHP_TP              AS AC_OWNSHP_TP,  -- [MATCHED] DRD source verified against ODI (ODI projects AR_DIM.OWNSHP_TP)
    ar_dim.OWNSHP_TP              AS BKR_AC_OWNSHP_TP,  -- [MATCHED] DRD source verified against ODI (ODI projects BKR_AR_DIM.OWNSHP_TP)
    ar_dim.FIRM_AC_F              AS BKR_FIRM_AC_F,  -- [MATCHED] DRD source verified against ODI (ODI projects BKR_AR_DIM.FIRM_AC_F)
    ar_dim.FEE_BASE_F             AS BKR_FEE_BASE_AC_F,  -- [MATCHED] DRD source verified against ODI (ODI projects BKR_AR_DIM.FEE_BASE_F)
    ar_dim.BSN_LINE_AFFLT_CD      AS BKR_RJ_TRUST_F,  -- [MATCHED] DRD source verified against ODI (ODI projects .BSN_LINE_AFFLT_CD)
    fa_number_v.FA_NUMBER         AS OWN_PRIM_FA_NUM,  -- [MATCHED] DRD source verified against ODI (ODI projects FA_NUMBER_V2.FA_NUMBER)
    person_rv.CSS_PERSON_ID       AS OWN_FA_CSS_PSN_ID,  -- [MATCHED] DRD source verified against ODI (ODI projects BRK_OWN_PSN.CSS_PERSON_ID)
    person_brokerage_subdimension_v.CURRENT_ADVISOR_FLAG AS OWN_FA_CRN_ADV_F,  -- [MATCHED] DRD source verified against ODI (ODI projects BRK_OWN_PSN_BRK_SUBDIM.CURRENT_ADVISOR_FLAG)
    person_rv.DEPARTMENT_BRANCH_CODE AS OWN_FA_DEPT_BR_CD,  -- [MATCHED] DRD source verified against ODI (ODI projects BRK_OWN_PSN.DEPARTMENT_BRANCH_CODE)
    person_ams_discretionary_status_v.DISCRETIONARY_INDICATOR AS OWN_FA_DSCR_F,  -- [MATCHED] DRD source verified against ODI (ODI projects BRK_OWN_RESP_AMS_DISC.DISCRETIONARY_INDICATOR)
    person_ams_discretionary_status_v.DISCRETIONARY_STATUS AS OWN_FA_DSCR_ST,  -- [MATCHED] DRD source verified against ODI (ODI projects BRK_OWN_RESP_AMS_DISC.DISCRETIONARY_STATUS)
    person_ams_discretionary_status_v.DISCRETIONARY_STATUS_CODE AS OWN_FA_DSCR_ST_CD,  -- [MATCHED] DRD source verified against ODI (ODI projects BRK_OWN_RESP_AMS_DISC.DISCRETIONARY_STATUS_CODE)
    person_rv.FINRA_CRD_CLASS_CODE AS OWN_FA_FINRA_CRD_CLSS_CD,  -- [MATCHED] DRD source verified against ODI (ODI projects BRK_OWN_PSN.FINRA_CRD_CLASS_CODE)
    person_rv.HR_STATUS_CODE      AS OWN_FA_HR_ST_CD,  -- [MATCHED] DRD source verified against ODI (ODI projects BRK_OWN_PSN.HR_STATUS_CODE)
    person_rv.PRODUCER_FLAG       AS OWN_FA_PRODUCER_F,  -- [MATCHED] DRD source verified against ODI (ODI projects BRK_OWN_PSN.PRODUCER_FLAG)
    person_brokerage_subdimension_v.QUALIFIED_ADVISOR_FLAG AS OWN_FA_QUALF_ADV_F,  -- [MATCHED] DRD source verified against ODI (ODI projects BRK_OWN_PSN_BRK_SUBDIM.QUALIFIED_ADVISOR_FLAG)
    enterprise_entity_dim_v.ENTITY_BRANCH_CODE AS OWN_FA_ENT_BR_CD,  -- [MATCHED] DRD source verified against ODI (ODI projects OWN_FA_ENT.ENTITY_BRANCH_CODE)
    enterprise_entity_dim_v.ENTITY_BUSINESS_STATUS AS OWN_FA_ENT_BSN_ST,  -- [MATCHED] DRD source verified against ODI (ODI projects OWN_FA_ENT.ENTITY_BUSINESS_STATUS)
    enterprise_entity_dim_v.ENTITY_DIVISION_CODE AS OWN_FA_ENT_DIV_CD,  -- [MATCHED] DRD source verified against ODI (ODI projects OWN_FA_ENT.ENTITY_DIVISION_CODE)
    enterprise_entity_dim_v.ENTITY_DIVISION_DESCRIPTION AS OWN_FA_ENT_DIV_DSC,  -- [MATCHED] DRD source verified against ODI (ODI projects OWN_FA_ENT.ENTITY_DIVISION_DESCRIPTION)
    enterprise_entity_dim_v.ENTITY_DIVISION_NODE AS OWN_FA_ENT_DIV_NODE,  -- [MATCHED] DRD source verified against ODI (ODI projects OWN_FA_ENT.ENTITY_DIVISION_NODE)
    enterprise_entity_dim_v.ENTITY_MAIN_BRANCH_STATE AS OWN_FA_ENT_MAIN_BR_STE,  -- [MATCHED] DRD source verified against ODI (ODI projects OWN_FA_ENT.ENTITY_MAIN_BRANCH_STATE)
    enterprise_entity_dim_v.ENTITY_OSJ AS OWN_FA_ENT_OSJ,  -- [MATCHED] DRD source verified against ODI (ODI projects OWN_FA_ENT.ENTITY_OSJ)
    enterprise_entity_retail_dimension_v.ENTITY_RETAIL_BUSINESS_MODEL_CODE AS OWN_FA_ENT_RTL_HIER_BSN_MODL_CD,  -- [MATCHED] DRD source verified against ODI (ODI projects OWN_RTL_ENT.ENTITY_RETAIL_BUSINESS_MODEL_CODE)
    enterprise_entity_retail_dimension_v.ENTITY_RETAIL_BUSINESS_MODEL_DESCRIPTION AS OWN_FA_ENT_RTL_HIER_BSN_MODL_DSC,  -- [MATCHED] DRD source verified against ODI (ODI projects OWN_RTL_ENT.ENTITY_RETAIL_BUSINESS_MODEL_DESCRIPTION)
    enterprise_entity_retail_dimension_v.ENTITY_RETAIL_SALES_LOB_CODE AS OWN_FA_ENT_RTL_SALE_HIER_LOB_CD,  -- [MATCHED] DRD source verified against ODI (ODI projects OWN_RTL_ENT.ENTITY_RETAIL_SALES_LOB_CODE)
    enterprise_entity_retail_dimension_v.ENTITY_RETAIL_SALES_LOB_DESCRIPTION AS OWN_FA_ENT_RTL_SALE_HIER_LOB_DSC,  -- [MATCHED] DRD source verified against ODI (ODI projects OWN_RTL_ENT.ENTITY_RETAIL_SALES_LOB_DESCRIPTION)
    enterprise_entity_retail_dimension_v.ENTITY_RETAIL_REPORTING_UNIT_CODE AS OWN_FA_ENT_RTL_HIER_RPT_UNIT_CD,  -- [MATCHED] DRD source verified against ODI (ODI projects OWN_RTL_ENT.ENTITY_RETAIL_REPORTING_UNIT_CODE)
    enterprise_entity_retail_dimension_v.ENTITY_RETAIL_REPORTING_UNIT_DESCRIPTION AS OWN_FA_ENT_RTL_HIER_RPT_UNIT_DSC,  -- [MATCHED] DRD source verified against ODI (ODI projects OWN_RTL_ENT.ENTITY_RETAIL_REPORTING_UNIT_DESCRIPTION)
    enterprise_entity_retail_dimension_v.ENTITY_RETAIL_SALES_DIVISION_CODE AS OWN_FA_ENT_RTL_SALE_DIV_CD,  -- [MATCHED] DRD source verified against ODI (ODI projects OWN_RTL_ENT.ENTITY_RETAIL_SALES_DIVISION_CODE)
    enterprise_entity_retail_dimension_v.ENTITY_RETAIL_SALES_REGION_CODE AS OWN_FA_ENT_RTL_SALE_HIER_RGON_CD,  -- [MATCHED] DRD source verified against ODI (ODI projects OWN_RTL_ENT.ENTITY_RETAIL_SALES_REGION_CODE)
    enterprise_entity_retail_dimension_v.ENTITY_RETAIL_SALES_REGION_DESCRIPTION AS OWN_FA_ENT_RTL_SALE_HIER_RGON_DSC,  -- [MATCHED] DRD source verified against ODI (ODI projects OWN_RTL_ENT.ENTITY_RETAIL_SALES_REGION_DESCRIPTION)
    enterprise_entity_retail_dimension_v.ENTITY_RETAIL_TERRITORY_CODE AS OWN_FA_ENT_RTL_HIER_TERR_CD,  -- [MATCHED] DRD source verified against ODI (ODI projects OWN_RTL_ENT.ENTITY_RETAIL_TERRITORY_CODE)
    enterprise_entity_retail_dimension_v.ENTITY_RETAIL_TERRITORY_DESCRIPTION AS OWN_FA_ENT_RTL_HIER_TERR_DSC,  -- [MATCHED] DRD source verified against ODI (ODI projects OWN_RTL_ENT.ENTITY_RETAIL_TERRITORY_DESCRIPTION)
    enterprise_entity_risk_dim.ENTITY_RISK_BUSINESS_UNIT_CODE AS OWN_FA_ENT_RSK_HIER_BSN_UNIT_CD,  -- [MATCHED] DRD source verified against ODI (ODI projects OWN_RISK_ENT.ENTITY_RISK_BUSINESS_UNIT_CODE)
    enterprise_entity_risk_dim.ENTITY_RISK_BUSINESS_UNIT_DESCRIPTION AS OWN_FA_ENT_RSK_HIER_BSN_UNIT_DSC,  -- [MATCHED] DRD source verified against ODI (ODI projects OWN_RISK_ENT.ENTITY_RISK_BUSINESS_UNIT_DESCRIPTION)
    enterprise_entity_dim_v.ENTITY_RJAS_ID_BOOLEAN AS OWN_FA_ENT_RJAS_ID_F,  -- [MATCHED] DRD source verified against ODI (ODI projects .ENTITY_RJAS_ID_BOOLEAN)
    enterprise_entity_dim_v.ENTITY_SUBDIVISION_CODE AS OWN_FA_ENT_SUBDIV_CD,  -- [MATCHED] DRD source verified against ODI (ODI projects OWN_FA_ENT.ENTITY_SUBDIVISION_CODE)
    enterprise_entity_dim_v.ENTITY_SUBDIVISION_DESCRIPTION AS OWN_FA_ENT_SUBDIV_DSC,  -- [MATCHED] DRD source verified against ODI (ODI projects OWN_FA_ENT.ENTITY_SUBDIVISION_DESCRIPTION)
    enterprise_entity_dim_v.ENTITY_SUBSIDIARY AS OWN_FA_ENT_SUBS,  -- [MATCHED] DRD source verified against ODI (ODI projects OWN_FA_ENT.ENTITY_SUBSIDIARY)
    enterprise_entity_dim_v.ENTITY_SUBTYPE AS OWN_FA_ENT_SBTP,  -- [MATCHED] DRD source verified against ODI (ODI projects OWN_FA_ENT.ENTITY_SUBTYPE)
    enterprise_entity_dim_v.ENTITY_SUBTYPE_CODE AS OWN_FA_ENT_SBTP_CD,  -- [MATCHED] DRD source verified against ODI (ODI projects OWN_FA_ENT.ENTITY_SUBTYPE_CODE)
    enterprise_entity_dim_v.ENTITY_TYPE AS OWN_FA_ENT_TP,  -- [MATCHED] DRD source verified against ODI (ODI projects OWN_FA_ENT.ENTITY_TYPE)
    enterprise_entity_dim_v.ENTITY_TYPE_CODE AS OWN_FA_ENT_TP_CD,  -- [MATCHED] DRD source verified against ODI (ODI projects OWN_FA_ENT.ENTITY_TYPE_CODE)
    enterprise_entity_dim_v.LOB_ALEX_BROWN_BOOLEAN AS OWN_FA_ENT_LOB_AB_F,  -- [MATCHED] DRD source verified against ODI (ODI projects .LOB_ALEX_BROWN_BOOLEAN)
    enterprise_entity_dim_v.LOB_AMS_BOOLEAN AS OWN_FA_ENT_LOB_AMS_F,  -- [MATCHED] DRD source verified against ODI (ODI projects .LOB_AMS_BOOLEAN)
    enterprise_entity_dim_v.LOB_BUSINESS_MODEL AS OWN_FA_ENT_LOB_BSN_MODL,  -- [MATCHED] DRD source verified against ODI (ODI projects OWN_FA_ENT.LOB_BUSINESS_MODEL)
    enterprise_entity_dim_v.ENTITY_BUSINESS_OPEN_DATE AS OWN_FA_ENT_BSN_OPN_DT,  -- [MATCHED] DRD source verified against ODI (ODI projects OWN_FA_ENT.ENTITY_BUSINESS_OPEN_DATE)
    enterprise_entity_dim_v.ENTITY_CODE_LONG AS OWN_FA_ENT_LONG_CD,  -- [MATCHED] DRD source verified against ODI (ODI projects OWN_FA_ENT.ENTITY_CODE_LONG)
    enterprise_entity_dim_v.ENTITY_CODE_SHORT AS OWN_FA_ENT_SHRT_CD,  -- [MATCHED] DRD source verified against ODI (ODI projects OWN_FA_ENT.ENTITY_CODE_SHORT)
    enterprise_entity_dim_v.ENTITY_CSS_ID AS OWN_FA_ENT_CSS_ID,  -- [MATCHED] DRD source verified against ODI (ODI projects OWN_FA_ENT.ENTITY_CSS_ID)
    enterprise_entity_retail_dimension_v.ENTITY_RETAIL_SALES_COMPLEX_CODE AS OWN_FA_ENT_RTL_SALE_CPX_CD,  -- [MATCHED] DRD source verified against ODI (ODI projects OWN_RTL_ENT.ENTITY_RETAIL_SALES_COMPLEX_CODE)
    imt_pd_dim.EQTY_SECT_LVL_4    AS EQTY_IDY,  -- [MATCHED] DRD source verified against ODI (ODI projects IMT_PD_DIM.EQTY_SECT_LVL_4)
    imt_pd_dim.EQTY_SECT_LVL_4_CD AS EQTY_IDY_CD,  -- [MATCHED] DRD source verified against ODI (ODI projects IMT_PD_DIM.EQTY_SECT_LVL_4_CD)
    imt_pd_dim.EQTY_SECT_LVL_3    AS EQTY_IDY_GRP,  -- [MATCHED] DRD source verified against ODI (ODI projects IMT_PD_DIM.EQTY_SECT_LVL_3)
    imt_pd_dim.EQTY_SECT_LVL_3_CD AS EQTY_IDY_GRP_CD,  -- [MATCHED] DRD source verified against ODI (ODI projects IMT_PD_DIM.EQTY_SECT_LVL_3_CD)
    imt_pd_dim.EQTY_SECT_LVL_2    AS EQTY_SECT,  -- [MATCHED] DRD source verified against ODI (ODI projects IMT_PD_DIM.EQTY_SECT_LVL_2)
    imt_pd_dim.EQTY_SECT_LVL_2_CD AS EQTY_SECT_CD,  -- [MATCHED] DRD source verified against ODI (ODI projects IMT_PD_DIM.EQTY_SECT_LVL_2_CD)
    imt_pd_dim.EQTY_SECT_LVL_1    AS EQTY_SUP_SECT,  -- [MATCHED] DRD source verified against ODI (ODI projects IMT_PD_DIM.EQTY_SECT_LVL_1)
    imt_pd_dim.EQTY_SECT_LVL_1_CD AS EQTY_SUP_SECT_CD,  -- [MATCHED] DRD source verified against ODI (ODI projects IMT_PD_DIM.EQTY_SECT_LVL_1_CD)
    imt_pd_dim.FIRM_MODL_LVL_2    AS MODL_STRTG_DTL_AST_CLSS,  -- [MATCHED] DRD source verified against ODI (ODI projects IMT_PD_DIM.FIRM_MODL_LVL_2)
    imt_pd_dim.FIRM_MODL_LVL_2_CD AS MODL_STRTG_DTL_AST_CLSS_CD,  -- [MATCHED] DRD source verified against ODI (ODI projects IMT_PD_DIM.FIRM_MODL_LVL_2_CD)
    imt_pd_dim.FIRM_MODL_LVL_1    AS MODL_STRTG_SMY_AST_CLSS,  -- [MATCHED] DRD source verified against ODI (ODI projects IMT_PD_DIM.FIRM_MODL_LVL_1)
    imt_pd_dim.FIRM_MODL_LVL_1_CD AS MODL_STRTG_SMY_AST_CLSS_CD,  -- [MATCHED] DRD source verified against ODI (ODI projects IMT_PD_DIM.FIRM_MODL_LVL_1_CD)
    apa.PD_CMPOS_DSC              AS PD_CMPOS_DSC,  -- [MATCHED] DRD source verified against ODI (ODI projects APA.PD_CMPOS_DSC)
    imt_pd_dim.PD_NM              AS PD_SHRT_NM,  -- [MATCHED] DRD source verified against ODI (ODI projects IMT_PD_DIM.PD_NM)
    imt_pd_dim.PD_DSC             AS PD_DSC,  -- [MATCHED] DRD source verified against ODI (ODI projects IMT_PD_DIM.PD_DSC)
    imt_pd_dim.RPT_CL_LVL_1       AS RPT_CL_LVL_1,  -- [MATCHED] DRD source verified against ODI (ODI projects IMT_PD_DIM.RPT_CL_LVL_1)
    imt_pd_dim.RPT_CL_LVL_2       AS RPT_CL_LVL_2,  -- [MATCHED] DRD source verified against ODI (ODI projects IMT_PD_DIM.RPT_CL_LVL_2)
    imt_pd_dim.FIRM_RPT_LVL_2     AS RPT_STRTG_DTL_AST_CLSS,  -- [MATCHED] DRD source verified against ODI (ODI projects IMT_PD_DIM.FIRM_RPT_LVL_2)
    imt_pd_dim.FIRM_RPT_LVL_2_CD  AS RPT_STRTG_DTL_AST_CLSS_CD,  -- [MATCHED] DRD source verified against ODI (ODI projects IMT_PD_DIM.FIRM_RPT_LVL_2_CD)
    imt_pd_dim.FIRM_RPT_LVL_1     AS RPT_STRTG_SMY_AST_CLSS,  -- [MATCHED] DRD source verified against ODI (ODI projects IMT_PD_DIM.FIRM_RPT_LVL_1)
    imt_pd_dim.FIRM_RPT_LVL_1_CD  AS RPT_STRTG_SMY_AST_CLSS_CD,  -- [MATCHED] DRD source verified against ODI (ODI projects IMT_PD_DIM.FIRM_RPT_LVL_1_CD)
    imt_pd_dim.FND_FAM            AS FND_FAM,  -- [MATCHED] DRD source verified against ODI (ODI projects IMT_PD_DIM.FND_FAM)
    imt_pd_dim.SHR_CLSS_TP_CD     AS SHR_CLSS_TP_CD,  -- [MATCHED] DRD source verified against ODI (ODI projects IMT_PD_DIM.SHR_CLSS_TP_CD)
    imt_pd_dim.SHR_CLSS_TP_NM     AS SHR_CLSS_TP,  -- [MATCHED] DRD source verified against ODI (ODI projects IMT_PD_DIM.SHR_CLSS_TP_NM)
    imt_pd_dim.IMT_CL_LVL_1       AS IMT_CL_LVL_1,  -- [MATCHED] DRD source verified against ODI (ODI projects IMT_PD_DIM.IMT_CL_LVL_1)
    imt_pd_dim.IMT_CL_LVL_1_CD    AS IMT_CL_LVL_1_CD,  -- [MATCHED] DRD source verified against ODI (ODI projects IMT_PD_DIM.IMT_CL_LVL_1_CD)
    imt_pd_dim.IMT_CL_LVL_2       AS IMT_CL_LVL_2,  -- [MATCHED] DRD source verified against ODI (ODI projects IMT_PD_DIM.IMT_CL_LVL_2)
    imt_pd_dim.IMT_CL_LVL_2_CD    AS IMT_CL_LVL_2_CD,  -- [MATCHED] DRD source verified against ODI (ODI projects IMT_PD_DIM.IMT_CL_LVL_2_CD)
    imt_pd_dim.IMT_CL_LVL_3       AS IMT_CL_LVL_3,  -- [MATCHED] DRD source verified against ODI (ODI projects IMT_PD_DIM.IMT_CL_LVL_3)
    imt_pd_dim.IMT_CL_LVL_3_CD    AS IMT_CL_LVL_3_CD,  -- [MATCHED] DRD source verified against ODI (ODI projects IMT_PD_DIM.IMT_CL_LVL_3_CD)
    imt_pd_dim.IMT_CL_LVL_4       AS IMT_CL_LVL_4,  -- [MATCHED] DRD source verified against ODI (ODI projects IMT_PD_DIM.IMT_CL_LVL_4)
    imt_pd_dim.IMT_CL_LVL_4_CD    AS IMT_CL_LVL_4_CD,  -- [MATCHED] DRD source verified against ODI (ODI projects IMT_PD_DIM.IMT_CL_LVL_4_CD)
    imt_pd_dim.IMT_CL_LVL_5       AS IMT_CL_LVL_5,  -- [MATCHED] DRD source verified against ODI (ODI projects IMT_PD_DIM.IMT_CL_LVL_5)
    imt_pd_dim.IMT_CL_LVL_5_CD    AS IMT_CL_LVL_5_CD,  -- [MATCHED] DRD source verified against ODI (ODI projects IMT_PD_DIM.IMT_CL_LVL_5_CD)
    fa_number_v.FA_NUMBER_TYPE_CODE AS OWN_FA_NUM_TP_CD,  -- [MATCHED] DRD source verified against ODI (ODI projects FA_NUMBER_V.FA_NUMBER_TYPE_CODE)
    code_set_value_v.CODE_VALUE_DESCRIPTION AS OWN_FA_NUM_TP,  -- [MATCHED] DRD source verified against ODI (ODI projects CODE_SET_VALUE_V.CODE_VALUE_DESCRIPTION)
    apa.ORIG_QTY                  AS BOND_ACRTN_DCN_AMT,  -- [MATCHED] DRD source verified against ODI (ODI projects .ORIG_QTY)
    apa.ORIG_QTY                  AS BOND_AMRZ_PREM_AMT,  -- [MATCHED] DRD source verified against ODI (ODI projects .ORIG_QTY)
    apa.ORIG_QTY                  AS RJ_TRUST_BOOK_VAL_AMT,  -- [MATCHED] DRD source verified against ODI (ODI projects .ORIG_QTY)
    apa.ORIG_QTY                  AS RJ_TRUST_RLZD_TAX_GAIN_OR_LOSS_AMT,  -- [MATCHED] DRD source verified against ODI (ODI projects .ORIG_QTY)
    apa.ORIG_QTY                  AS BFR_REPYMT_FACE_VAL_AMT,  -- [MATCHED] DRD source verified against ODI (ODI projects .ORIG_QTY)
    apa.ORIG_QTY                  AS BFR_INCM_PYMT_FACE_VAL_AMT,  -- [MATCHED] DRD source verified against ODI (ODI projects .ORIG_QTY)
    apa.ORIG_QTY                  AS BASE_POS_QTY,  -- [MATCHED] DRD source verified against ODI (ODI projects .ORIG_QTY)
    apa.ORIG_QTY                  AS NO_SIS_SCR_MVMT_TXN_QTY,  -- [MATCHED] DRD source verified against ODI (ODI projects .ORIG_QTY)
    apa.SCR_PRC_IN_TXN_CCY        AS NO_SIS_SCR_MVMT_TXN_PRC,  -- [MATCHED] DRD source verified against ODI (ODI projects .SCR_PRC_IN_TXN_CCY)
    apa.ORIG_QTY                  AS REIVS_SHR_QTY,  -- [MATCHED] DRD source verified against ODI (ODI projects .ORIG_QTY)
    apa.SCR_PRC_IN_TXN_CCY        AS REIVS_PRC  -- [MATCHED] DRD source verified against ODI (ODI projects .SCR_PRC_IN_TXN_CCY)
FROM CCAL_REPL_OWNER.TXN t
  JOIN CCAL_REPL_OWNER.SHDW_TXN_TP shdw_txn_tp ON shdw_txn_tp.SRC_TXN_TP = t.SRC_TXN_TP
  JOIN REFERENCE_REPL_OWNER.IMPCT_ACTION_LKU impct_action_lku ON impct_action_lku.ACTION_CODE = t.SRC_ACTN_CODE
  JOIN CCAL_REPL_OWNER.CL_VAL cl_val ON cl_val.CL_VAL_ID = t.SRC_BUY_SELL_MULTI_ID
  JOIN CCSI_OWNER.AR_GRP_SUBDIM ar_grp_subdim ON ar_grp_subdim.AR_ID = t.AR_ID
  -- TODO: replace CROSS JOIN with operator-supplied ON clause for SSDS_DAL_OWNER.FA_NUMBER_V
  CROSS JOIN SSDS_DAL_OWNER.FA_NUMBER_V fa_number_v
  -- TODO: replace CROSS JOIN with operator-supplied ON clause for SSDS_DAL_OWNER.ENTERPRISE_ENTITY_DIM_V
  CROSS JOIN SSDS_DAL_OWNER.ENTERPRISE_ENTITY_DIM_V enterprise_entity_dim_v
  JOIN CCAL_REPL_OWNER.ACATS_BROKER acats_broker ON acats_broker.BROKER_ID = t.ORIG_SRC_STM_CODE AND T.SRC_STM_ID IN ( 53, 54 )
  JOIN CCSI_OWNER.AR_DIM ar_dim ON ar_dim.AR_ID = t.AR_ID
  JOIN COMMON_OWNER.SRC_STM_DIM src_stm_dim ON src_stm_dim.SRC_STM_ID = t.SRC_STM_ID
  JOIN CCAL_REPL_OWNER.CL_VAL cl_val_2 ON cl_val_2.CL_VAL_ID = t.TXN_ST_ID
  JOIN COMMON_OWNER.DATE_DIM date_dim ON date_dim.CAL_DT = t.TD
  JOIN CIRD_OWNER.EXG_DIM exg_dim ON exg_dim.EXG_CD = t.EXG_CODE
  -- TODO: replace CROSS JOIN with operator-supplied ON clause for COMMON_OWNER.ACG_TP_DIM
  CROSS JOIN COMMON_OWNER.ACG_TP_DIM acg_tp_dim
  JOIN CCAL_REPL_OWNER.APA apa ON apa.EXEC_ID = t.TXN_ID
  JOIN CCAL_REPL_OWNER.J$TXN j$txn ON j$txn.TXN_ID = t.TXN_ID
  -- TODO: replace CROSS JOIN with operator-supplied ON clause for CCAL_REPL_OWNER.AVY_CL
  CROSS JOIN CCAL_REPL_OWNER.AVY_CL avy_cl
  JOIN CCAL_REPL_OWNER.TXN_AVY_CL txn_avy_cl ON txn_avy_cl.TXN_ID = t.TXN_ID
  -- TODO: replace CROSS JOIN with operator-supplied ON clause for CCAL_REPL_OWNER.CCAL_CIRD_PD_MAP
  CROSS JOIN CCAL_REPL_OWNER.CCAL_CIRD_PD_MAP ccal_cird_pd_map
  -- TODO: replace CROSS JOIN with operator-supplied ON clause for COMMON_OWNER.CASH_POS_TP_DIM
  CROSS JOIN COMMON_OWNER.CASH_POS_TP_DIM cash_pos_tp_dim
  -- TODO: replace CROSS JOIN with operator-supplied ON clause for CIRD_OWNER.IMT_PD_DIM
  CROSS JOIN CIRD_OWNER.IMT_PD_DIM imt_pd_dim
  -- TODO: replace CROSS JOIN with operator-supplied ON clause for CIRD_OWNER.CCY_DIM
  CROSS JOIN CIRD_OWNER.CCY_DIM ccy_dim
  JOIN TRANSACTIONS_OWNER.LGCY_CNCL_CMPLN_RSN_TP_DIM lgcy_cncl_cmpln_rsn_tp_dim ON lgcy_cncl_cmpln_rsn_tp_dim.LGCY_CNCL_CMPLN_RSN_TP_ID = t.LGCY_CNCL_CMPLN_RSN_TP_ID
  JOIN TRANSACTIONS_OWNER.LGCY_CNCL_CMPLN_SRC_TP_DIM lgcy_cncl_cmpln_src_tp_dim ON lgcy_cncl_cmpln_src_tp_dim.LGCY_CNCL_CMPLN_SRC_TP_ID = t.LGCY_CNCL_CMPLN_SRC_TP_ID
  JOIN TRANSACTIONS_OWNER.LGCY_MKT_TP_DIM lgcy_mkt_tp_dim ON lgcy_mkt_tp_dim.LGCY_MKT_TP_ID = t.LGCY_MKT_TP_ID
  JOIN TRANSACTIONS_OWNER.LGCY_TRD_CPCTY_TP_DIM lgcy_trd_cpcty_tp_dim ON lgcy_trd_cpcty_tp_dim.LGCY_TRD_CPCTY_TP_ID = t.LGCY_TRD_CPCTY_TP_ID
  JOIN CCAL_REPL_OWNER.TXN_RLTNP txn_rltnp ON txn_rltnp.SRC_TXN_ID = t.TXN_ID
  JOIN TRANSACTIONS_OWNER.SRC_ENTR_CNL_TP_DIM src_entr_cnl_tp_dim ON src_entr_cnl_tp_dim.SRC_ENTR_CNL_TP_ID = t.SRC_ENTR_CNL_TP_ID
  JOIN TRANSACTIONS_OWNER.SRC_PCS_TP_DIM src_pcs_tp_dim ON src_pcs_tp_dim.SRC_PCS_TP_ID = t.SRC_PCS_TP_ID
  JOIN TRANSACTIONS_OWNER.TRD_SLCT_TP_DIM trd_slct_tp_dim ON trd_slct_tp_dim.TRD_SLCT_TP_ID = t.TRD_SLCT_TP_ID
  -- TODO: replace CROSS JOIN with operator-supplied ON clause for CCAL_REPL_OWNER.FIP
  CROSS JOIN CCAL_REPL_OWNER.FIP fip
  JOIN CCAL_REPL_OWNER.TXN_SRC_TAX_CODE_LKUP txn_src_tax_code_lkup ON txn_src_tax_code_lkup.SRC_TAX_CODE_ID = t.SRC_TAX_CODE_ID
  -- TODO: replace CROSS JOIN with operator-supplied ON clause for CCAL_REPL_OWNER.NNA_CGY
  CROSS JOIN CCAL_REPL_OWNER.NNA_CGY nna_cgy
  -- TODO: replace CROSS JOIN with operator-supplied ON clause for REFERENCE_REPL_OWNER.CCY
  CROSS JOIN REFERENCE_REPL_OWNER.CCY ccy
  -- TODO: replace CROSS JOIN with operator-supplied ON clause for SSDS_DAL_OWNER.PERSON_RV
  CROSS JOIN SSDS_DAL_OWNER.PERSON_RV person_rv
  -- TODO: replace CROSS JOIN with operator-supplied ON clause for SSDS_DAL_OWNER.PERSON_BROKERAGE_SUBDIMENSION_V
  CROSS JOIN SSDS_DAL_OWNER.PERSON_BROKERAGE_SUBDIMENSION_V person_brokerage_subdimension_v
  -- TODO: replace CROSS JOIN with operator-supplied ON clause for SSDS_DAL_OWNER.PERSON_AMS_DISCRETIONARY_STATUS_V
  CROSS JOIN SSDS_DAL_OWNER.PERSON_AMS_DISCRETIONARY_STATUS_V person_ams_discretionary_status_v
  -- TODO: replace CROSS JOIN with operator-supplied ON clause for SSDS_DAL_OWNER.ENTERPRISE_ENTITY_RETAIL_DIMENSION_V
  CROSS JOIN SSDS_DAL_OWNER.ENTERPRISE_ENTITY_RETAIL_DIMENSION_V enterprise_entity_retail_dimension_v
  -- TODO: replace CROSS JOIN with operator-supplied ON clause for SSDS_DAL_OWNER.ENTERPRISE_ENTITY_RISK_DIM
  CROSS JOIN SSDS_DAL_OWNER.ENTERPRISE_ENTITY_RISK_DIM enterprise_entity_risk_dim
  -- TODO: replace CROSS JOIN with operator-supplied ON clause for SSDS_DAL_OWNER.CODE_SET_VALUE_V
  CROSS JOIN SSDS_DAL_OWNER.CODE_SET_VALUE_V code_set_value_v
  -- TODO: replace CROSS JOIN with operator-supplied ON clause for CCAL_REPL_OWNER.CL_VAL (discriminator: 114)
  CROSS JOIN CCAL_REPL_OWNER.CL_VAL cl_val_3
  -- TODO: replace CROSS JOIN with operator-supplied ON clause for CCAL_REPL_OWNER.CL_VAL (discriminator: 115)
  CROSS JOIN CCAL_REPL_OWNER.CL_VAL cl_val_4